#!/usr/bin/env python3
"""build_notes_en.py — compile notes_en_source.json → notes_en.js overlay.

  window.CULTURE_NOTES_EN = { "<itemId>": "<english redraft>" }

Keyed by item id (the redrafts are authored per item). enrichExtras() attaches it
as `item.noteEn`; the Reader's quote becomes click-to-translate when it exists.
Edit/extend notes_en_source.json (drop the `_comment` key in output), then re-run:
python build_notes_en.py
"""
import json, os, sys
try: sys.stdout.reconfigure(encoding='utf-8')
except Exception: pass

SD = os.path.dirname(os.path.abspath(__file__))
src = json.load(open(os.path.join(SD, 'notes_en_source.json'), encoding='utf-8'))
notes = {k: v for k, v in src.items() if not k.startswith('_')}

header = ('// notes_en.js — generated by build_notes_en.py from notes_en_source.json.\n'
          '// Interpretive English redrafts of your notes, keyed by item id. Do not edit\n'
          '// by hand. Re-run: python build_notes_en.py\n'
          'window.CULTURE_NOTES_EN = ')
open(os.path.join(SD, 'notes_en.js'), 'w', encoding='utf-8').write(
    header + json.dumps(notes, ensure_ascii=False, indent=1) + ';\n')
print(f'notes_en.js written: {len(notes)} English redrafts.')
