# build_script_mood.py — score film DIALOGUE mood from the local transcripts dump using the NRC
# EmoLex (English), emit script_mood.js (committed overlay, id-keyed like the other overlays).
#   window.CULTURE_SCRIPT_MOOD = { id: { v: valence0-100, e: [top,second emotion], m: emotiveWords } }
# valence = positive-vs-negative word share ("reads dark" = low). Same NRC approach as Rotation's
# lyric mood — transcripts are English subtitle scrapes, so the English lexicon fits regardless of
# the film's original language.
#
# LOCAL-ONLY: needs archive_transcripts.zip (860 MB, gitignored) + the NRC lexicon. The emitted
# script_mood.js IS committed. Prereq: `node dump_films.js` (writes .film-index.json).
# Run:  python build_script_mood.py
import zipfile, io, json, re, time, os
from collections import Counter

HERE = os.path.dirname(os.path.abspath(__file__))
ZIP = os.path.join(HERE, "archive_transcripts.zip")
FILM_INDEX = os.path.join(HERE, ".film-index.json")
OUT = os.path.join(HERE, "script_mood.js")
# NRC English wordlevel — downloaded once for the Rotation lyric-mood work; local-only.
NRC_EN = os.path.join(HERE, "..", "..", ".sptmp", "nrc", "NRC-Emotion-Lexicon",
                      "NRC-Emotion-Lexicon-Wordlevel-v0.92.txt")

COLS = ["anger", "anticipation", "disgust", "fear", "joy", "negative", "positive", "sadness", "surprise", "trust"]
POS_I, NEG_I = COLS.index("positive"), COLS.index("negative")
EMO = ["anger", "anticipation", "disgust", "fear", "joy", "sadness", "surprise", "trust"]
EMO_I = [COLS.index(e) for e in EMO]

def load_nrc():
    lex = {}
    with open(NRC_EN, encoding="utf-8") as f:
        for line in f:
            p = line.rstrip("\n").split("\t")
            if len(p) != 3 or p[2] != "1":
                continue
            row = lex.get(p[0])
            if row is None:
                row = lex[p[0]] = [0] * 10
            if p[1] in COLS:
                row[COLS.index(p[1])] = 1
    return lex

print("loading NRC English lexicon…", flush=True)
LEX = load_nrc()
print("lexicon words:", len(LEX), flush=True)

WORD_RE = re.compile(r"[a-z']+")
def score(text):
    acc = [0] * 10
    matched = 0
    for w in WORD_RE.findall(text.lower()):
        row = LEX.get(w)
        if row:
            for k in range(10):
                acc[k] += row[k]
            matched += 1
    pos, neg = acc[POS_I], acc[NEG_I]
    if pos + neg < 20:  # too few emotive words to trust a whole film
        return None
    valence = round(100 * pos / (pos + neg))
    emo_counts = sorted(((acc[i], EMO[j]) for j, i in enumerate(EMO_I)), reverse=True)
    top = [e for c, e in emo_counts[:2] if c > 0]
    return {"v": valence, "e": top, "m": matched}

# film index: normalized "title|year" -> id
def norm(s):
    return re.sub(r"[^a-z0-9]+", "", (s or "").lower())
films = json.load(open(FILM_INDEX, encoding="utf-8"))
by_key = {}
for x in films:
    by_key[norm(x["title"]) + "|" + str(x["year"] or "")] = x["id"]
print(f"film index: {len(by_key)} keys", flush=True)

# stream transcript members, score the ones that match a film in the library
z = zipfile.ZipFile(ZIP)
name_re = re.compile(r"transcripts/(.+) _(\d{4})_ - full transcript\.txt$")
out = {}
t0 = time.time(); seen = 0
for info in z.infolist():
    m = name_re.match(info.filename)
    if not m:
        continue
    seen += 1
    key = norm(m.group(1)) + "|" + m.group(2)
    fid = by_key.get(key)
    if not fid or fid in out:
        continue
    with z.open(info) as fh:
        text = io.TextIOWrapper(fh, encoding="utf-8", errors="replace").read()
    sc = score(text)
    if sc:
        out[fid] = sc
    if len(out) % 200 == 0 and len(out):
        print(f"  scored {len(out)} films… ({time.time()-t0:.0f}s)", flush=True)

header = ("// script_mood.js — generated by build_script_mood.py. Per-film dialogue mood from the\n"
          "// transcripts dump, scored with the NRC EmoLex (English). Do not edit by hand.\n"
          "//   id -> { v: lyricValence0-100 (low = reads dark), e: [top,second emotion], m: emotiveWords }\n"
          "window.CULTURE_SCRIPT_MOOD = ")
with open(OUT, "w", encoding="utf-8") as f:
    f.write(header + json.dumps(out, ensure_ascii=False, sort_keys=True) + ";\n")

vals = [v["v"] for v in out.values()]
print(f"\nDONE: {seen:,} transcripts scanned in {time.time()-t0:.0f}s · {len(out)} films scored → script_mood.js", flush=True)
print("valence mean:", round(sum(vals)/len(vals), 1) if vals else "n/a")
print("dominant emotions:", Counter(v["e"][0] for v in out.values() if v["e"]).most_common())
