#!/usr/bin/env python3
"""build_badges.py — compile badges_source.json → badges.js.

badges_source.json (the editable curation source) maps item id → list of standout
badges to ADD. enrichExtras() merges them additively into each item's `highlights`
at runtime, so they survive data re-imports and stay in one editable place.
Edit badges_source.json, then: python build_badges.py
"""
import json, os, sys
try: sys.stdout.reconfigure(encoding='utf-8')
except Exception: pass

SD = os.path.dirname(os.path.abspath(__file__))
src = json.load(open(os.path.join(SD, 'badges_source.json'), encoding='utf-8'))
src = {k: v for k, v in src.items() if not k.startswith('_') and v}

header = ('// badges.js — generated by build_badges.py from badges_source.json.\n'
          '// Curated standout-badge ADDITIONS, merged additively into each item\'s\n'
          '// `highlights` at runtime (enrichExtras). 🪞 cognitive · 💀 horrifying ·\n'
          '// 🧠 cerebral … Edit badges_source.json then re-run: python build_badges.py\n'
          'window.CULTURE_BADGES = ')
open(os.path.join(SD, 'badges.js'), 'w', encoding='utf-8').write(
    header + json.dumps(dict(sorted(src.items())), ensure_ascii=False, indent=1) + ';\n')
print(f'badges.js written: {len(src)} items.')
