#!/usr/bin/env python3
"""Turn filmweb_reviews.csv into the runtime overlay filmweb_notes.js.

  window.CULTURE_NOTES = { "<kind>/<filmwebId>": "<comment>", ... }

`kind` is film|serial|videogame (matches the Filmweb link path), so the runtime
can key by the item's link without numeric-id collisions across mediums.
enrichExtras() applies a note ONLY to items that have no hand-written note, so
curated data.js notes always win. Re-run after re-scraping: python build_filmweb_notes.py
"""
import csv, json, os, sys
try: sys.stdout.reconfigure(encoding='utf-8')
except Exception: pass

SD = os.path.dirname(os.path.abspath(__file__))
notes = {}
with open(os.path.join(SD, 'filmweb_reviews.csv'), encoding='utf-8') as f:
    for r in csv.DictReader(f):
        c = (r.get('comment') or '').strip()
        if c:
            notes[f"{r['medium']}/{r['filmwebId']}"] = c

header = ('// filmweb_notes.js — generated by build_filmweb_notes.py from your\n'
          '// scraped Filmweb opinions. Applied at runtime only where you have no\n'
          '// hand-written note. Do not edit by hand. Re-run: python build_filmweb_notes.py\n'
          'window.CULTURE_NOTES = ')
with open(os.path.join(SD, 'filmweb_notes.js'), 'w', encoding='utf-8') as f:
    f.write(header + json.dumps(notes, ensure_ascii=False, indent=1) + ';\n')

print(f'filmweb_notes.js written: {len(notes)} comments.')
