#!/usr/bin/env python3
"""Re-enrich ONLY the rows named in igdb_overrides.json, from the corrected IGDB game.

A blanket `update_igdb.py --force` would refetch all 359 games and overwrite rows that are fine.
These 17 are the rows whose payload came from the wrong product, so their cover, summary,
franchise, publisher, tags and genres are all wrong together and must be replaced as a set.
Overwrites unconditionally (unlike the normal fill-when-absent path) — that is the whole point.
"""
import json, os, re, sys, time
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), 'fuad.au', 'culture'))
import update_igdb as ug

CULT = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'fuad.au', 'culture')
CAST = os.path.join(CULT, 'cast_data.js')
OVR = os.path.join(CULT, 'igdb_overrides.json')
APPLY = '--apply' in sys.argv

CAST_FIELDS = ['igdbId', 'igdbName', 'igdbCover', 'tags', 'productionCompanies',
               'igdbPublisher', 'igdbSummary', 'igdbFranchise']

def load_cast():
    s = open(CAST, encoding='utf-8').read()
    m = re.search(r'window\.CULTURE_CAST\s*=\s*(\{[\s\S]*\});', s)
    return json.loads(m.group(1))

def patch_row_field(text, item_id, field, value):
    """Replace or insert a scalar field on the row line carrying item_id."""
    lines = text.split('\n')
    for i, ln in enumerate(lines):
        # data.js uses unquoted keys with single-quoted values (id: 'twd-game'); imports.js is
        # mostly JSON-quoted. Match either or the row is silently skipped.
        if ('"%s"' % item_id) not in ln and ("'%s'" % item_id) not in ln:
            continue
        val = json.dumps(value, ensure_ascii=False)
        pat = re.compile(r'("%s"|\b%s)\s*:\s*("(?:[^"\\]|\\.)*"|\'(?:[^\'\\]|\\.)*\'|[\d.]+)' % (field, field))
        if pat.search(ln):
            lines[i] = pat.sub(lambda m: '"%s": %s' % (field, val), ln, count=1)
        else:
            j = ln.rstrip().rfind('}')
            if j < 0:
                continue
            lines[i] = ln[:j].rstrip().rstrip(',') + ', "%s": %s' % (field, val) + ln[j:]
        return '\n'.join(lines), True
    return text, False

def main():
    env = ug.load_env()
    cid, secret = env.get('TWITCH_CLIENT_ID', ''), env.get('TWITCH_CLIENT_SECRET', '')
    token = ug.get_token(cid, secret)
    overrides = json.load(open(OVR, encoding='utf-8'))
    cast = load_cast()

    data_txt = open(os.path.join(CULT, 'data.js'), encoding='utf-8').read()
    imp_txt = open(os.path.join(CULT, 'imports.js'), encoding='utf-8').read()

    changed = 0
    for item_id, gid in overrides.items():
        r = ug.igdb_fetch_by_id(token, cid, gid)
        if not r:
            print('  FETCH FAILED %s (igdb %s)' % (item_id, gid)); continue
        enr = ug.parse_igdb_result(r)
        old = cast.get(item_id, {})
        print('%s  %r -> %r' % (item_id, old.get('igdbName'), enr.get('igdbName')))
        e = dict(old)
        for f in CAST_FIELDS:
            if f in enr:
                e[f] = enr[f]
            elif f in e:
                del e[f]          # wrong product's value with no replacement must not survive
        cast[item_id] = e
        # an empty genre string is worse than none — Minesweeper's correct match has no IGDB genres
        if enr.get('_genres'):
            for name, txt in (('data.js', data_txt), ('imports.js', imp_txt)):
                new, hit = patch_row_field(txt, item_id, 'igdbGenres', enr['_genres'])
                if hit:
                    if name == 'data.js': data_txt = new
                    else: imp_txt = new
                    print('      genres -> %s  (%s)' % (enr['_genres'], name))
                    break
        if '_rating' in enr:
            for name, txt in (('data.js', data_txt), ('imports.js', imp_txt)):
                new, hit = patch_row_field(txt, item_id, 'igdbRating', enr['_rating'])
                if hit:
                    if name == 'data.js': data_txt = new
                    else: imp_txt = new
                    break
        changed += 1
        time.sleep(0.25)

    print('\nre-enriched %d rows' % changed)
    if not APPLY:
        print('(dry run — pass --apply to write)'); return
    with open(CAST, 'w', encoding='utf-8') as f:
        f.write('// cast_data.js — generated by update_cast.py / update_igdb.py. Do not edit by hand.\n')
        f.write('// Re-run: python update_cast.py  /  python update_igdb.py\n')
        f.write('window.CULTURE_CAST = ')
        f.write(json.dumps(cast, indent=2, ensure_ascii=False))
        f.write(';\n')
    open(os.path.join(CULT, 'data.js'), 'w', encoding='utf-8').write(data_txt)
    open(os.path.join(CULT, 'imports.js'), 'w', encoding='utf-8').write(imp_txt)
    print('written')

if __name__ == '__main__':
    main()
