// ────────────────────────────────────────────────────────────────
// Culture library — Fuad's personal canon.
//
// SHAPE: { id, title, year, medium, link, poster, note?, length?, region?, rating? }
//   note   — your personal sentence/paragraph; appears in popup + Reader
//   length — how "thick" the spine renders (1 = slim, 2 = medium, 3 = thick).
//            Defaults work fine; only set if you want a specific item to feel
//            heavier or slighter than its medium would suggest.
//   region — country/region of origin (web-verified per title); colors the
//            spine in Spines / Mix mode. Recognized: 'pl','jp','kr','us','uk',
//            'fr','it','de','su','ru','au','ca','ie','il','se','fi','ch','eu',
//            'other'. Omit to use a decade-based color.
//   rating — your personal Filmweb score (0-10) from the CSV exports; shown at
//            the foot of each spine. Blank when there is no Filmweb rating.
//
// PICK ONE FOR ME pool: edit PICKABLE_IDS below to control which titles can
// be surfaced by the "Pick one for me" button. Each picked title gets a red
// pip that persists for the rest of the session.
// ────────────────────────────────────────────────────────────────

const POSTER = (n) => `https://fuad.design/Culture/${n}`;

const ITEMS = [
  // ─────────── MOVIES ───────────
  // Reordered so the centered shelf reflects Fuad's stated ranking:
  //   centre → Age of Success, then Walkabout & Fight Club to either side,
  //   then Ikiru & La Haine, then everything else.
  { id: 'age-of-success',     title: 'The Age of Success',       year: 1988, medium: 'Movies', favorite: true, region: 'kr', rating: '10', link: 'https://www.filmweb.pl/film/Songgong+sidae-1988-169765',          poster: POSTER('theageofsuccess.jpg'), note: 'Fight Club na sterydach i w wersji koreańskiej, niesamowity przekrój pogoni za sukcesem, konsumpcjonizmem, bezwzględności korporacji, hierarchi kapitalistycznej', director: 'Jang Sun-woo', fwAvg: 7.5, runtime: 110, highlights: ['direction', 'style', 'satire', 'impact', 'social-xray'] },
  { id: 'walkabout',          title: 'Walkabout',                year: 1971, medium: 'Movies', favorite: true, region: 'uk', rating: '10', link: 'https://www.filmweb.pl/film/Walkabout-1971-11531',                    poster: POSTER('walkabout.jpg'), note: 'Arcydzieło, mezalians, który nie sposób było przewidzieć - surrealistyczna kwintesencja Australii i kompletnie przenikliwie piękna proza życia na drugim krańcu.', director: 'Nicolas Roeg', fwAvg: 7.3, runtime: 95, highlights: ['visuals', 'atmosphere', 'cinematography'] },
  { id: 'fight-club',         title: 'Fight Club',               year: 1999, medium: 'Movies', favorite: true, region: 'us', rating: '10', link: 'https://www.filmweb.pl/film/Podziemny+kr%C4%85g-1999-837',         poster: POSTER('fightclub.jpg'), note: 'Exhilirating, still fresh and ahead of its time, phenomenally acted out and with a phenomenally explored core concept, Fincher\'s opus magnum', director: 'David Fincher', fwAvg: 8.3, runtime: 139, highlights: ['gem', 'style', 'cognitive'] },
  { id: 'ikiru',              title: 'Ikiru',                    year: 1952, medium: 'Movies', favorite: true, region: 'jp', rating: '10', link: 'https://www.filmweb.pl/film/Pi%C4%99tno+%C5%9Bmierci-1952-31684',     poster: POSTER('ikiru.jpg'), note: 'Film, kalibru 12 gniewnych ludzi, łączący najlepsze z najlepszych elementów kinematografii wyróżniający się najwyższej klasy walorami merytorycznymi i sztuki.', director: 'Akira Kurosawa', fwAvg: 7.9, runtime: 143, highlights: ['devastating', 'direction', 'writing'] },
  { id: 'la-haine',           title: 'La Haine',                 year: 1995, medium: 'Movies', favorite: true, region: 'fr', rating: '10', link: 'https://www.filmweb.pl/film/Nienawi%C5%9B%C4%87-1995-8106',         poster: POSTER('LaHaine.jpg'), note: 'Bardzo zgrabna narracja i reżyseria, świetnie ujęty przekrój społeczny, trochę w środku zwalniał ale ostatecznie opuściłem kino porażony, naturalizm w pełni.', director: 'Mathieu Kassovitz', fwAvg: 7.9, runtime: 98, highlights: ['style', 'intense', 'cinematography', 'impact'] },
  { id: 'possession',         title: 'Possession',               year: 1981, medium: 'Movies', favorite: true, region: 'fr', rating: '9', link: 'https://www.filmweb.pl/film/Op%C4%99tanie-1981-8801',                 poster: POSTER('possession.jpg'), note: 'Jak gdyby połączenie lśnienia z egzorcystą na najwyższych obrotach, niesamowite. Kosmiczne role, realizacja, charakteryzacja i gra aktorska. Wow.', director: 'Andrzej Żuławski', fwAvg: 7.4, runtime: 124, highlights: ['acting', 'intense', 'impact'] },
  { id: '12-angry-men',       title: '12 Angry Men',             year: 1957, medium: 'Movies', favorite: true, region: 'us', rating: '10', link: 'https://www.filmweb.pl/film/Dwunastu+gniewnych+ludzi-1957-30701', poster: POSTER('12angrymen_b.jpg'), note: 'Dosłownie, egzekucja tego formatu to kino absolutne.', director: 'Sidney Lumet', fwAvg: 8.7, runtime: 97, highlights: ['writing', 'acting', 'impact'] },
  { id: 'burning',            title: 'Burning',                  year: 2018, medium: 'Movies', favorite: true, region: 'kr', rating: '9', link: 'https://www.filmweb.pl/film/P%C5%82omienie-2018-784582',              poster: POSTER('burning.webp'), note: 'Jak wiele można przekazać przez tak subtelną i nieskazitelną pracę całej kadry, choć druga połowa mnie nie satysfakcjonowała, jest to mocno hipnotyzujące kino', director: 'Lee Chang-dong', fwAvg: 7.0, runtime: 148, highlights: ['slowburn', 'atmosphere', 'cinematography'] },
  { id: 'come-and-see',       title: 'Come and See',             year: 1985, medium: 'Movies', favorite: true, region: 'su', rating: '10', link: 'https://www.filmweb.pl/film/Id%C5%BA+i+patrz-1985-35185',          poster: POSTER('comeandsee_b.jpg'), director: 'Elem Klimov', fwAvg: 8.2, runtime: 142, studio: 'Mosfilm', highlights: ['devastating', 'intense', 'acting', 'cinematography', 'impact', 'singular'] },
  { id: 'red-desert',         title: 'Red Desert',               year: 1964, medium: 'Movies', favorite: true, region: 'it', rating: '9', link: 'https://www.filmweb.pl/film/Czerwona+pustynia-1964-33487',            poster: POSTER('reddesert.jpg'), note: 'Turboklimatyczna i arcypiękna reżyseria, lecąca krok w krok za kunsztem aktorskim i podstawą filmu, rozbudowującą się z czasem, a z jaką wyjątkową subtelnością.', director: 'Michelangelo Antonioni', fwAvg: 7.3, runtime: 117, highlights: ['visuals', 'atmosphere', 'cinematography'] },
  { id: 'human-condition',    title: 'The Human Condition I',    year: 1959, medium: 'Movies', favorite: true, region: 'jp', rating: '10', link: 'https://www.filmweb.pl/film/Dola+cz%C5%82owiecza+I+-+Nie+ma+wi%C4%99kszej+mi%C5%82o%C5%9Bci-1958-94613', poster: POSTER('human_condition.webp'), note: 'Bezbłędna kinematografia, pomimo 3.5h dłużyzny się nie czuje, gra aktorska stoi bardzo wysoko, a sam motyw przewodni ujmuje mocno w przedstawionych realiach', director: 'Masaki Kobayashi', fwAvg: 8.0, runtime: 204, highlights: ['direction', 'cinematography', 'impact'], enTitle: 'The Human Condition I: No Greater Love' },
  { id: 'clockwork-orange',   title: 'A Clockwork Orange',       year: 1971, medium: 'Movies', favorite: true, region: 'uk', rating: '10', link: 'https://www.filmweb.pl/film/Mechaniczna+pomara%C5%84cza-1971-1275', poster: POSTER('aclockworkorange.webp'), note: 'Style is groundbreaking here', director: 'Stanley Kubrick', fwAvg: 7.9, runtime: 137, highlights: ['style', 'singular'] },
  { id: 'network',            title: 'Network',                  year: 1976, medium: 'Movies', favorite: true, region: 'us', rating: '10', link: 'https://www.filmweb.pl/film/Sie%C4%87-1976-35352',                  poster: POSTER('network.jpg'), note: 'Kapitalna dekompozycja mediów, z wieloma momentami, które kompletnie powalają na kolana. Niesamowicie napisane monologi i porażająca gra aktorska.', director: 'Sidney Lumet', fwAvg: 7.5, runtime: 122, highlights: ['writing', 'ahead', 'impact', 'gem'] },
  { id: 'the-housemaid',      title: 'The Housemaid',            year: 1960, medium: 'Movies', favorite: true, region: 'kr', rating: '10', link: 'https://www.filmweb.pl/film/Pokoj%C3%B3wka-1960-232044',             poster: POSTER('pokojowka.jpg'), note: 'Ten film jest wybitną pozycją, poraża jakością wykonania, treścią i egzekucją całego formatu, który praktycznie nie gaśnie przez cały runtime', director: 'Kim Ki-young', fwAvg: 7.2, runtime: 112, highlights: ['intense', 'direction'] },
  { id: 'woman-under',        title: 'A Woman Under the Influence', year: 1974, medium: 'Movies', favorite: true, region: 'us', rating: '10', link: 'https://www.filmweb.pl/film/Kobieta+pod+presj%C4%85-1974-105724', poster: POSTER('awomanundertheinfluence.jpg'), note: 'Jeden z tych filmów, które są bardzo dobre, ale obiera kierunek tematyczny, który praktycznie wyczerpuje w pełni - porażające role, wykonanie i dynamika postaci', director: 'John Cassavetes', fwAvg: 7.8, runtime: 155, highlights: ['acting', 'devastating', 'gem'] },
  { id: 'oldboy',             title: 'Oldboy',                   year: 2003, medium: 'Movies', favorite: true, region: 'kr', rating: '9', link: 'https://www.filmweb.pl/film/Oldboy-2003-115059',                    poster: POSTER('oldboy.jpg'), note: 'Dużo tutaj wyszło wyjątkowo, reżyseria przede wszystkim i balansowanie między komedią a dramatem, ale końcówka rozwaliła mnie jak nic od dawien dawna', director: 'Park Chan-wook', fwAvg: 7.7, runtime: 120, highlights: ['gem', 'intense', 'mindbending', 'cinematography', 'cognitive'] },
  { id: 'face-of-another',    title: 'The Face of Another',      year: 1966, medium: 'Movies', favorite: true, region: 'jp', rating: '10', link: 'https://www.filmweb.pl/film/Twarz+innego-1966-40633',               poster: POSTER('thefaceofanother.jpg'), note: 'Ciężki, ze wspaniałą reżyserią i pociskiem merytorycznym, który ciąży mocno.', director: 'Hiroshi Teshigahara', fwAvg: 7.8, runtime: 122, highlights: ['cerebral', 'visuals', 'impact'] },
  { id: '2001-space',         title: '2001: A Space Odyssey',    year: 1968, medium: 'Movies', favorite: true, region: 'us', rating: '10', link: 'https://www.filmweb.pl/film/2001%3A+Odyseja+kosmiczna-1968-1458',     poster: POSTER('spaceoddysey.jpg'), note: 'Biorąc pod uwage, że to film z 1968... niech będzie 10/10, ale ten finał... na wyrost te 10/10 :<', director: 'Stanley Kubrick', fwAvg: 7.7, runtime: 149, highlights: ['visuals', 'ahead', 'cinematography', 'singular'] },
  { id: 'short-film-killing', title: 'A Short Film About Killing', year: 1988, medium: 'Movies', favorite: true, region: 'pl', rating: '10', link: 'https://www.filmweb.pl/film/Kr%C3%B3tki+film+o+zabijaniu-1987-1157', poster: POSTER('ashortfilmaboutkilling.jpg'), note: 'Reżyseria i kinematografia to coś szczególnego, ale wyczerpanie tematu i jego naprawdę ostra i dogłębna wiwisekcja - wszystko robią piorunujące wrażenie', director: 'Krzysztof Kieślowski', fwAvg: 7.9, runtime: 85, highlights: ['intense', 'direction', 'impact'] },
  { id: 'the-shining',        title: 'The Shining',              year: 1980, medium: 'Movies', favorite: true, region: 'us', rating: '10', link: 'https://www.filmweb.pl/film/L%C5%9Bnienie-1980-1020',                poster: POSTER('theshining.webp'), note: 'Performances of the leading actors are some of the best Ive seen', director: 'Stanley Kubrick', fwAvg: 7.8, runtime: 144, highlights: ['atmosphere', 'direction', 'cinematography', 'acting'] },
  { id: 'apocalypse-now',     title: 'Apocalypse Now',           year: 1979, medium: 'Movies', favorite: true, region: 'us', rating: '9', link: 'https://www.filmweb.pl/film/Czas+Apokalipsy-1979-1092',             poster: POSTER('czasapokalipsy.jpg'), note: 'Progresja, głębia, groteska, ciężka atmosfera, produkcja równa tematyce samego filmu, artyzm, wielowymiarowy wydźwięk, psychologiczne nuty i świetna adaptacja', director: 'Francis Ford Coppola', fwAvg: 8.2, runtime: 147, highlights: ['visuals', 'atmosphere', 'cinematography'] },
  { id: 'escape-cinema',      title: 'Escape from the Liberty Cinema', year: 1990, medium: 'Movies', favorite: true, region: 'pl', rating: '9', link: 'https://www.filmweb.pl/film/Ucieczka+z+kina+%22Wolno%C5%9B%C4%87%22-1990-1181', poster: POSTER('ucieczkazkinawolnosc.webp'), note: 'Uuu jakie mezaliansy narracyjne, materia się ożywiła :)', director: 'Wojciech Marczewski', fwAvg: 7.5, runtime: 87, studio: 'Studio Filmowe Perspektywa', highlights: ['cerebral', 'mindbending'] },
  { id: 'platoon',            title: 'Platoon',                  year: 1986, medium: 'Movies', favorite: true, region: 'us', rating: '7', link: 'https://www.filmweb.pl/film/Pluton-1986-1068',                       poster: POSTER('pluton.jpg'), note: 'Amazing poster :)', director: 'Oliver Stone', fwAvg: 8.1, runtime: 120, highlights: ['intense'] },
  { id: 'no-country',         title: 'No Country for Old Men',   year: 2007, medium: 'Movies', favorite: true, region: 'us', rating: '10', link: 'https://www.filmweb.pl/film/To+nie+jest+kraj+dla+starych+ludzi-2007-259289', poster: POSTER('nocountryforoldmen.webp'), note: 'The flow of the movie and characters are riveting', director: 'Coen Brothers', fwAvg: 7.6, runtime: 122, highlights: ['direction', 'intense'] },
  { id: 'deer-hunter',        title: 'The Deer Hunter',          year: 1978, medium: 'Movies', favorite: true, region: 'us', rating: '9', link: 'https://www.filmweb.pl/film/%C5%81owca+jeleni-1978-1045',           poster: POSTER('thedeerhunter.webp'), note: 'Felt very complete and captures the scale and changes at an incredible level', director: 'Michael Cimino', fwAvg: 8.1, runtime: 183, highlights: ['devastating', 'acting'] },
  { id: 'shame',              title: 'Shame',                    year: 2011, medium: 'Movies', favorite: true, region: 'uk', rating: '9', link: 'https://www.filmweb.pl/film/Wstyd-2011-601499',                      poster: POSTER('shame_2.jpg'), note: 'Piorunujące role główne, bardzo mocny scenariusz i scenografia, i realizacja wgniatają w fotel w tandemie z wręcz pedantycznie uchwyconymi detalami.', director: 'Steve McQueen', fwAvg: 6.8, runtime: 102, highlights: ['acting', 'cinematography', 'impact', 'devastating'] },
  // { id: 'three-colors-white', title: 'Three Colors: White',      year: 1994, medium: 'Movies', favorite: true, region: 'pl', link: 'https://www.filmweb.pl/film/Trzy+kolory%3A+Bia%C5%82y-1994-1160',   poster: POSTER('trzykolorybialy.webp'), fwAvg: 7.7, runtime: 92, highlights: ['direction'] },
  { id: 'weather-forecast',   title: 'Weather Forecast',         year: 1982, medium: 'Movies', favorite: true, region: 'pl', rating: '9', link: 'https://www.filmweb.pl/film/Prognoza+pogody-1982-8900',              poster: POSTER('prognozapogody.webp'), note: 'Polski lot nad kukułczym gniazdem', director: 'Antoni Krauze', fwAvg: 6.7, watchedDate: '2020-09-18', studio: 'Studio TOR', highlights: ['atmosphere'], enTitle: 'The Weather Forecast' },
  { id: 'pygmalion',          title: 'Pygmalion',                year: 1938, medium: 'Movies', favorite: true, region: 'uk', rating: '9', link: 'https://www.filmweb.pl/film/Pigmalion-1938-126074',                  poster: POSTER('pygmalion.webp'), note: 'Zaskakująco świetny warsztat reżyserski i aktorski, z opowieścią, którą można nazwać sztandarowym klasykiem - pięknym i z wielotorowością podbijającą stawkę.', director: 'Anthony Asquith', fwAvg: 7.5, runtime: 96, highlights: ['writing'] },
  { id: 'limelight',          title: 'Limelight',                year: 1952, medium: 'Movies', favorite: true, region: 'us', rating: '9', link: 'https://www.filmweb.pl/film/%C5%9Awiat%C5%82a+rampy-1952-91770',     poster: POSTER('Limelight.jpg'), note: 'Fantastic character Arc', director: 'Charlie Chaplin', fwAvg: 7.9, runtime: 137, highlights: ['devastating', 'writing'] },
  { id: 'cinema-paradiso',    title: 'Cinema Paradiso',          year: 1988, medium: 'Movies', favorite: true, region: 'it', rating: '9', link: 'https://www.filmweb.pl/film/Cinema+Paradiso-1988-8228',              poster: POSTER('CinemaParadiso_2.jpg'), note: 'The reason "Nuovo Cinema Paradiso" plays in my head every time a film ends.', director: 'Giuseppe Tornatore', fwAvg: 8.1, runtime: 124 , watchedDate: '2023-02-13', highlights: ['score', 'gem'] },
  { id: 'tar',                title: 'Tár',                      year: 2022, medium: 'Movies', favorite: true, region: 'us', rating: '9', link: 'https://www.filmweb.pl/film/T%C3%A1r-2022-10016709',                 poster: POSTER('tar.jpg'), note: 'Kapitalny mariaż subtelności wszelakich, w punkt i meandruje wszerz najróżniejszych zawiłości, ale trochę trafił donikąd i brakuje punktu nad i.', director: 'Todd Field', fwAvg: 7.1, runtime: 158, highlights: ['acting', 'cerebral'], enTitle: 'TÁR' },
  { id: 'corpus-christi',     title: 'Corpus Christi',           year: 2019, medium: 'Movies', favorite: true, region: 'pl', rating: '9', link: 'https://www.filmweb.pl/film/Bo%C5%BCe+Cia%C5%82o-2019-808863',       poster: POSTER('bozecialo.jpg'), note: 'Świetny warsztat, kinematografia, światło. Bardzo naturalnie zagrany i silnie odwzorowany portret społeczny, film zostawia widza z wieloma przemyśleniami', director: 'Jan Komasa', fwAvg: 7.7, runtime: 116, watchedDate: '2020-11-02', highlights: ['acting', 'direction'] },
  { id: 'there-will-be-blood',title: 'There Will Be Blood',      year: 2007, medium: 'Movies', favorite: true, region: 'us', rating: '9', link: 'https://www.filmweb.pl/film/A%C5%BC+poleje+si%C4%99+krew-2007-239166', poster: POSTER('lettherebeblood.webp'), note: 'Klimat i atmosferę można wręcz gryźć tak gęste. Rozpiętość fabularna robi wrażenie, również kompletność tejże. Świetna gra aktorska i pewnego rodzaju naturalizm', director: 'Paul Thomas Anderson', fwAvg: 7.8, runtime: 158, highlights: ['acting', 'score', 'cinematography'] },
  { id: 'blade-runner-2049',  title: 'Blade Runner 2049',        year: 2017, medium: 'Movies', favorite: true, region: 'us', rating: '9', link: 'https://www.filmweb.pl/film/Blade+Runner+2049-2017-630798',          poster: POSTER('bladerunner2049.jpg'), note: 'Dawno czegoś takiego nie widziałem. Podbudowane ambrozją iluzji, o dużej dozie świeżości. Paradoksalnie brakowało atmosfery i to zwieńczenie.. Poproszę więcej!', director: 'Denis Villeneuve', fwAvg: 7.5, runtime: 164, highlights: ['visuals', 'atmosphere', 'cinematography', 'gem'] },

  // ─────────── TV ───────────
  { id: 'dekalog',            title: 'Dekalog',                  year: 1989, medium: 'TV',     favorite: true, region: 'pl', rating: '10', link: 'https://www.imdb.com/title/tt0092337/',                              poster: POSTER('dekalog.jpg'), length: 3, note: 'Unlike anything I have seen, unbelievable execution of an incredible concept', director: 'Krzysztof Kieślowski', studio: 'TVP', totalMinutes: 550, highlights: ['writing', 'devastating', 'singular'] },
  { id: 'black-mirror',       title: 'Black Mirror',             year: 2011, medium: 'TV',     favorite: true, region: 'uk', rating: '10', link: 'https://www.filmweb.pl/serial/Czarne+lustro-2011-640699',            poster: POSTER('blackmirror_2.jpg'), length: 2, note: 'Przyszły fenomen na skalę Breaking Bad...', director: 'Charlie Brooker', studio: 'Netflix', totalMinutes: 1485, highlights: ['gem', 'cerebral', 'impact'] },
  { id: 'westworld',          title: 'Westworld',                year: 2016, medium: 'TV',     favorite: true, region: 'us', rating: '10', link: 'https://www.filmweb.pl/serial/Westworld-2016-232988',                poster: POSTER('westworld.jpg'), length: 2 , note: 'Totalny zachwyt nad scenariuszem i egzekucją tej niezwykle ambitnej produkcji, z jej wszystkimi szczegółami, subtelnościami i wielowymiarową głębią.', director: 'Jonathan Nolan', studio: 'HBO', totalMinutes: 1620, highlights: ['gem', 'mindbending', 'impact'] },
  { id: 'green-planet',       title: 'The Green Planet',         year: 2022, medium: 'TV',     favorite: true, region: 'uk', rating: '10', link: 'https://www.filmweb.pl/serial/Zielona+planeta-2021-867712',          poster: POSTER('greenplanet.jpg'), length: 1, note: 'Wybitny, przebili Planet Earth 2, najlepsza scenografia i kinematografia jaką widziałem na ekranie, a w całej reszcie przebijają zenit wyjątkowo często.', director: 'David Attenborough', studio: 'BBC', totalMinutes: 225, highlights: ['visuals', 'singular'] },
  { id: 'breaking-bad',       title: 'Breaking Bad',             year: 2008, medium: 'TV',     favorite: true, region: 'us', rating: '9', link: 'https://www.filmweb.pl/serial/Breaking+Bad-2008-430668',             poster: POSTER('breakingbad.jpg'), length: 3, note: 'Kapitalny.', director: 'Vince Gilligan', studio: 'AMC', totalMinutes: 2790, highlights: ['writing', 'acting', 'impact'] },
  { id: 'planet-earth-ii',    title: 'Planet Earth II',          year: 2016, medium: 'TV',     favorite: true, region: 'uk', rating: '9', link: 'https://www.filmweb.pl/serial/Planeta+Ziemia+II-2016-777975',        poster: POSTER('planetearthII.jpg'), length: 1 , note: 'Absolutnie przepiękny, podbija wysoko zawieszoną poprzeczkę jedynki wprowadzając mixy fabularne naturalnie występujące przy tym trzymając najwyższą klasę roboty', director: 'David Attenborough', studio: 'BBC', totalMinutes: 270, highlights: ['visuals'] },
  { id: 'six-feet-under',     title: 'Six Feet Under',           year: 2001, medium: 'TV',     favorite: true, region: 'us', rating: '8', link: 'https://www.filmweb.pl/serial/Sze%C5%9B%C4%87+st%C3%B3p+pod+ziemi%C4%85-2001-89546', poster: POSTER('sixfeetunder.jpg'), length: 3, note: 'Odpala petardą i wieńczy petardą, bywa i lepiej i gorzej, ale jako koncept i miks groteski zrealizowanej w niesamowitym stylu, jest w nim coś niepowtarzalnego.', director: 'Alan Ball', studio: 'HBO', totalMinutes: 2835, highlights: ['writing', 'devastating'] },
  { id: 'sopranos',           title: 'The Sopranos',             year: 1999, medium: 'TV',     favorite: true, region: 'us', rating: '9', link: 'https://www.filmweb.pl/serial/Rodzina+Soprano-1999-35405',           poster: POSTER('TheSopranos.jpg'), length: 3, note: 'It is just great and last season gets incredibly creative', director: 'David Chase', studio: 'HBO', totalMinutes: 3870, highlights: ['writing', 'acting'] },
  { id: 'fallout',            title: 'Fallout',                  year: 2024, medium: 'TV',     favorite: true, region: 'us', rating: '9', link: 'https://www.filmweb.pl/serial/Fallout-2024-867454',                  poster: POSTER('Fallout.jpg'), length: 1, note: 'How to make a proper video game adaptation?', director: 'Jonathan Nolan', studio: 'Prime Video', totalMinutes: 720, highlights: ['style', 'impact', 'intense'] },
  { id: 'the-expanse',        title: 'The Expanse',              year: 2015, medium: 'TV',     favorite: true, region: 'us', rating: '9', link: 'https://www.filmweb.pl/serial/The+Expanse-2015-721026',              poster: POSTER('TheExpanse.jpg'), length: 3, note: 'Mało znani, dobrze grający aktorzy, wielowarstwowa i przestrzenna fabuła, stosunkowo finezyjnie prowadzona reżyseria. O takie sci-fi nic nie robiłem ( :', director: 'Mark Fergus', studio: 'Prime Video', totalMinutes: 2790, highlights: ['visuals'] },
  { id: 'twin-peaks',         title: 'Twin Peaks',               year: 1990, medium: 'TV',     favorite: true, region: 'us', rating: '8', link: 'https://www.filmweb.pl/serial/Miasteczko+Twin+Peaks-1990-37003',     poster: POSTER('TwinPeaks.jpg'), length: 3, director: 'David Lynch', studio: 'Showtime', totalMinutes: 2160, highlights: ['atmosphere', 'gem'] },
  { id: 'the-wire',           title: 'The Wire',                 year: 2002, medium: 'TV',     favorite: true, region: 'us', rating: '9', link: 'https://www.filmweb.pl/serial/Prawo+ulicy-2002-87721',               poster: POSTER('thewire_2.jpg'), length: 3, director: 'David Simon', studio: 'HBO', totalMinutes: 2700, highlights: ['writing', 'gem'] },
  { id: 'band-of-brothers',   title: 'Band of Brothers',         year: 2001, medium: 'TV',     favorite: true, region: 'us', rating: '9', link: 'https://www.filmweb.pl/serial/Kompania+braci-2001-35584',            poster: POSTER('bandofbrothers.jpg'), length: 2, director: 'Steven Spielberg', studio: 'HBO', totalMinutes: 450, highlights: ['intense'] },
  { id: 'mr-robot',           title: 'Mr. Robot',                year: 2015, medium: 'TV',     favorite: true, region: 'us', rating: '9', link: 'https://www.filmweb.pl/serial/Mr.+Robot-2015-733795',                poster: POSTER('MrRobot.webp'), length: 2, director: 'Sam Esmail', studio: 'USA Network', totalMinutes: 2025, highlights: ['gem', 'style', 'cognitive'] },
  { id: 'the-shield',         title: 'The Shield',               year: 2002, medium: 'TV',     favorite: true, region: 'us', rating: '8', link: 'https://www.filmweb.pl/serial/%C5%9Awiat+gliniarzy-2002-114052',     poster: POSTER('theshield.jpg'), length: 3, note: 'The ride culminates so well that other shows should keep this on repeat', director: 'Shawn Ryan', studio: 'FX', totalMinutes: 3960, highlights: ['intense'] },
  { id: 'in-treatment',       title: 'In Treatment',             year: 2011, medium: 'TV',     favorite: true, region: 'pl', rating: '9', link: 'https://www.filmweb.pl/serial/Bez+tajemnic-2011-607039',             poster: POSTER('beztajemnic.jpg'), length: 1, note: 'Struktura serialu jest silna scenariuszem, obsadzonymi postaciami oraz silnym ugruntowaniem w psychologii, choć raczej wybiórczo i powierzchownie rollowanej.', director: 'Hagai Levi', studio: 'TVP', totalMinutes: 2875, highlights: ['acting', 'writing'] },
  { id: 'pitbull',            title: 'PitBull',                  year: 2005, medium: 'TV',     favorite: true, region: 'pl', rating: '8', link: 'https://www.filmweb.pl/serial/PitBull-2005-282083',                  poster: POSTER('Pitbull.jpg'), length: 2, note: 'Klimatyczny, szorstki, realistyczny - znakomite zobrazowanie postkomunistycznej rzeczywistości z policyjnej strony', director: 'Patryk Vega', studio: 'TVP', totalMinutes: 1395, enTitle: 'Pitbull', highlights: ['atmosphere'] },
  { id: 'dead-set',           title: 'Dead Set',                 year: 2008, medium: 'TV',     favorite: true, region: 'uk', rating: '9', link: 'https://www.filmweb.pl/serial/W+domu+zombie-2008-491355',            poster: POSTER('deadset.jpg'), length: 1, note: 'Świetnie napisany, świetny aktorsko, denerwująca reżyseria i telepanie kamerą, ogółem bardzo miłe zaskoczenie i jeden z lepszych zombie-seansów jakie widziałem', director: 'Charlie Brooker', studio: 'E4', totalMinutes: 150, highlights: ['intense', 'writing'] },
  { id: 'fargo',              title: 'Fargo',                    year: 2014, medium: 'TV',     favorite: true, region: 'us', rating: '9', link: 'https://www.filmweb.pl/serial/Fargo-2014-688850',                    poster: POSTER('fargo.jpg'), length: 2, note: 'Keeps surprising with each season really, keeping Coen Brothers vibes alive', director: 'Noah Hawley', studio: 'FX', totalMinutes: 2295, highlights: ['writing', 'style'] },
  { id: 'dark',               title: 'Dark',                     year: 2017, medium: 'TV',     favorite: true, region: 'de', rating: '8', link: 'https://www.filmweb.pl/serial/Dark-2017-771383',                     poster: POSTER('Dark.jpg'), length: 2, note: 'Seriously mindbending.', director: 'Baran bo Odar', studio: 'Netflix', totalMinutes: 1170, highlights: ['mindbending', 'atmosphere'] },
  { id: 'chernobyl',          title: 'Chernobyl',                year: 2019, medium: 'TV',     favorite: true, region: 'us', rating: '8', link: 'https://www.filmweb.pl/serial/Czarnobyl-2019-799827',                poster: POSTER('czarnobyl.jpg'), length: 1, note: 'Taki brytyjski ten Czernobyl taki. Poza tym, porządnie wykonany, trailery zapowiadały coś bardziej przerażającego, wyszło mniej ale jest dobrze.', director: 'Craig Mazin', studio: 'HBO', totalMinutes: 225, highlights: ['impact', 'cinematography'] },
  { id: 'skins',              title: 'Skins',                    year: 2007, medium: 'TV',     favorite: true, region: 'uk', rating: '8', link: 'https://www.filmweb.pl/serial/Kumple-2007-378865',                   poster: POSTER('Skins.webp'), length: 2, note: 'Późno się wziąłem, a szkoda. Pierwsze 2 sezony stały silną konstrukcją postaci, mocno przerysowanymi, choć wiarygodnymi historiami i szeroko ujętą problematyką.', director: 'Bryan Elsley', studio: 'E4', totalMinutes: 2684, highlights: ['impact'] },
  { id: 'severance',          title: 'Severance',                year: 2022, medium: 'TV',     favorite: true, region: 'us', rating: '8', link: 'https://www.filmweb.pl/serial/Rozdzielenie-2022-878161',             poster: POSTER('Severance.jpg'), length: 2, note: 'Całkiem ładnie eksploruje zakątki korporacyjnej kultury, trochę zbyt subtelnie jeździ po bandzie, ale z finałem, który jednak odpalił', director: 'Dan Erickson', studio: 'Apple TV+', totalMinutes: 855, highlights: ['mindbending', 'style'] },
  { id: 'vietnam-war',        title: 'The Vietnam War',          year: 2017, medium: 'TV',     favorite: true, region: 'us', rating: '9', link: 'https://www.filmweb.pl/serial/Wojna+wietnamska%3A+film+Kena+Burnsa+i+Lynn+Novick-2017-641457', poster: POSTER('vietnamwar.jpg'), length: 2, director: 'Ken Burns', studio: 'PBS', totalMinutes: 450, highlights: ['devastating'] },
  { id: 'lost',               title: 'Lost',                     year: 2004, medium: 'TV',     favorite: true, region: 'us', rating: '8', link: 'https://www.filmweb.pl/serial/Zagubieni-2004-133834',                poster: POSTER('Lost.jpg'), length: 3, director: 'J.J. Abrams', studio: 'ABC', totalMinutes: 5310, highlights: ['atmosphere'] },
  { id: 'squid-game',         title: 'Squid Game',               year: 2021, medium: 'TV',     favorite: true, region: 'kr', rating: '8', link: 'https://www.filmweb.pl/serial/Squid+Game-2021-841842',               poster: POSTER('squidgame.jpg'), length: 1, note: 'Charakteryzacja nie z tej ziemi, a przede wszystkim oryginał, wykonany piorunująco dobrze, z gigantyczną ilością wątków socjo-polityczno-ekonomicznych, klasyk.', director: 'Hwang Dong-hyuk', studio: 'Netflix', totalMinutes: 990, highlights: ['visuals', 'impact'] },
  { id: 'blinded-by-lights',  title: 'Blinded by the Lights',    year: 2018, medium: 'TV',     favorite: true, region: 'pl', rating: '8', link: 'https://www.filmweb.pl/serial/%C5%9Alepn%C4%85c+od+%C5%9Bwiate%C5%82-2018-786525', poster: POSTER('SlepnacodSwiatel.jpg'), length: 1, note: 'Dobrze wykreowana rzeczywistość, ale mocno nierówna egzekucja. Wiele błędów warsztatowych, ale ogółem serial się broni.', director: 'Krzysztof Skonieczny', studio: 'Canal+', totalMinutes: 440, highlights: ['style'] },
  { id: 'cosmos',             title: 'Cosmos: A Spacetime Odyssey', year: 2014, medium: 'TV', favorite: true, region: 'us', rating: '9', link: 'https://www.filmweb.pl/serial/Kosmos-2014-696381',                    poster: POSTER('cosmos.webp'), length: 1, director: 'Ann Druyan', studio: 'National Geographic', totalMinutes: 1170, highlights: ['cerebral', 'visuals'], enTitle: 'Cosmos' },
  { id: 'atlanta',            title: 'Atlanta',                  year: 2016, medium: 'TV',     favorite: true, region: 'us', rating: '9', link: 'https://www.filmweb.pl/serial/Atlanta-2016-767468',                  poster: POSTER('Atlanta.jpg'), length: 2, note: 'Zaskakująco naturalny, bardzo fajnie zagrane role, ciekawy scenariusz pełny jakiegoś takiego pokręconego naturalizmu', director: 'Donald Glover', studio: 'FX', totalMinutes: 902, highlights: ['style'] },
  { id: 'mad-men',            title: 'Mad Men',                  year: 2007, medium: 'TV',     favorite: true, region: 'us', rating: '9', link: 'https://www.filmweb.pl/serial/Mad+Men-2007-436999',                  poster: POSTER('madmen.jpg'), length: 3, director: 'Matthew Weiner', studio: 'AMC', totalMinutes: 4140, highlights: ['writing', 'style'] },
  { id: 'watchmen',           title: 'Watchmen',                 year: 2019, medium: 'TV',     favorite: true, region: 'us', rating: '9', link: 'https://www.filmweb.pl/serial/Watchmen-2019-809681',                 poster: POSTER('watchmen.jpg'), length: 1, note: 'Zdecydowana superprodukcja, fenomenalna charakteryzacja, bardzo spójna i fascynująca wizja artystyczna z pewnymi niedociągnięciami ale najwyższej klasy jakością', director: 'Damon Lindelof', studio: 'HBO', totalMinutes: 405, highlights: ['writing', 'style'] },
  { id: 'true-detective',     title: 'True Detective',           year: 2014, medium: 'TV',     favorite: true, region: 'us', rating: '8', link: 'https://www.filmweb.pl/serial/Detektyw-2014-654010',                 poster: POSTER('truedetective.webp'), length: 1, director: 'Nic Pizzolatto', studio: 'HBO', totalMinutes: 1350, highlights: ['atmosphere', 'acting'] },
  { id: 'utopia',             title: 'Utopia',                   year: 2013, medium: 'TV',     favorite: true, region: 'uk', rating: '8', link: 'https://www.filmweb.pl/serial/Utopia-2013-663388',                   poster: POSTER('Utopia.jpg'), length: 1, note: 'Kolory, OST i kreatywne, świeże podejście sprawia, że jest w tym serialu sporo magii', director: 'Dennis Kelly', studio: 'Channel 4', totalMinutes: 600, highlights: ['style', 'intense', 'visuals', 'score', 'gem'] },
  { id: 'bojack',             title: 'BoJack Horseman',          year: 2014, medium: 'TV',     favorite: true, region: 'us', rating: '8', link: 'https://www.filmweb.pl/serial/BoJack+Horseman-2014-718443',          poster: POSTER('Bojack.jpg'), length: 2, director: 'Raphael Bob-Waksberg', studio: 'Netflix', totalMinutes: 1748, highlights: ['devastating', 'writing'] },
  { id: 'better-call-saul',   title: 'Better Call Saul',         year: 2015, medium: 'TV',     favorite: true, region: 'us', rating: '8', link: 'https://www.filmweb.pl/serial/Zadzwo%C5%84+do+Saula-2015-697645',    poster: POSTER('bettercallsaul.jpg'), length: 3, note: 'Z każdym kolejnym sezonem robi się coraz lepszy, chociaż w porównaniu do Breaking Bad, Better Call Saul zaczynał z dosyć skromnego pułapu.', director: 'Vince Gilligan', studio: 'AMC', totalMinutes: 2835, highlights: ['writing', 'acting'] },
  { id: 'fleabag',            title: 'Fleabag',                  year: 2016, medium: 'TV',     favorite: true, region: 'uk', rating: '9', link: 'https://www.filmweb.pl/serial/Fleabag-2016-769619',                  poster: POSTER('fleabag.jpg'), length: 1, note: 'Mocno nafaszerowany, świetnie zaaranżowanym, skomponowanym contentem, który zagrany jest niemal bezbłędnie, bardzo naturalny w odbiorze i scenariusz mistrzowski', director: 'Phoebe Waller-Bridge', studio: 'BBC Three', totalMinutes: 264, highlights: ['writing', 'funny'] },

  // ─────────── GAMES ───────────
  { id: 'spec-ops',           title: 'Spec Ops: The Line',       year: 2012, medium: 'Games',  favorite: true, region: 'de', rating: '8', link: 'https://www.filmweb.pl/videogame/Spec+Ops%3A+The+Line-2012-615645', poster: POSTER('specopstheline.jpg'), director: 'Cory Davis', studio: 'Yager Development', igdbRating: 79, igdbGenres: 'Shooter, Arcade', highlights: ['writing', 'gem', 'devastating', 'cerebral', 'singular', 'cognitive'] },
  { id: 'tlou2',              title: 'The Last of Us Part II',   year: 2020, medium: 'Games',  favorite: true, region: 'us', rating: '10', link: 'https://www.filmweb.pl/videogame/The+Last+of+Us+Part+II-2020-775468', poster: POSTER('thelastofuspart2.jpg'), director: 'Neil Druckmann', studio: 'Naughty Dog', igdbRating: 93, igdbGenres: 'Shooter, Arcade', highlights: ['devastating', 'visuals', 'intense', 'impact', 'cerebral', 'cognitive'] },
  { id: 'twd-game',           title: 'The Walking Dead: S1',     year: 2012, medium: 'Games',  favorite: true, region: 'us', rating: '9', link: 'https://www.filmweb.pl/videogame/The+Walking+Dead%3A+Season+One-2012-631588', poster: POSTER('thewalkingdeadthegame.jpg'), director: 'Sean Vanaman', studio: 'Telltale Games', highlights: ['devastating', 'writing', 'impact'] },
  { id: 'undertale',          title: 'Undertale',                year: 2015, medium: 'Games',  favorite: true, region: 'us', rating: '9', link: 'https://www.filmweb.pl/videogame/Undertale-2015-715189',             poster: POSTER('undertale.png'), director: 'Toby Fox', igdbRating: 91, igdbGenres: 'Puzzle, RPG, Arcade, Visual Novel', highlights: ['writing', 'singular', 'impact'] },
  { id: 'antichamber',        title: 'Antichamber',              year: 2013, medium: 'Games',  favorite: true, region: 'au', rating: '10', link: 'https://www.filmweb.pl/videogame/Antichamber-2013-680088',          poster: POSTER('Antichamber.jpg'), director: 'Alexander Bruce', igdbRating: 82, igdbGenres: 'Platform, Puzzle, Arcade, Visual Novel', highlights: ['mindbending', 'cognitive'] },
  { id: 'max-payne',          title: 'Max Payne',                year: 2001, medium: 'Games',  favorite: true, region: 'fi', rating: '10', link: 'https://www.filmweb.pl/videogame/Max+Payne-2001-607023',             poster: POSTER('MaxPayne.jpg'), studio: 'Remedy Entertainment', igdbGenres: 'Shooter, Arcade', highlights: ['style', 'atmosphere', 'writing', 'impact'] },
  { id: 'wic',                title: 'World in Conflict',        year: 2007, medium: 'Games',  favorite: true, region: 'se', rating: '9', link: 'https://www.filmweb.pl/videogame/World+in+Conflict-2007-608112',     poster: POSTER('worldinconflict.jpg'), studio: 'Massive Entertainment', igdbRating: 87, igdbGenres: 'RTS, Strategy' },
  { id: 'tlou',               title: 'The Last of Us',           year: 2013, medium: 'Games',  favorite: true, region: 'us', rating: '9', link: 'https://www.filmweb.pl/videogame/The+Last+of+Us-2013-642590',        poster: POSTER('TheLastofUs.jpg'), director: 'Neil Druckmann', studio: 'Naughty Dog', igdbRating: 92, igdbGenres: 'Shooter, Arcade', highlights: ['atmosphere', 'writing', 'impact'] },
  { id: 'edith-finch',        title: 'What Remains of Edith Finch', year: 2017, medium: 'Games', favorite: true, region: 'us', rating: '9', link: 'https://www.filmweb.pl/videogame/What+Remains+of+Edith+Finch-2017-729227', poster: POSTER('whatremainsofedithfinch.jpg'), director: 'Ian Dallas', studio: 'Giant Sparrow', igdbRating: 85, igdbGenres: 'Puzzle, Arcade, Visual Novel', highlights: ['devastating'] },
  { id: 'max-payne-2',        title: 'Max Payne 2',              year: 2003, medium: 'Games',  favorite: true, region: 'fi', rating: '9', link: 'https://www.filmweb.pl/videogame/Max+Payne+2%3A+The+Fall+of+Max+Payne-2003-607024', poster: POSTER('maxpayne2.jpg'), studio: 'Remedy Entertainment', igdbGenres: 'Shooter, Arcade', highlights: ['style', 'impact'] },
  { id: 'manifold-garden',    title: 'Manifold Garden',          year: 2019, medium: 'Games',  favorite: true, region: 'us', rating: '9', link: 'https://www.filmweb.pl/videogame/Manifold+Garden-2019-793925',       poster: POSTER('ManifoldGarden.jpg'), director: 'William Chyr', igdbRating: 83, igdbGenres: 'Puzzle, Arcade, Visual Novel', highlights: ['mindbending', 'visuals'] },
  { id: 'life-is-strange',    title: 'Life is Strange',          year: 2015, medium: 'Games',  favorite: true, region: 'fr', rating: '8', link: 'https://www.filmweb.pl/videogame/Life+is+Strange-2015-720567',       poster: POSTER('lifeisstrange.webp'), studio: 'Dontnod', igdbRating: 81, igdbGenres: 'Puzzle, Arcade, Visual Novel', highlights: ['impact'], enTitle: 'Life Is Strange' },
  { id: 'cod4',               title: 'Call of Duty 4: Modern Warfare', year: 2007, medium: 'Games', favorite: true, region: 'us', rating: '10', link: 'https://www.filmweb.pl/videogame/Call+of+Duty+4%3A+Modern+Warfare-2007-608432', poster: POSTER('cod4.jpg'), studio: 'Infinity Ward', igdbRating: 57, igdbGenres: 'Shooter', highlights: ['thrilling', 'gem', 'singular', 'impact'] },
  { id: 'gta-iv',             title: 'Grand Theft Auto IV',      year: 2008, medium: 'Games',  favorite: true, region: 'uk', rating: '9', link: 'https://www.filmweb.pl/videogame/Grand+Theft+Auto+IV-2008-608436',   poster: POSTER('grandtheftautoIV.jpg'), studio: 'Rockstar North', igdbRating: 86, igdbGenres: 'Shooter, Racing, Arcade', highlights: ['atmosphere'] },
  { id: 'mass-effect',        title: 'Mass Effect',              year: 2007, medium: 'Games',  favorite: true, region: 'ca', rating: '9', link: 'https://www.filmweb.pl/videogame/Mass+Effect-2007-606340',           poster: POSTER('masseffect.jpg'), director: 'Casey Hudson', studio: 'BioWare', igdbGenres: 'RPG', highlights: ['atmosphere'] },
  { id: 'bioshock',           title: 'BioShock',                 year: 2007, medium: 'Games',  favorite: true, region: 'us', rating: '9', link: 'https://www.filmweb.pl/videogame/BioShock-2007-608595',              poster: POSTER('Bioshock.jpg'), director: 'Ken Levine', studio: 'Irrational Games', igdbRating: 86, igdbGenres: 'Shooter, RPG, Arcade', highlights: ['gem', 'atmosphere', 'cognitive'] },
  { id: 'mirrors-edge',       title: "Mirror's Edge",            year: 2008, medium: 'Games',  favorite: true, region: 'se', rating: '9', link: 'https://www.filmweb.pl/videogame/Mirror%27s+Edge-2008-607605',       poster: POSTER('MirrorsEdge.jpg'), studio: 'DICE' , 'igdbGenres': 'Platform, Adventure', 'igdbRating': 84},
  { id: 'bulletstorm',        title: 'Bulletstorm',              year: 2011, medium: 'Games',  favorite: true, region: 'pl', rating: '9', link: 'https://www.filmweb.pl/videogame/Bulletstorm-2011-611271',           poster: POSTER('Bulletstorm.webp'), studio: 'People Can Fly', igdbRating: 83, igdbGenres: 'Shooter', highlights: ['thrilling'] },
  { id: 'subnautica',         title: 'Subnautica',               year: 2018, medium: 'Games',  favorite: true, region: 'us', rating: '9', link: 'https://www.filmweb.pl/videogame/Subnautica-2018-738588',            poster: POSTER('Subnautica.jpg'), studio: 'Unknown Worlds', igdbRating: 83, igdbGenres: 'Arcade, Visual Novel', highlights: ['atmosphere'] },
  { id: 'crysis',             title: 'Crysis',                   year: 2007, medium: 'Games',  favorite: true, region: 'de', rating: '9', link: 'https://www.filmweb.pl/videogame/Crysis-2007-608586',                poster: POSTER('Crysis.webp'), studio: 'Crytek', igdbRating: 83, igdbGenres: 'Shooter, Arcade', highlights: ['visuals'] },
  { id: 'the-witcher',        title: 'The Witcher',              year: 2007, medium: 'Games',  favorite: true, region: 'pl', rating: '9', link: 'https://www.filmweb.pl/videogame/Wied%C5%BAmin-2007-608108',         poster: POSTER('TheWitcher.jpg'), studio: 'CD Projekt Red', igdbRating: 85, igdbGenres: 'RPG, Arcade', highlights: ['atmosphere', 'gem'] },
  { id: 'heavy-rain',         title: 'Heavy Rain',               year: 2010, medium: 'Games',  favorite: true, region: 'fr', rating: '9', link: 'https://www.filmweb.pl/videogame/Heavy+Rain-2010-607549',            poster: POSTER('heavyrain.jpg'), director: 'David Cage', studio: 'Quantic Dream', igdbRating: 81, igdbGenres: 'Arcade', highlights: ['gem'] },
  { id: 'codmw2',             title: 'Call of Duty: MW2',        year: 2009, medium: 'Games',  favorite: true, region: 'us', rating: '9', link: 'https://www.filmweb.pl/videogame/Call+of+Duty%3A+Modern+Warfare+2-2009-608594', poster: POSTER('codmw2.jpg'), studio: 'Infinity Ward', igdbRating: 83, igdbGenres: 'Shooter', highlights: ['thrilling'], enTitle: 'Call of Duty: Modern Warfare 2' },
  { id: 'firewatch',          title: 'Firewatch',                year: 2016, medium: 'Games',  favorite: true, region: 'us', rating: '7', link: 'https://www.filmweb.pl/videogame/Firewatch-2016-724536',             poster: POSTER('Firewatch.webp'), director: 'Sean Vanaman', studio: 'Campo Santo', igdbRating: 79, igdbGenres: 'Arcade, Visual Novel', highlights: ['atmosphere', 'writing'] },
  { id: 'ico',                title: 'Ico',                      year: 2001, medium: 'Games',  favorite: true, region: 'jp', rating: '9', link: 'https://www.filmweb.pl/videogame/Ico-2001-618893',                   poster: POSTER('ICO.jpg'), director: 'Fumito Ueda', studio: 'Team ICO', igdbRating: 91, igdbGenres: 'Platform, Puzzle, Arcade', highlights: ['atmosphere', 'singular'] },
  { id: 'wolf-among-us',      title: 'The Wolf Among Us',        year: 2013, medium: 'Games',  favorite: true, region: 'us', rating: '9', link: 'https://www.filmweb.pl/videogame/The+Wolf+Among+Us-2013-688673',     poster: POSTER('WolfAmongUs.jpg'), studio: 'Telltale Games', igdbRating: 82, igdbGenres: 'Point-and-click, Arcade', highlights: ['style', 'atmosphere'] },

  // ─────────── ANIMATED SERIES ───────────
  { id: 'ldr',                title: 'Love, Death & Robots',     year: 2019, medium: 'Animated Series', favorite: true, region: 'us', rating: '10', link: 'https://www.filmweb.pl/serial/Mi%C5%82o%C5%9B%C4%87%2C+%C5%9Bmier%C4%87+i+roboty-2019-824633', poster: POSTER('LDR.jpg'), length: 1, director: 'Tim Miller', studio: 'Netflix', totalMinutes: 1035, highlights: ['visuals', 'style', 'singular', 'impact', 'devastating', 'funny'] },
  { id: 'kaiba',              title: 'Kaiba',                    year: 2008, medium: 'Animated Series', favorite: true, region: 'jp', rating: '10', link: 'https://www.filmweb.pl/serial/Kaiba-2008-470038', poster: POSTER('kaiba.jpg'), length: 1, director: 'Masaaki Yuasa', studio: 'Madhouse', totalMinutes: 288, highlights: ['singular', 'devastating', 'visuals', 'mindbending'] },
  { id: 'gits-sac',           title: 'Ghost in the Shell: SAC',  year: 2002, medium: 'Animated Series', favorite: true, region: 'jp', rating: '8', link: 'https://www.filmweb.pl/serial/Ghost+in+the+Shell%3A+Stand+Alone+Complex-2002-93085', poster: POSTER('GhostInTheShell.jpg'), length: 2, director: 'Kenji Kamiyama', studio: 'Production I.G', totalMinutes: 1300, highlights: ['cerebral', 'writing'], enTitle: 'Ghost in the Shell: Stand Alone Complex' },
  { id: 'opm',                title: 'One-Punch Man',            year: 2015, medium: 'Animated Series', favorite: true, region: 'jp', rating: '9', link: 'https://www.filmweb.pl/serial/One-Punch+Man-2015-740929', poster: POSTER('onepunch.jpg'), length: 1, director: 'Shingo Natsume', studio: 'Madhouse', totalMinutes: 864, highlights: ['funny'] },
  { id: 'fma-brotherhood',    title: 'Fullmetal Alchemist: Brotherhood', year: 2009, medium: 'Animated Series', favorite: true, region: 'jp', rating: '8', link: 'https://www.filmweb.pl/serial/Fullmetal+Alchemist%3A+Brotherhood-2009-495827', poster: POSTER('FullMetalAlchemist.jpg'), length: 3, director: 'Yasuhiro Irie', studio: 'Bones', totalMinutes: 1600, highlights: ['writing'] },
  { id: 'made-in-abyss',      title: 'Made in Abyss',            year: 2017, medium: 'Animated Series', favorite: true, region: 'jp', rating: '9', link: 'https://www.filmweb.pl/serial/Made+in+Abyss-2017-786999', poster: POSTER('MadeInAbyss.jpg'), length: 1, director: 'Masayuki Kojima', studio: 'Kinema Citrus', totalMinutes: 600, highlights: ['devastating', 'atmosphere'] },
  { id: 'hellsing',           title: 'Hellsing Ultimate',        year: 2006, medium: 'Animated Series', favorite: true, region: 'jp', rating: '9', link: 'https://www.filmweb.pl/serial/Hellsing-2006-248532', poster: POSTER('hellsing.jpg'), length: 1, director: 'Tomokazu Tokoro', studio: 'Madhouse', totalMinutes: 490, highlights: ['style', 'intense'] },
  { id: 'paranoia-agent',     title: 'Paranoia Agent',           year: 2004, medium: 'Animated Series', favorite: true, region: 'jp', rating: '9', link: 'https://www.filmweb.pl/serial/Paranoia+Agent-2004-162349', poster: POSTER('ParanoiaAgent.jpg'), length: 1, director: 'Satoshi Kon', studio: 'Madhouse', totalMinutes: 325, highlights: ['mindbending', 'style', 'singular', 'impact'] },
  { id: 'gurren-lagann',      title: 'Gurren Lagann',            year: 2007, medium: 'Animated Series', favorite: true, region: 'jp', rating: '8', link: 'https://www.filmweb.pl/serial/Tengen+Toppa+Gurren-Lagann-2007-380233', poster: POSTER('gurrenlagann.jpg'), length: 2, director: 'Hiroyuki Imaishi', studio: 'Gainax', totalMinutes: 648, highlights: ['thrilling', 'impact'] },
  { id: 'scavengers-reign',   title: 'Scavengers Reign',         year: 2023, medium: 'Animated Series', favorite: true, region: 'us', rating: '9', link: 'https://www.filmweb.pl/serial/Scavengers+Reign-2023-10029337', poster: POSTER('ScavengersReign.webp'), length: 1, director: 'Charles Huettner', studio: 'Max', totalMinutes: 276, highlights: ['visuals', 'atmosphere'] },
  { id: 'cowboy-bebop',       title: 'Cowboy Bebop',             year: 1998, medium: 'Animated Series', favorite: true, region: 'jp', rating: '8', link: 'https://www.filmweb.pl/serial/Cowboy+Bebop-1998-98666', poster: POSTER('cowboybebop.jpg'), length: 2, director: 'Shinichiro Watanabe', studio: 'Sunrise', totalMinutes: 650, highlights: ['style', 'score'] },
  { id: 'kino-journey',       title: "Kino's Journey",           year: 2017, medium: 'Animated Series', favorite: true, region: 'jp', rating: '8', link: 'https://www.filmweb.pl/serial/Kino+no+Tabi%3A+The+Beautiful+World-2017-794586', poster: POSTER('kinojourney.jpg'), length: 1, note: 'Fantastyczny format eksplorujący motywy filozoficzno-polityczne, ubrany w piękne barwy, lecz rozjeżdżający i rozdrabniający się z czasem, i bywa zbyt ostry.', director: 'Tomohisa Taguchi', studio: 'Lerche' },
  { id: 'samurai-champloo',   title: 'Samurai Champloo',         year: 2004, medium: 'Animated Series', favorite: true, region: 'jp', rating: '8', link: 'https://www.filmweb.pl/serial/Samurai+champloo-2004-167103', poster: POSTER('samuraichamploo.jpg'), length: 2, director: 'Shinichiro Watanabe', studio: 'Manglobe', totalMinutes: 624, highlights: ['style', 'score'] },
  { id: 'haibane',            title: 'Haibane Renmei',           year: 2002, medium: 'Animated Series', favorite: true, region: 'jp', rating: '8', link: 'https://www.filmweb.pl/serial/Stowarzyszenie+Szaropi%C3%B3rych-2002-129544', poster: POSTER('angels.jpg'), length: 1, director: 'Tomokazu Tokoro', studio: 'Radix', totalMinutes: 312, highlights: ['atmosphere'] },
  { id: 'berserk',            title: 'Berserk (1997)',           year: 1997, medium: 'Animated Series', favorite: true, region: 'jp', rating: '8', link: 'https://www.filmweb.pl/serial/Kenp%C5%AB+Denki+Berserk-1997-98661', poster: POSTER('berserk.jpg'), length: 1, director: 'Naohito Takahashi', studio: 'OLM', totalMinutes: 575, highlights: ['devastating', 'intense'], enTitle: 'Berserk' },
  { id: 'psycho-pass',        title: 'Psycho-Pass',              year: 2012, medium: 'Animated Series', favorite: true, region: 'jp', rating: '8', link: 'https://www.filmweb.pl/serial/Psycho-pass-2012-653085', poster: POSTER('PsychoPass.jpg'), length: 2, director: 'Naoyoshi Shiotani', studio: 'Production I.G', totalMinutes: 1148, highlights: ['cerebral', 'impact'] },
  { id: 'trigun',             title: 'Trigun',                   year: 1998, medium: 'Animated Series', favorite: true, region: 'jp', rating: '8', link: 'https://www.filmweb.pl/serial/Trigun-1998-98878', poster: POSTER('trigun.jpg'), length: 2, director: 'Satoshi Nishimura', studio: 'Madhouse', totalMinutes: 624, highlights: ['funny', 'thrilling'], enTitle: 'TRIGUN' },
  { id: 'lain',               title: 'Serial Experiments Lain',  year: 1998, medium: 'Animated Series', favorite: true, region: 'jp', rating: '8', link: 'https://www.filmweb.pl/serial/Wirtualna+Lain-1998-98877', poster: POSTER('serialexperimentslain.jpg'), length: 1, director: 'Ryutaro Nakamura', studio: 'Triangle Staff', totalMinutes: 312, highlights: ['mindbending', 'cerebral', 'ahead'] },
  { id: 'sonny-boy',          title: 'Sonny Boy',                year: 2021, medium: 'Animated Series', favorite: true, region: 'jp', rating: '8', link: 'https://www.filmweb.pl/serial/Sonny+Boy-2021-10017027', poster: POSTER('SonnyBoy.jpg'), length: 1, director: 'Shingo Natsume', studio: 'Madhouse', totalMinutes: 288, highlights: ['gem', 'atmosphere'] },
  { id: 'scott-pilgrim',      title: 'Scott Pilgrim Takes Off',  year: 2023, medium: 'Animated Series', favorite: true, region: 'jp', rating: '8', link: 'https://www.filmweb.pl/serial/Scott+Pilgrim+zaskakuje-2023-10033460', poster: POSTER('scottpilgrim.jpg'), length: 1, director: 'Abel Góngora', studio: 'Science SARU', totalMinutes: 184, highlights: ['style', 'visuals', 'writing', 'gem'] },
  { id: 'macross-plus',       title: 'Macross Plus',             year: 1994, medium: 'Animated Series', favorite: true, region: 'jp', rating: '8', link: 'https://www.filmweb.pl/serial/Macross+Plus-1994-99320', poster: 'https://m.media-amazon.com/images/M/MV5BNWI0OGIwNTEtZDUyYS00YjBjLWEzM2ItYmFiNmQwZmI0MmRlXkEyXkFqcGdeQXVyOTUzMjk0NDE@._V1_UY268_CR3,0,182,268_AL_.jpg', length: 1, director: 'Shoji Kawamori', studio: 'Satelight', totalMinutes: 156, highlights: [] },
  { id: 'ghost-hound',        title: 'Ghost Hound',              year: 2007, medium: 'Animated Series', favorite: true, region: 'jp', rating: '8', link: 'https://www.filmweb.pl/serial/Shinreigari%3A+Ghost+Hound-2007-426887', poster: POSTER('ghosthound.jpg'), length: 1, director: 'Ryutaro Nakamura', studio: 'Production I.G', totalMinutes: 550, highlights: ['atmosphere', 'impact'] },
  { id: 'terror-resonance',   title: 'Terror in Resonance',      year: 2014, medium: 'Animated Series', favorite: true, region: 'jp', rating: '7', link: 'https://www.filmweb.pl/serial/Zanky%C5%8D+no+Terror-2014-711692', poster: POSTER('terrorinrezonance.jpg'), length: 1, director: 'Shinichiro Watanabe', studio: 'MAPPA', totalMinutes: 253, highlights: ['atmosphere'] },
  { id: 'eva',                title: 'Neon Genesis Evangelion',  year: 1995, medium: 'Animated Series', favorite: true, region: 'jp', rating: '8', link: 'https://www.filmweb.pl/serial/Neon+Genesis+Evangelion-1995-100434', poster: POSTER('neongenesis.webp'), length: 1, director: 'Hideaki Anno', studio: 'Gainax', totalMinutes: 650, highlights: ['cerebral', 'devastating'] },
  { id: 'steins-gate',        title: 'Steins;Gate',              year: 2011, medium: 'Animated Series', favorite: true, region: 'jp', rating: '7', link: 'https://www.filmweb.pl/serial/Steins+Gate-2011-597724', poster: POSTER('steinsgate.webp'), length: 2, director: 'Hiroshi Hamasaki', studio: 'White Fox', totalMinutes: 576, highlights: ['mindbending', 'impact'] },
  { id: 'gunnm',              title: 'Battle Angel Alita (OVA)', year: 1993, medium: 'Animated Series', favorite: true, region: 'jp', rating: '8', link: 'https://www.filmweb.pl/serial/Gunnm-1993-95798', poster: POSTER('gunnm.webp'), length: 1, director: 'Hiroshi Fukutomi', studio: 'KSS', totalMinutes: 60, enTitle: 'Battle Angel' },
  { id: 'eizouken',           title: 'Keep Your Hands Off Eizouken!', year: 2020, medium: 'Animated Series', favorite: true, region: 'jp', rating: '9', link: 'https://www.filmweb.pl/serial/Eiz%C5%8Dken+ni+wa+Te+o+Dasu+na-2020-846151', poster: POSTER('letsdoanimation.jpg'), length: 1, director: 'Masaaki Yuasa', studio: 'Science SARU', totalMinutes: 300, highlights: ['singular', 'impact'] },
  { id: 'black-lagoon',       title: 'Black Lagoon',             year: 2006, medium: 'Animated Series', favorite: true, region: 'jp', rating: '8', link: 'https://www.filmweb.pl/serial/Black+Lagoon-2006-304751', poster: POSTER('blacklagoon.webp'), length: 1, director: 'Sunao Katabuchi', studio: 'Madhouse', totalMinutes: 576, highlights: ['style', 'thrilling'] },
  { id: 'mononoke',           title: 'Mononoke',                 year: 2007, medium: 'Animated Series', favorite: true, region: 'jp', rating: '8', link: 'https://www.filmweb.pl/serial/Mononoke-2007-426889', poster: POSTER('Mononoke.jpg'), length: 1, director: 'Kenji Nakamura', studio: 'Toei Animation', totalMinutes: 276, highlights: ['visuals', 'style', 'writing', 'impact'] },
  { id: 'aot',                title: 'Attack on Titan',          year: 2013, medium: 'Animated Series', favorite: true, region: 'jp', rating: '8', link: 'https://www.filmweb.pl/serial/Shingeki+no+Kyojin-2013-636227', poster: POSTER('AttackonTitan.jpg'), length: 3, director: 'Tetsuro Araki', studio: 'Wit Studio', totalMinutes: 2001, highlights: ['intense', 'impact'] },
  { id: 'flcl',               title: 'FLCL',                     year: 2000, medium: 'Animated Series', favorite: true, region: 'jp', rating: '7', link: 'https://www.filmweb.pl/serial/FLCL-2000-106022', poster: POSTER('flcl.jpg'), length: 1, director: 'Kazuya Tsurumaki', studio: 'Gainax', totalMinutes: 600, highlights: ['style', 'thrilling'] },
  { id: 'wolfs-rain',         title: "Wolf's Rain",              year: 2003, medium: 'Animated Series', favorite: true, region: 'jp', rating: '7', link: 'https://www.filmweb.pl/serial/Wolf%27s+Rain-2003-127898', poster: POSTER('wolfsrain.jpg'), length: 1, note: 'Bardzo unikalny, niestety dialogi bywają tendencyjne, w środku się strasznie dłuży, ale OST rewelacyjny, tematycznie nie znam niczego podobnego i czasem rozwala', director: 'Tensai Okamura', studio: 'Bones' },
  { id: 'cyberpunk-edge',     title: 'Cyberpunk: Edgerunners',   year: 2022, medium: 'Animated Series', favorite: true, region: 'jp', rating: '7', link: 'https://www.filmweb.pl/serial/Cyberpunk%3A+Edgerunners-2022-856325', poster: POSTER('cyberpunkedge.jpg'), length: 1, director: 'Hiroyuki Imaishi', studio: 'Trigger', totalMinutes: 250, highlights: ['style', 'impact'] },
  { id: 'elfen-lied',         title: 'Elfen Lied',               year: 2004, medium: 'Animated Series', favorite: true, region: 'jp', rating: '6', link: 'https://www.filmweb.pl/serial/Elfen+Lied-2004-226952', poster: POSTER('ElfenLied.jpg'), length: 1, director: 'Mamoru Kanbe', studio: 'Arms', totalMinutes: 325, highlights: ['intense'] },
  { id: 'wonder-egg',         title: 'Wonder Egg Priority',      year: 2021, medium: 'Animated Series', favorite: true, region: 'jp', rating: '8', link: 'https://www.filmweb.pl/serial/Wonder+Egg+Priority-2021-871412', poster: POSTER('WonderEggPriority.jpg'), length: 1, director: 'Shin Wakabayashi', studio: 'CloverWorks', totalMinutes: 276, highlights: ['gem'] },
  { id: 'invincible',         title: 'Invincible',               year: 2021, medium: 'Animated Series', favorite: true, region: 'us', rating: '8', link: 'https://www.filmweb.pl/serial/Niezwyci%C4%99%C5%BCony-2021-862677', poster: POSTER('invincible.jpg'), length: 1, director: 'Robert Kirkman', studio: 'Prime Video', totalMinutes: 736, highlights: ['gem', 'intense'], enTitle: 'INVINCIBLE' },
  { id: 'rick-and-morty',     title: 'Rick and Morty',           year: 2013, medium: 'Animated Series', favorite: true, region: 'us', rating: '9', link: 'https://www.filmweb.pl/serial/Rick+i+Morty-2013-671074', poster: POSTER('RickandMorty.jpg'), length: 2, director: 'Dan Harmon', studio: 'Adult Swim', totalMinutes: 2093, highlights: ['funny', 'cerebral'] },
  { id: 'korra',              title: 'The Legend of Korra',      year: 2012, medium: 'Animated Series', favorite: true, region: 'us', rating: '8', link: 'https://www.filmweb.pl/serial/Legenda+Korry-2012-590629', poster: POSTER('LegendofKorra.jpg'), length: 2, director: 'Michael DiMartino', studio: 'Nickelodeon', totalMinutes: 1196, highlights: ['writing', 'impact', 'devastating'] },
  { id: 'short-circuit',      title: 'Short Circuit',            year: 2020, medium: 'Animated Series', favorite: true, region: 'us', rating: '9', link: 'https://www.filmweb.pl/serial/Short+Circuit-2020-868051', poster: POSTER('shortcircuit.webp'), length: 1, studio: 'Pixar', totalMinutes: 506, highlights: ['visuals'], enTitle: 'Walt Disney Animation Studios: Short Circuit Experimental Films' },
  { id: 'midnight-gospel',    title: 'The Midnight Gospel',      year: 2020, medium: 'Animated Series', favorite: true, region: 'us', rating: '8', link: 'https://www.filmweb.pl/serial/The+Midnight+Gospel-2020-850265', poster: POSTER('MidnightGospel.jpg'), length: 1, director: 'Pendleton Ward', studio: 'Netflix', totalMinutes: 184, highlights: ['cerebral'] },
  { id: 'avatar-tla',         title: 'Avatar: The Last Airbender', year: 2005, medium: 'Animated Series', favorite: true, region: 'us', rating: '8', link: 'https://www.filmweb.pl/serial/Awatar%3A+Legenda+Aanga-2005-194037', poster: POSTER('Avatar.jpg'), length: 2, director: 'Michael DiMartino', studio: 'Nickelodeon', totalMinutes: 1464, highlights: ['writing'] },
  { id: 'hilda',              title: 'Hilda',                    year: 2018, medium: 'Animated Series', favorite: true, region: 'uk', rating: '9', link: 'https://www.filmweb.pl/serial/Hilda-2018-800921', poster: POSTER('Hilda.jpg'), length: 1, director: 'Luke Pearson', studio: 'Netflix', totalMinutes: 918, highlights: ['atmosphere'] },
  { id: 'tatami-galaxy',      title: 'The Tatami Galaxy',        year: 2010, medium: 'Animated Series', favorite: true, region: 'jp', rating: '8', link: 'https://www.filmweb.pl/serial/Yoj%C5%8D-Han+Shinwa+Taikei-2010-555640', poster: POSTER('tatamigalaxy.webp'), length: 1, director: 'Masaaki Yuasa', studio: 'Madhouse', totalMinutes: 275, highlights: ['style', 'gem'] },

  // ─────────── FEATURE ANIMATION ───────────
  { id: 'soul',               title: 'Soul',                     year: 2020, medium: 'Feature Animation', favorite: true, region: 'us', rating: '10', link: 'https://www.filmweb.pl/film/Co+w+duszy+gra-2020-836650', poster: POSTER('soul.jpg'), note: 'Praktycznie niemal w pełni wypełniony subtelnościami, detalami i contentem pięknym, który zaskakuje nawiązuje i technicznie i pod względem emocjonalnym rozpływa', director: 'Pete Docter', studio: 'Pixar', fwAvg: 7.8, runtime: 101, highlights: ['devastating', 'score', 'gem', 'writing'] },
  { id: 'fantasia',           title: 'Fantasia',                 year: 1940, medium: 'Feature Animation', favorite: true, region: 'us', rating: '10', link: 'https://www.filmweb.pl/film/Fantazja-1940-36316', poster: POSTER('fantasia.jpg'), director: 'Walt Disney', studio: 'Walt Disney', fwAvg: 7.6, runtime: 124, highlights: ['visuals', 'score', 'singular'] },
  { id: 'belladonna',         title: 'Belladonna of Sadness',    year: 1973, medium: 'Feature Animation', favorite: true, region: 'jp', rating: '10', link: 'https://www.filmweb.pl/film/Belladonna+smutku-1973-128976', poster: POSTER('belladonaofsadness.jpg'), note: 'Najpiękniejsza i zarazem najsmutniejsza animacja jaką miałem w życiu zobaczyć, kunszt artystyczny po prostu nie ma porównania, szokuje ale absolutnie zachwyca.', director: 'Eiichi Yamamoto', studio: 'Mushi Production', fwAvg: 7.6, runtime: 87, watchedDate: '2020-02-02', highlights: ['visuals', 'singular', 'impact'] },
  { id: 'spider-verse',       title: 'Across the Spider-Verse',  year: 2023, medium: 'Feature Animation', favorite: true, region: 'us', rating: '10', link: 'https://www.filmweb.pl/film/Spider+Man%3A+Poprzez+multiwersum-2023-842826', poster: POSTER('spiderverse.jpg'), director: 'Joaquim Dos Santos', studio: 'Sony Pictures', fwAvg: 8.0, runtime: 140 , watchedDate: '2023-06-01', highlights: ['visuals', 'style'], enTitle: 'Spider-Man: Across the Spider-Verse' },
  { id: 'ernest-celestine',   title: 'Ernest & Celestine',       year: 2012, medium: 'Feature Animation', favorite: true, region: 'fr', rating: '10', link: 'https://www.filmweb.pl/film/Ernest+i+Celestyna-2012-654784', poster: POSTER('ErnestandCelestine.jpg'), note: 'Nieskazitelna jakość animacji, akcentowanie w scenariuszu perfekcyjnie precyzyjne, jest morał, parallele, symbolizm, a to wszystko przystępne i wielce śliczne.', director: 'Benjamin Renner', studio: 'Les Armateurs', fwAvg: 7.7, runtime: 80 , watchedDate: '2021-03-05', highlights: ['visuals'] },
  { id: 'memories',           title: 'Memories',                 year: 1995, medium: 'Feature Animation', favorite: true, region: 'jp', rating: '9', link: 'https://www.filmweb.pl/film/Memories-1995-34359', poster: POSTER('memories.jpg'), director: 'Katsuhiro Otomo', studio: 'Madhouse', fwAvg: 7.5, runtime: 113, highlights: ['visuals', 'impact'] },
  { id: 'neo-tokyo',          title: 'Neo Tokyo',                year: 1987, medium: 'Feature Animation', favorite: true, region: 'jp', rating: '10', link: 'https://www.filmweb.pl/film/Labirynt+opowie%C5%9Bci-1987-201649', poster: POSTER('neotokyo.jpg'), director: 'Katsuhiro Otomo', studio: 'Madhouse', fwAvg: 7.0, runtime: 50 , watchedDate: '2017-01-22', highlights: ['visuals'] },
  { id: 'metropolis',         title: 'Metropolis',               year: 2001, medium: 'Feature Animation', favorite: true, region: 'jp', rating: '9', link: 'https://www.filmweb.pl/film/Metropolis-2001-34220', poster: POSTER('metropolis.jpg'), director: 'Rintaro', studio: 'Madhouse', fwAvg: 7.6, runtime: 107, highlights: ['visuals'] },
  { id: 'tokyo-godfathers',   title: 'Tokyo Godfathers',         year: 2003, medium: 'Feature Animation', favorite: true, region: 'jp', rating: '9', link: 'https://www.filmweb.pl/film/Rodzice+chrzestni+z+Tokio-2003-107897', poster: POSTER('christmas.jpg'), director: 'Satoshi Kon', studio: 'Madhouse', fwAvg: 7.6, runtime: 92, highlights: ['writing'] },
  { id: 'galactic-railroad',  title: 'Night on the Galactic Railroad', year: 1985, medium: 'Feature Animation', favorite: true, region: 'jp', rating: '9', link: 'https://www.filmweb.pl/film/Ginga+tetsud%C3%B4+no+yoru-1985-169073', poster: POSTER('galactic.webp'), director: 'Gisaburō Sugii', fwAvg: 7.8, runtime: 108, watchedDate: '2020-10-26', highlights: ['atmosphere', 'impact'] },
  { id: 'jin-roh',            title: 'Jin-Roh: The Wolf Brigade', year: 1999, medium: 'Feature Animation', favorite: true, region: 'jp', rating: '8', link: 'https://www.filmweb.pl/film/Jin-R%C5%8D-1999-36919', poster: POSTER('jinroh.jpg'), director: 'Hiroyuki Okiura', studio: 'Production I.G', fwAvg: 7.6, runtime: 102, highlights: ['devastating', 'atmosphere'] },
  { id: 'nausicaa',           title: 'Nausicaä of the Valley of the Wind', year: 1984, medium: 'Feature Animation', favorite: true, region: 'jp', rating: '8', link: 'https://www.filmweb.pl/film/Nausica%C3%A4+z+Doliny+Wiatru-1984-34636', poster: POSTER('Nausicaa.jpg'), director: 'Hayao Miyazaki', studio: 'Topcraft', fwAvg: 7.8, runtime: 95, watchedDate: '2018-03-25', highlights: ['atmosphere'], enTitle: 'Warriors of the Wind' },
  { id: 'peasants',           title: 'The Peasants',             year: 2023, medium: 'Feature Animation', favorite: true, region: 'pl', rating: '9', link: 'https://www.filmweb.pl/film/Ch%C5%82opi-2023-857962', poster: POSTER('chlopi.jpg'), director: 'DK Welchman', studio: 'BreakThru Films', fwAvg: 7.8, runtime: 115, highlights: ['visuals', 'impact', 'score', 'singular', 'direction'] },
  { id: 'your-name',          title: 'Your Name',                year: 2016, medium: 'Feature Animation', favorite: true, region: 'jp', rating: '9', link: 'https://www.filmweb.pl/film/Kimi+no+Na+wa.-2016-760082', poster: POSTER('yourname.webp'), director: 'Makoto Shinkai', studio: 'CoMix Wave', fwAvg: 8.2, runtime: 106, watchedDate: '2017-03-02', highlights: ['visuals', 'devastating'], enTitle: 'Your Name.' },
  { id: 'redline',            title: 'Redline',                  year: 2009, medium: 'Feature Animation', favorite: true, region: 'jp', rating: '9', link: 'https://www.filmweb.pl/film/Redline-2009-512229', poster: POSTER('redline.jpg'), director: 'Takeshi Koike', studio: 'Madhouse', fwAvg: 7.6, runtime: 102, highlights: ['visuals', 'style', 'thrilling'] },
  { id: 'silent-voice',       title: 'A Silent Voice',           year: 2016, medium: 'Feature Animation', favorite: true, region: 'jp', rating: '8', link: 'https://www.filmweb.pl/film/Koe+no+Katachi-2016-769531', poster: POSTER('asilentvoice.jpg'), director: 'Naoko Yamada', studio: 'KyoAni', fwAvg: 8.1, runtime: 129, watchedDate: '2018-03-26', highlights: ['devastating'], enTitle: 'A Silent Voice: The Movie' },
  { id: 'grave-fireflies',    title: 'Grave of the Fireflies',   year: 1988, medium: 'Feature Animation', favorite: true, region: 'jp', rating: '8', link: 'https://www.filmweb.pl/film/Grobowiec+%C5%9Bwietlik%C3%B3w-1988-34655', poster: POSTER('graveofthefireflies.webp'), director: 'Isao Takahata', studio: 'Studio Ghibli', fwAvg: 8.1, runtime: 89, watchedDate: '2017-02-23', highlights: ['devastating'] },
  { id: 'in-this-corner',     title: 'In This Corner of the World', year: 2016, medium: 'Feature Animation', favorite: true, region: 'jp', rating: '9', link: 'https://www.filmweb.pl/film/Kono+Sekai+no+Katasumi+ni-2016-746761', poster: POSTER('inthiscornerofthisworld.webp'), director: 'Sunao Katabuchi', studio: 'MAPPA', fwAvg: 7.7, runtime: 130, watchedDate: '2020-06-21', highlights: ['devastating'] },
  { id: 'laputa',             title: 'Castle in the Sky',        year: 1986, medium: 'Feature Animation', favorite: true, region: 'jp', rating: '8', link: 'https://www.filmweb.pl/film/Laputa+%E2%80%93+podniebny+zamek-1986-34654', poster: POSTER('Laputa.jpg'), director: 'Hayao Miyazaki', studio: 'Studio Ghibli', fwAvg: 7.7, runtime: 125, highlights: ['atmosphere'] },
  { id: 'kaguya',             title: 'The Tale of Princess Kaguya', year: 2013, medium: 'Feature Animation', favorite: true, region: 'jp', rating: '9', link: 'https://www.filmweb.pl/film/Ksi%C4%99%C5%BCniczka+Kaguya-2013-560009', poster: POSTER('PrincessKaguya.jpg'), director: 'Isao Takahata', studio: 'Studio Ghibli', fwAvg: 7.8, runtime: 137, watchedDate: '2020-06-09', highlights: ['visuals', 'devastating'], enTitle: 'The Tale of The Princess Kaguya' },
  { id: 'wolfwalkers',        title: 'Wolfwalkers',              year: 2020, medium: 'Feature Animation', favorite: true, region: 'ie', rating: '8', link: 'https://www.filmweb.pl/film/Sekret+wilczej+gromady-2020-800312', poster: POSTER('wolfwalkers.webp'), director: 'Tomm Moore', studio: 'Cartoon Saloon', fwAvg: 8.1, runtime: 102, highlights: ['visuals'] },
  { id: 'gits-movie',         title: 'Ghost in the Shell',       year: 1995, medium: 'Feature Animation', favorite: true, region: 'jp', rating: '6', link: 'https://www.filmweb.pl/film/Ghost+in+the+Shell-1995-31866', poster: POSTER('GhostInTheShellMovie.jpg'), director: 'Mamoru Oshii', studio: 'Production I.G', fwAvg: 7.9, runtime: 83, watchedDate: '2016-12-12', highlights: ['cerebral', 'visuals', 'ahead', 'atmosphere'] },
  { id: 'watership-down',     title: 'Watership Down',           year: 1978, medium: 'Feature Animation', favorite: true, region: 'uk', rating: '8', link: 'https://www.filmweb.pl/film/Wzg%C3%B3rze+kr%C3%B3lik%C3%B3w-1978-11558', poster: POSTER('watershipdown.webp'), director: 'Martin Rosen', fwAvg: 7.6, runtime: 92, highlights: ['impact'] },
  { id: 'promare',            title: 'Promare',                  year: 2019, medium: 'Feature Animation', favorite: true, region: 'jp', rating: '9', link: 'https://www.filmweb.pl/film/Promare-2019-839338', poster: POSTER('promare.jpg'), director: 'Hiroyuki Imaishi', studio: 'Trigger', fwAvg: 7.3, runtime: 111, highlights: ['visuals', 'style'] },
  { id: 'plague-dogs',        title: 'The Plague Dogs',          year: 1982, medium: 'Feature Animation', favorite: true, region: 'uk', rating: '8', link: 'https://www.filmweb.pl/film/The+Plague+Dogs-1982-10740', poster: POSTER('plaguedogs.webp'), director: 'Martin Rosen', fwAvg: 8.0, runtime: 86, highlights: ['devastating'] },
  { id: 'mononoke-hime',      title: 'Princess Mononoke',        year: 1997, medium: 'Feature Animation', favorite: true, region: 'jp', rating: '8', link: 'https://www.filmweb.pl/film/Ksi%C4%99%C5%BCniczka+Mononoke-1997-971', poster: POSTER('mononokehime.webp'), director: 'Hayao Miyazaki', studio: 'Studio Ghibli', fwAvg: 8.0, runtime: 134, watchedDate: '2018-03-21', highlights: ['visuals'] },
  { id: 'angels-egg',         title: "Angel's Egg",              year: 1985, medium: 'Feature Animation', favorite: true, region: 'jp', rating: '8', link: 'https://www.filmweb.pl/film/Tenshi+no+tamago-1985-34450', poster: POSTER('angelsegg.webp'), director: 'Mamoru Oshii', fwAvg: 7.5, watchedDate: '2021-03-20', runtime: 71 },
  { id: 'yamadas',            title: 'My Neighbors the Yamadas', year: 1999, medium: 'Feature Animation', favorite: true, region: 'jp', rating: '9', link: 'https://www.filmweb.pl/film/Rodzinka+Yamad%C3%B3w-1999-111709', poster: POSTER('Yamada.jpg'), director: 'Isao Takahata', studio: 'Studio Ghibli', fwAvg: 7.2, runtime: 104 },
  { id: 'waltz-bashir',       title: 'Waltz with Bashir',        year: 2008, medium: 'Feature Animation', favorite: true, region: 'il', rating: '8', link: 'https://www.filmweb.pl/film/Walc+z+Baszirem-2008-479844', poster: POSTER('walzwithbashir.jpg'), director: 'Ari Folman', fwAvg: 7.8, runtime: 90, watchedDate: '2019-07-28', highlights: ['visuals', 'devastating'] },
  { id: 'pom-poko',           title: 'Pom Poko',                 year: 1994, medium: 'Feature Animation', favorite: true, region: 'jp', rating: '9', link: 'https://www.filmweb.pl/film/Szopy+w+natarciu-1994-111708', poster: POSTER('pompoko.jpg'), director: 'Isao Takahata', studio: 'Studio Ghibli', fwAvg: 7.2, runtime: 119 },
  { id: 'loving-vincent',     title: 'Loving Vincent',           year: 2017, medium: 'Feature Animation', favorite: true, region: 'pl', rating: '9', link: 'https://www.filmweb.pl/film/Tw%C3%B3j+Vincent-2017-698207', poster: POSTER('vincent.webp'), director: 'Dorota Kobiela', studio: 'BreakThru Films', fwAvg: 7.9, runtime: 95, highlights: ['visuals', 'singular'] },
  { id: 'porco-rosso',        title: 'Porco Rosso',              year: 1992, medium: 'Feature Animation', favorite: true, region: 'jp', rating: '9', link: 'https://www.filmweb.pl/film/Szkar%C5%82atny+pilot-1992-34658', poster: POSTER('porcorosso.jpg'), director: 'Hayao Miyazaki', studio: 'Studio Ghibli', fwAvg: 7.5, runtime: 93, watchedDate: '2020-02-10' },
  { id: 'kite',               title: 'Kite',                     year: 1998, medium: 'Feature Animation', favorite: true, region: 'jp', rating: '8', link: 'https://www.filmweb.pl/film/Kite-1998-34361', poster: POSTER('Kite.jpg'), director: 'Yasuomi Umetsu', fwAvg: 6.6, runtime: 50, highlights: ['intense'] },
  { id: 'zucchini',           title: 'My Life as a Zucchini',    year: 2016, medium: 'Feature Animation', favorite: true, region: 'ch', rating: '8', link: 'https://www.filmweb.pl/film/Nazywam+si%C4%99+Cukinia-2016-664117', poster: POSTER('Zuchini.jpg'), director: 'Claude Barras', fwAvg: 7.6, runtime: 66, watchedDate: '2020-07-22', highlights: ['devastating'] },
  { id: 'nightmare-christmas',title: 'The Nightmare Before Christmas', year: 1993, medium: 'Feature Animation', favorite: true, region: 'us', rating: '9', link: 'https://www.filmweb.pl/film/Miasteczko+Halloween-1993-7705', poster: POSTER('nightmarebeforechristmas.webp'), director: 'Henry Selick', studio: 'Disney', fwAvg: 7.6, runtime: 76, highlights: ['visuals', 'score', 'style'] },
  { id: 'mary-and-max',       title: 'Mary and Max',             year: 2009, medium: 'Feature Animation', favorite: true, region: 'au', rating: '9', link: 'https://www.filmweb.pl/film/Mary+i+Max-2009-479892', poster: POSTER('maryandmax.jpg'), director: 'Adam Elliot', fwAvg: 7.9, runtime: 92, highlights: ['devastating'] },
  { id: 'swallows-kabul',     title: 'The Swallows of Kabul',    year: 2019, medium: 'Feature Animation', favorite: true, region: 'fr', rating: '9', link: 'https://www.filmweb.pl/film/Jask%C3%B3%C5%82ki+z+Kabulu-2019-829461', poster: POSTER('kabul.webp'), director: 'Zabou Breitman', fwAvg: 7.3, runtime: 81, watchedDate: '2020-08-31', highlights: ['devastating'] },
  { id: 'konosuba',           title: 'KonoSuba: Legend of Crimson', year: 2019, medium: 'Feature Animation', favorite: true, region: 'jp', rating: '9', link: 'https://www.filmweb.pl/film/Kono+Subarashii+Sekai+ni+Shukufuku+o+Kurenai+Densetsu-2019-831928', poster: POSTER('konosuba.jpg'), director: 'Takaomi Kanasaki', studio: 'J.C.Staff', fwAvg: 7.6, runtime: 90, watchedDate: '2022-01-04', highlights: ['funny'], enTitle: 'KONOSUBA – God\'s blessing on this wonderful world! Legend of Crimson' },
  { id: 'tekkonkinkreet',     title: 'Tekkonkinkreet',           year: 2006, medium: 'Feature Animation', favorite: true, region: 'jp', rating: '8', link: 'https://www.filmweb.pl/film/Tekkonkinkreet-2006-350090', poster: POSTER('tekkon.jpg'), director: 'Michael Arias', studio: 'Studio 4°C', fwAvg: 7.9, runtime: 103 , watchedDate: '2023-01-30', highlights: ['visuals', 'impact'] },
  { id: 'colorful',           title: 'Colorful',                 year: 2010, medium: 'Feature Animation', favorite: true, region: 'jp', rating: '8', link: 'https://www.filmweb.pl/film/Colorful-2010-563824', poster: POSTER('colorful.jpg'), director: 'Eiichi Obara', studio: 'Sunrise', fwAvg: 7.3, runtime: 127, highlights: ['devastating'] },
  { id: 'iron-boy',           title: 'Iron Boy',                 year: 2026, medium: 'Feature Animation', favorite: true, region: 'eu', rating: '9', director: 'Louis Clichy', runtime: 90, highlights: ['writing'], watchedDate: '2026-06-24' },

  // ─────────── BOOKS ───────────
  { id: 'limes-inferior',     title: 'Limes Inferior',           year: 1982, medium: 'Books',  favorite: true, region: 'pl', link: 'https://www.goodreads.com/book/show/2108205.Limes_inferior', poster: POSTER('Limesinferior.jpg'), length: 1, director: 'Janusz Zajdel', pages: 213, highlights: ['ahead', 'gem', 'writing'] },
  { id: 'norwegian-wood',     title: 'Norwegian Wood',           year: 1987, medium: 'Books',  favorite: true, region: 'jp', link: 'https://www.goodreads.com/book/show/11297.Norwegian_Wood', poster: 'https://covers.openlibrary.org/b/id/2237620-L.jpg', length: 2, director: 'Haruki Murakami', pages: 296, highlights: ['impact', 'writing', 'devastating'] },
  { id: 'punpun',             title: 'Goodnight Punpun',         year: 2007, medium: 'Books',  favorite: true, region: 'jp', link: 'https://www.goodreads.com/book/show/32918991-goodnight-punpun-omnibus-vol-7', poster: POSTER('punpun.jpg'), length: 3, note: 'Finished the last volume and sat in the dark for an hour. A graphic novel does not get to do this to you.', director: 'Inio Asano', pages: 434, highlights: ['devastating'] },
  { id: 'illustrated-man',    title: 'The Illustrated Man',      year: 1951, medium: 'Books',  favorite: true, region: 'us', link: 'https://www.goodreads.com/book/show/24830.The_Illustrated_Man', poster: POSTER('illustratedman.webp'), length: 1, director: 'Ray Bradbury', pages: 251 },
  { id: 'velveteen-rabbit',   title: 'The Velveteen Rabbit',     year: 1922, medium: 'Books',  favorite: true, region: 'uk', link: 'https://www.goodreads.com/book/show/144974.The_Velveteen_Rabbit', poster: POSTER('velveteenrabbit.jpg'), length: 1, director: 'Margery Williams', pages: 44, highlights: ['devastating'] },
  { id: '1001-nights',        title: 'One Thousand and One Nights', year: 800, medium: 'Books', favorite: true, region: 'other', link: 'https://www.goodreads.com/book/show/6971441-1001-arabian-nights', poster: POSTER('1001.webp'), length: 3, pages: 200 },
  { id: 'the-idiot',          title: 'The Idiot',                year: 1869, medium: 'Books',  favorite: true, region: 'ru', link: 'https://www.goodreads.com/book/show/12505.The_Idiot', poster: POSTER('theidiot.webp'), length: 3, director: 'Fyodor Dostoevsky', pages: 614, highlights: ['writing'] },
  { id: 'heart-of-darkness',  title: 'Heart of Darkness',        year: 1899, medium: 'Books',  favorite: true, region: 'uk', link: 'https://www.goodreads.com/book/show/4900.Heart_of_Darkness', poster: POSTER('heartofdarkness.webp'), length: 1, director: 'Joseph Conrad', pages: 136, highlights: ['writing', 'atmosphere'] },
  { id: 'robot',              title: 'Robot (Lem)',              year: 1964, medium: 'Books',  favorite: true, region: 'pl', link: 'https://www.goodreads.com/book/show/16131728-robot', poster: 'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1352148289l/16131728.jpg', length: 1, director: 'Stanisław Lem' },
  { id: 'fahrenheit',         title: 'Fahrenheit 451',           year: 1953, medium: 'Books',  favorite: true, region: 'us', link: 'https://www.goodreads.com/book/show/17470674-fahrenheit-451', poster: POSTER('fahrenheit451.jpg'), length: 1, director: 'Ray Bradbury', pages: 190, highlights: ['cerebral'] },
  { id: '1984',               title: '1984',                     year: 1949, medium: 'Books',  favorite: true, region: 'uk', link: 'https://www.goodreads.com/book/show/6606279-1984', poster: POSTER('1984.webp'), length: 2, director: 'George Orwell', highlights: ['cerebral', 'devastating'] },
  { id: 'animal-farm',        title: 'Animal Farm',              year: 1945, medium: 'Books',  favorite: true, region: 'uk', link: 'https://www.goodreads.com/book/show/170448.Animal_Farm', poster: POSTER('animalfarm.jpg'), length: 1, director: 'George Orwell', pages: 128 },
  { id: 'blood-of-elves',     title: 'Blood of Elves',           year: 1994, medium: 'Books',  favorite: true, region: 'pl', link: 'https://www.goodreads.com/book/show/6043781-blood-of-elves', poster: POSTER('wiedzminkrewelfow.jpg'), length: 2, director: 'Andrzej Sapkowski' },
  { id: 'paradyzja',          title: 'Paradyzja',                year: 1984, medium: 'Books',  favorite: true, region: 'pl', link: 'https://www.goodreads.com/book/show/2099342.Paradyzja', poster: POSTER('paradyzja.jpg'), length: 1, director: 'Janusz Zajdel', pages: 196 },

  // ─────────── SHORTS ───────────
  { id: 'premier-automne', title: 'Premier Automne',         year: 2013, medium: 'Shorts', favorite: true, region: 'fr', rating: '10', director: 'Carlos de Carvalho, Aude Danset', runtime: 10 , studio: 'École des Gobelins', watchedDate: '2020-08-23', fwAvg: 7.3, link: 'https://www.filmweb.pl/film/Premier+Automne-2013-685546', highlights: ['visuals', 'gem'], enTitle: 'First Fall' },
  { id: 'kiwi',            title: 'Kiwi!',                   year: 2006, medium: 'Shorts', favorite: true, region: 'us', rating: '10', director: 'Dony Permedi', studio: 'School of Visual Arts', poster: POSTER('kiwi.jpg'), link: 'https://www.filmweb.pl/film/Kiwi%21-2006-452169', fwAvg: 7.5, runtime: 4, watchedDate: '2007-05-23', highlights: ['devastating', 'singular'] },
  { id: 'urzad',           title: 'Urząd',                   year: 1966, medium: 'Shorts', favorite: true, region: 'pl', rating: '9', director: 'Krzysztof Kieślowski', runtime: 6 , watchedDate: '2021-05-05', fwAvg: 7.4, link: 'https://www.filmweb.pl/film/Urz%C4%85d-1966-107889', enTitle: 'The Office', highlights: ['impact'] },
  { id: 'skaly',           title: 'Skały',                   year: 2003, medium: 'Shorts', favorite: true, region: 'de', rating: '9', director: 'Chris Stenner', poster: POSTER('skaly.webp'), link: 'https://www.filmweb.pl/film/Ska%C5%82y-2003-90382', fwAvg: 7.1, runtime: 8, watchedDate: '2020-09-11'},
  { id: 'in-the-fall',     title: 'In the Fall',             year: 2011, medium: 'Shorts', favorite: true, rating: '8' , director: 'Steve Cutts', region: 'uk', watchedDate: '2020-08-28', fwAvg: 6.7, link: 'https://www.filmweb.pl/film/In+the+Fall-2011-765398', poster: POSTER('inthefall.webp'), highlights: ['impact'] },
  { id: 'pierwsza-milosc', title: 'Pierwsza miłość',         year: 1974, medium: 'Shorts', favorite: true, region: 'pl', rating: '9', director: 'Krzysztof Kieślowski', runtime: 52 , watchedDate: '2021-06-21', fwAvg: 7.3, link: 'https://www.filmweb.pl/film/Pierwsza+mi%C5%82o%C5%9B%C4%87-1974-8644', highlights: ['impact'], enTitle: 'First Love' },
  { id: 'siec',            title: 'Sieć',                    year: 2010, medium: 'Shorts', favorite: true, region: 'pl', link: 'https://www.filmweb.pl/film/Sie%C4%87-2010-625645' },
  { id: 'linia-zycia',     title: 'Linia życia',             year: 2009, medium: 'Shorts', favorite: true, region: 'pl', poster: POSTER('liniazycia.webp'), link: 'https://www.filmweb.pl/film/Next+Generation+-+Linia+%C5%BCycia-2009-543214'},
  { id: 'odrzucone',       title: 'Odrzucone',               year: 2000, medium: 'Shorts', favorite: true, region: 'us', rating: '8', director: 'Don Hertzfeldt', poster: POSTER('odrzucone.webp'), link: 'https://www.filmweb.pl/film/Odrzucone-2000-148774', fwAvg: 7.2, runtime: 9, watchedDate: '2021-03-17' },
  { id: 'tori-no-uta',     title: 'Tori no Uta',             year: 2007, medium: 'Shorts', favorite: true, region: 'jp', rating: '8', runtime: 35 , director: 'Yoshitaka Amano', watchedDate: '2021-03-16', fwAvg: 7.4, link: 'https://www.filmweb.pl/film/Tori+no+Uta-2007-393374', enTitle: 'Bird Song' },
  { id: 'hinterland',      title: 'Hinterland',              year: 2010, medium: 'Shorts', favorite: true, rating: '8' , director: 'Linda McCarthy', region: 'uk', watchedDate: '2021-04-04', fwAvg: 6.1, link: 'https://www.filmweb.pl/film/Hinterland-2010-646080'},
  { id: 'solo-na-ugorze',  title: 'Solo na ugorze',          year: 1981, medium: 'Shorts', favorite: true, region: 'pl', rating: '8' , director: 'Jerzy Kalina', watchedDate: '2020-10-15', fwAvg: 5.7, link: 'https://www.filmweb.pl/film/Solo+na+ugorze-1981-117029', enTitle: 'Alone in a Fallow Field' },
];

// Default ordering: featured first, then by medium grouping, then by year desc.
const MEDIA = ['Movies', 'TV', 'Games', 'Animated Series', 'Feature Animation', 'Books', 'Shorts'];
const MEDIA_SHORT = { 'Movies': 'FILM', 'TV': 'TV', 'Games': 'GAME', 'Animated Series': 'ANIM SER', 'Feature Animation': 'ANIM FILM', 'Books': 'BOOK', 'Shorts': 'SHORT' };
const MEDIA_GLYPH = { 'Movies': 'F', 'TV': 'T', 'Games': 'G', 'Animated Series': 'A', 'Feature Animation': 'A', 'Books': 'B', 'Shorts': 'S' };

// ─────────────────────────────────────────────────────────────────────────
// PICK ONE FOR ME
//
// The "Pick one for me" button picks at random from this list. Add or remove
// item ids freely. By default, anything that has a `note` is included; the
// extras below let you surface picks that don't have a note yet.
// ─────────────────────────────────────────────────────────────────────────
const PICKABLE_IDS = [
  // Movies
  'age-of-success', 'walkabout', 'fight-club', 'ikiru', 'la-haine',
  'come-and-see', '2001-space', 'cinema-paradiso', 'tar', 'oldboy',
  'burning', 'three-colors-white', 'apocalypse-now',
  // TV
  'dekalog', 'twin-peaks', 'the-wire', 'sopranos', 'mad-men',
  'breaking-bad', 'six-feet-under', 'better-call-saul', 'severance',
  // Games
  'spec-ops', 'edith-finch', 'tlou', 'bioshock', 'ico',
  // Animated Series
  'cowboy-bebop', 'lain', 'eva', 'gits-sac', 'avatar-tla',
  'scavengers-reign',
  // Feature Animation
  'grave-fireflies', 'angels-egg', 'mononoke-hime', 'gits-movie',
  // Books
  'punpun', '1984',
];

// ─────────────────────────────────────────────────────────────────────────
// Spine coloring
//
// In Spines / Mix mode each spine gets a color. If an item has a `region`,
// the regional palette is used; otherwise the spine is colored by the
// item's decade. Edit either map to retune the library's overall feeling.
// ─────────────────────────────────────────────────────────────────────────
const REGION_COLORS = {
  pl:    '#7a3526',  // Polish — warm brick red
  jp:    '#2b3a52',  // Japanese — deep indigo
  kr:    '#3a5942',  // Korean — pine green
  us:    '#604832',  // American — saddle brown
  uk:    '#2a3a6a',  // British — navy (Union Jack blue)
  fr:    '#5b3a4a',  // French — burgundy
  it:    '#7a4a2a',  // Italian — terracotta
  de:    '#3b3b3b',  // German — graphite
  su:    '#5e2424',  // Soviet — oxblood
  ru:    '#5a4e2e',  // Russian — antique gold
  au:    '#8a5a26',  // Australian — red-earth ochre
  ca:    '#9c3b3b',  // Canadian — maple red
  ie:    '#24503a',  // Irish — emerald
  il:    '#34597e',  // Israeli — azure
  se:    '#2f6068',  // Swedish — teal
  fi:    '#4a6e86',  // Finnish — steel blue
  ch:    '#8f4038',  // Swiss — red clay
  eu:    '#4b5b40',  // Other European — olive
  other: '#3d3d3d',  // Other / unknown
  es:    '#7a3028',  // Spanish — dark carmine (flag red)
  nl:    '#8b4520',  // Dutch — dark burnt orange (royal orange)
  dk:    '#7a2434',  // Danish — dark rose crimson
  cz:    '#2a4a7a',  // Czech — slate blue (flag blue)
  hu:    '#6a3020',  // Hungarian — dark auburn
  bg:    '#4a5a30',  // Bulgarian — deep olive green
  hr:    '#5a2820',  // Croatian — dark rust
  gr:    '#1a4a7a',  // Greek — deep cerulean (flag blue)
  br:    '#2a5a2a',  // Brazilian — deep forest green
  hk:    '#6a3a2a',  // Hong Kong — deep vermilion (bauhinia red, muted)
  cn:    '#6a2828',  // Chinese — dark cinnabar (PRC red, muted)
  mx:    '#3a6a3a',  // Mexican — deep jade green
  tw:    '#2f5a52',  // Taiwanese — teal-green
  ar:    '#3a6a9a',  // Argentine — sky blue
  in:    '#9a5a24',  // Indian — saffron / deep orange
  lb:    '#3a6a3a',  // Lebanese — cedar green
  eg:    '#8a7a32',  // Egyptian — desert gold
  is:    '#3a5a7a',  // Icelandic — cold glacial blue
  th:    '#7a2a4a',  // Thai — deep magenta
  nz:    '#2a5240',  // New Zealand — deep forest
  sg:    '#7a3a3a',  // Singaporean — muted crimson
  ee:    '#2a4a6a',  // Estonian — deep blue
  uy:    '#5a82a8',  // Uruguayan — steel sky blue
  aq:    '#5a7a8a',  // Antarctica — icy slate (catch-all for unknown origin)
  ge:    '#6a3a52',  // Georgian — deep wine (qvevri red)
};

const DECADE_COLORS = {
  1800: '#3a3328', 1900: '#3a3328',
  1920: '#42332a', 1930: '#4a3a2c',
  1940: '#5b3f30', 1950: '#6b4a3a',
  1960: '#5b4a3a', 1970: '#4a4a5b',
  1980: '#3a4a5b', 1990: '#3a5b4a',
  2000: '#4a5b3a', 2010: '#5b4a3a',
  2020: '#5b3a3a',
};

window.CULTURE = {
  ITEMS,
  MEDIA, MEDIA_SHORT, MEDIA_GLYPH,
  PICKABLE_IDS,
  REGION_COLORS, DECADE_COLORS,
};
