// interpretations.js — Opus-written interpretations, keyed by item id. A deeper
// "what the work is really about" reading, distinct from the factual IMDb/TMDB
// description. Surfaced in the Reader as an extra description source (labelled
// "interpretation — Opus"); the toggle only appears for items that have one.
window.CULTURE_INTERPRETATIONS = {
 "spec-ops": "The special thing this game does is weaponize the one verb it shares with every other shooter: you keep pressing fire, and the game keeps letting you, and then it turns around and asks who told you to. The white phosphorus sequence is the spine of it — the interface hands you a targeting screen that looks exactly like the drone-camera detachment of a hundred power fantasies, you paint the map, and only afterward does the game walk you down through the burned bodies of the civilians you couldn't see from above. That is craft as accusation: the loading screens stop giving tips and start indicting you, Walker's voice frays from bark to whimper, and the medium's own conventions become the murder weapon. Your badges say it exactly — cerebral, cognitive, singular — because this is a work that thinks with its mechanics rather than its cutscenes, and it aimed that thinking at you, the player who came in fluent in the language it wanted to break. The hidden gem tag lands because its brilliance is buried inside something disguised as generic, so finding it feels like catching a confession no one else stayed long enough to hear. It rates an 8 and stays devastating and haunting for you because it refuses the exit every other shooter offers: there is no version where you were the good guy, only the version where you kept playing.",
 "dead-set": "The genius of the premise is that it needs almost no invention — Brooker just seals the Big Brother house during an outbreak and lets the reality-TV apparatus do the horror for him, because the format was already about caged people watched by a baying crowd that wants them destroyed. That is the social x-ray you tagged: the zombies outside behave exactly like the audience did, shambling toward the spectacle, and the show barely has to editorialize because the metaphor is load-bearing structure, not decoration. Your note nails the split that keeps this a 9 and not a 10 for you — the writing and acting are genuinely sharp, so the shaky handheld direction reads as a needless irritant grafted onto strong bones rather than a choice that earns its nausea. What makes it brutal in your sense is that it commits: the producer Patrick is written as the real monster and the show lets the dead take him without mercy or catharsis, honoring the cruelty of its own logic instead of blinking. You came for a zombie watch and got outwitted, which is why it registers as a surprise — the pleasure is watching a disposable genre turn out to have a scalpel hidden in it.",
 "ikiru": "Kurosawa's masterstroke is the structural gamble: he kills Watanabe two-thirds through and hands the final act to a room of drunk mourners reconstructing what the dying man actually did, so the film's real subject becomes memory arguing with itself about the meaning of a life. That fractured wake is the spine — the bureaucrats congratulate themselves, then slowly, resentfully, assemble the truth of the little park he willed into being, and the swing scene lands not as sentiment but as the one image that survives every self-serving retelling. This is why your 12 Angry Men comparison is exactly right: both films trust that a single confined space full of talking people can generate more tension and moral pressure than any spectacle, that substance and form are the same thing when the writing is this precise. You rate it a perfect 10 and call it the highest class of substance and art because it fuses the devastating, the directed, and the written — your three badges — into one argument, that a life means nothing until it does one true thing. It hits you where craft and meaning refuse to separate, which is the exact standard your other tens are measured against.",
 "walkabout": "Roeg edits by rhyme rather than plot — he cuts a butcher's cleaver against the outback, a city escalator against a rock face, so meaning arrives through collision instead of explanation, and the film becomes a sensory argument about what civilization costs. The unpredictable mismatch you name is the whole engine: two lost English children and an Aboriginal boy on walkabout share a landscape but never the same reality, and the tragedy is quietly built from the fact that the girl cannot read the one gesture that matters until it is far too late. That is the piercing beauty you felt — the desert shot as scripture, gorgeous and indifferent, while the human failure to connect plays out inside it as prose about life at the other end of the world. Your visuals, atmosphere, and cinematography badges are really one perception: here the image is the story, and Roeg refuses to translate the wonder into words because translation is precisely the wound the film is about. It earns your 10 as a surrealist quintessence of Australia because it makes you feel the loss of a connection that was offered, misread, and never recoverable — a beauty you can only mourn."
};
