#!/usr/bin/env python3
"""
update_cast.py
Fetches cast, crew, and tags for every film/TV entry and writes cast_data.js.

Data gathered (films & TV via TMDB, books via OpenLibrary):
  cast             top 20–25 billed actors (array)
  cinematographer  director of photography (string)
  composer         original score composer (string)
  animationDirector animation director, if applicable (string)
  writer           lead screenplay / story writer(s) (string)
  productionCompanies array of production/VFX company names
  tags             TMDB keywords → films/TV  |  OpenLibrary subjects → books

Setup — create a .env file in this directory:
  TMDB_API_KEY=your_key_here   (free at themoviedb.org/settings/api)

Run:
  python update_cast.py              full run (all media)
  python update_cast.py --dry-run    preview, no writes
  python update_cast.py --type=films
  python update_cast.py --type=tv
  python update_cast.py --type=books

Safe to re-run — entries already in cast_data.js are skipped unless --force.
Cache in cast_cache.json avoids redundant API calls.
"""

import json, os, re, sys, time, unicodedata
from urllib.request import urlopen, Request
from urllib.parse import urlencode
from urllib.error import HTTPError, URLError
try: sys.stdout.reconfigure(encoding='utf-8')   # Windows console: don't crash on ✓/✗
except Exception: pass

SCRIPT_DIR      = os.path.dirname(os.path.abspath(__file__))
IMPORTS_JS      = os.path.join(SCRIPT_DIR, 'imports.js')
DATA_JS         = os.path.join(SCRIPT_DIR, 'data.js')
CAST_JS         = os.path.join(SCRIPT_DIR, 'cast_data.js')
CACHE_FILE      = os.path.join(SCRIPT_DIR, 'cast_cache.json')
ENV_FILE        = os.path.join(SCRIPT_DIR, '.env')
OVERRIDES_FILE  = os.path.join(SCRIPT_DIR, 'tmdb_overrides.json')
MISSES_FILE     = os.path.join(SCRIPT_DIR, 'cast_misses.txt')

DRY_RUN   = '--dry-run' in sys.argv
FORCE     = '--force' in sys.argv
ONLY_TYPE = next((a.split('=', 1)[1] for a in sys.argv if a.startswith('--type=')), None)
ONLY_IDS  = next((set(a.split('=', 1)[1].split(',')) for a in sys.argv if a.startswith('--ids=')), None)
CAST_SIZE = 22  # actors per title

# Manual TMDB ID overrides: { "normalized title|year": tmdb_id }
# Populate tmdb_overrides.json after a run to fix titles that weren't matched.
OVERRIDES = {}
if os.path.exists(OVERRIDES_FILE):
    with open(OVERRIDES_FILE, encoding='utf-8') as _f:
        try:
            OVERRIDES = json.load(_f)
        except json.JSONDecodeError:
            pass

# ── .env / cache ──────────────────────────────────────────────────────────────

def load_env():
    env = {}
    if os.path.exists(ENV_FILE):
        with open(ENV_FILE) as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#') and '=' in line:
                    k, _, v = line.partition('=')
                    env[k.strip()] = v.strip().strip('"').strip("'")
    for k in ('TMDB_API_KEY',):
        if k in os.environ and k not in env:
            env[k] = os.environ[k]
    return env

def load_cache():
    if os.path.exists(CACHE_FILE):
        with open(CACHE_FILE, encoding='utf-8') as f:
            return json.load(f)
    return {}

def save_cache(cache):
    if not DRY_RUN:
        with open(CACHE_FILE, 'w', encoding='utf-8') as f:
            json.dump(cache, f, indent=2, ensure_ascii=False)

def load_cast_data():
    if os.path.exists(CAST_JS):
        content = open(CAST_JS, encoding='utf-8').read()
        m = re.search(r'window\.CULTURE_CAST\s*=\s*(\{[\s\S]*\});', content)
        if m:
            try:
                return json.loads(m.group(1))
            except json.JSONDecodeError:
                pass
    return {}

def save_cast_data(data):
    if DRY_RUN:
        return
    lines = ['// cast_data.js — generated by update_cast.py. Do not edit by hand.\n',
             '// Re-run: python update_cast.py\n',
             'window.CULTURE_CAST = ']
    lines.append(json.dumps(data, indent=2, ensure_ascii=False))
    lines.append(';\n')
    with open(CAST_JS, 'w', encoding='utf-8') as f:
        f.writelines(lines)

# ── HTTP ──────────────────────────────────────────────────────────────────────

def http_get(url, headers=None):
    try:
        h = {'User-Agent': 'culture-app/1.0', 'Accept-Encoding': 'identity'}
        if headers:
            h.update(headers)
        req = Request(url, headers=h)
        with urlopen(req, timeout=14) as r:
            return json.loads(r.read().decode('utf-8'))
    except (HTTPError, URLError, json.JSONDecodeError):
        return None

# ── String utils ──────────────────────────────────────────────────────────────

def normalize(s):
    s = unicodedata.normalize('NFKD', s.lower())
    s = ''.join(c for c in s if unicodedata.category(c) != 'Mn')
    s = re.sub(r'[^a-z0-9 ]', ' ', s)
    return re.sub(r'\s+', ' ', s).strip()

def match_score(query, candidate):
    nq, nc = normalize(query), normalize(candidate)
    if nq == nc: return 1.0
    if nq in nc or nc in nq: return 0.8
    wq, wc = set(nq.split()), set(nc.split())
    if not wq or not wc: return 0.0
    return len(wq & wc) / max(len(wq), len(wc))

# ── TMDB helpers ──────────────────────────────────────────────────────────────

TMDB = 'https://api.themoviedb.org/3'

def tmdb_search(kind, key, title, year):
    """Returns (tmdb_id, title_match_score) or (None, 0)."""
    override_key = f'{normalize(title)}|{year}'
    if override_key in OVERRIDES:
        return OVERRIDES[override_key], 1.0
    year_param = 'year' if kind == 'movie' else 'first_air_date_year'
    params = urlencode({'api_key': key, 'query': title, year_param: year})
    data = http_get(f'{TMDB}/search/{kind}?{params}')
    if not data or not data.get('results'):
        params2 = urlencode({'api_key': key, 'query': title})
        data = http_get(f'{TMDB}/search/{kind}?{params2}')
    if not data or not data.get('results'):
        return None, 0
    title_fields = ['title', 'original_title'] if kind == 'movie' else ['name', 'original_name']
    best, best_score = None, 0.42
    for r in data['results']:
        s = max((match_score(title, r.get(f) or '') for f in title_fields), default=0)
        r_year = (r.get('release_date') or r.get('first_air_date') or '')[:4]
        if r_year and abs(int(r_year) - int(year)) > 2:
            s *= 0.55
        if s > best_score:
            best, best_score = r, s
    return (best['id'] if best else None), best_score

def tmdb_movie_data(key, tmdb_id):
    """Fetch credits, keywords, genres, and poster for a movie in one request."""
    data = http_get(f'{TMDB}/movie/{tmdb_id}?append_to_response=credits,keywords&api_key={key}')
    if not data:
        return {}
    credits  = data.get('credits') or {}
    keywords = {'keywords': (data.get('keywords') or {}).get('keywords') or []}
    return _parse_tmdb(credits, keywords, data, kind='movie')

def tmdb_tv_data(key, tmdb_id):
    """Fetch aggregate_credits, keywords, genres, and poster for a TV show in one request."""
    data = http_get(f'{TMDB}/tv/{tmdb_id}?append_to_response=aggregate_credits,keywords&api_key={key}')
    if not data:
        return {}
    credits  = data.get('aggregate_credits') or {}
    keywords = {'results': (data.get('keywords') or {}).get('results') or []}
    return _parse_tmdb(credits, keywords, data, kind='tv')

def _parse_tmdb(credits, keywords, details, kind):
    out = {}

    # Cast (top N)
    cast_raw = (credits or {}).get('cast') or []
    # aggregate_credits wraps cast members differently — normalise
    cast_list = []
    for c in cast_raw[:CAST_SIZE]:
        name = c.get('name') or ''
        if name:
            cast_list.append(name)
    if cast_list:
        out['cast'] = cast_list

    # Crew fields
    crew = (credits or {}).get('crew') or []
    # aggregate_credits: crew items have 'jobs' array
    def crew_find(dept, jobs):
        for c in crew:
            if c.get('department') != dept:
                continue
            c_jobs = c.get('jobs') or [{'job': c.get('job', '')}]
            for j in c_jobs:
                if j.get('job') in jobs:
                    return c.get('name') or ''
        return ''

    dop = crew_find('Camera', ['Director of Photography', 'Cinematographer'])
    if dop: out['cinematographer'] = dop

    composer = crew_find('Sound', ['Original Music Composer', 'Music', 'Composer'])
    if composer: out['composer'] = composer

    anim_dir = crew_find('Directing', ['Animation Director', 'Head of Animation',
                                        'Supervising Animator'])
    if anim_dir: out['animationDirector'] = anim_dir

    writers = []
    for c in crew:
        dept = c.get('department')
        c_jobs = c.get('jobs') or [{'job': c.get('job', '')}]
        if dept == 'Writing':
            for j in c_jobs:
                if j.get('job') in ('Screenplay', 'Story', 'Writer', 'Novel',
                                     'Script', 'Creator'):
                    n = c.get('name') or ''
                    if n and n not in writers:
                        writers.append(n)
    if writers:
        out['writer'] = ', '.join(writers[:2])  # lead 1–2 writers

    # Production companies
    companies = [(c.get('name') or '') for c in (details or {}).get('production_companies', [])]
    companies = [c for c in companies if c]
    if companies:
        out['productionCompanies'] = companies

    # Tags from keywords
    kw_list = (keywords or {}).get('keywords') or (keywords or {}).get('results') or []
    tags = [k.get('name') for k in kw_list if k.get('name')]
    if tags:
        out['tags'] = tags

    # Genres
    genres = [g['name'] for g in (details or {}).get('genres', []) if g.get('name')]
    if genres:
        out['genres'] = genres

    # Poster — stored as tmdbPoster so it doesn't override locally-set poster fields
    poster_path = (details or {}).get('poster_path')
    if poster_path:
        out['tmdbPoster'] = f'https://image.tmdb.org/t/p/w500{poster_path}'

    return out

# ── OpenLibrary ───────────────────────────────────────────────────────────────

def ol_book_data(title, author=None):
    params = {'title': title, 'limit': '5',
              'fields': 'title,author_name,subject'}
    if author:
        params['author'] = author
    data = http_get(f'https://openlibrary.org/search.json?{urlencode(params)}')
    docs = (data or {}).get('docs') or []
    best, best_score = None, 0.42
    for doc in docs:
        s = match_score(title, doc.get('title') or '')
        if author:
            a_match = max((match_score(author, a) for a in (doc.get('author_name') or [])), default=0)
            s = (s + a_match) / 2
        if s > best_score:
            best, best_score = doc, s
    if not best:
        return {}
    subjects = best.get('subject') or []
    # Filter: skip very generic subjects and limit to 15
    skip = {'Fiction', 'Nonfiction', 'Large print', 'Accessible book', 'Protected DAISY',
            'In library', 'OverDrive', 'Open Library Staff Picks', 'Lending library'}
    tags = [s for s in subjects if s not in skip][:15]
    return {'tags': tags} if tags else {}

# ── Entry parsing from source files ──────────────────────────────────────────

def parse_entries(path):
    """
    Yields (item_id, title, year, author, medium, is_json_fmt) per entry line.
    Handles both JSON (TV/game/book) and JS object literal (film/data.js) formats.
    """
    with open(path, encoding='utf-8') as f:
        for line in f:
            # JSON format: "id": "imp-s-..."
            m = re.search(r'"id"\s*:\s*"([^"]+)"', line)
            if m:
                item_id = m.group(1)
                title = _json_field(line, 'title')
                year  = _json_field(line, 'year')
                author = _json_field(line, 'director')
                medium = _json_field(line, 'medium')
                if title and year:
                    yield item_id, title, year, author, medium, True
                continue
            # JS object literal: id: 'slug' or id: 'imp-f-...'
            m = re.search(r"\bid\s*:\s*'([^']+)'", line)
            if m:
                item_id = m.group(1)
                title_m = re.search(r"\btitle\s*:\s*'((?:[^'\\]|\\.)*)'", line)
                year_m  = re.search(r'\byear\s*:\s*(\d{4})', line)
                dir_m   = re.search(r"\bdirector\s*:\s*'((?:[^'\\]|\\.)*)'", line)
                med_m   = re.search(r"\bmedium\s*:\s*'([^']+)'", line)
                if title_m and year_m:
                    title  = re.sub(r"\\(.)", r"\1", title_m.group(1))
                    year   = year_m.group(1)
                    author = re.sub(r"\\(.)", r"\1", dir_m.group(1)) if dir_m else None
                    medium = med_m.group(1) if med_m else None
                    yield item_id, title, year, author, medium, False

def _json_field(line, field):
    m = re.search(rf'"{re.escape(field)}"\s*:\s*"([^"]*)"', line)
    if m: return m.group(1)
    m = re.search(rf'"{re.escape(field)}"\s*:\s*(\d+)', line)
    if m: return m.group(1)
    return None

# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    env = load_env()
    tmdb_key = env.get('TMDB_API_KEY', '')
    if not tmdb_key:
        print('ERROR: TMDB_API_KEY not found.')
        print('  1. Get a free key at https://www.themoviedb.org/settings/api')
        print('  2. Add to .env:  TMDB_API_KEY=your_key_here')
        sys.exit(1)

    cache        = load_cache()
    cast_data    = load_cast_data()
    stats        = {'added': 0, 'skipped': 0, 'not_found': 0}
    not_matched  = []  # (title, year, medium, best_score)

    print(f'{"[DRY RUN] " if DRY_RUN else ""}Loaded {len(cast_data)} existing entries from cast_data.js\n')

    want_films = not ONLY_TYPE or ONLY_TYPE in ('films', 'movies')
    want_tv    = not ONLY_TYPE or ONLY_TYPE in ('tv', 'shows')
    want_books = not ONLY_TYPE or ONLY_TYPE in ('books',)

    film_media = {'Movies', 'Feature Animation', 'Shorts'}
    tv_media   = {'TV', 'Animated Series'}

    for path in (IMPORTS_JS, DATA_JS):
        label = os.path.basename(path)
        print(f'=== {label} ===')
        for item_id, title, year, author, medium, is_json in parse_entries(path):
            if not medium:
                continue
            if ONLY_IDS and item_id not in ONLY_IDS:
                continue

            # Type filter
            if medium in film_media and not want_films:
                continue
            if medium in tv_media and not want_tv:
                continue
            if medium == 'Books' and not want_books:
                continue
            if medium == 'Games':
                continue  # no cast enrichment for games

            # Skip if already present (unless --force)
            if not FORCE and item_id in cast_data:
                stats['skipped'] += 1
                continue

            cache_key = f'{item_id}|{normalize(title)}|{year}'

            if cache_key not in cache:
                print(f'  [{medium}] {title} ({year})')
                entry_data = {}

                if medium in film_media:
                    tmdb_id, score = tmdb_search('movie', tmdb_key, title, year)
                    if tmdb_id and score >= 0.42:
                        time.sleep(0.3)
                        entry_data = tmdb_movie_data(tmdb_key, tmdb_id)
                    else:
                        print(f'    ✗ no TMDB match (best score {score:.2f})')
                        not_matched.append((title, year, medium, score))

                elif medium in tv_media:
                    tmdb_id, score = tmdb_search('tv', tmdb_key, title, year)
                    if tmdb_id and score >= 0.42:
                        time.sleep(0.3)
                        entry_data = tmdb_tv_data(tmdb_key, tmdb_id)
                    else:
                        print(f'    ✗ no TMDB match (best score {score:.2f})')
                        not_matched.append((title, year, medium, score))

                elif medium == 'Books':
                    entry_data = ol_book_data(title, author)

                cache[cache_key] = entry_data
                time.sleep(0.3)
            else:
                entry_data = cache[cache_key]

            if entry_data:
                cast_data[item_id] = entry_data
                stats['added'] += 1
                summary = []
                if 'cast' in entry_data:
                    summary.append(f'{len(entry_data["cast"])} actors')
                for f in ('cinematographer', 'composer', 'writer', 'animationDirector'):
                    if f in entry_data:
                        summary.append(f'{f}: {entry_data[f][:25]}')
                if 'tags' in entry_data:
                    summary.append(f'{len(entry_data["tags"])} tags')
                if summary:
                    print(f'    ✓ {", ".join(summary)}')
            else:
                stats['not_found'] += 1

        print()

    save_cache(cache)
    save_cast_data(cast_data)

    print(f'Done — added/updated: {stats["added"]}, skipped: {stats["skipped"]}, no match: {stats["not_found"]}')
    print(f'cast_data.js now has {len(cast_data)} entries')
    if DRY_RUN:
        print('(dry run — no files written)')
    else:
        print('Add  <script src="cast_data.js"></script>  to index.html if not already there.')

    if not_matched:
        print(f'\n── UNMATCHED ({len(not_matched)}) ──')
        for t, y, med, sc in sorted(not_matched):
            print(f'  {med:<22} {y}  {t}  (best {sc:.2f})')
        print('  → Add manual overrides to tmdb_overrides.json to fix these.')
        if not DRY_RUN:
            with open(MISSES_FILE, 'w', encoding='utf-8') as f:
                for t, y, med, sc in sorted(not_matched):
                    f.write(f'{med}\t{y}\t{t}\t{sc:.2f}\n')
            print(f'  → Misses written to cast_misses.txt')

if __name__ == '__main__':
    main()
