#!/usr/bin/env python3
"""update_tmdb_overview.py — pull TMDB synopses into tmdb_data.js.

The Reader's IMDb⇄TMDB description toggle needs a TMDB synopsis to flip to, but
none was ever stored. TMDB's per-title details carry `overview`; update_cast.py
already resolves each title to a TMDB id, so we reuse that resolver here and store
just the overview.

Output (own file, merged at runtime as item.summary when not already set):
  window.CULTURE_TMDB = { "<itemId>": "<overview>" }

Resumable (tmdb_cache.json). Order: data.js favorites → imports → wishlist.
Run: python update_tmdb_overview.py [--dry-run] [--limit N] [--force]
TMDB_API_KEY must be in .env.
"""
import json, os, sys, time
try: sys.stdout.reconfigure(encoding='utf-8')
except Exception: pass
import update_cast as uc      # load_env, http_get, tmdb_search, TMDB
import update_omdb as uo      # parse_items, MOVIE, TV, FILES

SD    = os.path.dirname(os.path.abspath(__file__))
OUT   = os.path.join(SD, 'tmdb_data.js')
CACHE = os.path.join(SD, 'tmdb_cache.json')
DRY   = '--dry-run' in sys.argv
FORCE = '--force' in sys.argv
LIMIT = next((int(sys.argv[i + 1]) for i, a in enumerate(sys.argv)
              if a == '--limit' and i + 1 < len(sys.argv)), None)


def fetch_overview(key, item):
    kind = 'movie' if item['medium'] in uo.MOVIE else 'tv'
    tid, score = uc.tmdb_search(kind, key, item['en'] or item['title'], item['year'] or 0)
    if not tid:
        return None
    data = uc.http_get(f'{uc.TMDB}/{kind}/{tid}?api_key={key}')
    ov = (data or {}).get('overview') or ''
    return ov.strip() or None


def main():
    env = uc.load_env()
    key = env.get('TMDB_API_KEY')
    if not key:
        print('No TMDB_API_KEY in .env'); return

    items, seen = [], set()
    for name, rank in uo.FILES:
        p = os.path.join(SD, name)
        if not os.path.exists(p):
            continue
        for it in uo.parse_items(p):
            if it['id'] not in seen:
                seen.add(it['id']); it['_rank'] = rank; items.append(it)
    items.sort(key=lambda x: (x['_rank'], -x['rating'], x['title']))

    cache = json.load(open(CACHE, encoding='utf-8')) if os.path.exists(CACHE) else {}
    todo = [x for x in items if FORCE or x['id'] not in cache]
    if LIMIT:
        todo = todo[:LIMIT]
    print(f'{"[DRY] " if DRY else ""}Film/TV: {len(items)}  ·  to fetch now: {len(todo)}')
    if DRY:
        for it in todo[:12]:
            print(f"  {it['id']}  {it['en'] or it['title']} ({it['year']})")
        print('\n--dry-run: no calls, nothing written.'); return

    found = 0
    for n, it in enumerate(todo, 1):
        ov = fetch_overview(key, it)
        cache[it['id']] = ov          # cache misses (None) too
        if ov:
            found += 1
        if n % 25 == 0:
            json.dump(cache, open(CACHE, 'w', encoding='utf-8'), ensure_ascii=False, indent=1)
            print(f'  … {n}/{len(todo)}, {found} overviews')
        time.sleep(0.06)

    json.dump(cache, open(CACHE, 'w', encoding='utf-8'), ensure_ascii=False, indent=1)
    good = {k: v for k, v in cache.items() if v}
    header = ('// tmdb_data.js — generated by update_tmdb_overview.py. TMDB synopses for\n'
              '// the Reader IMDb⇄TMDB toggle. Do not edit by hand. Re-run:\n'
              '// python update_tmdb_overview.py\n'
              'window.CULTURE_TMDB = ')
    open(OUT, 'w', encoding='utf-8').write(header + json.dumps(good, ensure_ascii=False, indent=1) + ';\n')
    print(f'\nDone. {found} overviews this run; tmdb_data.js holds {len(good)} '
          f'(of {len(cache)} looked up).')


if __name__ == '__main__':
    main()
