// art-about.js — Fable reads for the canon's flagship works (Phase 5). Two tiers, same
// convention as rotation's llm-about: `about` = what you're looking at (Info), `deep` =
// how the work works — composition, light, history, where to stand (Interpretation).
// Hand-written via Claude (Fable) or drafted by Opus + Fable-polished (per-entry by:); keyed by canvas work id.
window.CANVAS_ART_ABOUT = {
"impression-sunrise": {
about: "Le Havre's harbour at sunrise, 1872 — an orange sun over grey-blue mist, cranes and masts dissolved in haze, two small rowboats. The quick harbour sketch whose title a mocking critic turned into the name of an entire movement: Impressionism.",
deep: "The trick is tonal, not chromatic: turn the painting greyscale and the sun nearly vanishes — it is almost exactly as bright as the sky around it, differing only in hue. That's why it vibrates instead of glowing. Everything else is one blue-grey weather, laid down in a single sitting; the rowboat is six calligraphic strokes. The title was modesty — 'impression', a sketch of an instant, not a finished view — and the honesty is what the critics mistook for laziness. Stand back: it assembles at distance, like all weather does." },

"monet-woman-with-a-parasol": {
about: "Camille Monet and their son Jean on a summer bluff, 1875 — seen from below against a windy sky, her veil and dress alive, the grass throwing green light up into the white fabric.",
deep: "The real subject is wind. It runs through everything: the veil, the tilted parasol, the grass leaning one way, the clouds streaking the same diagonal. Monet paints from below, so Camille towers against sky rather than landscape — a figure becoming weather. Look at the 'white' dress: it is green underneath (light bounced up off the grass) and violet in the shadows; there is almost no actual white. Jean stands further back, smaller and softer-edged — depth of field done in paint before photography taught everyone the word. A portrait in which the sitter's face is the least important thing, veiled, in shadow, turned to the light." },

"monet-nympheas-orangerie": {
about: "The two oval rooms of the Orangerie: eight room-length panels of Monet's pond at Giverny — water, lilies, willow reflections, no horizon, no shore. His gift to France, signed the day after the WWI armistice.",
deep: "There is no horizon anywhere — you never see the sky, only the sky reflected. That single decision removes the ground you'd normally stand on as a viewer, which is why the rooms feel like floating. The panels follow the day around the ovals, dawn to dusk. Monet built them as a war memorial without a single soldier: an 'asylum of peaceful meditation', he called it, for a country that had just buried a generation. The scale is the argument — painting as an environment you enter, half a century before installation art had a name." },

"the-clouds": {
about: "One of the Orangerie's Water Lilies panels: clouds crossing the pond's surface — the sky existing only as its own reflection among the lilies.",
deep: "The inversion is the whole idea: to see the sky you look down. The clouds are under the lilies, which float on top of them — a quiet reversal of every landscape convention, near and far collapsed onto one watery plane. What floored you here is the painting teaching your eye a new default: surface as depth, reflection as reality. It is the closest the cycle comes to pure abstraction while still being, verifiably, just a pond." },

"the-thinker": {
about: "Rodin's seated giant, mid-thought — conceived in 1880 as 'The Poet' (Dante himself) for the top of the Gates of Hell, gazing down at his own damned, then enlarged into the world's most famous statue of thinking.",
deep: "He thinks with his whole body, not his head. Every muscle is clenched — toes gripping the rock, back rounded like a coiled spring — because for Rodin thought was labour, not repose. Look closely at the pose: the right elbow rests on the LEFT knee, a torsion that no one sits in comfortably; it winds the body a quarter-turn tighter than rest. The figure was meant to be seen from below, brooding over the Gates — in the museum garden you can still walk around him and watch the silhouette change from effort to exhaustion depending on where you stand." },

"the-kiss": {
about: "Rodin's marble lovers, 1880s — Paolo and Francesca from Dante's Inferno, the adulterous couple murdered mid-kiss; the book that made them fall in love is still slipping from his hand.",
deep: "It is a kiss that never lands: look — their lips do not actually touch. Rodin froze the instant before, which is the erotic engine of the thing. His right hand hesitates on her thigh; the book (they were reading Lancelot when it happened, Dante says) falls from his left. The couple were bound for the Gates of Hell but Rodin cut them from the design — too happy for the door of the damned. He came to dislike the piece, calling it conventional, 'a large sculpted knick-knack' — the polished lovers rising out of the rough-hewn base show exactly the finished/unfinished contrast he preferred elsewhere. The public overruled him, permanently." },

"klimt-kiss": {
about: "Klimt's golden couple, 1908 Vienna: a man and woman on the edge of a flowered cliff, wrapped into a single gilded shape, her face serene, his hidden — the icon of the Secession's golden period.",
deep: "The two bodies fuse into one gold silhouette — but the ornament splits them: his robe carries hard black-and-white rectangles, hers soft circles and blooms, masculine and feminine coded straight into pattern, joined without merging. Her position is stranger than the poster versions let on: she kneels at a cliff edge, toes curled over into empty flowered space — bliss on the brink. Klimt was a goldsmith's son and the gold is real leaf, Byzantine in intent: the flat, holy gold-ground of icons wrapped around profane love. Whether she is melting or enduring the kiss is left exactly, deliberately, undecidable." },

"the-great-wave-off-kanagawa": {
about: "Hokusai's woodblock print, c. 1830: a colossal wave with claw-like foam about to crash on three fishing boats, with Mount Fuji — the print's true subject — tiny and calm in the trough.",
deep: "Read it the way its first audience did, right to left: the wave then attacks INTO your reading direction, against the grain, which is why it feels aggressive rather than merely big. The foam breaks into literal claws over the rowers, who bow flat into it. And the joke of the composition: this is one of the Thirty-six Views of Mount Fuji — the mountain is the smallest thing in it, echoed by the wave itself, whose silhouette is a false Fuji looming where the real one should be. The deep blue was brand new: Prussian blue, a synthetic European pigment that had just reached Japan — the most famous image of 'old Japan' is partly made of imported chemistry. And it's a print: thousands were pulled; you stood in front of one of many originals." },

"the-birth-of-venus": {
about: "Bouguereau's 1879 Venus: the goddess standing full-length on the shell, ringed by tritons, nereids and putti — French academic painting at its most perfect, made at the exact moment the Impressionists were rendering it obsolete.",
deep: "The brushwork is deliberately invisible — porcelain skin with no visible stroke anywhere, the polar opposite of everything else you've floored (Monet's open weave, Rodin's thumb-marks). Her pose is a double quotation: the antique Venus Anadyomene wringing her hair, filtered through Raphael's Galatea — Bouguereau declaring the whole lineage in one S-curve. Floored by this AND by Impression, Sunrise is not a contradiction; it's the full argument of 1870s Paris hanging in one head: what painting had perfected, next to what it was about to become." },

"pont-de-l-europe-gare-saint-lazare": {
about: "Monet inside Gare Saint-Lazare, 1877: the iron bridge and signals of the Pont de l'Europe, locomotives filling the station with steam — modernity painted as weather.",
deep: "Monet asked the stationmaster to delay trains and stoke the engines so the steam would perform. That's the tell of what the series is: not a picture of a train station but of a new kind of sky, man-made, indoors. The iron geometry — bridge, tracks, glass roof — supplies the hard drawing, and the steam immediately dissolves it, the two halves of the industrial age (structure and vapour) fighting in one frame. It is the same painter who would spend his last decades on water lilies: already, here, the subject is what light does to something that won't hold still." },

"water-lilies-reflection-of-a-weeping-willow": {
about: "Late Monet at the Marmottan: the pond at Giverny with a weeping willow doubled in the water — painted in the cataract years, when his eyes were failing and the colour loosened toward abstraction.",
deep: "The willow was Monet's grief motif — he painted them through WWI, mourning trees for a mourning country, while his own sight clouded. Up close the canvas barely depicts: raw, dragged strokes, colours from memory as much as sight (the cataracts pushed everything toward hot reds and muddy yellows he couldn't fully see). It becomes a willow only when you step away. What you loved at the Marmottan is the hinge in art history: the last Impressionist canvases and the first abstract ones are, for a few years, the same objects." },

"walk-near-argenteuil": {
about: "Monet, 1875: Camille and Jean on a path through poppies and high summer grass at Argenteuil — the small domestic Monet, the family inside the landscape.",
deep: "The figures barely have faces; the poppies get more paint than the people. That inversion is the quiet radicalism of the Argenteuil years — the family walk matters as a colour event (red spots against green, a blue parasol against sky), not as a portrait. It pairs with Woman with a Parasol, painted the same year: the same wife, the same son, the same wind — one monumental and seen from below, this one small and level, as if you were walking a few steps behind them." },

"podkowinski-szal-uniesien": {
about: "Podkowiński's Frenzy of Exultations, 1894: a naked woman in ecstasy clinging to a monstrous rearing black horse — Polish Symbolism's succès de scandale. One canvas exists, and it carries scars: the painter slashed it himself.",
deep: "Kraków laughed at it and gossiped about the model's identity; after five weeks on show Podkowiński walked in and took a knife to the canvas — then died within the year at 29, and the painting was restored with his cuts inside it. The image itself is pure fin-de-siècle: eros as a runaway animal, the horse's head a storm-cloud of black paint that stops depicting and becomes pure vortex. You likely saw it in the Sukiennice's quiet salon of 19th-century Polish art, where it still radiates exactly the scandal the varnish can't cover." },

"leech-the-sunshade": {
about: "William John Leech, c. 1913: a woman — his wife Elizabeth — under a parasol in strong Concarneau light, the Irish post-impressionist's answer to the French plein-air masters. (Image withheld: Leech is in copyright until 2039 — see it at the NGI.)",
deep: "Leech was an Irishman painting in Brittany with French eyes: the parasol filters the light green, the same bounced-colour game Monet played with Camille's dress, and the whole picture is really about that filtered glow on white fabric. That you singled this out at the National Gallery of Ireland — and its sibling, A Convent Garden, Brittany — before knowing any of this context, is your taste being consistent: parasols, filtered sunlight, figures dissolved in it. It's the same painting-idea you floored twice under other names." },

"peasants-houses-eragny": {
about: "Pissarro, 1887: cottages at Éragny in his pointillist period — the patriarch of Impressionism borrowing the dot from Seurat, twenty years his junior. Found floored in, of all places, Sydney.",
deep: "Pissarro was the only painter in all eight Impressionist exhibitions, and here he is in his late fifties humbly adopting a younger man's technique — the divisionist dot — because he thought it truer. The dots force patience: the picture shimmers rather than describes, and the humble subject (backs of houses, a bit of garden) makes clear the method is the point. He later abandoned it as too slow, too rigid. Your one Australian floored work being a French field painted in dots is the taste-data equivalent of a signature." },

"the-tuileries-study": {
about: "Monet, 1876: the Tuileries gardens from a window above — a study, kept loose, Paris hazed in light with the garden's geometry dissolving under it.",
deep: "It is labelled a study and that is its virtue: Monet at speed, the formal French garden — the most geometric landscape in Europe — melting into dabs. The view is from Victor Chocquet's apartment, looking down: the elevated viewpoint flattens the garden into bands of colour, a proto-aerial abstraction. Where the finished Monets of the period negotiate between drawing and light, here light simply wins." },

"strindberg-underlandet": {
about: "An oil landscape by August Strindberg — the playwright, painting. A dark mass of forest splits open onto a burst of golden light, more sensation than scene. He painted it in 1894, in one of the short feverish spells when he painted at all. Its home is Stockholm's Nationalmuseum, however far it travels.",
deep: "Strindberg only painted when he couldn't write — in crisis, fast, trusting the accident. He worked with a palette knife, no drawing underneath, no fixed motif, and argued in an essay that same year that chance should do half the making: smear the paint, then find the image in it, the way you find shapes in clouds. Underlandet is built as a tunnel — dark, thickly scraped woodland framing a radiant gap, so your eye is dragged through the gloom to the light before you register a single detail. The title does the rest: that bright opening reads less like sky than like a hole into another world. Zoom into the central gap — what glows from a distance is bare ridged knife-work close up, image and substance at once. Painting this chance-made and subjectless wouldn't have a name until art informel, half a century on.",
by: 'Opus · Fable' },

"sergel-hetsigt-karlekspar": {
about: "An ink-and-wash drawing by Johan Tobias Sergel, the great Swedish sculptor of the late eighteenth century: two lovers caught mid-embrace in a handful of urgent strokes. It was never meant for exhibition — Sergel's drawings were private, done for himself — which is exactly why it still feels alive. Nationalmuseum, Stockholm.",
deep: "By day Sergel carved marble gods and royal monuments; on paper he answered to no one. The couple is drawn the way a sculptor thinks — in mass and torsion, not outline — so two bodies read as one twisting volume, the wash doing the work of shadow falling over form. Nothing is finished and nothing is missing: the anatomy is summarised down to pressure, one body against another. Zoom in on the arms and hands, where a few overlapping strokes lock the figures together — that knot is the whole drawing. The irony is that these private sheets, tossed off at speed, now look more modern than the neoclassical marbles that made his name. The official Sergel obeyed antiquity; this one obeyed the moment.",
by: 'Opus · Fable' },

"women-in-the-garden": {
about: "Monet at twenty-five, thinking enormous: nearly two and a half metres of canvas, four women in summer dresses among trees and flowerbeds, painted in 1866 — before Impressionism had a name. The real subject is already sunlight: how it sifts through leaves and lands on white fabric. Musée d'Orsay, Paris.",
deep: "Monet insisted on painting it outdoors at full scale, digging a trench in the garden so the huge canvas could be lowered on a pulley and he could keep working at eye level. Camille, his companion, modelled for several of the figures, but the women are nearly a pretext. Watch the seated woman in the foreground shade: she goes cool grey-blue while the sunlit dresses behind stay warm, and her face is lit from below by light bouncing off her own dress — light, not story, organises everything. The Salon rejected it in 1867 as raw and unfinished. The joke came later: in 1921 the French state, heir to the jury that turned it down, bought it from the elderly Monet for 200,000 francs — a rejection repaid with half a century's interest.",
by: 'Opus · Fable' },

"the-town": {
about: "A late seascape by August Strindberg from 1903, his final period of painting. Stockholm — the town of the title — is a thin dark strip on the horizon; nearly everything else is storm, worked in heavy palette-knife impasto. Small, turbulent, close to abstract: landscape as a weather report from inside a mind. Nationalmuseum, Stockholm.",
deep: "By 1903 Strindberg no longer painted in front of the motif at all — he built pictures like this indoors, from memory, letting the dragged knife find cloud and spray on its own. The composition is deliberate imbalance: the horizon shoved low, the sky given most of the canvas, so the storm doesn't sit over the town, it looms. Then look where the light lands — a pale glow breaks exactly over the little silhouette of Stockholm, the city he spent his whole writing life fighting granted one centimetre of canvas and a single mercy of brightness. Step back and the crusted ridges resolve into moving air and water; step in and they collapse into raw pigment again. That flicker between picture and matter is what later abstraction would build a whole aesthetic on.",
by: 'Opus · Fable' },

"midsummer-dance": {
about: "Anders Zorn's 1897 scene of villagers dancing through a midsummer night in his native Dalarna. Couples whirl between the timber cottages under a sky that never quite darkens. It is Sweden's most beloved image of itself — folk dress, red houses and the long pale light of the north. Nationalmuseum, Stockholm.",
deep: "The subject is dancing but the achievement is light. At midsummer this far north the sun barely dips below the horizon, and Zorn paints exactly that hour: no lamps, no moon, yet everything is visible in a warm, sourceless glow — a village lit by a sun that has set but not gone. The sky behind the rooftops is already turning back into morning; the dance has simply outlasted the night. In the foreground couples, feet and skirts blur into broad wet strokes while the faces stay sharp and flushed — Zorn paints the sensation of spinning, not the anatomy of it. By 1897 he was an international portrait star, painting the rich on two continents; this is the world he kept coming home to, and it shows — nothing here is observed coldly.",
by: 'Opus · Fable' },

"the-starry-night": {
about: "Van Gogh's 1889 night sky over a village, painted at the asylum in Saint-Rémy-de-Provence where he had committed himself. A cypress flames up the left edge; eleven stars and a crescent moon churn above the hills. You know it before you see it — which is the thing worth fighting. Museum of Modern Art, New York.",
deep: "It looks like ecstatic reportage; it's a composite, painted by day in a downstairs studio — he wasn't allowed to work in his bedroom. The sky is from his east-facing window, but the village can't be seen from there, and the spire is a Dutch church smuggled in from memory. The one documented observation is the brightest light beside the cypress: Venus, the morning star, which he had written to Theo about watching before dawn. Around that fact he let go — thick curling strokes knotting the sky into two great spirals, the cypress, a tree he associated with death, binding earth to heaven while the village sleeps below in straight, sober lines. Turbulence organised against calm. Van Gogh judged the picture a failure, telling Bernard its abstraction had gone too far. Every gift shop on earth has since disagreed.",
by: 'Opus · Fable' },
};
