// art_inspect.js — the INSPECTION layer: deep readings written by Fable (the site's resident
// model), from actually studying each image. Four lenses per work:
//   see     — what is literally on the surface and how it works on the eye
//   about   — what the picture is about; the layer behind the subject
//   craft   — why it sings: technique, composition, the decisions
//   context — the moment around it: history, biography, scandal
// Pilot batch 2026-07-12: Szał uniesień · Woman with a Parasol · A Convent Garden, Brittany ·
// The Milkmaid (the Rijksmuseum IIIF test work).
window.CANVAS_INSPECT = {

"podkowinski-szal-uniesien": {
  see: "A naked woman with copper hair rides — no, clings to — a black horse rearing through nothing. There is no ground, no horizon, no sky: the whole canvas is one churned storm of gray-black strokes, and the only light in it is her body, pressed along the animal's neck. Look where her hair ends and the mane begins: you can't find the seam. The horse's head is barely a horse — the eye burns red, the mouth gapes, it is closer to a skull with nostrils. Her face isn't afraid. Her eyes are closed, cheek against the beast, somewhere between prayer and dissolution.",
  about: "Desire, painted as the thing that carries you off. She holds no reins — there are none — and she isn't riding the horse so much as surrendering to it: the animal is not her transport but her own passion given a body, and the void around them is what's left of the world once obsession has eaten it. The title says it plainly and plurally — a frenzy of raptures — and the picture refuses to tell you whether this is ecstasy or destruction, because its whole argument is that at this pitch they are the same thing.",
  craft: "One light source: her skin. Podkowiński carves the figure out of the dark the way you'd carve a flame out of night, and lets the horse stay half-dissolved — it reads as darkness that has grown anatomy. The composition is a single rising diagonal, and every stroke in the surrounding void swirls to serve it; stand close and the 'background' is pure directional impasto, weather rather than place. Then the temperature spikes: the red of the eye, the red in her hair — two embers in three metres of storm. It is enormous (three metres tall), and the scale is part of the argument: a private state made monumental.",
  context: "Kraków, 1894 — the painting that detonated Polish Symbolism. Crowds queued; critics called it obscene; and thirty-six days into the exhibition Podkowiński walked in with a knife and slashed the canvas — his own painting, his own confession (the usual reading: an unrequited love, painted too legibly). It was restored, but he was dead within a year, at twenty-nine, and the slashing became inseparable from the work: the frenzy in the title claimed the painter too. It hangs in the Sukiennice in Kraków."
},

"monet-woman-with-a-parasol": {
  see: "You are standing at the bottom of a small rise, looking up. Camille Monet turns toward you mid-stride — veil blown across her face, green parasol tilted against the light — and two-thirds of the canvas is sky, fast clouds dragged in comma-strokes. Her dress catches everything: look closely and the 'white' fabric is painted blue, grey, yellow — the sky and grass reflected off it. Behind her, small over the crest of the hill, her son Jean watches. The grass streaks with wind. Everything in the picture is moving, and all of it belongs to one single second.",
  about: "It isn't a portrait — her face is the least finished thing in it. The subject is the gust: one instant of wind, light and turning, seized whole. That's the radical claim of the picture — that a moment of a woman glancing back on a walk deserves the monumentality painting used to reserve for saints; the low viewpoint sets her against the sky like a figurehead. And it is family made luminous: his wife, his son, an ordinary afternoon at Argenteuil — which is exactly why it later reads as elegy.",
  craft: "Painted outdoors, almost certainly in a single session of a few hours — the speed is visible everywhere and is the point: no reworking, no studio finish, decisions made at the pace of weather. The famous lesson is the dress: white rendered with nearly no white, because Impressionism's core discovery is that local colour is a lie — things are the colour of the light that hits them. The shadow slanting down the grass pins the whole airy composition to the hill; the parasol's dense green is the one solid accent holding the sky back. Signed low right, 'Claude Monet 75.'",
  context: "Argenteuil, 1875 — the high summer of the first Impressionist decade, painted for no commission. Camille was already unwell; she died four years later, at thirty-two. In 1886 Monet painted the composition twice more with his stepdaughter — deliberately faceless. Seen from there, this canvas becomes the memory before the loss: the one where the face, however loosely brushed, is still hers. It hangs in the National Gallery of Art in Washington — the DC Monet."
},

"leech-convent-garden": {
  see: "A young woman in white — lace dress, Breton coiffe — walks in profile through a garden where the lilies stand taller than she does. Sunlight detonates everywhere: the greens are acid and joyous, and the whites are never white — her dress runs lilac and cream, the lilies green-silver, and behind her, strung between the trees, hangs a third register of white: convent linen drying in the sun, with dark-habited figures moving beneath it. She reads from a small book and doesn't see us. Nothing in the garden is still, yet the picture is utterly quiet.",
  about: "A threshold, painted as a garden. She is a novice — the white dress is the bridal dress of taking vows — and the towering Madonna lilies, purity's oldest emblem, crowd around her like a congregation. The walled garden itself is the ancient symbol (the hortus conclusus, the enclosed garden of virginity), but Leech paints the theology as pure sensation: enclosure not as deprivation but as blazing, ordered peace. Whether that peace is hers or the painter's longing is the picture's open question.",
  craft: "The problem Leech sets himself is three whites in one sunstruck frame — dress, lilies, laundry — and he solves it with temperature: each white is built from different colours, so they separate without an outline anywhere. The lily stalks give the canvas its architecture, verticals rising like organ pipes against the diagonal of her walk. And the light is post-impressionist, not academic: flat confident dabs, shadow painted violet and green, closer to what he'd absorbed in France than anything in Irish painting before him.",
  context: "Concarneau, Brittany, around 1913. The model is Elizabeth, Leech's first wife — the same Elizabeth under the parasol in The Sunshade. Leech suffered recurring depressions, and the garden pictures radiate the calm he went to Brittany to find; this one hangs in the National Gallery of Ireland, where it holds a wall on its own. He remains in copyright until 2039 — one of the reasons the world knows him less than it should."
},

"the-milkmaid": {
  see: "A kitchen maid pours milk, and that thread of milk is the only thing moving in the room. Vermeer gives her the build of someone who actually works — solid forearms, sleeves pushed up — and the light from the leaded window does everything else: it finds the bread's crust in raised dots of paint, the brass, the blue apron, the seeds and pocks of the wall. Look at that wall: bare plaster, two nails, nail holes, a shadowed patch — a nothing surface painted with the attention other painters spent on faces. At the floor, a foot warmer and a strip of Delft tiles.",
  about: "The elevation of the completely ordinary. This is a servant doing the least glamorous task in the house, painted at the scale and with the gravity of an altarpiece — and utterly without irony or moral caption. The picture's claim is that attention is a form of reverence: pour milk carefully enough, paint pouring milk carefully enough, and the kitchen becomes sacred space. Three centuries before anyone said 'mindfulness,' this is what it looks like.",
  craft: "The color chord is one of the most famous in painting: lead-tin yellow bodice against lapis blue apron — Vermeer spent money on ultramarine the way rivals spent it on gold. The milk itself is the technical dare: white falling against shadow, painted so it reads as motion in a picture with no other movement. The bread is pointillé — actual raised dots of paint catching actual light. And the geometry is quietly perfect: her bowed head, the pour, the pot form a triangle the window light enters like a stage direction.",
  context: "Delft, around 1658, when Vermeer was in his mid-twenties; roughly 35 paintings by him exist, and the Netherlands regards this one as a national possession. It anchors the Rijksmuseum in Amsterdam — where it also anchors this site's first Rijksmuseum deep-zoom: their new open platform serves it in full-resolution tiles, so the bread's raised dots are actually visible. A pilgrimage piece — not yet seen in person."
}
};
