// art_artists.js — short artist reads, shown under the compressed header on #/artist/<id>.
// Written and QC'd per READS_SPEC.md §10: how the work is made → why it is made that way → a
// hook that reframes, with an optional collection tie-back only where the link is real.
//
// EVERY claim here went through the §10 fact-check loop (swarm → own pass → repeat until stable).
// That loop overturned four of its own corrections along the way, so if you edit a line, re-verify
// it — including any correction you are tempted to make from memory.
window.CANVAS_ARTISTS = {

"monet": "Painted the same haystack, façade and pond over and over because the subject was never the point; the envelope was, the air and light between eye and object. Worked fast and outdoors, and let broken colour do the mixing on your retina rather than on the palette. Cataracts took hold in his seventies and pushed his sight — and his canvases — towards yellow and brown; the 1923 operation stripped that filter away and the blues came flooding back.",

"turner": "Spent fifty years dissolving solid things into weather, until a critic could report his paintings dismissed as “pictures of nothing”. Ships, sun and storm all become the same suspended light. He left his finished paintings to the nation on condition a gallery be built to house them — a condition met only in 1987, which is why so many of yours are at Tate Britain.",

"rembrandt": "Painted his own face across forty years, in some forty pictures and thirty-odd etchings, as a working record of what age does to a head. Late on he laid paint thick enough to catch raking light, so the surface itself does the modelling. He was bankrupt by 1656 and painting better afterwards.",

"vermeer": "Left barely more than thirty paintings. Nearly all are one room, one window, light from the left, a woman absorbed in something small — and the stillness is engineered, not observed. The odd pinpoint highlights have convinced many that he worked with a camera obscura, though the question has never closed. He died in debt and was essentially forgotten for two centuries.",

"seurat": "Tried to put painting on a scientific footing: separate dots of unmixed colour left for the eye to combine, on the theory that optical mixing stays brighter than mixing on a palette. The theory was wrong — it borrows the physics of light for the physics of paint — and the paintings are extraordinary anyway. He died at thirty-one.",

"johan-christian-dahl": "Founded Norwegian landscape painting largely by refusing to idealise it, and painted skies from life as working studies — the same impulse that had Constable annotating clouds over Hampstead at the same moment. Eight of your fifteen are drawings rather than finished canvases.",

"sergel": "His public commissions are cool neoclassical marble; his private drawings are fast, frank and often erotic, made to be passed around among friends. The Passionate Couple is entirely that second Sergel — which is presumably why it is the one you live with.",

"knud-baade": "Painted almost nothing but moonlight: wrecks, cliffs and coastal night under a single cold silver source, over and over. He trained under Johan Christian Dahl in Dresden — so the two Norwegians in your collection are teacher and student.",

"van-gogh": "Painted fast and loaded, laying colour on in ropes and slabs so the brushstroke is the subject as much as the wheatfield is. He turned to it seriously only at twenty-seven and had about a decade in all. Wrote some 820 letters explaining exactly what he was trying to do, and almost everything you would recognise came out of the final two years.",

"renoir": "Trained as a porcelain painter, and it shows in the dissolved, flattering edges — flesh handled as light rather than anatomy. Alone among the Impressionists he kept faith with pleasure as a legitimate subject. Rheumatoid arthritis deformed his hands from around fifty and he painted on, the brush placed into them.",

"manet": "Painted with brutal tonal shorthand — mid-tones dropped, figures flattened against the ground like playing cards — which is why contemporaries thought he could not finish a picture. He never showed in any of the eight Impressionist exhibitions, despite inventing much of what they used.",

"cezanne": "Built form from patches of colour laid side by side rather than modelled with light and shade, so a mountain and a tablecloth get the same architectural treatment. After roughly 115 sittings for Vollard's portrait he declared himself “not altogether displeased with the shirt-front” and abandoned it. Painted Mont Sainte-Victoire more than eighty times, and everything Cubism did afterwards starts here.",

"courbet": "Insisted on painting only what he could see, at a scale previously reserved for gods and generals — a village funeral given a canvas ten feet high and twenty-two wide. Often worked with a palette knife, which gives the surface its trowelled, unglamorous grain. He was jailed after the Commune and died in exile in Switzerland.",

"pissarro": "The only painter to exhibit in all eight Impressionist shows, and the one the others went to for advice — Cézanne and Gauguin both learned from him. An anarchist by conviction who painted peasants working rather than posed, and who in his mid-fifties took up Seurat's dot method before abandoning it.",

"degas": "Called himself a realist, not an Impressionist, and almost never painted outdoors — the dancers are studio constructions, built from memory and repetition. Cropped figures at the frame like a snapshot decades before that was a visual language. He worked increasingly in pastel as his sight failed.",

"kandinsky": "Trained as a lawyer, turned to painting at thirty, then spent his life removing the subject from it — arguing that colour and line could work on you directly, the way music does, without depicting anything. He may have had synaesthesia; he certainly wrote as though hearing colour were ordinary.",

"klimt": "Gold leaf laid flat against faces painted with academic realism, so the ornament and the person sit in different worlds on the same panel. He took the gold from Byzantine mosaics he saw in Ravenna in 1903. His university ceiling paintings were attacked as pornographic; he bought them back and kept them, and they burned with Schloss Immendorf in 1945.",

"zorn": "Made his name in watercolour and spent his career chasing water and skin — reflected light on both. Famous for the Zorn palette: four pigments and no more. He portrayed three American presidents, painting Cleveland and Taft and etching Roosevelt, then went home to Mora and painted midsummer.",

"rodin": "Modelled surfaces deliberately rough so light breaks across them and the bronze never settles into stillness. The Age of Bronze was so convincing that he was accused of casting it from a live model, and had to be publicly defended. He worked in fragments — a hand, a torso — and treated the incomplete thing as finished, which is most of modern sculpture's inheritance.",

"matisse": "Chased colour released from description: a face can be green if the composition needs green. The critic who called the group fauves — wild beasts — meant it as an insult. After surgery for duodenal cancer in 1941 left him unable to stand at an easel, he cut painted paper with scissors instead and called it drawing with colour.",

"odilon-redon": "Spent two decades working almost entirely in black — charcoal and lithograph, floating eyes and spiders, which he called his noirs. Then at fifty he turned to pastel and oil and the palette went luminous. The pivot is one of the most complete in the period.",

"morisot": "Painted with an open, unfinished-looking touch, and a critic asked in 1880 why, with this talent, she would not “take the trouble to finish”. She showed in seven of the eight Impressionist exhibitions, missing only 1879, having just given birth. Barred as a bourgeois woman from the cafés where the movement argued itself into being, so the arguing happened in her drawing room instead.",

"mondrian": "Arrived at the grid slowly, through a dozen years of trees and piers reduced step by step until only vertical, horizontal and primaries remained. It was a spiritual programme, not a design one — he had joined the Theosophical Society in 1908 and believed those elements were universal. He broke with Theo van Doesburg over the use of diagonals.",

"giovanni-boldini": "Painted society portraits at a speed that looks like showing off, with long whipping brushstrokes that stretch a figure past anatomy into pure momentum. Silk in particular is done in strokes you can count. Enormously fashionable in Belle Époque Paris, and dismissed afterwards for exactly the qualities that made him fashionable.",

"constable": "Painted a small stretch of Suffolk over and over on the grounds that he knew it, and made full-size oil sketches before the final canvases, so the study is often livelier than the picture. Obsessed with weather; he annotated cloud studies with the date, time and wind direction. Sold better in France than at home.",

"stanis-aw-ignacy-witkiewicz": "Ran a portrait firm with a printed price list and formal types, some executed under alcohol or drugs with the substance noted on the work beside the signature. Mostly pastel, which suited the speed. A playwright and philosopher who treated painting as the commercial arm, and who took his own life the day after the Soviet invasion in September 1939.",

"jean-baptiste-camille-corot": "The hinge between classical landscape and Impressionism: silvery, tonal, painted outdoors when that was still unusual. Notoriously generous — he signed work by struggling friends so it would sell, which is a large part of why he is among the most forged painters in existence.",

"unknown": "Not an artist but a gap: works whose maker is unrecorded. Anonymity here usually means the object outlived its attribution — workshop pieces, antiquities, things catalogued by what they are rather than who made them.",

"vinci": "Painted very little and finished less, because a picture was a research problem and research does not conclude. Built form through sfumato — smoke — laying glazes so thin the transitions have no edge at all, which is why the Mona Lisa's expression will not hold still. He kept her for some sixteen years and was still adjusting her at the end.",

"rubens": "Ran a studio like a business, with specialists for animals, drapery and landscape, and priced canvases by how much of the surface was his own hand — he set it out in writing to a buyer in 1618. Painted flesh in transparent layers over a warm ground so bodies look lit from within. Also a working diplomat, knighted by both Spain and England, who helped negotiate peace between them.",

"hopper": "Built pictures out of raking light and empty architecture, then put one or two figures in them who are not talking. The mood is engineered by geometry rather than expression — you can cover the faces and lose nothing. His wife Josephine modelled every woman he painted after their marriage, and kept the ledgers that catalogue the work.",

"caillebotte": "Painted with a plunging, photographic perspective — wet boulevards seen from above, floor-scrapers foreshortened along the boards — which looked cold beside Renoir's warmth. Rich enough never to need sales, he bought his friends' work instead. France accepted forty of the sixty-seven he left it and refused the rest as filth; the forty are the core of the Musée d'Orsay.",

"signac": "Took Seurat's dot and enlarged it into a mosaic tile, so the later canvases read as bright blocks rather than stipple. A serious sailor who owned thirty-two boats over his life and painted harbours the way someone paints their own street. Kept Neo-Impressionism going for forty-four years after Seurat died at thirty-one.",

"marc": "Assigned colours fixed meanings — blue the male principle, spiritual and severe; yellow the female, gentle and sensual; red brute matter — and then painted animals, believing they saw the world more purely than people. Killed near Verdun in March 1916, aged thirty-six.",

"umberto-boccioni": "Tried to paint motion itself rather than a thing that moves, dissolving figures into force-lines so the crowd and the air it displaces become one event. The Futurists loved speed and machines; he died in 1916 when his horse bolted at a passing lorry during cavalry exercises and threw him.",

"sisley": "The most consistent of the Impressionists and the least varied — skies, water, snow, the same modest French villages, painted for forty years without a stylistic swerve. Born in Paris to English parents, he was ruined when the family silk business collapsed in 1870, and died poor four months before his prices multiplied at auction.",

"pierre-bonnard": "Painted from memory and small notes rather than the motif — he said the presence of the object was cramping — which is why interiors glow at temperatures no room actually holds. Marthe, his companion for nearly fifty years, appears in the bath again and again. He was known to slip into museums with a small brush and retouch his own hanging pictures while the guards moved on.",

"chaim-soutine": "Attacked the canvas — buildings lean, faces twist, everything is in a wind that is not there. Hauled a beef carcass up to his studio and painted it as it rotted, fetching buckets of blood from the slaughterhouse to keep the colour alive, until the neighbours complained and the police came.",

"lovis-corinth": "Painted with a heavy, confident naturalism until a stroke in 1911, after which the touch went loose and urgent — and the late work is what he is remembered for. Whether that change was the illness or a turn toward Expressionism he was already making is still argued.",

"matejko": "Painted enormous set-piece scenes from Polish history at a moment when Poland did not exist on any map, which makes the canvases arguments as much as pictures. Crowded, meticulously costumed, deliberately legible. He taught Wyspiański and Mehoffer, so a generation of Polish modernism came out of his classroom.",

"podkowinski": "Began as a competent Impressionist and then made one enormous symbolist scandal, Frenzy of Exultations — a naked woman on a black horse — which drew crowds until he took a knife to it himself at the exhibition in April 1894. He died the following January at twenty-eight, and the picture survives because it was repaired.",

"che-monski": "Painted the Polish countryside at eye level and full speed — horse teams coming straight at the viewer, mud, weather, no ennobling distance. Made his name in Paris selling exactly that, then returned in 1889 to a village outside Warsaw and farmed.",

"jan-ciaglinski": "A Warsaw-born painter who spent his career in St Petersburg and travelled compulsively — India, Egypt, Palestine, Spain, Morocco — painting small, fast, bright studies on the road rather than finished salon pictures. The looseness was deliberate, and closer to Impressionism than anything around him at the Academy.",

"boudin": "Painted beaches and skies outdoors decades before that was normal, and pushed the teenage Monet into doing the same. Monet was still saying it in old age: “I owe everything to Boudin.” Corot called him the king of skies, and two thirds of a typical Boudin is cloud.",

"charles-francois-daubigny": "Fitted out a studio boat, Le Botin, and painted rivers from the water, which is why the bank is so often at eye level and slightly too close. Attacked for exhibiting what critics called mere impressions, years before the word became a movement. As a Salon juror he pushed the young Impressionists through, and resigned in 1870 when Monet was rejected.",

"narcisse-virgilio-diaz": "A Barbizon painter of forest interiors, working in thick, jewel-dark paint with light breaking through the canopy in patches. He lost a leg in childhood and walked on a wooden one. He gave the young Renoir encouragement and free paint.",

"adolphe-joseph-thomas-monticelli": "Loaded paint so thickly that figures dissolve into encrusted colour, closer to enamel than to painting — dismissed in his lifetime as a decorative eccentric. Van Gogh saw the work in Paris, decided he was a serious ancestor, and wrote to Theo that he was continuing it as if he were Monticelli's son or brother.",

"edouard-vuillard": "Painted small domestic interiors in which pattern eats people — wallpaper, dress fabric and upholstery given the same weight as a face, so figures half-disappear into the room. A Nabi, working on cardboard in muffled distemper. He lived with his mother, who ran a corset and dressmaking business, until her death when he was sixty; her workroom is most of the subject.",

// ── batch 3, 2026-08-20 ─────────────────────────────────────────────────────────────────

"bruno-liljefors": "Paints the animal into its ground rather than in front of it — scaled to the landscape instead of posed for you, with predation treated as ordinary weather rather than as drama. He hunted, climbed to eagle and osprey nests and watched from camouflaged blinds, and he kept foxes, badgers, owls and an eagle in an enclosure at home so he could study them alive.",

"emile-bernard": "Worked out flat unmodulated colour inside dark contours — cloisonnism, named for the metal strips in cloisonné enamel — with Louis Anquetin around 1887, when he was nineteen. He then spent the rest of his life arguing that Gauguin had taken the credit for what the two of them built at Pont-Aven; left France in 1893, turned against modern art entirely, and went back to Renaissance models. Nine of your ten are after 1900, so what you have is almost all the reactionary Bernard rather than the nineteen-year-old.",

"maximilien-luce": "Took the neo-impressionist dot — the period's most advanced way of painting light — and pointed it at navvies, foundries and building sites instead of at bathers and harbours. He was an anarchist, arrested in July 1894 in the round-up after President Carnot's assassination and tried among the thirty; he was acquitted, after forty-eight days in Mazas.",

"ivan-shishkin": "Painted forest interiors at species-level exactness — you can name the tree — and was a serious etcher besides, so bark and needle come out drawn rather than suggested. He was a founding Wanderer, taking Russian painting out of the academy and around the provinces, and the forest was what he thought deserved that precision. The bear cubs in his most famous picture were painted by someone else.",

"henri-jean-guillaume-martin": "Uses the divided touch of neo-impressionism but stretches the dot into a long hatched filament, in a high, pale, chalky key. The method is optical and the subjects are symbolist — muses, allegories, figures in a light that belongs to no particular hour — which is the unusual pairing. The state kept handing him enormous mural commissions anyway: the Sorbonne, the Conseil d'État, the Capitole at Toulouse.",

"theo-van-rysselberghe": "Converted to strict pointillism the moment he saw Seurat's Grande Jatte, and is one of the very few who then took the dot into portraiture rather than landscape — he went on preferring faces to scenery for the rest of his life. He was standing in front of that painting in 1886 with the poet Émile Verhaeren; he then helped Octave Maus choose who Les XX showed in Brussels, and Seurat was there the following year.",

"menzel": "Drew compulsively: one of his overcoats had eight pockets, each holding a sketchbook of a different size, and the paintings are built out of that forensic looking rather than out of studio convention. He was an empiricist among history painters. For the rolling mill he went to an ironworks in Upper Silesia in 1872 and spent weeks making hundreds of studies on the factory floor.",

"millais": "Pre-Raphaelite method meant painting into a wet white ground with small brushes, so the colour stays jewelled and everything holds focus at once — foreground weed as sharp as a face. He then became a society portraitist and President of the Royal Academy, which the movement read as desertion, and your five straddle both halves. His Ophelia model lay in a bath warmed by lamps underneath; the lamps went out, she fell ill, and her father made him pay the doctor's bills.",

"tissot": "Renders contemporary dress with a fashion plate's precision and then leaves the story unresolved, so the whole reading hangs on a glance or a turned shoulder. Kathleen Newton, who had been living with him in London, died in 1882 and he was back in Paris within the week. His later career went into illustrating the Bible, with long research journeys to the Holy Land — two of your five come from that second life.",

"petrus-van-der-velden": "Loads paint heavily in the dark tonal key of the Hague School, so the weather is in the handling before it is in the subject. He emigrated to New Zealand in 1890 and reached the Otira Gorge that January; it became the thing he returned to. Your five straddle the crossing — Dutch canal on one side, Canterbury rock on the other.",

"henri-le-sidaner": "Paints the table laid and nobody at it, in twilight or lamplight, with a touch soft enough to hold everything just short of focus; the absence is the subject. He rented a house at Gerberoy in 1901 and bought it in 1904, then built the terraced gardens up around it. He went further than his own walls: he got the villagers planting roses too, and founded a rose festival there in 1928 that is still held every June.",

"henri-fantin-latour": "Ran two practices at once: flower pieces of almost photographic sobriety, and smoky, dissolving lithographs on Wagner, Berlioz and Schumann. The flowers sold in Britain and stayed practically unknown in France in his lifetime, so his English reputation and his French one are for different work entirely. Your Schumann overture is the ambition; the pansies are the income.",

"hodler": "Built pictures on what he called Parallelism — figures and forms repeated and mirrored across the canvas, symmetry used as structure rather than as ornament — and reduced the late landscapes to flat horizontal bands. He thought repetition was how nature reveals its order, and said so in a lecture in 1897. Your symmetrical reflection on Lake Thun is that theory stated about as plainly as he ever stated it.",

"arshile-gorky": "Floats improvised line over thin stained washes so the drawing sits on top of the colour instead of containing it — the hinge between Surrealist automatism and what American painting did next. He was born Vosdanig Adoian and got out of the Armenian genocide as a child; his mother died of starvation in 1919. The name is invented, and he let people believe he was related to Maxim Gorky.",

"ivan-aivazovsky": "Painted the sea in the studio from memory, fast, glazing thin translucent layers so a wave crest reads as lit from behind rather than on its surface. He held that a storm cannot be painted in front of you, only recalled. He was official painter to the Russian Navy from 1844, and left something like six thousand works.",

"albert-lebourg": "Works light and rapid in a silvery tonal register on the Seine and the Rouen quays — an impressionist who stayed with atmosphere rather than crossing over into pure colour. He spent five years from 1872 teaching drawing in Algiers, and showed in the fourth and fifth Impressionist exhibitions, in 1879 and 1880. A stroke in September 1920 paralysed his left side, and he went on painting anyway.",

"george-frederic-watts": "Works dry, muted earth colour over a canvas he keeps returning to for years, so the surface reads as fresco or as memory rather than as paint. The symbolic pictures were meant to belong to one connected scheme he called the House of Life, in which every aspiration would get its symbol. He refused a baronetcy twice, and gave the major symbolic works to the nation rather than selling them.",

"cole": "Worked large studio canvases up from studies made on the spot in the Catskills, and founded the Hudson River School doing it. The serial pictures are moral arguments — empire, decline, the course of a life — landscape recruited to sermon. His patron died before the first Voyage of Life cycle was done and the heirs would not cooperate, so he painted all four again in Rome; the 1842 set is that second one, and it is the one you have.",

"makart": "Worked enormous, in deep bituminous reds and browns, staging figures as theatre — and the pigments were unstable, so much of it has darkened and cracked since. He was the impresario of Ringstrasse Vienna, where painting, costume and interior decoration arrived as one commission. He designed the 1879 imperial pageant, some fourteen thousand people, and rode at the head of it dressed as Rubens.",

"johan-jongkind": "Made the watercolours outdoors on the spot and built the oils up from them in the studio, keeping a broken, nervous touch that holds the weather of a particular hour. Monet met him at Le Havre in 1862 and said later that it was to him he owed the definitive education of his eye.",

// ── batch 4, 2026-08-20 ─────────────────────────────────────────────────────────────────

"eugene-jansson": "Painted Stockholm at night in almost nothing but blue: long swirling strokes, gaslight lying on the water, the city seen downhill from the Södermalm heights where he lived his whole life. In 1904 he stopped almost dead and gave the rest of his career to male nudes — bathers, sailors, the naval bathhouse. All three of yours sit on the blue side of that break.",

"jozef-pankiewicz": "Started as one of the first Polish impressionists, went through symbolist nocturnes in the 1890s, and came out the other side a colourist working in France, where Bonnard was a friend. He then led the students who formed the Paris Committee — the Kapiści — and took them to France with him, which is how French colour reached Polish painting wholesale. Your three land in three different decades, one from each of those lives.",

"georges-lemmen": "Took up Seurat's dot as a member of Les XX from 1888 and used it hardest in the early 1890s, on the Belgian coast. He later left it behind for intimist interiors and portraits much closer to Bonnard and Vuillard. He was a graphic designer as well — book covers, posters, and a typeface cut with Harry Kessler. All three of yours are 1891, the pointillist peak.",

"henry-brokmann": "Oil on canvas in wide horizontal formats, with haze built as close-toned graduated passages rather than by contrast. A Dane who trained in Copenhagen, reached the Académie Julian in 1886 and came out committed to a systematic study of light, which he then chased across Egypt, Syria, Brittany, the Italian lakes and Menton. Almost none of it was collected while he lived: his entire public presence dates from 1979, when his son gave fifty-one paintings and twenty-seven drawings to the Petit Palais, forty-six years after he died.",

"theo-van-doesburg": "Founded De Stijl, and was not born to the name — he was Christian Emil Marie Küpper. He ran a second identity alongside it: I. K. Bonset, who published Dada poetry in De Stijl while van Doesburg edited the magazine. In 1925 he brought in the diagonal, and it ended his friendship with Mondrian for good. Your three are 1904 and 1905 — night landscapes and a portrait, a decade before any of that, the painter before he had invented himself.",

"strindberg": "The playwright painted in thick impasto pushed about with a palette knife, in bursts, outside any exhibiting career. In 1894 he published an essay arguing for the role of chance in making art, and worked that way: letting the accident produce the image and finding the subject in it afterwards. That is automatism, proposed some thirty years before the Surrealists made a programme of it.",

"fjaestad": "Builds snow and hoar frost out of small contrasting touches worked into rhythmic, almost decorative surfaces, so a frozen river reads as pattern before it reads as place. He helped found the Rackstad colony near Arvika, an arts-and-crafts community, and designed furniture and weaving patterns alongside the painting. Bruno Liljefors hired him in 1893 as an assistant on the landscape panorama for the Biological Museum in Stockholm.",

"bouguereau": "Blends every transition out until the brushwork disappears and the surface reads as porcelain — the finish the Salon existed to reward, defended by the man who had most mastered it, and who worked to keep the Impressionists out of it. His reputation then collapsed so thoroughly after his death that the name became shorthand for kitsch and he was barely hung for most of the twentieth century, before a late rehabilitation. He also spent years pushing to get women admitted to art training.",

"hokusai": "Not a painting: a woodblock print, and the work of three pairs of hands — designer, block-cutter, printer — in a Prussian blue that had only lately become available as an import. It was one sheet of a commercial series aimed at a mass market. He used more than thirty artistic names across his life, and wrote at seventy-five that nothing he had made before seventy was worth counting.",

"henry-fuseli": "Foreshortens violently, pushes musculature past anatomy, and lights figures from below out of the surrounding dark. He painted Shakespeare, Milton and nightmares — literature rather than anything in front of him. He had been ordained a Zwinglian minister before he ever took up painting, and ended as Professor of Painting and Keeper at the Royal Academy.",

"witold-wojtkiewicz": "Mixes oil with tempera for a deliberately matte, chalky surface, and paints circuses, dolls, marionettes and children acting out adult griefs. André Gide saw the work in Berlin in 1906, arranged him a one-man show at Galerie Druet in Paris the next year and wrote the catalogue introduction. He had a congenital heart defect and was dead at twenty-nine, two years after that show.",

"thomas-alexander-harrison": "Works enormous and horizontal, in tonal fields with almost no incident — a strip of water and one gradient of light — and though he was known for painting outdoors, the big canvases were built in the studio from rapid sketches, because a moonrise will not hold still for a session. He came to it late: about five years as a draughtsman for the US Coast Survey, mapping shorelines, before he painted anything. Cecilia Beaux, who knew him, said his method had the quality of science, perhaps because he had been trained as an engineer.",

"alphonse-osbert": "Works in near-monochrome blue, with motionless hieratic figures set in twilight landscape and composed flat, like a frieze. The manner comes from Puvis de Chavannes and the intent from Symbolism — a picture meant to induce a state rather than report an event. He showed at the Salon de la Rose+Croix.",

"julian-ashton": "Watercolour with opaque white worked over the washes for the highlights rather than reserving bare paper, handled loose and fast on the spot. He had trained at the Académie Julian and brought the Barbizon habit of working outdoors to Sydney. He was a trustee of the Art Gallery of New South Wales for some fifty years and used it — the Streeton he bought for seventy pounds in 1890 was the first in any public collection — and the school he founded is the oldest still running in Australia.",

"michael-wutky": "Paints the eruption at night so the lava is the only light source, the ground kept dark, with tiny figures at the edge for scale. The pictures come out of studies made at the rim rather than out of studio invention, and were long held to be the most accurate images of an eruption anyone had before photography. He climbed to the crater during the great eruption of 1779 in the company of Sir William Hamilton, the British envoy who went up Vesuvius more than sixty times and published what he saw for the Royal Society.",

"teodor-axentowicz": "Worked mostly in pastel, and got melancholy out of a medium usually asked for charm — a society portraitist trained in Munich and then in Paris under Carolus-Duran. He gave the other half of his life to the Hutsuls of the Carpathians, painting their dances and rites with exactly the seriousness he gave his Parisian sitters. He founded an art school for women in Kraków in 1897 and became the Academy's rector in 1910.",

"hiromitsu-nakazawa": "Oil on canvas in the manner Kuroda Seiki brought back from Raphaël Collin's Paris studio: violet in the shadows in place of the browns the older Japanese school of Western-style painting used, and the figure set in a soft, light-filled atmosphere. He was a founding member of the Hakubakai, the society formed to push that lighter French palette — and the nude was still contested in Japan, Kuroda's own having drawn a police order a decade before. He was at the same time one of Meiji Japan's leading magazine illustrators, and was made an Imperial Household Artist in 1944.",

"pierre-isidore-bureau": "Nocturnes on the Oise in a near-monochrome range — dark ground, silvery reflected light, closer to seventeenth-century Dutch tonal painting than to broken colour. He was a pupil of Jules Dupré, and applied Barbizon's habit of direct observation to the one thing Barbizon rarely painted, which was night. He showed four pictures in the first Impressionist exhibition of 1874, one of them a moonlight on the banks of the Oise at L'Isle-Adam; and when the Société Anonyme that ran it was wound up he was one of the three artists, with Renoir and Sisley, who liquidated it.",

"valentin-serov": "Made sitters come back dozens of times, so a portrait that looks caught in one glance is in fact heavily built. He trained under Repin and then at the Academy, and wanted the freshness of a study to survive the labour of a finished picture. He watched the Bloody Sunday shootings of 1905 from the Academy's own windows, and resigned his membership over it.",

"ludwik-de-laveaux": "Painted Paris at night in a dark tonal key learned first in Kraków and then in Munich under Otto Seitz. He died of tuberculosis in Paris in 1894, aged twenty-five and poor. Wyspiański, who had studied alongside him, put him into Wesele as the Widmo — the ghost who comes back for Marysia, the girl from Bronowice he had really been engaged to before he left.",

// ── batch 5, 2026-08-20 ─────────────────────────────────────────────────────────────────

"albert-chmielowski": "Trained as a painter in Munich, and good enough that the work still hangs. He had fought in the January Uprising at eighteen and lost a leg to it; in his forties he moved into the Kraków homeless shelters, took the name Brother Albert and founded an order to run them. John Paul II canonised him in 1989. The break was not clean: your one picture is dated 1888, the year he took his final vows.",

"kawabata-ryushi": "Painted nihonga at deliberately enormous scale, made for exhibition halls rather than for the alcove a scroll hangs in, and founded his own society, Seiryūsha, so there would be somewhere to show that way. The burning Golden Pavilion is not history painting: a novice at the temple set it alight in July 1950, and he had it on the wall of his own exhibition two months later.",

"nils-kreuger": "Flattened Swedish landscape into broad simplified shapes under Gauguin's influence, with a preference for dawn or dusk, haze or rain — the conditions that do the flattening for you. He was one of the three of the Varberg School, with Richard Bergh and Karl Nordström, who turned that manner into a national-romantic language for Sweden.",

"victor-muller": "Took Courbet's method whole — heavy direct paint off the knife and brush, the reverse of the glazing Couture had taught him — and brought it back to Frankfurt to use on German fairy tales. Courbet spent six months in Frankfurt in 1858 working alongside him. In Munich he gathered the younger painters, Leibl and Thoma among them, out of whom the Leibl circle came; he died at forty-one, before it had properly formed.",

"charles-angrand": "A founding member of the Indépendants alongside Seurat and Signac, and a neo-impressionist painter who then, from the early 1890s, all but stopped painting and worked in Conté crayon instead. By varying the pressure so the paper's tooth takes more or less of the greasy black, he built darks that still hold light inside them. Signac called the drawings masterpieces.",

"gustaf-ankarcrona": "Trained in Berlin and painted rural Dalarna in a precise tonal naturalism — but the pictures are the smaller half of what he was doing there. In 1904 he started the first rural handicraft association in Sweden, at Leksand; in 1908 he bought land at Tällberg and had old timber buildings taken down in the countryside and rebuilt around his studio as an open-air museum. He commissioned the women who still knew the old patterns to weave, so the craft would survive as practice rather than as exhibits.",

"eugene-carriere": "Works in a near-monochrome brown with the edges dissolved, figures surfacing out of fog as though the picture were developing rather than being painted. He was a close friend of Rodin, and the same instinct for the unfinished form runs through both. His first large public commission was the decoration of the Hôtel de Ville in Paris in 1889 — which is what yours is a study for.",

"antoine-chintreuil": "Painted outdoors at first light and at dusk, after atmospheric effects that hold for minutes, and did it so persistently that his doctors blamed the practice for the lung disease that killed him. Corot took him on around 1843 and eventually told him he had learned what he could be taught. He was one of the organisers of the 1863 Salon des Refusés — not simply a painter in it, but on the committee that made it exist.",

"paul-steck": "Trained under Gérôme, so the drawing is academic and the surface polished, then turned that training on Symbolist subjects — literary, languid, mood standing in for narrative. He showed at the Salon de la Rose+Croix in 1896. He was also a composer and librettist, and ended up deputy director of the school of decorative arts in Paris.",

"john-martin": "Painted catastrophe at spectacle scale, with tiny figures set against architecture and light. His real audience came through mezzotint, which he engraved himself and which earned him considerably more than the paintings did. His older brother Jonathan set fire to York Minster in 1829 and was confined to an asylum for it.",

"francesc-pausas-i-coll": "A Catalan portraitist trained in Barcelona and then in Madrid under Sorolla, copying in the Prado — drawing built to catch a sitter's gesture directly rather than to flatter it. He moved to New York in 1906 and stayed twenty-three years, painting opera singers and society. He had no heirs and the work scattered: only a handful of his pictures are in public collections anywhere, and the portrait of his wife is in one because she gave it herself after he died.",

"hendrick-van-balen-the-elder": "Small cabinet pictures, often on copper rather than panel, with the figures his own and the landscape, flowers and still life somebody else's — he collaborated constantly, most of all with Jan Brueghel the Elder, who took the setting while van Balen took the gods. Antwerp ran painting as an industry of specialists, and he was a dean of its guild. He taught van Dyck, who painted his old master's portrait more than once, decades later.",

"mikhail-matyushin": "Played violin in the imperial court orchestra in St Petersburg for over thirty years while becoming a painter, and wrote the score for the futurist opera Victory over the Sun in 1913. He then built a theory of seeing he called Zorved — see-know — which held that sight reaches past the field in front of you, out to the sides and behind, and he painted to test it.",

"stanis-aw-witkiewicz": "A painter and critic who ended up inventing a building style: he took Podhale highlander carpentry and worked it into the Zakopane Style, a complete architectural and decorative idiom he argued should be Poland's national manner. He was Witkacy's father — so the two Witkiewiczes in your collection are parent and child.",

"lesser-ury": "Painted Berlin after dark — wet asphalt taking electric light and throwing it back up, figures cut down to silhouettes under umbrellas. Max Liebermann kept him out of the Berlin Secession for as long as he ran it. Ury got in only in 1911, once Liebermann had resigned and Corinth taken over.",

"clarice-beckett": "Painted the Beaumaris foreshore at dawn and dusk in Meldrum's tonal method, wheeling her easel and paints out to the spot in a cart built for the purpose. She caught pneumonia painting through a winter storm and died in 1935. The work was left stacked in an open-sided shed for decades, where rain and possums destroyed some 1,600 of them; 369 were still salvageable when Rosalind Hollinrake reached them in 1971.",

"munch": "Left canvases outside in sun and rain on purpose — he called it the horse cure — so the surfaces come scoured and thin by design rather than by neglect. He said he painted not what he saw but what he had seen, which is why the pictures are shaped like memory rather than observation. He left 1,158 paintings to the city of Oslo in his will.",

"gauguin": "Flat unmodelled colour inside dark contours, often on coarse sacking instead of proper canvas because he wanted the tooth, and worked from memory rather than in front of the motif. He was a stockbroker who painted on Sundays until he was thirty-four, and then was not. Your earliest is from 1875, when he still had the job.",

"whistler": "Thinned paint to a wash he called the sauce and let it run, then titled the results nocturnes, symphonies and harmonies to force you to read them as arrangements of tone rather than as views of things. Ruskin wrote that he had flung a pot of paint in the public's face; Whistler sued for libel and won a farthing. He was bankrupt within a year.",

"marquet": "Gets a view down to a few flat tones and one economical silhouette, and leaves the drawing to do the rest. He was in the room when Fauvism got its name — a student with Matisse under Gustave Moreau, and in the 1905 Salon d'Automne that produced the label — but kept the restraint the others were throwing out. He painted the Seine from the windows of one apartment after another for decades; five of your six are that river.",


"leech": "Laid the paint thick and let unmixed patches sit side by side, cadmium yellow against viridian, so sunlight reads as a substance on the surface rather than an illusion behind it. Fourteen years on the Breton coast trained that eye for where colour shifts fastest, in the shadow a bright thing throws onto skin. The walled garden he painted in 1913 belonged to the convent where he had convalesced from typhoid nine years earlier.",
"claudel": "Modelled in clay and then cut the marble herself, at a time when most sculptors handed that stage to a paid carver, so the final surface is hers and not a technician's reading of it. The difference shows in how the stone is finished around a joint. Her mother and brother had her committed in March 1913; she stayed confined for thirty years and died there in 1943.",
"greco": "Stretched his figures past human proportion deliberately: underdrawings show the bodies starting at normal scale and being pulled long in the final layers. The elongation came out of Byzantine icon practice, where leaving the natural behind was how a figure registered as holy. About fifty wax and clay models were listed in the inventory taken at his death, posed and worked from.",
"guardi": "Flicked the brush rather than drew it: figures built from a few dabs, water and sky dissolved into nervous marks that only resolve into weather at a distance. Where Canaletto sold Venice as accurate topography, this is Venice as light. His brother was a founding member of the Venetian Academy in 1756; he was not elected until 1784, at seventy-one, and died poor.",
"goya": "Finished the head and dispatched everything else: a sitter's face worked up carefully while lace, braid and satin go in with a few loaded strokes that only cohere at a distance. Court portraiture paid, and speed was the point. The prints he made alongside it went unseen, the war series staying unpublished until 1863, thirty-five years after his death.",
"pekka-halonen": "Stood out in sub-zero air to get the shadows right: on snow they fall blue and violet, never grey, and the colour only holds if you are looking at the real angle of winter light. Studio memory flattens it. He learned in Paris under Gauguin, the winter Gauguin came back from Tahiti, then took that licence with colour home and spent it almost entirely on snow.",
"gainsborough": "Kept brushes as long as six feet, by the account of men who knew him, and stood back the same distance he stood from the sitter, so marks that look like loose feathering up close settle into a face at conversational range. Portraits were the paying work; he wrote plainly that he was sick of them and wanted to walk off and paint landscape instead, which is the other half of what you hold.",
"titian": "Turned canvases to the wall for months at a stretch, then came back and finished them with fingers as much as brushes, pressing pigment about until the flesh stopped looking painted. A pupil who watched him work left the description. Three of yours were made after he settled into that method, and the portrait from around 1510 shows what it replaced.",
"roberts": "Set a canvas up inside an empty shearing shed and paid children sixpence to kick dust into the air, so the light coming through it could be studied rather than invented. Seventy-odd sketches made on the station fed the same picture. A decade later he spent two and a half years on one commissioned canvas holding two hundred and sixty-nine portraits, sitting his subjects in Melbourne, Sydney and London.",
"durer": "Cut every line with a burin into copper, each mark a furrow holding ink, then printed, so one plate yields hundreds of impressions that are all equally the work. That is why you can meet the same image in more than one museum and why none of them is the original. The rhinoceros he drew without ever seeing one, from a written description, and it stayed Europe's standard picture of the animal into the late eighteenth century.",
"friedrich": "Recorded shore and sky in pencil on the spot, then rebuilt them in the studio from memory in thin glazes, each layer left to dry before the next. Fog and last light cannot be painted in front of the thing; they exist only as something held. His reputation was already going when he died in 1840 and did not properly return until a Berlin exhibition in 1906 put thirty-six of his paintings back in one room.",
"schiele": "Drew the contour first, in pencil or black chalk and in one pass, then dropped watercolour and gouache inside it and left bare paper to do the work shading usually does. A line put down that way cannot be corrected, only abandoned. He was jailed in 1912 not for seducing a minor, a charge that collapsed, but for leaving an erotic drawing where children could see it; he died of influenza in 1918, three days after his wife.",
"eugene-delacroix": "Placed complementary colours side by side and built shadow from crosshatched strokes instead of dark paint, so the mixing happens in the eye and the surface never deadens. The journals he kept argue it explicitly: a colour is made by its neighbour. The landscapes and marines were largely private work, made around his country house and rarely exhibited, the part of him the public did not get.",
"henri-edmond-cross": "Enlarged the neo-impressionist dot into a broad squared-off tile and left raw canvas showing between the tiles, which pushes colour far harder than tight optical mixing allows. Chronic rheumatism had driven him permanently south in 1891, and the work got hotter as the joints got worse. He had changed his surname a decade before that: born Delacroix, he took Cross so as not to be confused with the other one.",
"millet": "Planted figures low against an open horizon and built them heavy, so bodies read as weight rather than grace, at a scale the period reserved for saints and generals. Giving that format to women stooping in a stubble field was the argument. Thirty years on, the state failed to buy the evening prayer picture at auction; it went to America for 553,000 francs, and a French collector bought it back a year later for 750,000.",
"lawrence-alma-tadema": "Assembled some five thousand three hundred photographs of Roman sites and objects, so no step, couch or floor tile in these scenes was guessed at. The marble is the reason people looked: glazed for translucency rather than painted opaque, after a teacher told him his stone looked like cheese. His reputation collapsed at his death and only came back in the 1960s and 70s, which means these were near-worthless for half a century.",
"max-beckmann": "Ringed every form in heavy black, the way lead holds glass, so a crowded space stays legible no matter how much is packed into it. He gave a lecture in London in 1938 setting out why. The Nazis had already removed him from his Frankfurt teaching post in 1933; he heard Hitler denounce modern art on the radio in July 1937 and left for Amsterdam the next morning, staying ten years.",
"max-liebermann": "Started in heavy tonal masses and thick impasto, figures sunk in interior shadow in the Hague School manner, and only opened the palette once a garden at Wannsee became the subject after 1909. He painted that garden season after season for the rest of his life, the touch loosening as the colour brightened. His wife took an overdose of sleeping pills in March 1943 rather than board the transport to Theresienstadt.",
"raoul-dufy": "Let the colour slide off the drawing: washes laid across a scene with no attempt to keep them inside the contour, so the two layers sit slightly out of register and the whole thing stays lit. He settled on it deliberately around 1926. Rheumatoid arthritis deformed his hands from 1935; he went to Boston in 1950 for the early cortisone trials and got enough movement back to keep working.",
"blake": "Reversed the usual process: wrote and drew straight onto copper with an acid-resistant varnish and let the acid eat the blank areas away, so the lines stood up and printed like type. It meant no engraver, no printer and no publisher stood between him and the page. The 1795 colour prints came another way again, pigment pressed off a board while still wet then finished by hand, so no two pulls match.",

"winslow-homer": "Lifted as much colour off the paper as he put on it, scraping, blotting and sanding washes back to bare white so the sheet itself does the light. Watercolour let him work at the speed the weather changed. He came to it at thirty-seven, after two decades supplying wood engravings to a weekly paper, and returned to one Adirondack club twenty-one times across forty years.",
"gierymski": "Repainted each canvas until the built-up layers formed ridges and peaks across the surface; one in your collection took five years. He was chasing a single condition of light, the way filtered sun sits on fabric, skin, a basket of oranges at a market stall. That orange-seller was stolen from Warsaw in 1944, surfaced at a sale in northern Germany in 2010, and was bought back.",
"andre-derain": "Abandoned colour-as-sensation around 1908 and spent the rest of his life pulling toward quieter sources — Cézanne's architecture, Italian primitives, African carving — until the palette settled into ochres and the handling went cool and deliberate. Mobilised in 1914, he was kept in uniform until 1919. In 1941 he accepted a Nazi-organised trip to Berlin; a postwar committee cleared him, but a professional ban followed and the damage held.",
"arnold-bocklin": "Mixed tempera and oil in the same layered surface, not as experiment but as method, hunting a matte density that pure oil would not give. Conservators have found the bond between those media unstable, and the surfaces have shifted accordingly. He said of his most famous painting, whose counterpart you own, that it should produce such stillness that a knock at the door would startle you.",
"caravaggio": "Scored incisions directly into the wet ground, an awl fixing key positions, no preparatory drawings made, then built the image from posed live models against a dark surface with a single hard light. Sentenced to beheading in absentia after killing a man in a 1606 duel, he died at Porto Ercole; the cause remains disputed. Art history lost him for three centuries until Roberto Longhi's 1951 Milan exhibition.",
"conder": "Spread watercolour and bodycolour across folded silk, the fan shape dictating where figures crowd at the edges and dissolve at the spine. The constraint was the point: a masquerade that closes into a handheld object refuses to be read as a painting. He designed the 1889 exhibition catalogue at twenty, left Australia the following year, and died of syphilis at forty.",
"christian-rohlfs": "Scrubbed water tempera onto handmade paper in repeated layers, then washed and brushed the paint back to build a luminous, almost textile surface. The method came late: he was painting academic landscape into his fifties before Nolde and Van Gogh pushed him into Expressionism, thirty years older than the Brücke founders when he made the turn. In 1937 the Nazis pulled 412 of his works from German museums; he died the following January.",
"fernand-leger": "Reduced bodies to cylinders and tubes, volumes so mechanical that critics coined Tubism for it, then pushed on into flat primaries and thick black contours closer to industrial signage than to Cubism. Gassed at Verdun in 1916 and sent to convalesce, he painted the card game there, the soldiers turned into armoured machines. He had written that a gun breech catching sunlight taught him more than any museum.",
"fritz-von-uhde": "Stripped Christ of gilding and halo and put him in German peasant kitchens under north light falling on rough linen; the aim was to make the sacred legible without ceremony. Catholic critics called it a destruction of sacred aura. He had served eleven years as a cavalry officer before turning to painting, and the battle canvases date from those years. The palette only lightened after an 1882 trip to the Netherlands.",
"tiepolo": "Sketched the composition first at small scale in oil, not as a study but as a formal proposal, shown to the patron for approval before a single brushstroke of plaster was touched. The finished fresco stayed on the ceiling; the modello travelled, survived, and is what you can stand close to. He died in Madrid, his late work already being replaced on the palace walls, and spent much of the next century out of fashion.",
"toulouse-lautrec": "Soaked the oil out of paint with turpentine before it touched the board, so colour dried flat and chalky with bare cardboard showing through wherever he left it. The lean paint let him work as fast as a draughtsman. The pastel in your collection is among the handful he ever made; the two men met most evenings at a Montmartre café while training under the same teacher, and almost nothing that close between them survives.",
"rousseau": "Retired from the Paris toll office at forty-nine and built each jungle canvas by stacking dozens of distinct greens in successive passes, not blending, so the foliage reads dense as something grown rather than imagined. Every leaf and animal pose came from the greenhouses and stuffed-animal dioramas at the Jardin des Plantes; he never left France. The tiger drew ridicule in 1891; Picasso threw him a banquet in 1908, the year of the footballers you hold, and the rehabilitation stuck.",
"malczewski": "Dropped fauns, chimeras and a Thanatos into documented Polish farmland and painted them sharing space with living peasants as though physically present, collapsing allegory into observed fact rather than separating the two. The portrait of Aleksander Wielopolski, grandson of the politician who worked with Russia, flanks him with two women: chained old Poland and a young figure breaking free. It was painted in 1903, when Poland had no state and Warsaw answered to the Tsar.",
"ruisdael": "Filled the upper two-thirds of each canvas with sky, not as backdrop but as the primary subject, bearing down on whatever mill or ruin sits below. The land existed to give the weather something to press against. He painted Castle Bentheim roughly fourteen times, each version raising the sandstone hill steeper than it stands, so the fortress towers over you rather than merely sitting on its rise.",
"david": "Suppressed every brushstroke until the surface reads like enamel, and drew his figures nude from posed models before clothing them, so the anatomy stays exact under the fabric. The finish was the argument: no ornament, antique moral severity. The study portrait is engineered down to the clock reading past four in the morning and the candles burnt to stubs. Napoleon never sat for it.",
"jean-baptiste-carpeaux": "Pressed and gouged the clay fast, leaving thumb-marks and tool-drag legible in the finished bronze, a roughness that catches raking light where polished Neoclassical marble throws it back flat. Feeling was to come off the surface itself. The starving children in his Ugolino group, taken from Dante's thirty-third canto, offer themselves to their father to be eaten; the director of the Académie in Rome, who was funding him, at first refused to let him make it.",
"joaquin-sorolla": "Anchored huge canvases in the sand with guy-ropes and worked in full midday glare, so the light coming off water and wet skin could be taken at the hour it actually looked like that. Grains of sand are still set into the surfaces. The commission that filled his last working years ran to fourteen panels and nearly two hundred feet; a stroke in 1920 stopped him painting, and he lived three more years.",
"maxime-maufra": "Carried his easel to the Breton coast and painted directly in front of the sea, returning to the same wild creeks and cliff-faces years apart and working each light as he found it. He knew Gauguin at Pont-Aven, heard the arguments for Synthetism, and refused all of it: no doctrine, no school. He had been sent to Liverpool in 1881 to sharpen his business instincts, and the Turners in the city's galleries ended that plan.",
"elder": "Brushed the paint thin enough that the pale chalk ground shows through and lights the colour from beneath. Underdrawing carried the early panels; he dropped it as the direct handling grew surer. Five survive of a cycle of six months painted for one Antwerp merchant. He was educated and city-dwelling rather than the peasant his subjects suggest, and dropped the h from his name in 1559; his sons put it back and spent their careers copying him.",
"santiago-rusinol-i-prats": "Emptied the gardens of every figure — paths, clipped hedges, still water and nobody in them — so abandonment could carry the picture without a story attached. From a Catalan textile family, he bought a fisherman's house in Sitges, filled it with wrought iron and two El Grecos, and ran the Festes Modernistes there through the 1890s. He died at Aranjuez, the royal gardens he came back to more than anywhere else.",
"vilhelm-hammersh-i": "Held to a narrow band of greys and washed ochres, laying dryish paint down layer over layer until every tone in a room settled into one sustained note. Ida, his wife and near-constant model, is almost always turned away, absorbed in something you are not shown. He was largely forgotten outside Denmark for most of a century; the retrospectives that brought him back came only in the late 1990s.",
"velazquez": "Loosened the marks across the career: early work is tightly observed, but the late portraits are built to be read from across a room, disconnected dabs up close that resolve into presence only when you step back. Palomino, writing within living memory of the studio, put it as incomprehensible near to and a miracle at distance. The man in the 1650 portrait was his enslaved assistant, freed by signed document the same year the sitting happened.",
"streeton": "Sat out in the cutting itself in over forty degrees and put each stroke down once, without reworking into wet paint, because at that heat the light will not hold still long enough for second thoughts. The certainty in the surface is the certainty of having been there. The vertical railway picture records a death: he was on the site when a blast in the tunnel killed one of the gang, and the warning shout the workers used gave the painting its title.",
"canal": "Followed his patrons to London in 1746, after war cut off British travel to Venice and with it his income, and stayed nearly nine years. A camera obscura bearing his name survives, but he used it as a starting point and then altered what it projected; the precision was chosen, not mechanical. Grand Tourists wanted a verifiable record of what they had seen, and his dealer Joseph Smith spent four decades connecting him to exactly that demand.",
"murillo": "Earned the word vaporoso from contemporaries, vapourous, for the softened dissolved contours that separated his mature manner from the harder Sevillian realism he trained in. A devotional picture was meant to move you rather than impress you, and edges that melt do that work. His beggar-child scenes look like a secular departure but were bought almost entirely by Flemish and Dutch merchants in Seville, for whom that was a familiar northern genre.",
"landseer": "Dissected animals to get the musculature right, and the anatomy is not what anyone disputes. What it was put to is: the creatures grieve, mourn and stay loyal in ways no animal manages, which made him the most popular painter in Victorian Britain and later the most embarrassing. His picture of two polar bears working over the wreckage of the Franklin expedition is covered with a Union Jack during exams, because students believe it drives you mad.",
"ernst-ludwig-kirchner": "Enrolled in architecture rather than art, and so did the three friends he founded Die Brücke with in 1905; none of the four had formal fine-arts training. The street pictures work by compression, figures jammed into shallow space and colour pitched against expectation, so the city reads as pressure rather than scenery. In 1937 the Nazi authorities removed 639 of his works from German museums. He shot himself the following year.",
"amedeo-modigliani": "Carved limestone heads in Paris for around five years, then stopped and never went back to stone. The long necks and blank almond eyes he had cut into them transferred straight into the paintings — the sources were African masks and Cycladic figures, and he did not soften them on the way. He died of tubercular meningitis in January 1920; two days later Jeanne Hébuterne, eight months pregnant, threw herself from a fifth-floor window.",
"august-macke": "Travelled to Tunisia in April 1914 with Paul Klee and Louis Moilliet, spending two weeks working in watercolour across Tunis, Hammamet and Kairouan. Where Kandinsky and the other Blaue Reiter painters loaded colour with spiritual theory, he kept it closer to sensation, the pleasure of light and of human presence on a street. He was killed in action in Champagne on 26 September 1914, aged twenty-seven, weeks after coming home.",
"alexej-von-jawlensky": "Distilled a face down to its barest schema — eyes, a nose, a cross of lines — then repeated that schema across four successive series over twenty years. The intent was devotional, each one conceived as a window onto the divine in the tradition of the Russian Orthodox icons he grew up among. Arthritis took his hands from 1929, and for the last of the series, which run into the hundreds, the brush was tied to his fist.",
"frantisek-kupka": "Supported himself from fifteen as a medium at séances in Prague and Vienna, and kept the spiritualist frame long afterwards, describing painting as a way of showing forces that have no visible form. Two fully non-objective canvases went up at the 1912 Salon d'Automne to general consternation; they are among the earliest purely abstract works ever publicly shown. The series that got him there began as drawings of his stepdaughter playing with a ball.",
"theodore-rousseau": "Rejected by the Salon every year from 1836 to 1841 and nicknamed le grand refusé, he spent those years returning to the same clearings and oak stands at Fontainebleau across every season, letting accumulated outdoor looking replace studio invention. The bark, mud and winter sky carry that unidealised weight. In 1861 he led the campaign that won an imperial decree protecting over a thousand hectares of the forest, France's first designated reserve.",
"bilinska-bohdanowicz": "Studied at the Académie Julian, one of the few Paris ateliers admitting women at a time when the École des Beaux-Arts barred them outright and would go on barring them until 1897. Her 1887 self-portrait, brushes in hand, took a third-class medal at the Salon that year. She died of a heart condition at thirty-eight.",
"tadeusz-makowski": "Constructed his masked children out of cylinders, cones and angular blocks, a Cubist armature under the festive surface, absorbed from Le Fauconnier's circle in Montparnasse after 1908. The figures read as wooden puppets precisely because that is how they are built: geometry first, sentiment laid over it. Before any of this he spent four years studying classical philology at the Jagiellonian.",
"wilhelm-trubner": "Joined the circle around Wilhelm Leibl, who held that an unsparing eye on the thing in front of you — paint laid down wet and direct, no correcting afterwards — was the only honest method, and that what you painted mattered less than how. The later decades went to landscape: the same sites returned to again and again under different weather, a serial habit nothing in the early portraits predicts.",
"ruszczyc": "Pushed the horizon so low that sky and earth split the canvas almost evenly; in the largest of them dark ploughed furrows take the bottom half, cloud fills everything above, and the ploughing figure is nearly swallowed. That structural severity came out of training under Arkhip Kuindzhi, whose atmospheric drama shaped a generation of Eastern European landscapists. He stopped painting after settling in Vilnius and founded the university's fine-arts faculty, serving as its first dean.",
"achille-lauge": "Reached divisionism on his own, separate dots of unmixed colour set on a regular grid, without having seen Seurat or Signac first, and never took on the scientific apparatus they built around it. For him it was a way of holding southern light rather than a theory. He studied in Paris beside the sculptor Bourdelle, then went back to the Languedoc village he came from after his father died and painted the same countryside for the rest of his life.",
"elihu-vedder": "Devoted eleven months to fifty-six illustrations for FitzGerald's Rubáiyát, published in 1884, and the book made him: it sold out immediately and fixed his reputation on both sides of the Atlantic. The sea-serpent subject predates all of that by twenty years, and he came back and painted it again thirty-five years later. He settled in Rome in 1866 and stayed for the rest of his life.",
"edward-frederick-skinner": "Produced factory interiors, forgers and file-cutters and spring-coilers mid-task, under the 1918 turn in Britain's official war art scheme from active propaganda toward a permanent national record. The point was no longer to persuade anyone; it was to leave evidence that this work had been done, by these people, at this scale. He had trained at Herkomer's school and come up through illustrated periodicals, which is the eye these use: legible, close to the machine, uninterested in heroics.",
"carl-grabow": "Served a nine-year apprenticeship in Berlin before returning to Stockholm to paint theatrical scenery, backdrops built to read from the stalls under gaslight rather than to be examined at arm's length. Scenery is made to be struck and repainted, so almost nothing any scene-painter makes survives. His did, and it is among the fullest surviving records of late nineteenth-century Swedish stagecraft. The framed pictures you hold are the side-line, not the career.",
"sargent": "Scraped down each evening's work before the next session, chasing the two or three minutes of dusk that made the garden picture work; it took two autumns. The 1884 society portrait was more decisive: a fallen shoulder strap on a sitter all Paris recognised caused a scandal, and he repainted it upright and left for London.",
"waterhouse": "Borrowed the Pre-Raphaelite programme — doomed women out of Tennyson, Keats and classical myth — but laid the paint with the looser broken touch of French naturalism rather than the hard jewelled surface the Brotherhood favoured. He was working a generation after them and drew on both. One Tennyson poem held him longest: he came back to it in 1888, 1894 and 1915, taking a different moment each time.",
"mccubbin": "Traced the settler's arc across three panels — arrival, clearing, family — then closed the sequence on a grave with a city rising behind it. He taught at the National Gallery School for some thirty years, and two of the painters elsewhere in your collection sat in that classroom. A single trip to Europe in 1907, at fifty-two, put him in front of Turner and the Impressionists and loosened his handling for good.",
"bonheur": "Required a police permit, renewed every six months and signed off by a doctor, to wear men's clothes in the slaughterhouses and livestock fairs where she studied her subjects; cross-dressing was illegal in France. She went further and bought carcasses from her butcher to dissect at home. In 1865 the Empress came to her studio and made her the first woman to receive the Légion d'honneur.",
"walter-sickert": "Squared up each composition from drawings and photographs rather than working from life; his own rule was that squaring-up is for the studio, far from the subject. The music-hall pictures take the sightline of the cheap seats at the back of the stalls — the audience seen from behind, in a crush of bodies, the performer small and glare-lit and far off. He named the 1908 series after a real murder in his neighbourhood.",
"william-etty": "Grounded his flesh tones in Titian, Tintoretto and Veronese, bravura brushwork and saturated colour taken from the Venetians rather than from any system. Long after his reputation was made he kept attending the Royal Academy life class, which his peers thought unbecoming in an Academician. To the charge of indecency he answered that there was nothing indecent in the pictures, only in the notions people brought to them.",
"fragonard": "Applied paint so fast that a label on the back of one portrait records it as an hour's work — wet on wet throughout, the surface built without waiting for anything to dry. The Progress of Love panels were commissioned by the king's mistress, delivered, refused, and returned to him; he kept them rolled up for twenty years. The Revolution did the same thing to his whole market, and he died in obscurity in 1806.",
"raphael": "Divided the labour across a Roman workshop of around fifty assistants; the papal commissions could not have come from one pair of hands. The smallest work you own hung for a century and a half as the best of several copies until Nicholas Penny re-attributed it in 1991. The Getty agreed £35 million for it in 2002, an export block intervened, and the National Gallery bought it two years later for £22 million.",
"delaunay": "Pitched flat colour fields against each other and never blended them, because the optical vibration at every edge was the whole point. The method came out of Chevreul's 1839 law of simultaneous contrast: adjacent colours intensify rather than cancel. Apollinaire named the result Orphism in 1912, and across a tower series he returned to for two decades the ironwork dissolves into angled planes until it is barely a scaffold for light.",
"kazimir-malevich": "Pared painting down to a black square on white, which he called Suprematism: pure feeling, freed from any depicted object. At the 1915 Petrograd exhibition the canvas hung high in the corner where an Orthodox household hangs its icon — a claim about what it had replaced. Forced back to figuration by Soviet decree, he signed those late canvases with a small black square, and the same mark went on his coffin.",
"laszlo-moholy-nagy": "Ordered a set of enamel panels from a sign factory in 1923, specifying each one on graph paper against the firm's colour chart and never touching the work himself. He told the story afterwards as an order placed by telephone, and the name stuck; the point either way was that the artist's hand had become optional. At the Bauhaus he also made photograms, objects laid straight onto light-sensitive paper, no camera involved.",
"seon": "Covered granite peaks in repeated dark ink retouches until the rock went almost black, the look of wet stone under breaking cloud. This was jingyeong sansuhwa, true-view landscape — actual Korean mountains rather than the idealised Chinese scenery that had governed Joseon painting before him. The 1751 work, his most celebrated, was painted at seventy-five: a summer mountain just after rain, mist still lying in the valleys.",
"seraphine-louis": "Compounded her own paint from commercial enamel, oil and varnish to a formula she would not share, working at night after cleaning houses by day. She was found in 1912 only because a German dealer happened to take rooms where she charred. She said an angel had instructed her to paint for the glory of God. Committed to an asylum in 1932, she died there ten years later and went into a common grave.",
"hubert-robert": "Nicknamed Robert des Ruines for decades of ruin paintings that combine archaeological fact and free invention in the same canvas. He spent eleven years in Rome from 1754, came back to be made keeper of the king's pictures, and proposed turning the Louvre's Grande Galerie into a continuous public gallery. Arrested in 1793, he painted more than fifty canvases in prison before his release nine months later.",
"leon-augustin-lhermitte": "Celebrated for charcoal drawings treated as finished works rather than studies, an unusual ambition for the period. The subject was peasants at labour, the same ground Millet had staked, but where Millet cut monumental silhouettes this is cumulative intimacy — texture, soot, grain. Van Gogh, writing to his brother, set him down as the Millet of black and white.",
"leon-wyczo-kowski": "Shifted from historical subjects to sun-struck scenes of field labour after a trip to Paris, taking on Impressionist light and impasto without losing the documentary impulse. Later he turned to lithography and produced thematic portfolios on the Tatras, Lithuania, Gdańsk and Wawel between 1906 and 1920. He taught at the Kraków Academy from 1895 to 1911.",
"konrad-krzyzanowski": "Sited a face in near-darkness and worked it fast, wet and thick, so the head surfaces out of a brown-black ground with the brushmarks still legible — expressionist handling a decade before the word was current in Poland. In 1900 he co-founded a private Warsaw painting school that folded four years later into what became the Academy of Fine Arts, and he took his students outdoors to Lithuania and Finland to work.",
"wincenty-kasprzycki": "Documented an 1828 Warsaw art exhibition by painting the room itself: canvases stacked three rows high on a timber framework, individual works still identifiable against the printed catalogue and the press notices. No photograph could exist to do that job, so the painting is now the primary visual record of how early Polish exhibitions were hung. Otherwise he worked in vedute — palaces and parks, a genre kept alive by aristocratic commission.",
"witold-pruszkowski": "Handled Slavic folklore and national grief in pastel as much as oil, a medium whose softness sits strangely against subjects that include Siberian exile marches and religious persecution. The Unitka of the title is a Uniate woman, a Greek Catholic whose church was abolished by Russian decree, shown in the aftermath of that suppression. He died in Budapest in 1896, at fifty.",
"thomas-hiram-hotchkiss": "Relocated to Italy in 1860 and never came back: nine years, a permanent Rome studio, close company with Sanford Gifford and Elihu Vedder, and an output of small intimate oil sketches that the Hudson River School never quite knew where to file. Tuberculosis killed him at thirty-five, before any public success arrived. Almost everything that survives went into a single New York collection, which is why he stayed invisible so long.",

"klee": "Invented an oil-transfer method around 1919: a sheet blackened with oil laid between the drawing and a fresh page, then traced through, so the line arrives softened and slightly beyond his control. He taught form theory at the Bauhaus for a decade and the notebooks from it run to some four thousand pages. Scleroderma took hold of his hands in the late 1930s and the late line thickened to broad bars; 1939 was his most productive year, over twelve hundred works.",
"yves-tanguy": "Glimpsed a de Chirico through a shop window in 1923 and jumped off the bus to look; self-taught, never formally trained, he became a painter that same year. The canvases build soft-edged biomorphic objects on flat vast plains with meticulous, almost geological care, and the spaces read as seabed or outer atmosphere. He declined to say what the forms are and left no account of them.",
"stuck": "Framed the paintings himself, not as an afterthought but as a designed component, the gilded architectural borders conceived as part of one object. He painted his image of a woman coiled with a serpent across at least twelve known versions, each in a frame of his own making. His students at the Munich Academy included Kandinsky and Klee, and the villa he designed for himself, down to the furniture, is now a museum.",
"jozef-mehoffer": "Won an international competition in 1895 at twenty-five, an unknown student from Kraków submitting the top-ranked design for stained glass in a Swiss cathedral, then spent forty years executing it. He treated lead lines as graphic drawing and held colour in flat enclosed fields, a cloisonné logic applied to glass. The single oil you hold shows the same decorative flattening.",
};
