// art_fallbacks.js — last-resort Wikimedia Commons mirrors for works whose primary image
// lives on a single museum CDN host (cyfrowe-cdn.mnw.art.pl for MNW Warsaw works;
// api.nga.gov for NGA Washington works). When that host is unreachable, these URLs
// provide a visible card rather than a blank one.
//
// How generated: Wikidata P18 (depicts-image) claims resolved per work qid; image
// dimensions decoded from the Commons JPEG/PNG headers. All entries verified high-confidence.
//
// Shape: { slug: [url, width, height] } — width/height are the native pixel dimensions
// of the Commons original. 25 MNW entries are low-resolution originals (~800 px long side);
// those carry a 4th element "lowres" so callers can note the quality tier if needed.
// The app reads only [0] (url), [1] (w), [2] (h) — the 4th element is silently ignored.
//
// Sorted alphabetically by slug.
window.CANVAS_FALLBACKS = {
  "a-girl-with-a-watering-can": ["https://upload.wikimedia.org/wikipedia/commons/3/3f/Auguste_Renoir_-_A_Girl_with_a_Watering_Can_-_Google_Art_Project.jpg", 7201, 9888],
  "a-lady-writing-a-letter": ["https://upload.wikimedia.org/wikipedia/commons/7/7d/A_Lady_Writing_by_Johannes_Vermeer%2C_1665-6.png", 2469, 2789],
  "a-polish-nobleman": ["https://upload.wikimedia.org/wikipedia/commons/2/23/Rembrandt_van_Rijn%2C_A_Polish_Nobleman%2C_1637%2C_NGA_85.jpg", 2735, 4000],
  "a-young-girl-reading": ["https://upload.wikimedia.org/wikipedia/commons/6/69/Fragonard%2C_The_Reader.jpg", 3182, 4000],
  "adam-and-eve": ["https://upload.wikimedia.org/wikipedia/commons/1/1f/Albrecht_D%C3%BCrer_-_Adam_and_Eve_-_Google_Art_Project.jpg", 4471, 5749],
  "albert-chmielowski-opuszczona-plebania": ["https://upload.wikimedia.org/wikipedia/commons/8/8f/Adam_Chmielowski_-_Opuszczona_plebania.jpg", 1862, 2356],
  "alba-madonna": ["https://upload.wikimedia.org/wikipedia/commons/7/75/Raphael%2C_The_Alba_Madonna%2C_c._1510%2C_NGA_26.jpg", 12090, 12090],
  "alfred-sisley-the-banks-of-the-oise": ["https://upload.wikimedia.org/wikipedia/commons/2/22/Alfred_Sisley_021.jpg", 2904, 2407],
  "anders-zorn-hugo-reisinger": ["https://upload.wikimedia.org/wikipedia/commons/c/c7/Anders_Zorn_-_Hugo_Reisinger.jpg", 2263, 3089],
  "arnold-bocklin-the-sanctuary-of-hercules": ["https://upload.wikimedia.org/wikipedia/commons/5/50/Arnold_B%C3%B6cklin_-_Das_Heiligtum_des_Herkules_%281884%29.jpg", 8309, 5205],
  "auguste-rodin-the-evil-spirits": ["https://upload.wikimedia.org/wikipedia/commons/b/bc/Auguste_Rodin%2C_The_Evil_Spirits%2C_c._1899%2C_NGA_1010.jpg", 3715, 4000],
  "bartolome-esteban-murillo-the-return-of-the-prodigal-son": ["https://upload.wikimedia.org/wikipedia/commons/1/1d/Return_of_the_Prodigal_Son_1667-1670_Murillo.jpg", 4000, 3611],
  "caspar-david-friedrich-northern-landscape-spring": ["https://upload.wikimedia.org/wikipedia/commons/6/65/Caspar_David_Friedrich_-_Nordische_Landschaft%2C_Fr%C3%BChling.jpg", 9655, 6950],
  "christian-dirce": ["https://upload.wikimedia.org/wikipedia/commons/6/6b/Siemiradzki_Christian_Dirce.jpg", 2273, 1100],
  "christian-rohlfs-white-beeches-in-fall": ["https://upload.wikimedia.org/wikipedia/commons/9/92/Christian_Rohlfs_Wei%C3%9Fe_Birken_im_Herbst_1910.jpg", 3242, 4096],
  "claude-monet-the-artist-s-garden-at-vetheuil": ["https://upload.wikimedia.org/wikipedia/commons/8/89/Claude_Monet_-_Monet%27s_garden_at_V%C3%A9theuil_%281880%29.jpg", 2470, 3130],
  "claude-monet-banks-of-the-seine-vetheuil": ["https://upload.wikimedia.org/wikipedia/commons/f/f0/Claude_Monet_-_Au_Bord_de_la_Seine%2C_pr%C3%A8s_de_V%C3%A9theuil.jpg", 1600, 1096],
  "claude-monet-bazille-and-camille-study-for-dejeuner-sur-l-he": ["https://upload.wikimedia.org/wikipedia/commons/4/4a/Bazille_and_Camille_%28Study_for_D%C3%A9jeuner_sur_l%27Herbe%29_A35075.jpg", 2975, 4000],
  "claude-monet-bridge-at-argenteuil-on-a-gray-day": ["https://upload.wikimedia.org/wikipedia/commons/c/c9/Claude_Monet%2C_Bridge_at_Argenteuil_on_a_Gray_Day%2C_c._1876%2C_NGA_52188.jpg", 9439, 7109],
  "claude-monet-cliffs-at-pourville": ["https://upload.wikimedia.org/wikipedia/commons/4/46/Cliffs_at_Pourville_A21450.jpg", 4000, 2386],
  "claude-monet-interior-after-dinner": ["https://upload.wikimedia.org/wikipedia/commons/b/b7/Claude_Monet_-_Int%C3%A9rieur%2C_Apr%C3%A8s_d%C3%AEner.jpg", 7671, 5936],
  "claude-monet-jerusalem-artichoke-flowers": ["https://upload.wikimedia.org/wikipedia/commons/9/9b/Jerusalem_Artichoke_Flowers_E10330.jpg", 12622, 17418],
  "claude-monet-morning-haze": ["https://upload.wikimedia.org/wikipedia/commons/7/7f/Claude_Monet%2C_Morning_Haze%2C_1888%2C_NGA_45872.jpg", 4000, 3181],
  "claude-monet-palazzo-da-mula-venice": ["https://upload.wikimedia.org/wikipedia/commons/f/f2/Claude_Monet_-_Palazzo_da_Mula_in_Venice_1908.jpg", 3600, 2700],
  "claude-monet-rouen-cathedral-west-facade": ["https://upload.wikimedia.org/wikipedia/commons/a/a9/Claude_Monet_-_Rouen_Cathedral%2C_West_Facade.jpg", 1776, 2500],
  "claude-monet-sainte-adresse": ["https://upload.wikimedia.org/wikipedia/commons/8/84/Sainte-Adresse_A12549.jpg", 4000, 2786],
  "claude-monet-ships-riding-on-the-seine-at-rouen": ["https://upload.wikimedia.org/wikipedia/commons/e/ed/Ships_Riding_on_the_Seine_at_Rouen_by_Claude_Monet%2C_1872.jpg", 11078, 9011],
  "claude-monet-still-life-with-bottle-carafe-bread-and-wine": ["https://upload.wikimedia.org/wikipedia/commons/b/b4/Still_Life_with_Bottle%2C_Carafe%2C_Bread%2C_and_Wine_A26263.jpg", 4000, 2633],
  "claude-monet-the-artist-s-garden-in-argenteuil-a-corner-of-t": ["https://upload.wikimedia.org/wikipedia/commons/8/8e/The_Artist%27s_Garden_in_Argenteuil_%28A_Corner_of_the_Garden_with_Dahlias%29_A12382.jpg", 4000, 3005],
  "claude-monet-the-bridge-at-argenteuil": ["https://upload.wikimedia.org/wikipedia/commons/f/f3/Claude_Monet_-_The_Bridge_at_Argenteuil_%281874%29_-_NGA_1983.1.24.jpg", 7999, 5998],
  "claude-monet-the-cradle-camille-with-the-artist-s-son-jean": ["https://upload.wikimedia.org/wikipedia/commons/3/34/The_Cradle_-_Camille_with_the_Artist%27s_Son_Jean_A14894.jpg", 3066, 4000],
  "claude-monet-the-houses-of-parliament-sunset": ["https://upload.wikimedia.org/wikipedia/commons/a/ab/Claude_Monet_-_The_Houses_of_Parliament%2C_Sunset.jpg", 5500, 4858],
  "claude-monet-the-seine-at-giverny": ["https://upload.wikimedia.org/wikipedia/commons/f/fe/Claude_Monet%2C_The_Seine_at_Giverny%2C_1897%2C_NGA_46655.jpg", 9119, 7359],
  "claude-monet-the-willows": ["https://upload.wikimedia.org/wikipedia/commons/5/54/Claude_Monet%2C_The_Willows%2C_1880%2C_NGA_178254.jpg", 4000, 3207],
  "claude-monet-waterloo-bridge-london-at-dusk": ["https://upload.wikimedia.org/wikipedia/commons/1/18/Waterloo_Bridge%2C_London%2C_at_Dusk.JPG", 2152, 1338],
  "claude-monet-waterloo-bridge-london-at-sunset": ["https://upload.wikimedia.org/wikipedia/commons/c/cd/Waterloo_Bridge%2C_London%2C_at_Sunset_E11705.jpg", 3147, 2221],
  "claude-monet-woman-seated-under-the-willows": ["https://upload.wikimedia.org/wikipedia/commons/4/4e/Woman_Seated_under_the_Willows_E11686.jpg", 2205, 3000],
  "death-and-the-miser": ["https://upload.wikimedia.org/wikipedia/commons/4/48/Jheronimus_Bosch_050.jpg", 5901, 17766],
  "degas-grande-arabesque-third-time": ["https://upload.wikimedia.org/wikipedia/commons/6/6f/Edgar_Degas%2C_Grande_Arabesque%2C_Third_Time_%28First_Arabesque_Pench%C3%A9e%29%2C_c._1885-1890%2C_NGA_110301.jpg", 2877, 2430],
  "ernst-fries-berchtesgaden-with-the-watzmann-peak-in-the-dist": ["https://upload.wikimedia.org/wikipedia/commons/c/c5/Ernst_Fries%2C_Berchtesgaden_with_the_Watzmann_Peak_in_the_Distance%2C_1822%2C_NGA_155534.jpg", 4000, 2779],
  "eva-gonzales-nanny-and-child": ["https://upload.wikimedia.org/wikipedia/commons/6/63/Eva_Gonzal%C3%A8s_-_Nanny_and_Child_-_Google_Art_Project.jpg", 4615, 3698],
  "farmhouse-in-provence": ["https://upload.wikimedia.org/wikipedia/commons/0/06/Farmhouse_in_Provence%2C_1888%2C_Vincent_van_Gogh%2C_NGA.jpg", 16428, 12392],
  "ferdynand-ruszczyc-pejzaz-rzeczny": ["https://upload.wikimedia.org/wikipedia/commons/e/eb/Ferdynand_Ruszczyc_-_River_landscape_-_MP_449_-_National_Museum_in_Warsaw.jpg", 4000, 2743],
  "garden-in-kissingen": ["https://upload.wikimedia.org/wikipedia/commons/6/69/Menzel_Garden_in_Kissingen.jpg", 517, 781, "lowres"],
  "ginevra-de-benci": ["https://upload.wikimedia.org/wikipedia/commons/e/ee/Ginevra_de%27_Benci_-_National_Gallery_of_Art.jpg", 23235, 23968],
  "girl-in-white": ["https://upload.wikimedia.org/wikipedia/commons/d/d4/Girl_in_White_by_Vincent_Van_Gogh_-_NGA.jpg", 2034, 3000],
  "giovanni-boldini-bust-of-a-young-woman-in-profile": ["https://upload.wikimedia.org/wikipedia/commons/b/ba/Giovanni_Boldini_-_Bust_of_a_Young_Woman_in_Profile_-_NGA_2020.44.1.jpg", 2952, 4096],
  "giovanni-boldini-whistler-asleep": ["https://upload.wikimedia.org/wikipedia/commons/6/6a/Giovanni_Boldini%2C_Whistler_Asleep%2C_1897%2C_NGA_164006.jpg", 4000, 2654],
  "gossamer": ["https://upload.wikimedia.org/wikipedia/commons/5/58/J%C3%B3zef_Che%C5%82mo%C5%84ski_-_Indian_summer_-_Google_Art_Project.jpg", 3205, 2457],
  "gustav-klimt-baby-cradle": ["https://upload.wikimedia.org/wikipedia/commons/f/f5/Baby_%28Cradle%29_A18969.jpg", 3969, 4000],
  "gustave-le-gray-cavalry-maneuvers-camp-de-chalons": ["https://upload.wikimedia.org/wikipedia/commons/1/14/Gustave_Le_Gray%2C_Cavalry_Maneuvers%2C_Camp_de_Ch%C3%A2lons%2C_1857%2C_NGA_136418.jpg", 4000, 3232],
  "hendrick-ter-brugghen-bagpipe-player": ["https://upload.wikimedia.org/wikipedia/commons/b/b8/Hendrick_ter_Brugghen_-_Bagpipe_Player_-_Google_Art_Project.jpg", 7729, 9346],
  "henri-gervex-study-for-autopsy-at-the-hotel-dieu": ["https://upload.wikimedia.org/wikipedia/commons/2/2a/Study_for_Autopsy_at_the_H%C3%B4tel-Dieu_A11096.jpg", 2366, 2954],
  "henry-fuseli-oedipus-cursing-his-son-polynices": ["https://upload.wikimedia.org/wikipedia/commons/c/c2/Oedipus_Cursing_His_Son%2C_Polynices_A15036.jpg", 12417, 11337],
  "hubert-robert-the-ponte-salario": ["https://upload.wikimedia.org/wikipedia/commons/3/3b/Hubert_Robert_-_The_Old_Bridge.JPG", 1732, 1310],
  "in-the-arbour": ["https://upload.wikimedia.org/wikipedia/commons/4/4f/Gierymski_In_the_arbour.png", 1948, 1787],
  "introduction-of-christianity-in-poland": ["https://upload.wikimedia.org/wikipedia/commons/0/03/Jan_Matejko_-_Zaprowadzenie_chrze%C5%9Bcija%C5%84stwa_R.P.965%2C_z_cyklu_%22Dzieje_Cywilizacji_w_Polsce%22_-_01_%28MP_3894%29.jpg", 2500, 1796],
  "jacek-malczewski-chrystus-w-emaus": ["https://upload.wikimedia.org/wikipedia/commons/6/6c/Jacek_Malczewski_-_Christ_in_Emmaus_-_MP_1053_MNW_-_National_Museum_in_Warsaw.jpg", 2500, 1938],
  "jacek-malczewski-pejzaz-z-jarzebina-czesc-prawa-tryptyku-idz": ["https://upload.wikimedia.org/wikipedia/commons/8/83/Malczewski_Landscape_with_rowan_trees_left.jpg", 754, 334, "lowres"],
  "james-tissot-hide-and-seek": ["https://upload.wikimedia.org/wikipedia/commons/5/58/James_Tissot_-_Hide_and_Seek.jpg", 13102, 17904],
  "jan-both-an-italianate-evening-landscape": ["https://upload.wikimedia.org/wikipedia/commons/e/e1/An_Italianate_Evening_Landscape_A15583.jpg", 4000, 3192],
  "jan-ciaglinski-ganges-po-zachodzie-s-onca-z-podrozy-do-indii": ["https://upload.wikimedia.org/wikipedia/commons/f/f3/Jan_Ci%C4%85gli%C5%84ski_-_Ganges_after_sunset._From_the_journey_to_India_-_MP_1794_MNW_-_National_Museum_in_Warsaw.jpg", 800, 645, "lowres"],
  "jan-ciaglinski-himalaje-z-podrozy-do-indii": ["https://upload.wikimedia.org/wikipedia/commons/c/cb/Jan_Ci%C4%85gli%C5%84ski_-_The_Himalayas._From_the_journey_to_India_-_MP_1680_MNW_-_National_Museum_in_Warsaw.jpg", 800, 622, "lowres"],
  "jan-ciaglinski-morze-z-podrozy-do-konstantynopola": ["https://upload.wikimedia.org/wikipedia/commons/3/35/Jan_Ci%C4%85gli%C5%84ski_-_Sea._From_the_journey_to_Constantinople_-_MP_1491_MNW_-_National_Museum_in_Warsaw.jpg", 800, 552, "lowres"],
  "jan-ciaglinski-noc-na-morzu-z-podrozy-do-konstantynopola": ["https://upload.wikimedia.org/wikipedia/commons/b/bc/Jan_Ci%C4%85gli%C5%84ski_-_Night_on_the_sea._From_the_journey_to_Constantinople_-_MP_1478_MNW_-_National_Museum_in_Warsaw.jpg", 2500, 1372],
  "jan-ciaglinski-ognie-z-okretu-z-podrozy-do-palestyny": ["https://upload.wikimedia.org/wikipedia/commons/5/51/Jan_Ci%C4%85gli%C5%84ski_-_Fires_from_a_ship._From_the_journey_to_Palestine_-_MP_1558_MNW_-_National_Museum_in_Warsaw.jpg", 800, 575, "lowres"],
  "jan-ciaglinski-portret-eugenii-aleksandry-rubcowej-matki-mal": ["https://upload.wikimedia.org/wikipedia/commons/4/43/Jan_Ci%C4%85gli%C5%84ski_-_Portrait_of_Eugenia_Alexandra_Rubtsov%2C_mother_of_the_painter_Rubtsov_-_MP_1738_MNW_-_National_Museum_in_Warsaw.jpg", 2500, 1909],
  "jan-ciaglinski-portret-wandy-z-ciaglinskich-szwengrubenowej": ["https://upload.wikimedia.org/wikipedia/commons/9/9e/Jan_Ci%C4%85gli%C5%84ski_-_Portrait_of_Wanda_Szwengruben_n%C3%A9e_Ci%C4%85gli%C5%84ska%2C_artist%27s_sister_-_MP_1875_MNW_-_National_Museum_in_Warsaw.jpg", 2224, 2500],
  "jan-ciaglinski-starozytne-ruiny-z-podrozy-do-egiptu": ["https://upload.wikimedia.org/wikipedia/commons/9/9f/Jan_Ci%C4%85gli%C5%84ski_-_Ancient_ruins._From_the_journey_to_Egypt_-_MP_1590_MNW_-_National_Museum_in_Warsaw.jpg", 2500, 1862],
  "jan-ciaglinski-studium-g-owy-do-obrazu-taniec-symboliczny": ["https://upload.wikimedia.org/wikipedia/commons/c/c8/Jan_Ci%C4%85gli%C5%84ski_-_Study_of_the_head_for_the_painting_%E2%80%9CSymbolic_dance%E2%80%9D_-_MP_1757_MNW_-_National_Museum_in_Warsaw.jpg", 657, 800, "lowres"],
  "jan-ciaglinski-studium-ulicznicy-do-obrazu-wschod": ["https://upload.wikimedia.org/wikipedia/commons/d/de/Jan_Ci%C4%85gli%C5%84ski_-_Study_of_a_streetwalker_for_the_painting_%E2%80%9CEast%E2%80%9D_-_MP_1422_MNW_-_National_Museum_in_Warsaw.jpg", 565, 800, "lowres"],
  "jan-ciaglinski-szkic-do-obrazu-vita-i": ["https://upload.wikimedia.org/wikipedia/commons/c/c0/Jan_Ci%C4%85gli%C5%84ski_-_Sketch_for_the_painting_%E2%80%9CVita%E2%80%9D_I_-_MP_1803_MNW_-_National_Museum_in_Warsaw.jpg", 800, 665, "lowres"],
  "jan-ciaglinski-z-pierwszego-postoju-na-pustyni-z-podrozy-do": ["https://upload.wikimedia.org/wikipedia/commons/a/a5/Jan_Ci%C4%85gli%C5%84ski_-_From_the_first_stop_in_the_desert._From_the_journey_to_Palestine_-_MP_1568_MNW_-_National_Museum_in_Warsaw.jpg", 800, 578, "lowres"],
  "jan-ciaglinski-ze-statku-z-podrozy-do-indii": ["https://upload.wikimedia.org/wikipedia/commons/2/29/Jan_Ci%C4%85gli%C5%84ski_-_From_the_ship._From_the_journey_to_India_-_MP_1651_MNW_-_National_Museum_in_Warsaw.jpg", 800, 609, "lowres"],
  "jan-matejko-studium-ba-konskiego-do-dziewicy-orleanskiej": ["https://upload.wikimedia.org/wikipedia/commons/0/01/Jan_Matejko_-_Study_of_horse%E2%80%99s_head_for_%E2%80%9CThe_Maid_of_Orl%C3%A9ans%E2%80%9D_-_231060_MNW_-_National_Museum_in_Warsaw.jpg", 1758, 2500],
  "jean-baptiste-armand-guillaumin-the-bridge-of-louis-philippe": ["https://upload.wikimedia.org/wikipedia/commons/3/3e/The_Bridge_of_Louis_Philippe_A22727.jpg", 4000, 3018],
  "jean-beraud-paris-rue-du-havre": ["https://upload.wikimedia.org/wikipedia/commons/3/34/Paris%2C_rue_du_Havre_by_Jean_B%C3%A9raud_-_National_Gallery_of_Art.jpg", 7291, 9452],
  "jean-pierre-norblin-de-la-gourdaine-bathing-in-a-park": ["https://upload.wikimedia.org/wikipedia/commons/7/77/Norblin_Bath_in_the_park.jpg", 1428, 2448],
  "joachim-patinir-the-flight-into-egypt": ["https://upload.wikimedia.org/wikipedia/commons/8/85/The_Flight_into_Egypt_C17511.jpg", 4744, 7548],
  "johan-christian-dahl-view-from-vaekero-near-christiania": ["https://upload.wikimedia.org/wikipedia/commons/0/0c/Johan_Christian_Dahl_-_Utsikt_fra_V%C3%A6ker%C3%B8_n%C3%A6r_Christiania.jpg", 19205, 12106],
  "johan-jongkind-the-towpath": ["https://upload.wikimedia.org/wikipedia/commons/6/66/The_Towpath_A11144.jpg", 3000, 2167],
  "john-mackie-falconer-washing-morning-down-south": ["https://upload.wikimedia.org/wikipedia/commons/2/2e/John_Mackie_Falconer%2C_Washing_Morning_Down_South%2C_1882%2C_NGA_145102.jpg", 4000, 2433],
  "jozef-pankiewicz-nokturn-abedzie-w-ogrodzie-saskim-w-warszaw": ["https://upload.wikimedia.org/wikipedia/commons/3/37/Pankiewicz_Swans_in_the_Saxon_Garden.jpg", 1958, 1098],
  "jozef-pankiewicz-pejzaz-z-saint-tropez-pinie": ["https://upload.wikimedia.org/wikipedia/commons/d/dc/J%C3%B3zef_Pankiewicz_-_Landscape_from_Saint-Tropez_%E2%80%93_Stone_pines_-_MP_2251_MNW_-_National_Museum_in_Warsaw.jpg", 613, 800, "lowres"],
  "jozef-szermentowski-odpoczynek-oracza": ["https://upload.wikimedia.org/wikipedia/commons/8/8e/Szermentowski_Ploughman%27s_rest.jpg", 804, 577, "lowres"],
  "jules-bastien-lepage-simon-hayem": ["https://upload.wikimedia.org/wikipedia/commons/3/3e/Jules_Bastien-Lepage_-_Simon_Hayem_01.jpg", 2310, 3026],
  "jules-dupre-the-old-oak": ["https://upload.wikimedia.org/wikipedia/commons/f/f8/The_Old_Oak_by_Jules_Dupr%C3%A9%2C_c1870.jpg", 11269, 8690],
  "knight-death-and-the-devil": ["https://upload.wikimedia.org/wikipedia/commons/0/0a/Albrecht_D%C3%BCrer%2C_Knight%2C_Death_and_Devil%2C_1513%2C_NGA_6637.jpg", 3087, 4000],
  "konrad-krzyzanowski-brzozy": ["https://upload.wikimedia.org/wikipedia/commons/7/74/Konrad_Krzy%C5%BCanowski_-_Birch_trees_-_MP_34_MNW_-_National_Museum_in_Warsaw.jpg", 1674, 2500],
  "konrad-krzyzanowski-portret-teresy-z-konow-silberstein": ["https://upload.wikimedia.org/wikipedia/commons/e/ec/Konrad_Krzy%C5%BCanowski_-_Portrait_of_Teresa_Silberstein_n%C3%A9e_Cohn_-_MP_43_MNW_-_National_Museum_in_Warsaw.jpg", 2020, 2500],
  "konrad-krzyzanowski-werki-pod-wilnem": ["https://upload.wikimedia.org/wikipedia/commons/5/5c/Konrad_Krzy%C5%BCanowski_-_Werki_pod_Wilnem.jpg", 800, 600, "lowres"],
  "konstanty-mankowski-szarytka-w-ogrodzie-szpitalnym": ["https://upload.wikimedia.org/wikipedia/commons/3/3d/Ma%C5%84kowski_Sister_of_Charity.jpg", 773, 459, "lowres"],
  "laocoon": ["https://upload.wikimedia.org/wikipedia/commons/2/23/El_Greco_%28Domenikos_Theotokopoulos%29_-_Laoco%C3%B6n_-_Google_Art_Project.jpg", 14079, 11215],
  "lodgepole-pines-lyell-fork-of-the-merced-river": ["https://upload.wikimedia.org/wikipedia/commons/a/a9/Lodgepole_Pines_photo_by_Ansel_Adams.jpg", 1879, 1477],
  "ludwik-de-laveaux-plac-opery-w-paryzu": ["https://upload.wikimedia.org/wikipedia/commons/9/97/Laveaux_Place_de_l%27Op%C3%A9ra.jpg", 913, 805, "lowres"],
  "luis-melendez-still-life-with-figs-and-bread": ["https://upload.wikimedia.org/wikipedia/commons/e/e0/Luis_Mel%C3%A9ndez_-_Still_Life_with_Figs_and_Bread_-_Google_Art_Project.jpg", 3493, 4999],
  "maksymilian-gierymski-pejzaz-z-zagajnikiem-brzozowym": ["https://upload.wikimedia.org/wikipedia/commons/3/36/Maksymilian_Gierymski_-_Landscape_with_a_birch_grove_-_MP_1367_MNW_-_National_Museum_in_Warsaw.jpg", 800, 532, "lowres"],
  "marian-wawrzeniecki-wodna-boginka": ["https://upload.wikimedia.org/wikipedia/commons/2/23/Marian_Wawrzeniecki_-_Water_nymph_-_MP_944_MNW_-_National_Museum_in_Warsaw.jpg", 2117, 2500],
  "melencolia-i": ["https://upload.wikimedia.org/wikipedia/commons/0/0c/Albrecht_D%C3%BCrer_-_Melencolia_I_-_Google_Art_Project_%28427760%29.jpg", 4918, 6257],
  "monet-woman-with-a-parasol": ["https://upload.wikimedia.org/wikipedia/commons/1/1b/Claude_Monet_-_Woman_with_a_Parasol_-_Madame_Monet_and_Her_Son_-_Google_Art_Project.jpg", 6001, 7455],
  "nemesis": ["https://upload.wikimedia.org/wikipedia/commons/1/19/Albrecht_D%C3%BCrer%2C_Nemesis_%28The_Great_Fortune%29%2C_c._1501-1502%2C_NGA_6603.jpg", 2770, 4000],
  "paul-cezanne-arlequin": ["https://upload.wikimedia.org/wikipedia/commons/5/55/Arlequin%2C_par_Paul_C%C3%A9zanne%2C_NGA.jpg", 2574, 4000],
  "paul-gauguin-the-universe-is-created-l-univers-est-cree": ["https://upload.wikimedia.org/wikipedia/commons/4/4d/Paul_Gauguin%2C_The_Universe_is_Created_%28L%27Univers_est_cree%29%2C_c._1894%2C_NGA_39009.jpg", 4000, 2365],
  "paul-serusier-farmhouse-at-le-pouldu": ["https://upload.wikimedia.org/wikipedia/commons/7/7a/Paul_S%C3%A9rusier%2C_Farmhouse_at_Le_Pouldu%2C_1890%2C_NGA_116570.jpg", 3251, 4000],
  "paul-signac-antibes-ranek": ["https://upload.wikimedia.org/wikipedia/commons/3/3c/Signac_Antibes_-_Morning.jpg", 2306, 1558],
  "peasant-coffin": ["https://upload.wikimedia.org/wikipedia/commons/0/06/Aleksander_Gierymski%2C_Trumna_ch%C5%82opska.jpg", 2466, 1815],
  "piotr-micha-owski-kobieta-w-ogrodzie": ["https://upload.wikimedia.org/wikipedia/commons/d/d4/Piotr_Micha%C5%82owski_-_Woman_in_the_garden_-_MP_595_MNW_-_National_Museum_in_Warsaw.jpg", 584, 800, "lowres"],
  "polish-hamlet-portrait-of-aleksander-wielopolski": ["https://upload.wikimedia.org/wikipedia/commons/c/c2/Jacek_Malczewski%2C_Hamlet_Polski_-_Portret_Aleksandra_Wielopolskiego.jpg", 5315, 3571],
  "portrait-of-adam-mickiewicz-on-the-ayu-dag-cliff": ["https://upload.wikimedia.org/wikipedia/commons/1/10/Wa%C5%84kowicz_Adam_Mickiewicz.jpg", 1969, 2437],
  "portrait-of-bindo-altoviti": ["https://upload.wikimedia.org/wikipedia/commons/b/b6/Raffaello_Sanzio_-_Ritratto_di_Bindo_Altoviti.jpg", 10504, 14434],
  "robert-delaunay-political-drama": ["https://upload.wikimedia.org/wikipedia/commons/e/e1/Political_Drama_D11035.jpg", 3111, 4000],
  "rzeczpospolita-babinska": ["https://upload.wikimedia.org/wikipedia/commons/5/54/Jan_Matejko_-_Rzeczpospolita_Babi%C5%84ska.jpg", 2398, 1110],
  "soil": ["https://upload.wikimedia.org/wikipedia/commons/8/8c/Ferdynand_Ruszczyc%2C_Ziemia.jpg", 4000, 3127],
  "stanis-aw-ignacy-witkiewicz-portret-kobiecy": ["https://upload.wikimedia.org/wikipedia/commons/2/22/Witkacy_-_Portret_kobiecy_-_MNW.jpg", 2962, 3987],
  "stanis-aw-witkiewicz-droga-w-lesie": ["https://upload.wikimedia.org/wikipedia/commons/1/15/Witkacy_-_Droga_w_lesie.jpg", 1920, 2500],
  "symphony-in-white-no-1-the-white-girl": ["https://upload.wikimedia.org/wikipedia/commons/3/3f/Whistler_James_Symphony_in_White_no_1_%28The_White_Girl%29_1862.jpg", 10509, 21071],
  "tadeusz-makowski-pejzaz-z-przeswiecajacym-s-oncem": ["https://upload.wikimedia.org/wikipedia/commons/4/41/Tadeusz_Makowski_-_Landscape_with_the_sun_shining_through_-_MPW_2540_MNW_-_National_Museum_in_Warsaw.jpg", 2500, 1813],
  "tadeusz-makowski-pejzaz-z-trzema-postaciami": ["https://upload.wikimedia.org/wikipedia/commons/3/39/Tadeusz_Makowski_-_Landscape_with_three_figures_-_MPW_2499_MNW_-_National_Museum_in_Warsaw.jpg", 800, 738, "lowres"],
  "tadeusz-makowski-podwieczorek": ["https://upload.wikimedia.org/wikipedia/commons/0/0d/Tadeusz_Makowski_-_Afternoon_snack_-_MPW_2580_MNW_-_National_Museum_in_Warsaw.jpg", 800, 430, "lowres"],
  "tadeusz-makowski-statek-w-miescie": ["https://upload.wikimedia.org/wikipedia/commons/d/d6/Tadeusz_Makowski_-_Ship_in_a_city_-_MPW_2524_MNW_-_National_Museum_in_Warsaw.jpg", 1695, 2500],
  "teofil-kwiatkowski-pejzaz-widok-doliny-cousin": ["https://upload.wikimedia.org/wikipedia/commons/a/aa/Teofil_Kwiatkowski_-_Landscape_%E2%80%93_View_of_Vall%C3%A9e_du_Cousin_-_MP_320_MNW_-_National_Museum_in_Warsaw.jpg", 731, 800, "lowres"],
  "teodor-axentowicz-ko-omyjka": ["https://upload.wikimedia.org/wikipedia/commons/c/cb/Teodor_Axentowicz_-_Ko%C5%82omyjka.jpg", 2500, 1876],
  "the-emperor-napoleon-in-his-study-at-the-tuileries": ["https://upload.wikimedia.org/wikipedia/commons/b/bd/The_Emperor_Napoleon_in_His_Study_at_the_Tuileries%2C_by_Jacques-Louis_David_%281812%29_-_National_Gallery_of_Art_%28Samuel_H._Kress_Foundation%29.jpg", 16304, 26731],
  "the-old-musician": ["https://upload.wikimedia.org/wikipedia/commons/4/47/%C3%89douard_Manet_-_Le_Vieux_Musicien.jpg", 19867, 15029],
  "the-open-window": ["https://upload.wikimedia.org/wikipedia/commons/1/18/Fen%C3%AAtre_ouverte%2C_Collioure%2C_par_Henri_Matisse.jpg", 1608, 1927],
  "the-plum": ["https://upload.wikimedia.org/wikipedia/commons/5/5b/Edouard_Manet_-_The_Plum_-_National_Gallery_of_Art.jpg", 2675, 4000],
  "the-railway": ["https://upload.wikimedia.org/wikipedia/commons/7/74/Edouard_Manet_-_Le_Chemin_de_fer_-_Google_Art_Project.jpg", 11359, 9251],
  "the-raising-of-lazarus": ["https://upload.wikimedia.org/wikipedia/commons/5/59/Carel_Fabritius_-_Raising_of_Lazarus_%28John_11-41-44%29_-_M.Ob.563_-_National_Museum_in_Warsaw.jpg", 2669, 4000],
  "the-rhinoceros": ["https://upload.wikimedia.org/wikipedia/commons/9/95/Albrecht_D%C3%BCrer%2C_The_Rhinoceros%2C_1515%2C_NGA_47903.jpg", 4000, 3141],
  "the-voyage-of-life": ["https://upload.wikimedia.org/wikipedia/commons/8/89/Thomas_Cole_-_The_Voyage_of_Life_Childhood%2C_1842_%28National_Gallery_of_Art%29.jpg", 5121, 3459],
  "two-women-at-a-window": ["https://upload.wikimedia.org/wikipedia/commons/2/26/Bartolom%C3%A9_Esteban_Perez_Murillo_014.jpg", 17385, 20855],
  "vincent-van-gogh-self-portrait-2": ["https://upload.wikimedia.org/wikipedia/commons/1/18/Vincent_van_Gogh_-_Self-Portrait_-_Google_Art_Project_%28719161%29.jpg", 3571, 4633],
  "w-adys-aw-czachorski-dama-w-liliowej-sukni-z-kwiatami": ["https://upload.wikimedia.org/wikipedia/commons/b/b4/Czach%C3%B3rski_Lady_in_a_lilac_dress.jpg", 2395, 1666],
  "w-adys-aw-podkowinski-na-ace": ["https://upload.wikimedia.org/wikipedia/commons/0/08/W%C5%82adys%C5%82aw_Podkowi%C5%84ski_-_In_the_meadow_-_MP_4336_MNW_-_National_Museum_in_Warsaw.jpg", 2500, 1806],
  "w-adys-aw-podkowinski-portret-wincentyny-karskiej": ["https://upload.wikimedia.org/wikipedia/commons/e/eb/W%C5%82adys%C5%82aw_Podkowi%C5%84ski_-_Portrait_of_Wincentyna_Karska_-_MP_4645_-_National_Museum_in_Warsaw.jpg", 950, 2500],
  "w-adys-aw-podkowinski-sza-szkic": ["https://upload.wikimedia.org/wikipedia/commons/7/73/Podkowi%C5%84ski_Frenzy.png", 1432, 1796],
  "w-adys-aw-slewinski-cha-upy-w-sniegu": ["https://upload.wikimedia.org/wikipedia/commons/9/9f/W%C5%82adys%C5%82aw_%C5%9Alewi%C5%84ski_-_Cottages_in_the_snow_-_MP_111_MNW_-_National_Museum_in_Warsaw.jpg", 3000, 2065],
  "wac-aw-szymanowski-trzy-nimfy-nad-jeziorem-koncert": ["https://upload.wikimedia.org/wikipedia/commons/c/ca/Wac%C5%82aw_Szymanowski_-_Three_nymphs_at_the_lake_%E2%80%93_concert_-_MP_5016_-_National_Museum_in_Warsaw.jpg", 800, 546, "lowres"],
  "wac-aw-wasowicz-scena-w-lesie": ["https://upload.wikimedia.org/wikipedia/commons/8/8d/Wac%C5%82aw_W%C4%85sowicz_-_Scene_in_a_forest_-_MPW_3374_MNW_-_National_Museum_in_Warsaw.jpg", 800, 798, "lowres"],
  "watson-and-the-shark": ["https://upload.wikimedia.org/wikipedia/commons/a/a3/Watsonandtheshark-original.jpg", 9895, 7847],
  "willem-van-de-velde-the-younger-and-studio-after-the-storm": ["https://upload.wikimedia.org/wikipedia/commons/6/66/Willem_van_de_Velde_%28II%29_-_Voor_de_storm_%28NGA%29.jpg", 11691, 6872],
  "wincenty-kasprzycki-widok-morysinka-w-wilanowie": ["https://upload.wikimedia.org/wikipedia/commons/6/65/Kasprzycki_View_of_Morysin.jpg", 784, 547, "lowres"],
  "wincenty-kasprzycki-wystawa-sztuk-pieknych-w-warszawie-w-182": ["https://upload.wikimedia.org/wikipedia/commons/4/44/Wincenty_Kasprzycki%2C_Wystawa_Sztuk_Pi%C4%99knych_w_Warszawie_w_1828_roku.jpg", 2500, 2158],
  "witold-pruszkowski-unitka": ["https://upload.wikimedia.org/wikipedia/commons/6/6f/Witold_Pruszkowski_-_Uniate_woman_-_MP_926_MNW_-_National_Museum_in_Warsaw.jpg", 2500, 1779],
  "witold-pruszkowski-w-noc-swietojanska": ["https://upload.wikimedia.org/wikipedia/commons/2/2e/Pruszkowski_Fern_flower.jpg", 520, 779, "lowres"],
  "witold-wojtkiewicz-planty-w-krakowie": ["https://upload.wikimedia.org/wikipedia/commons/2/24/Witold_Wojtkiewicz_-_Planty_Park_in_Krak%C3%B3w_-_MP_778_MNW_-_National_Museum_in_Warsaw.jpg", 2500, 1661],
  "witold-wojtkiewicz-podmuchy-wiosenne": ["https://upload.wikimedia.org/wikipedia/commons/b/b6/Witold_Wojtkiewicz_-_Gusts_of_spring_-_Rys.Pol.5771_MNW_-_National_Museum_in_Warsaw.jpg", 3000, 2153],
  "wojciech-weiss-drzewa": ["https://upload.wikimedia.org/wikipedia/commons/9/91/Wojciech_Weiss_-_Trees_-_MP_217_MNW_-_National_Museum_in_Warsaw.jpg", 633, 800, "lowres"],
  "woman-holding-a-balance": ["https://upload.wikimedia.org/wikipedia/commons/6/68/Johannes_Vermeer_-_Woman_Holding_a_Balance_-_Google_Art_Project.jpg", 7201, 8143],
};
