// build-hunt.js — THE HUNT INDEX (2026-08-26, Fuad's design: "the real hunt is over the
// text"). Mines OUR OWN prose — tours (art_inspect) + reads (art-about) — for per-work
// hunt terms: time-of-day, weather, season, water, setting, figures, motifs. HUMAN PROSE
// ONLY, by ruling; coverage grows by completing tours/reads, never by machine text.
// Deterministic: re-run after any reads/tours apply → art_hunt.js re-emits.
//   node build-hunt.js
// Negation guard: a term within 3 words of no/not/never/without/nothing/nor doesn't count.
// The facet lexicon below is the LOOSE seed (Fuad: converge later) — edit here, re-run.
const fs = require('fs');
const path = require('path');

function parse(p, name) { const w = {}; new Function('window', fs.readFileSync(p, 'utf8'))(w); return w[name]; }
const IN = parse(path.join(__dirname, 'art_inspect.js'), 'CANVAS_INSPECT');
const AB = parse(path.join(__dirname, 'art-about.js'), 'CANVAS_ART_ABOUT');

const FACETS = {
  time: ['night', 'dusk', 'twilight', 'dawn', 'sunrise', 'sunset', 'moonlight', 'moonlit', 'midday', 'noon', 'evening', 'morning', 'nocturne'],
  weather: ['snow', 'rain', 'fog', 'mist', 'storm', 'wind', 'frost', 'ice', 'overcast', 'sunlight', 'sunlit', 'heat'],
  season: ['winter', 'spring', 'summer', 'autumn', 'harvest'],
  water: ['sea', 'river', 'harbour', 'harbor', 'canal', 'pond', 'lake', 'wave', 'beach', 'shore', 'regatta', 'boat', 'ship', 'sail'],
  setting: ['interior', 'bedroom', 'kitchen', 'studio', 'garden', 'orchard', 'forest', 'field', 'meadow', 'mountain', 'cliff', 'street', 'city', 'village', 'church', 'cathedral', 'cafe', 'theatre', 'window', 'doorway', 'bridge', 'path'],
  figures: ['nude', 'self-portrait', 'crowd', 'child', 'mother', 'lovers', 'dancer', 'reading', 'sleeping', 'bather', 'peasant', 'worker', 'soldier', 'musician'],
  motif: ['mirror', 'candle', 'lamp', 'bouquet', 'skull', 'horse', 'dog', 'cat', 'bird', 'swan', 'umbrella', 'parasol', 'letter', 'book', 'train', 'smoke', 'haystack', 'poppy', 'lily', 'iris', 'sunflower', 'wheat', 'moon', 'reflection'],
};
const NEG = /\b(no|not|never|without|nothing|nor)\b/;

const ids = new Set([...Object.keys(IN), ...Object.keys(AB)]);
const index = {};
let terms = 0;
for (const id of ids) {
  const parts = [];
  const t = IN[id];
  if (t) parts.push(t.see, t.about, t.craft, t.context, t.beside, ...(t.deeper || []).map(c => (c.t || '') + ' ' + (c.body || '')));
  const r = AB[id];
  if (r) parts.push(typeof r === 'string' ? r : (r.about || '') + ' ' + (r.deep || ''));
  const words = parts.filter(Boolean).join(' ').toLowerCase().split(/[^a-z-]+/);
  const hits = [];
  for (const [facet, list] of Object.entries(FACETS)) {
    for (const term of list) {
      for (let i = 0; i < words.length; i++) {
        if (words[i] !== term && words[i] !== term + 's') continue;
        if (NEG.test(words.slice(Math.max(0, i - 3), i).join(' '))) continue;
        hits.push(facet + ':' + term);
        break;
      }
    }
  }
  if (hits.length) { index[id] = hits; terms += hits.length; }
}
const out = '// GENERATED by build-hunt.js — per-work hunt terms mined from the tours/reads prose.\n' +
  '// Human prose only (Fuad 2026-08-26); re-run build-hunt.js after any reads apply.\n' +
  'window.CANVAS_HUNT = ' + JSON.stringify(index) + ';\n';
fs.writeFileSync(path.join(__dirname, 'art_hunt.js'), out, 'utf8');
console.log(`art_hunt.js written — ${Object.keys(index).length} works · ${terms} terms · ${(out.length / 1024).toFixed(0)} KB`);
