# extract-palette.py — dominant colours per artwork (Phase 5). Downloads each work's grid
# thumb from Commons (240px is plenty), quantizes with PIL, writes palette.js keyed by
# canvas work id: 4 hex swatches, dominant first. Cache-committed (palette_cache.json).
#   python extract-palette.py
import json, re, io, time, urllib.request, os, subprocess

HERE = os.path.dirname(os.path.abspath(__file__))
UA = {"User-Agent": "fuad.au-canvas/0.1 (https://fuad.au; fuadex@gmail.com)"}
CACHE = os.path.join(HERE, "palette_cache.json")

# read art_data.js via node (single source of truth for parsing)
raw = subprocess.check_output([
    "node", "-e",
    "const vm=require('vm'),fs=require('fs');const c={window:{}};vm.createContext(c);"
    "vm.runInContext(fs.readFileSync('art_data.js','utf8'),c);"
    "console.log(JSON.stringify(Object.fromEntries(Object.entries(c.window.CANVAS_ART_DATA.artworks)"
    ".filter(([k,v])=>v.imgGrid).map(([k,v])=>[k,v.imgGrid]))))"
], cwd=HERE, text=True)
works = json.loads(raw)

cache = {}
if os.path.exists(CACHE):
    cache = json.load(open(CACHE, encoding="utf-8"))

from PIL import Image
def palette_of(url):
    small = re.sub(r"width=\d+", "width=240", url)
    req = urllib.request.Request(small, headers=UA)
    img = Image.open(io.BytesIO(urllib.request.urlopen(req, timeout=30).read())).convert("RGB")
    q = img.quantize(colors=5, method=Image.Quantize.MEDIANCUT)
    pal = q.getpalette()[:15]
    counts = sorted(q.getcolors(), reverse=True)  # (count, index)
    out = []
    for _, idx in counts[:4]:
        r, g, b = pal[idx*3:idx*3+3]
        out.append("#%02x%02x%02x" % (r, g, b))
    return out

done, fail = 0, 0
for wid, url in works.items():
    if wid in cache:
        continue
    try:
        cache[wid] = palette_of(url)
        done += 1
        if done % 20 == 0:
            json.dump(cache, open(CACHE, "w"), indent=0)
            print(f"  {done} palettes…", flush=True)
        time.sleep(0.15)
    except Exception as e:
        fail += 1
        print("  fail", wid, str(e)[:60], flush=True)
json.dump(cache, open(CACHE, "w"), indent=0)

header = ("// GENERATED by extract-palette.py — dominant colours per work (PIL mediancut on the\n"
          "// Commons grid thumb). Do not hand-edit.\n")
with open(os.path.join(HERE, "palette.js"), "w", encoding="utf-8") as f:
    f.write(header + "window.CANVAS_PALETTE = " + json.dumps(cache) + ";\n")
print(f"palette.js written: {len(cache)} works ({done} new, {fail} failed)")
