// fetch-imgsize.js — TRUE pixel dimensions of every work's Commons image, written to
// art_imgsize.js as { <work id>: [width, height] }.
//
// Why this matters: art_data.js serves three derived urls off one Commons file —
//   imgGrid  ?width=480      imgMain ?width=900      imgZoom ?width=2000
// Commons DOES NOT UPSCALE. If the source file is 700px wide, "?width=2000" quietly returns the
// 700px original and the browser stretches it. Nothing in the data said how big the original is,
// so a work could look fine on the Wall and be mush in Study mode with no way to tell in advance.
// This pass asks Commons directly (keyless, 50 titles per call) and records the real size.
//
//   node fetch-imgsize.js            (resumable; cache in imgsize_cache.json)
//
// Bands, chosen against how the app actually renders:
//   poor  < 900   — cannot even fill the main card honestly; zoom is fiction
//   thin  < 2000  — fine on the Wall, upscaled in Study/zoom
//   good  >= 2000 — every derived size is real
const fs = require("fs"), path = require("path");
const HERE = __dirname;
const UA = { "User-Agent": "fuad.au-canvas/0.1 (https://fuad.au; fuadex@gmail.com)" };
const CACHE = path.join(HERE, "imgsize_cache.json");
const load = (f, fb) => { try { return JSON.parse(fs.readFileSync(f, "utf8")); } catch (e) { return fb; } };
const cache = load(CACHE, {});          // Commons file name -> [w, h] | null

const g = {};
new Function("window", fs.readFileSync(path.join(HERE, "artworks.js"), "utf8") + "\nreturn window;")(g);
new Function("window", fs.readFileSync(path.join(HERE, "art_data.js"), "utf8") + "\nreturn window;")(g);
const WORKS = g.CANVAS_ARTWORKS;
const AD = g.CANVAS_ART_DATA.artworks;

// Special:FilePath/<urlencoded file name>?width=N  ->  the bare Commons file name
const fileOf = (url) => {
  if (!url) return null;
  const m = String(url).match(/Special:FilePath\/([^?]+)/);
  if (!m) return null;
  try { return decodeURIComponent(m[1]).replace(/_/g, " "); } catch (e) { return m[1].replace(/_/g, " "); }
};

const byFile = new Map();               // file name -> [work ids]
for (const w of WORKS) {
  const f = fileOf(AD[w.id] && AD[w.id].img);
  if (!f) continue;
  if (!byFile.has(f)) byFile.set(f, []);
  byFile.get(f).push(w.id);
}
const todo = [...byFile.keys()].filter(f => !(f in cache));
console.log(`${WORKS.length} works · ${byFile.size} distinct Commons files · ${todo.length} to measure · ${Object.keys(cache).length} cached`);

const sleep = (ms) => new Promise(r => setTimeout(r, ms));
async function api(url) {
  for (let attempt = 0; attempt < 6; attempt++) {
    const res = await fetch(url, { headers: UA });
    const body = await res.text();
    await sleep(250);
    if (res.ok && body[0] === "{") { try { return JSON.parse(body); } catch (e) {} }
    const wait = 2000 * Math.pow(2, attempt);
    console.log(`  ⏳ ${res.status} throttled — backing off ${wait / 1000}s`);
    await sleep(wait);
  }
  throw new Error("Commons refused after 6 attempts");
}

(async () => {
  for (let i = 0; i < todo.length; i += 50) {
    const batch = todo.slice(i, i + 50);
    const titles = batch.map(f => "File:" + f).join("|");
    const j = await api("https://commons.wikimedia.org/w/api.php?action=query&format=json&prop=imageinfo&iiprop=size&titles=" + encodeURIComponent(titles));
    // the API normalises titles, so map results back by their returned title, not by index
    const pages = (j.query && j.query.pages) || {};
    const got = {};
    for (const p of Object.values(pages)) {
      const ii = p.imageinfo && p.imageinfo[0];
      if (ii && ii.width) got[String(p.title).replace(/^File:/, "")] = [ii.width, ii.height];
    }
    for (const f of batch) cache[f] = got[f] || null;
    fs.writeFileSync(CACHE, JSON.stringify(cache));
    console.log(`  ${Math.min(i + 50, todo.length)}/${todo.length}`);
  }

  const out = {};
  for (const [f, ids] of byFile) { const d = cache[f]; if (d) for (const id of ids) out[id] = d; }
  fs.writeFileSync(path.join(HERE, "art_imgsize.js"),
    "// GENERATED by fetch-imgsize.js — TRUE pixel size of each work's Commons source file.\n" +
    "// { <work id>: [width, height] }   Commons never upscales: a ?width=2000 request against a\n" +
    "// 700px original returns 700px. Use this to know when zoom is real.\n" +
    "window.CANVAS_IMGSIZE = " + JSON.stringify(out) + ";\n", "utf8");

  const band = (w) => w < 900 ? "poor" : w < 2000 ? "thin" : "good";
  const tally = { poor: 0, thin: 0, good: 0 };
  const poor = [];
  for (const w of WORKS) {
    const d = out[w.id]; if (!d) continue;
    tally[band(d[0])]++;
    if (d[0] < 900) poor.push({ w, d });
  }
  const measured = Object.keys(out).length;
  console.log(`\nmeasured ${measured} works · unmeasured ${WORKS.length - measured}`);
  console.log(`good (>=2000px): ${tally.good}   thin (<2000, zoom upscales): ${tally.thin}   poor (<900, card upscales): ${tally.poor}`);

  // what the site currently claims vs what it can deliver
  console.log(`\nworks whose Study/zoom (?width=2000) is silently upscaled: ${tally.thin + tally.poor}`);
  const inspect = {};
  try { new Function("window", fs.readFileSync(path.join(HERE, "art_inspect.js"), "utf8") + "\nreturn window;")(inspect); } catch (e) {}
  const TOURS = inspect.CANVAS_INSPECT || {};
  const hires = {};
  try { new Function("window", fs.readFileSync(path.join(HERE, "art_hires.js"), "utf8") + "\nreturn window;")(hires); } catch (e) {}
  const HI = hires.CANVAS_HIRES || {};
  // A work with a CANVAS_HIRES entry serves its zoom from the MUSEUM's IIIF tile source, not from
  // the Commons file measured here — so a thin Commons number says nothing about its tour. Szał
  // uniesień reads 600px here and tours off MNK's high-res scan quite happily.
  const touredThin = WORKS.filter(w => TOURS[w.id] && out[w.id] && out[w.id][0] < 2000 && !HI[w.id]);
  const shielded = WORKS.filter(w => TOURS[w.id] && out[w.id] && out[w.id][0] < 2000 && HI[w.id]);
  if (shielded.length) console.log(`(${shielded.length} more are thin on Commons but serve zoom from a museum hires source — not a problem: ${shielded.map(w => w.id).join(", ")})`);
  console.log(`of those, ${touredThin.length} carry a STUDY TOUR with no hires source — anchored crop boxes on an image that cannot support the zoom:`);
  touredThin.sort((a, b) => out[a.id][0] - out[b.id][0]).slice(0, 25)
    .forEach(w => console.log(`  ${String(out[w.id][0]).padStart(5)}px  ${w.title.slice(0, 52)} — ${w.artist}`));

  if (poor.length) {
    console.log(`\nworst offenders (<900px source):`);
    poor.sort((a, b) => a.d[0] - b.d[0]).slice(0, 20)
      .forEach(({ w, d }) => console.log(`  ${String(d[0]).padStart(5)}x${String(d[1]).padEnd(5)}  ${w.title.slice(0, 48)} — ${w.artist}`));
  }
})();
