// fetch-medium.js — per-artwork MEDIUM (what kind of object it is) from Wikidata P31
// (instance of), resolved to a small controlled vocabulary and written to art_medium.js as
// { <canvas work id>: "<medium>" }.
//
// Why: the Wall wanted a painting/sculpture/etc filter and nothing in the data supported it —
// art_data's `desc` yields a usable type for only ~10 of 645 works (the rest are empty or
// "(trusted deck qid)"). P31 is the real signal.
//
//   node fetch-medium.js            (resumable; cache-committed in medium_cache.json)
//
// Batches 45 qids per wbgetentities call, ~350ms apart. Anything whose P31 does not map to the
// vocabulary is written to the cache as its raw qid list so a later pass can widen the map
// rather than silently guessing.
const fs = require("fs"), path = require("path");
const HERE = __dirname;
const UA = { "User-Agent": "fuad.au-canvas/0.1 (https://fuad.au; fuadex@gmail.com)" };
const CACHE = path.join(HERE, "medium_cache.json");

// P31 qid -> medium label. Deliberately coarse: this feeds a filter, not a catalogue.
const MAP = {
  Q3305213: "painting", Q1028181: "painting",           // painting / painter's work
  Q93184: "drawing", Q11060274: "print", Q18219090: "print", Q11835431: "print",
  Q15123870: "lithograph", Q18761202: "etching", Q133067: "engraving",
  Q860861: "sculpture", Q179700: "sculpture", Q1400264: "sculpture",  // sculpture / statue
  Q125191: "photograph", Q13333778: "photograph",
  Q219423: "mural", Q22669139: "fresco", Q133067b: "relief",
  Q2264296: "installation", Q20437094: "installation",
  Q184296: "tapestry", Q131557: "mosaic", Q48498: "altarpiece",
  Q87167: "manuscript", Q213283: "manuscript",
  Q10855061: "artefact", Q220659: "artefact", Q17489160: "artefact",
  Q11642: "vase", Q1063071: "ceramic",
  Q11424: "film", Q20937557: "video",
  Q7748: "specimen", Q7377: "specimen",                  // natural-history objects
  Q4989906: "monument", Q811979: "structure",
};

const load = (f, fb) => { try { return JSON.parse(fs.readFileSync(f, "utf8")); } catch (e) { return fb; } };
const cache = load(CACHE, {});

// canon rows via node (single source of truth for parsing)
const w = {};
new Function("window", fs.readFileSync(path.join(HERE, "artworks.js"), "utf8") + "\nreturn window;")(w);
const WORKS = w.CANVAS_ARTWORKS;
const todo = WORKS.filter(x => x.qid && !(x.qid in cache)).map(x => x.qid);
const uniq = [...new Set(todo)];
console.log(`${WORKS.length} works · ${uniq.length} qids to fetch · ${Object.keys(cache).length} cached`);

const sleep = (ms) => new Promise(r => setTimeout(r, ms));
(async () => {
  for (let i = 0; i < uniq.length; i += 45) {
    const batch = uniq.slice(i, i + 45);
    const url = "https://www.wikidata.org/w/api.php?action=wbgetentities&props=claims&format=json&ids=" + batch.join("|");
    try {
      const j = await (await fetch(url, { headers: UA })).json();
      for (const qid of batch) {
        const ent = j.entities && j.entities[qid];
        const claims = (ent && ent.claims && ent.claims.P31) || [];
        const qids = claims.map(c => c.mainsnak && c.mainsnak.datavalue && c.mainsnak.datavalue.value && c.mainsnak.datavalue.value.id).filter(Boolean);
        const hit = qids.map(q => MAP[q]).find(Boolean) || null;
        cache[qid] = hit || { unmapped: qids };   // keep the raw ids when unmapped — never guess
      }
      fs.writeFileSync(CACHE, JSON.stringify(cache));
      console.log(`  ${Math.min(i + 45, uniq.length)}/${uniq.length}`);
    } catch (e) { console.log("  batch failed at " + i + ": " + String(e).slice(0, 80)); }
    await sleep(350);
  }

  const out = {};
  let mapped = 0, unmapped = 0;
  for (const wk of WORKS) {
    const v = wk.qid ? cache[wk.qid] : null;
    if (typeof v === "string") { out[wk.id] = v; mapped++; }
    else if (v) unmapped++;
  }
  fs.writeFileSync(path.join(HERE, "art_medium.js"),
    "// GENERATED by fetch-medium.js — per-work medium from Wikidata P31 (instance of).\n" +
    "// { <work id>: \"painting\" | \"sculpture\" | ... }  Unmapped P31s stay in medium_cache.json.\n" +
    "window.CANVAS_MEDIUM = " + JSON.stringify(out) + ";\n", "utf8");

  const tally = {};
  for (const v of Object.values(out)) tally[v] = (tally[v] || 0) + 1;
  console.log("mapped:", mapped, "| unmapped P31:", unmapped, "| no qid:", WORKS.filter(x => !x.qid).length);
  console.log(Object.entries(tally).sort((a, b) => b[1] - a[1]).map(r => r[0] + ":" + r[1]).join("  "));
})();
