// museums.js — hand-authored: museums/galleries Fuad has visited (Phase 0 seed).
// Approximate dates are legitimate data: "~2019" = about then; "TBC" = known visit,
// date to pin down. kind: art | natural-history. See memory-seed.md for the reasoning.
// ⚠ QIDs are drafted from memory — the Phase 1 Wikidata fetcher must RESOLVE BY NAME+CITY
// and verify/correct every qid before anything trusts them.
window.CANVAS_MUSEUMS = [
  { id: "artizon",        name: "Artizon Museum",                    city: "Tokyo",        country: "jp", qid: "Q913808",  kind: "art", visits: ["2026-03-24"],  note: "Big Monet/impressionist holdings (Ishibashi collection)." },
  { id: "tokyo-met",      name: "Tokyo Metropolitan Art Museum",     city: "Tokyo",        country: "jp", qid: "Q864957",  kind: "art", visits: ["2026-01-28","2026-02-15"],  note: "Swedish Masters exhibition (the Fjæstad wood-pattern painting — floored)." },
  { id: "nga-dc",         name: "National Gallery of Art",           city: "Washington DC", country: "us", qid: "Q214867",  kind: "art", visits: ["TBC"],  note: "Woman with a Parasol." },
  { id: "met-nyc",        name: "The Metropolitan Museum of Art",    city: "New York",     country: "us", qid: "Q160236",   kind: "art", visits: ["2019-02-27"] },
  { id: "amnh",           name: "American Museum of Natural History", city: "New York",    country: "us", qid: "Q217717",   kind: "natural-history", visits: ["2019-03-20"], note: "Best museum ever visited, by far — and only ~2 bottom floors seen." },
  { id: "orsay",          name: "Musée d'Orsay",                     city: "Paris",        country: "fr", qid: "Q23402",    kind: "art", visits: ["2017-01-15","2023-09-06","2023-09-22","2024"], note: "Several visits; the impressionist core." },
  { id: "orangerie",      name: "Musée de l'Orangerie",              city: "Paris",        country: "fr", qid: "Q726781",  kind: "art", visits: ["2023-09-06"],  note: "The Nymphéas rooms." },
  { id: "marmottan",      name: "Musée Marmottan Monet",             city: "Paris",        country: "fr", qid: "Q1327886",  kind: "art", visits: ["2023-09-24"],  note: "\"Monet's museum\" — Water Lilies seen here too." },
  { id: "pompidou",       name: "Centre Pompidou",                   city: "Paris",        country: "fr", qid: "Q178065",   kind: "art", visits: ["2017-01-14","2023-09-06"],  note: "\"The factory\" — some good works, TBC which." },
  { id: "rodin",          name: "Musée Rodin",                       city: "Paris",        country: "fr", qid: "Q650519",  kind: "art", visits: ["2023-09-22"],  note: "CONFIRMED — \"probably the best sculptures\"; Rodin best with expressions. (Bourdelle rated good too — did a Musée Bourdelle visit also happen? TBC.)" },
  { id: "ngi",            name: "National Gallery of Ireland",       city: "Dublin",       country: "ie", qid: "Q2018379",  kind: "art", visits: ["~2017-03"],  note: "Leech: The Sunshade + A Convent Garden, Brittany." },
  { id: "tate-modern",    name: "Tate Modern",                       city: "London",       country: "gb", qid: "Q193375",   kind: "art", visits: ["2024","2026-06-17"],  note: "Pollocks remembered." },
  { id: "belvedere",      name: "Upper Belvedere",            searchAs: "Österreichische Galerie Belvedere",                   city: "Vienna",       country: "at", qid: "Q303139",   kind: "art", visits: ["2017-06-20"], note: "The Kiss (probably) + more golden Klimts — venue near-confirmed by that combination." },
  { id: "mnw",            name: "Muzeum Narodowe w Warszawie",       city: "Warsaw",       country: "pl", qid: "Q153306",   kind: "art", visits: ["2014 (frequent)","2017","2019-08-01","2022-12-27","2023-09-20","2024 (4 visits)"] },
  { id: "sukiennice",     name: "Sukiennice Gallery (MNK)",          searchAs: "Sukiennice Museum", city: "Kraków", country: "pl", qid: "Q7635861", kind: "art", visits: ["2014-04-27","2015-07-07"],  note: "Gallery of 19th-C Polish Art — Szał uniesień hangs here." },
  { id: "nationalmuseum", name: "Nationalmuseum",                    city: "Stockholm",    country: "se", qid: "Q842858",   kind: "art", visits: ["2026-04-16"],  note: "Sergel CONFIRMED — sculptures + the unbelievable drawings." },
  { id: "harvard-art",    name: "Harvard Art Museums",               city: "Cambridge, MA", country: "us", qid: "Q3783572",  kind: "art", visits: ["TBC"], note: "Deck-only for now — grading the pageview-ranked majors (API pull 2026-07-13)." },
  // ——— Australia (visited; verdict \"only ok, at times even less\" — no works recalled yet) ———
  { id: "agnsw",          name: "Art Gallery of New South Wales",    city: "Sydney",       country: "au", qid: "Q705551",   kind: "art", visits: ["2014-2025 (45 visits)"] },
  { id: "ngv",            name: "National Gallery of Victoria",      city: "Melbourne",    country: "au", qid: "Q1464509",  kind: "art", visits: ["2020-12-20","2021-05-01"] },
  { id: "nga-canberra",   name: "National Gallery of Australia",     city: "Canberra",     country: "au", qid: "Q795228",   kind: "art", visits: ["2020-10-22"] },
  { id: "npg-canberra",   name: "National Portrait Gallery",         city: "Canberra",     country: "au", qid: "Q1489633",  kind: "art", visits: ["2020-10-22"],  note: "\"Canberra's two galleries\" — assumed NGA + NPG; correct if it was a different pair." },
  // ——— The Beksiński trail (seen in person, three venues) ———
  // noResolve on both Beksiński venues: neither gallery has its own Wikidata item, so fetch-art's
  // name search drifts to whatever matches loosely — it once resolved czestochowa-mgs to Galeria
  // Extravagance in Sosnowiec (QC 2026-08-22). Their art_data records are hand-placed; keep them.
  { id: "beksinski-krakow", name: "Galeria Zdzisława Beksińskiego", city: "Kraków",  country: "pl", qid: null,       kind: "art", noResolve: true, visits: ["TBC"],  note: "Confirmed by Fuad 2026-08-22 — the permanent gallery inside Nowohuckie Centrum Kultury, open since October 2016, showing the Dmochowski collection. The earlier TBC guess at NCK was right." },
  // Warsaw-Praga is deliberately NOT a venue entry (Fuad 2026-08-22: "not a museum"). It was a
  // temporary Beksiński show, and a one-off exhibition is an event rather than an institution —
  // listing it put a place on the Museums index that you cannot go to. The encounter is kept on
  // the work itself, which is what `via: "exhibition"` exists for.
  { id: "czestochowa-mgs",  name: "Miejska Galeria Sztuki (Beksiński collection)", city: "Częstochowa", country: "pl", qid: null, kind: "art", noResolve: true, visits: ["TBC"], note: "Permanent Beksiński museum room." },
  // ——— additions ———
  { id: "van-gogh-museum", name: "Van Gogh Museum", city: "Amsterdam", country: "nl", qid: "Q224124", kind: "art", visits: ["2016-08-08"] },
  { id: "kunsthaus-zurich", name: "Kunsthaus Zürich", city: "Zurich", country: "ch", qid: "Q685038", kind: "art", visits: ["2017-12-06"] },
  { id: "museum-ludwig", name: "Museum Ludwig", city: "Cologne", country: "de", qid: "Q703640", kind: "art", visits: ["2018-11-17"] },
  { id: "stadel", name: "Städel Museum", city: "Frankfurt", country: "de", qid: "Q163804", kind: "art", visits: ["2019-05-29"] },
  { id: "guggenheim", name: "Solomon R. Guggenheim Museum", city: "New York", country: "us", qid: "Q201469", kind: "art", visits: ["2019-03-16"] },
  { id: "frick", name: "The Frick Collection", city: "New York", country: "us", qid: "Q682827", kind: "art", visits: ["2019-03-20"] },
  { id: "cloisters", name: "The Cloisters", city: "New York", country: "us", qid: "Q1138030", kind: "art", visits: ["2019-03-18"] },
  { id: "whitney", name: "Whitney Museum of American Art", city: "New York", country: "us", qid: "Q639791", kind: "art", visits: ["2019-03-22"] },
  { id: "montreal-mfa", name: "Montreal Museum of Fine Arts", city: "Montreal", country: "ca", qid: "Q860812", kind: "art", visits: ["2019-05-22"] },
  { id: "moma", name: "Museum of Modern Art", city: "New York", country: "us", qid: "Q188740", kind: "art", visits: ["2019-01-24"] },
  { id: "national-gallery-london", name: "National Gallery", city: "London", country: "gb", qid: "Q180788", kind: "art", visits: ["2017-03-19", "2024"] },
  { id: "british-museum", name: "British Museum", city: "London", country: "gb", qid: "Q6373", kind: "art", visits: ["2024"] },
  { id: "soane", name: "Sir John Soane's Museum", city: "London", country: "gb", qid: "Q2060860", kind: "art", visits: ["2024"] },
  { id: "mam-paris", name: "Musée d'Art Moderne de Paris", city: "Paris", country: "fr", qid: "Q857276", kind: "art", visits: ["TBC"] },
  { id: "petit-palais", name: "Petit Palais (Musée des Beaux-Arts de la Ville de Paris)", city: "Paris", country: "fr", qid: "Q59546080", kind: "art", visits: ["TBC"] },
  { id: "bourdelle", name: "Musée Bourdelle", city: "Paris", country: "fr", qid: "Q2715373", kind: "art", visits: ["TBC"] },
  { id: "getty-villa", name: "Getty Villa", city: "Los Angeles", country: "us", qid: "Q180401", kind: "art", visits: ["2025"] },
  { id: "haus-der-kunst", name: "Haus der Kunst", city: "Munich", country: "de", qid: "Q697782", kind: "art", visits: ["TBC"] },
  { id: "reina-sofia", name: "Museo Reina Sofía", city: "Madrid", country: "es", qid: "Q460889", kind: "art", visits: ["TBC"] },
  { id: "scrovegni", name: "Scrovegni Chapel", city: "Padua", country: "it", qid: "Q963954", kind: "art", visits: ["2025"] },
  { id: "mori", name: "Mori Art Museum", city: "Tokyo", country: "jp", qid: "Q4410434", kind: "art", visits: ["TBC"] },
  { id: "yamatane", name: "Yamatane Museum of Art", city: "Tokyo", country: "jp", qid: "Q3329572", kind: "art", visits: ["TBC"] },
  { id: "hokusai-museum", name: "Sumida Hokusai Museum", city: "Tokyo", country: "jp", qid: "Q17220332", kind: "art", visits: ["2026-03-02"] },
  { id: "agsa", name: "Art Gallery of South Australia", city: "Adelaide", country: "au", qid: "Q705557", kind: "art", visits: ["2020-11-13"] },
  { id: "kunstmuseum-stuttgart", name: "Kunstmuseum Stuttgart", city: "Stuttgart", country: "de", qid: "Q317398", kind: "art", visits: ["2026-05-05"] },
  { id: "brandhorst", name: "Museum Brandhorst", city: "Munich", country: "de", qid: "Q258597", kind: "art", visits: ["2017-06-22"] },
  { id: "kunstpalast", name: "Museum Kunstpalast", city: "Düsseldorf", country: "de", qid: "Q461277", kind: "art", visits: ["2018-11-14"] },
  { id: "kunsthauswien", name: "KunstHausWien", city: "Vienna", country: "at", qid: "Q638493", kind: "art", visits: ["2017-06-20"] },
  { id: "acropolis", name: "Acropolis Museum", city: "Athens", country: "gr", qid: "Q421084", kind: "art", visits: ["2018-11-13"] },
  { id: "pergamon", name: "Pergamonmuseum", city: "Berlin", country: "de", qid: "Q157298", kind: "art", visits: ["2022-12-23"] },
  { id: "neues-museum", name: "Neues Museum", city: "Berlin", country: "de", qid: "Q157316", kind: "art", visits: ["TBC (long ago — Fuad confirmed)"] },
  { id: "altes-museum", name: "Altes Museum", city: "Berlin", country: "de", qid: "Q156722", kind: "art", visits: ["TBC (long ago — Fuad confirmed)"] },
  { id: "bode-museum", name: "Bode-Museum", city: "Berlin", country: "de", qid: "Q157825", kind: "art", visits: ["TBC"], note: "Fuad: 'I don't remember. Maybe?' — unconfirmed." },
  { id: "alte-pinakothek", name: "Alte Pinakothek", city: "Munich", country: "de", qid: "Q154568", kind: "art", visits: ["TBC (Munich 2016–17 era)"] },
  { id: "neue-pinakothek", name: "Neue Pinakothek", city: "Munich", country: "de", qid: "Q170152", kind: "art", visits: ["TBC (Munich 2016–17 era)"], note: "Fuad: 'the Pinakotheks' — der Moderne possibly too, unconfirmed." },
  { id: "nmk-seoul", name: "National Museum of Korea", city: "Seoul", country: "kr", qid: "Q494407", kind: "art", visits: ["2018-07-29"] },
  // ——— additions round 2 ———
  { id: "alte-nationalgalerie", name: "Alte Nationalgalerie", city: "Berlin", country: "de", qid: "Q162111", kind: "art", visits: ["2022-12-23"], note: "Museum Island — same trip as Islamische Kunst." },
  { id: "aegyptischer-kunst", name: "Staatliches Museum Ägyptischer Kunst", city: "Munich", country: "de", qid: "Q464872", kind: "art", visits: ["2016-09-10","2016-10-12","2017-07-06"] },
  { id: "tate-britain", name: "Tate Britain", city: "London", country: "gb", qid: "Q195436", kind: "art", visits: ["2024"], note: "Same day as Tate Modern." },
  { id: "nhm-london", name: "Natural History Museum", city: "London", country: "gb", qid: "Q309388", kind: "natural-history", visits: ["2024"] },
  { id: "mnk-main", name: "Muzeum Narodowe w Krakowie (Main Building)", city: "Kraków", country: "pl", qid: "Q195311", kind: "art", visits: ["2014-04-26"], note: "Day before Sukiennice." },
  { id: "coca-torun", name: "Centre of Contemporary Art Znaki Czasu", city: "Toruń", country: "pl", qid: "Q9186485", kind: "art", visits: ["2026-05-23"] },
  {id: "kunstmuseum-basel",name: "Kunstmuseum Basel",city: "Basel",country: "ch",qid: "Q194626",kind: "art",visits: ["2017-08-05"],note: ""},
  {id: "kunstsalon-franke-schenk",name: "Kunstsalon Franke-Schenk",city: "Altstadt-Lehel",country: "de",qid: "Q15428775",kind: "art",visits: ["2017-03-25"],note: ""},
  {id: "bavarian-state-paintings",name: "Bavarian State Painting Collections",city: "Munich",country: "de",qid: "Q812285",kind: "art",visits: ["2016-10-15","2016-11-27"],note: ""},
  {id: "lenbachhaus",name: "Lenbachhaus",city: "Munich",country: "de",qid: "Q262234",kind: "art",visits: ["2016-10-15"],note: ""},
  {id: "museo-fortuny",name: "Museo Fortuny",city: "Venice",country: "it",qid: "Q616676",kind: "art",visits: ["TBC"],note: ""},
  {id: "new-york-historical",name: "New York Historical",city: "New York",country: "us",qid: "Q1059456",kind: "art",visits: ["TBC"],note: ""},
  {id: "royal-castle-warsaw",name: "Zamek Królewski w Warszawie (Royal Castle)",city: "Warsaw",country: "pl",qid: "Q756098",kind: "art",visits: ["TBC"],note: ""},
  {id: "npg-london",name: "National Portrait Gallery",city: "London",country: "gb",qid: "Q238587",kind: "art",visits: ["2024"],note: ""},
  {id: "louvre",name: "Louvre Museum",city: "Paris",country: "fr",qid: "Q19675",kind: "art",visits: ["2024"],note: ""},
  {id: "v-and-a",name: "Victoria and Albert Museum",city: "London",country: "gb",qid: "Q213322",kind: "art",visits: ["2024"],note: ""},
  {id: "science-museum",name: "Science Museum",city: "London",country: "gb",qid: "Q674773",kind: "art",visits: ["2024"],note: ""},
  {id: "neue-kunst-karlsruhe",name: "Museum für Neue Kunst Karlsruhe",city: "Karlsruhe",country: "de",qid: "Q1495745",kind: "art",visits: ["2026-05-07"],note: ""},
  {id: "tubingen-antiquities",name: "Collection of antique and post-antique coins and medals of the Institute of Classical Archaeology, University of Tübingen",city: "Tübingen",country: "de",qid: "Q76632158",kind: "art",visits: ["2026-05-06"],note: ""},
  {id: "warsaw-old-town-centre",name: "Warsaw's Old Town Heritage Interpretation Center",city: "Warsaw",country: "pl",qid: "Q11689613",kind: "art",visits: ["2023-01-04"],note: ""},
  {id: "aus-performing-arts",name: "Australian Performing Arts Collection",city: "Melbourne",country: "au",qid: "Q7168281",kind: "art",visits: ["2024-05-01"],note: ""},
  {id: "ycba",name: "Yale Center for British Art",city: "New Haven",country: "us",qid: "Q6352575",kind: "art",visits: [],lat: 41.307908,lng: -72.930906,note: "The Mellon Turner/Constable mass — 21 wish works resolve here."},
  {id: "mfa-boston",name: "Museum of Fine Arts Boston",city: "Boston",country: "us",qid: "Q49133",kind: "art",visits: [],lat: 42.339444444444446,lng: -71.09416666666667,note: "Not visited — holds wish works (added 2026-08-27)."},
  {id: "pushkin-moscow",name: "Pushkin Museum of Fine Arts",city: "Moscow",country: "ru",qid: "Q4872",kind: "art",visits: [],lat: 55.74702868,lng: 37.60602901,note: "Not visited — holds wish works (added 2026-08-27)."},
  {id: "nasjonalmuseet-oslo",name: "Nasjonalmuseet",city: "Oslo",country: "no",qid: "Q1132918",kind: "art",visits: [],lat: 59.91166666666667,lng: 10.729166666666666,note: "Not visited — holds wish works (added 2026-08-27)."},
  {id: "getty-center",name: "J. Paul Getty Museum",city: "Los Angeles",country: "us",qid: "Q731126",kind: "art",visits: [],lat: 34.0775,lng: -118.475,note: "Not visited — holds wish works (added 2026-08-27)."},
  {id: "kroller-muller",name: "Kröller-Müller Museum",city: "Otterlo",country: "nl",qid: "Q1051928",kind: "art",visits: [],lat: 52.095833333333,lng: 5.8169444444444,note: "Not visited — holds wish works (added 2026-08-27)."},
  {id: "rijksmuseum",name: "Rijksmuseum",city: "Amsterdam",country: "nl",qid: "Q190804",kind: "art",visits: [],lat: 52.36,lng: 4.885277777777778,note: "Not visited — holds wish works (added 2026-08-27)."}
];
