// museum_about.js — institution reads for museum pages (pilot 10, 2026-07-17).
// Same two-tier convention as art-about: about = what this place is, deep = how it works
// as an experience. Drafted by Opus, verified and polished by Fable (per-entry by:).
window.CANVAS_MUSEUM_ABOUT = {
 "met-nyc": {
 about: "America's largest art museum, founded in 1870 by New Yorkers who felt the young country ought to have one. Encyclopedic by design — five thousand years, every continent, an Egyptian temple to European paint to arms and armour — behind a Beaux-Arts façade on the edge of Central Park, extended and re-extended for a century and a half.",
 deep: "The Met's ambition is coverage, not argument: one great example of everything, and it mostly has one, so the building rewards wanderers and punishes planners. It is really a dozen museums under one roof — each wing donor-built, donor-named, run to its own taste — which is why the whole reads as a city's accumulated appetite rather than a single vision. Crowds pool in the same few rooms, European paintings and the Temple of Dendur, so go at opening or aim where people don't: the American Wing, arms and armour, the instruments. The Great Hall staircase gets you to the paintings ahead of the tour groups. And give yourself permission to leave unfinished — nobody completes the Met, and treating it as many small museums, one per visit, is the only sane way in.",
 by: 'Opus · Fable' },
 "marmottan": {
 about: "A hunting lodge turned mansion on the edge of the Bois de Boulogne, left to the Académie des Beaux-Arts by Paul Marmottan in 1932. Michel Monet's 1966 bequest of his father's own holdings made it the largest Monet collection in the world — including Impression, Sunrise, the canvas that named Impressionism — with the finest Berthe Morisot holdings anywhere alongside.",
 deep: "A house, not a hall, and it works on you that way: panelled rooms of Empire furniture upstairs, then the floor gives way to a purpose-built basement gallery where the Monets hang — the late water lilies among them, dim and enveloping, close enough to read every stroke, and rarely a crowd between you and them. Impression, Sunrise carries two good stories: a hostile critic coined \"Impressionism\" from its title as a sneer and the movement kept the slur as a badge; then in 1985 the painting was stolen at gunpoint from these rooms and spent five years missing before turning up in Corsica. Go down to the Monets first, while you're fresh. Then climb back up for Morisot — most visitors treat her rooms as a corridor, and they are the best of her anywhere.",
 by: 'Opus · Fable' },
 "van-gogh-museum": {
 about: "The world's largest Van Gogh collection, built on what brother Theo's family kept and never sold: some two hundred paintings, five hundred drawings, and the letters. Opened in 1973 on Amsterdam's Museumplein in a building designed by Gerrit Rietveld of De Stijl, it traces one short, ferocious career from the dark Dutch years to the final blaze in France.",
 deep: "Because the collection descends from what the family kept rather than what the market picked, it tells a life in order, and it hangs that way: chronological, from the muddy Nuenen peasants up through Paris to the sunstruck south and the last weeks at Auvers. That inheritance also makes it rich in the unfamous — studies, misfires, second attempts — so this museum explains Van Gogh where greatest-hits hangs merely display him. The letters quoted on the walls do more than any label. And the whole thing exists because Jo van Gogh-Bonger, Theo's widow, spent decades placing and publishing the work of a man who sold almost nothing alive. Everyone climbs the same route in the same direction and the middle floors clot: book ahead, come at opening or in the last hours, and double back against the flow for the famous ones.",
 by: 'Opus · Fable' },
 "guggenheim": {
 about: "Frank Lloyd Wright's white spiral on Fifth Avenue, opened in 1959 and as much sculpture as building. It grew from Solomon R. Guggenheim's collection of \"non-objective\" painting, assembled on the advice of Hilla Rebay, and stays strongest in early European modernism — above all Kandinsky. The rotunda ramp, coiling up beneath its glass dome, is the collection's most famous object.",
 deep: "Wright built a building that tells you how to move: lift to the top, then walk down, gravity doing the choreography as each work swings into view around the curve. It is a beautiful idea permanently at war with the art — the floor slopes, the outer wall leans, and painters have grumbled for decades that nothing hangs straight — a museum whose masterpiece fights its own pictures. Wright himself died six months before the opening; he never stood in the finished rotunda. The spine of the collection is abstraction's founding generation, the Kandinskys above all, while the Renoirs and Manets you didn't expect come from the later Thannhauser gift, tucked into a side wing. Those galleries off the ramp are easy to miss and where the quiet treasures wait. Ride straight up, drift down, and let the building be the first exhibit.",
 by: 'Opus · Fable' },
 "belvedere": {
 about: "A baroque summer palace completed in 1723 for Prince Eugene of Savoy, crowning a terraced garden above Vienna. It now holds Austrian art across the centuries, and its glory is the world's largest collection of Klimt paintings — The Kiss above all — with strong Schiele and Viennese modernism beside. The gilded state rooms are half the visit.",
 deep: "You come for pictures and find yourself in a palace: in through the Sala Terrena, where four stone giants hold up the vault, then up the staircase to the Marble Hall — the room where, in 1955, the treaty restoring Austria's sovereignty was signed and shown from the balcony. Imperial baroque housing radical modernism is the whole character of the place; Klimt's gold reads differently in halls built to glitter, one empire's swagger framing the artists who broke with it. The Kiss pulls the entire crowd into a single room, phones up on arrival, so take Schiele and the nineteenth century first. Regulars remember the missing one: Adele Bloch-Bauer I hung here until 2006, when it was restituted to the family the Nazis robbed, and left for New York. Come early, and give the gardens and the city view their minutes — the view is why it stands up here.",
 by: 'Opus · Fable' },
 "orsay": {
 about: "Western art from 1848 to 1914, housed in Victor Laloux's Beaux-Arts railway station built for the 1900 World's Fair and nearly demolished in the 1970s. Opened as a museum in 1986, it bridges the Louvre and the Pompidou and holds the world's foremost Impressionist and Post-Impressionist collection under its vast glass train-shed vault.",
 deep: "The Orsay's spine is a chronology and its bones are a station: the sculpture court runs where the platforms lay, the great gilded clock still keeps time, and everything funnels upward to the Impressionists under the roof — which is why the fifth floor is a crush by noon. Reverse the flow: ride to the top at opening, take Monet, Renoir and Van Gogh while they're quiet, then descend through the realists and the academic Salon machines most people skip; the Bouguereaus and Courbets on the way down are half the argument of the place, the world Impressionism was fighting. The station itself died of progress — by 1939 its platforms were too short for modern trains — and in the 1970s France nearly flattened it for a hotel: the country that once refused to hang this art almost demolished its perfect frame.",
 by: 'Opus · Fable' },
 "nationalmuseum": {
 about: "Sweden's museum of art and design, founded in 1792 and housed since 1866 in Friedrich August Stüler's Renaissance-revival palace on the Stockholm waterfront, facing the Royal Palace across the water. Swedish painting and sculpture, older European masters, and a serious design collection share the building, rehung and re-coloured in a grand restoration finished in 2018.",
 deep: "A national self-portrait as much as an art museum: strongest where it tells Sweden's own story — Zorn's midsummer light, Sergel's furious drawings — so the Nordic rooms carry a charge the European masters don't quite match. Climb the ceremonial staircase and you're inside the collection's best story: Carl Larsson's murals cover it, and his vast Midwinter Sacrifice, painted for the top landing, was rejected on delivery, drifted for decades and reached Japan before Sweden bought it back in 1997 — it now hangs exactly where he meant it to. Crowds are gentle by continental standards; you can stand alone with the Rembrandts, including the Conspiracy of the Batavians that Amsterdam's town hall rejected too. Start at the top with the paintings, drift down through design, and don't treat the applied-arts floors as a footnote — here a chair ranks with a canvas on purpose.",
 by: 'Opus · Fable' },
 "frick": {
 about: "Steel-and-coke magnate Henry Clay Frick's private collection, shown in the Fifth Avenue mansion Carrère and Hastings built for him in 1914 — designed from the start to become a museum once the family was done living in it. Old Masters, French furniture, porcelain and bronzes, bought with a ruthless eye for quality over quantity. It opened to the public in 1935.",
 deep: "The Frick's genius is restraint: one man bought only what he judged best, so the walls hold few pictures and almost no weak ones — three Vermeers, Bellini's St Francis, Holbein's Cromwell and More glaring at each other across a fireplace — and you meet them in rooms built for living, not display. The serenity was bought with one of the Gilded Age's most hated fortunes; the man who hung the Vermeers also broke the Homestead strike and survived an anarchist's bullets, an irony the house never mentions and you can't unfeel. The Garden Court, everyone's resting place, isn't original — John Russell Pope added it in the museum conversion, over the old carriage court. Since the 2025 renovation the upstairs family rooms are open for the first time, small rooms with small pictures, and they restore what the collection is really about: living with it.",
 by: 'Opus · Fable' },
 "nga-dc": {
 about: "The United States' national gallery, Andrew Mellon's gift to the nation along with the core of its collection. John Russell Pope's neoclassical West Building opened on the Mall in 1941; I. M. Pei's angular East Building for modern art followed in 1978. Old Masters run deep here, including Ginevra de' Benci, the only Leonardo painting in the Americas.",
 deep: "Two buildings, two temperaments, joined underground: Pope's West Building is a marble temple, skylit rooms strung along garden courts with fountains, while Pei's East Building is sharp angles and atrium light for the twentieth century — the walk between them runs through Leo Villareal's LED tunnel, the one stretch of museum photographed more than the art. Mellon's modesty was strategy: he refused to let the gallery carry his name so that other collectors would give too, and they did — Kress, Widener, Dale — which is how a national collection materialised within a decade. It is free, it is not part of the Smithsonian despite what half its visitors assume, and it rarely overwhelms: crowds cluster at the Leonardo and the Impressionists while the Dutch and Italian rooms nearby stay calm. Take the West first, and rest in the garden courts — they're built for it.",
 by: 'Opus · Fable' },
 "ngi": {
 about: "Ireland's national collection, opened in 1864 on Merrion Square, holding a solid European survey alongside the fullest gathering of Irish painting anywhere. Its modern legend is Caravaggio's The Taking of Christ, which hung unrecognised in a Dublin Jesuit house until 1990. Successive wings, the Millennium extension among them, wrap the original Victorian galleries.",
 deep: "The gallery reads in two registers: a compact European survey — Vermeer, Velázquez, Goya — and beside it the national story, Irish painters given room no bigger country would spare them, with Jack B. Yeats a museum within the museum. Its luck is legendary in both directions. The Caravaggio hung misattributed in a Jesuit dining room for decades before a researcher recognised it in 1990; the Jesuits left it on permanent loan. The Vermeer came via the Beit collection, stolen twice — once by an IRA gang, once for a Dublin crime boss — and recovered both times. And the money is literary: Bernard Shaw, who called the gallery his real schoolroom, left it a share of his royalties, so My Fair Lady quietly paid for pictures. Admission is free, crowds are modest, and the Irish rooms are quietest of all — see the Caravaggio early, then give them your unhurried hour.",
 by: 'Opus · Fable' }
,
 "mnw": {
 about: "Poland's largest art museum, founded in 1862 and rebuilt more than once alongside the city itself. The core is Polish painting — Matejko's enormous history machines, the Gierymskis, the moderns — flanked by European old masters and the Faras Gallery: Europe's only permanent display of medieval Nubian wall painting, lifted from a cathedral in Sudan before the Aswan dam took the site.",
 deep: "A museum shaped by loss and salvage: much was looted or destroyed in the war, and what hangs now is partly the story of what came back. Gierymski's orange seller is that story in miniature — vanished in 1944, recovered at a German auction sixty-odd years later, home again. The Polish galleries are the heart, and they ask something of you: Matejko's vast canvases are less pictures than arguments, painted to keep a partitioned nation's memory alive when the state had vanished from the map. Then it softens into quiet portraits where looking is enough. Most visitors do the grand halls and thin out fast, which leaves the old masters and the Faras frescoes nearly private. Find Saint Anne there, finger raised to her lips — the museum's quietest famous face. Weekday mornings, the big rooms are close to yours alone.",
 by: 'Opus · Fable' },
 "artizon": {
 about: "One family's eye, made public: the collection of Shōjirō Ishibashi, the industrialist whose surname — 'stone bridge' — flipped into English gave Bridgestone its name. His Bridgestone Museum of Art opened in 1952 and re-emerged in 2020 as the Artizon, filling the lower floors of a new tower in Kyōbashi, minutes from Tokyo Station: French Impressionism beside the Japanese painters who answered it.",
 deep: "A connoisseur's museum rather than an encyclopaedic one — one family's taste, weighted to late-nineteenth-century France — and it rewards slow looking over long walking. The 2020 rebuild bought it high, immaculate galleries across three floors of the tower, and the hang is generous: paintings that would be jostled elsewhere get a wall to themselves. The real reward is watching the French and Japanese rooms talk to each other. Fujishima and his generation went to Paris, took what they needed and came home; the collection lets you follow that round trip across adjacent walls. Because it is compact and sits in office-block Kyōbashi, it is easy to underestimate — which is exactly why it stays calm while the big Ueno museums heave. Book the timed slot, come at opening, and let the Cézannes set your pace.",
 by: 'Opus · Fable' },
 "national-gallery-london": {
 about: "Founded in 1824 around thirty-eight pictures bought from a banker's estate, and grown since into one of the world's great surveys of European painting, thirteenth-century gold grounds to 1900. Deliberately compact, free to all, and dead-centre on Trafalgar Square — put there, its founders reasoned, so the poor could reach it as easily as the rich.",
 deep: "The scale is the secret: around 2,300 pictures, most of them on the walls, so this is a collection you can actually finish — a tight chronological spine you could walk in a morning if you were brutal about it. Don't be. The crowds pool around a dozen famous names — the Sunflowers, the Arnolfini, Turner's Temeraire — while whole centuries hang half-empty; the Sainsbury Wing's early Renaissance rooms are what people rush through on their way to the Impressionists, which is exactly backwards. Walked in order, the building tells one long story: gold-ground altarpieces losing their flatness, oil arriving, light dissolving into Turner and then Seurat. Come at opening or in the final hour, start at the medieval end, and move with time rather than against the flow of the crowd.",
 by: 'Opus · Fable' },
 "rodin": {
 about: "Rodin spent his last working years in the Hôtel Biron, an eighteenth-century Paris mansion, and in 1916 gave the state everything — sculpture, drawings, his own art collection — on condition it become his museum. The result is the fullest gathering of his work in bronze, marble and plaster, indoors and out, with Camille Claudel given serious space and a formal garden where The Thinker broods.",
 deep: "The bargain was shrewd on both sides: Rodin arranged his own immortality, and France got a museum that feels like a house because it is one — domestic rooms where marble sits by tall windows, a garden where the bronzes stand among roses exactly as he intended. Claudel is not a footnote here but the argument the museum quietly stages: The Waltz and The Mature Age get rooms of their own, so you can measure her against the master she loved and left, and decide the comparison is less one-sided than history pretended. There is also the collection Rodin kept for himself — his Van Goghs, Père Tanguy among them, hang inside: a sculptor's eye on painting. Most visitors cluster at the garden bronzes and never slow down indoors; take the house first, before the sun sends everyone out.",
 by: 'Opus · Fable' },
 "ngv": {
 about: "Founded in 1861 with gold-rush money, the National Gallery of Victoria is Australia's oldest public art gallery and its most visited. The international collection — European painting, antiquities, serious Asian holdings — lives behind the water wall on St Kilda Road, under Leonard French's vast stained-glass ceiling; the Australian pictures have their own building at Federation Square.",
 deep: "A gold-rush colony keen to prove itself cultured built early and bought well, which is why Melbourne holds a spread of European painting nobody expects to find here — Rembrandt, van Ruisdael, a run of Dürer prints. The split is the thing visitors trip over: International on St Kilda Road, Australian art a ten-minute walk away at Federation Square, so decide which you have come for and do it properly. Regulars know the Great Hall ritual — you lie flat on the floor and let Leonard French's stained-glass ceiling pour colour down on you. Meanwhile the crowds pat the water wall, queue for the ticketed blockbuster, and leave the permanent European and Asian rooms pleasantly empty. The Japanese holdings repay a detour. One collection taken slowly beats two taken at a jog.",
 by: 'Opus · Fable' },
 "agnsw": {
 about: "Sydney's state gallery has held its edge of the Domain's parkland since the 1870s: a Grecian temple front with the defining collection of Australian art inside, alongside European rooms, Asian galleries and one of the country's most significant First Nations holdings. In late 2022 it doubled — Naala Badu, a pavilion campus by SANAA, now steps down the slope toward the harbour.",
 deep: "The spine is Australian, and the nineteenth-century rooms tell a particular story: a settler nation teaching itself to look at its own light, Streeton and Roberts and McCubbin chasing a heat and distance the European formula could not handle. Around that core sit respectable European rooms, strong Asian galleries, and — in Naala Badu — the Yiribana galleries of Aboriginal and Torres Strait Islander art, moved from the old building's lowest level to the new one's front door, which tells you where the institution thinks its future lies. The expansion changed the choreography too: the older the art, the higher and older the building; the further you descend the slope, the more recent it gets. Start in the original building while your eye is fresh — the colonial and Heidelberg rooms — then walk down into the new.",
 by: 'Opus · Fable' },
 "agsa": {
 about: "Adelaide's gallery has held its spot on North Terrace — the city's single street of culture, shoulder to shoulder with museum, library and university — since 1881. For a mid-sized city the collection is outsized: deep nineteenth-century British and Australian painting, Waterhouse's Circe Invidiosa among the trophies, and the only permanent display of Islamic art in Australia.",
 deep: "The intimacy is the point: this is a gallery you can finish in an afternoon without the fatigue the encyclopaedic museums impose, and the collection runs deep enough that finishing it feels like an achievement. Its signature is the hang itself — the Melrose Wing was rehung close and high, salon-style, colonial pictures beside contemporary ones, centuries arguing across a single wall — so the rooms reward a second lap; you notice different pairings walking back the other way. The nineteenth-century holdings are the strength: British narrative and academic painting alongside the Australians, storytelling canvases built to be read standing still. Sharing North Terrace with the museum and the library keeps the flow steady but never crushing — walkable on days Sydney and Melbourne are heaving. Take it unhurried, and let the smallness work for you.",
 by: 'Opus · Fable' },
 "british-museum": {
 about: "Founded in 1753 around Hans Sloane's bequest — the first free national public museum in the world — and still trying to hold all human history under one roof: two million years of it, from hand axes to Hokusai. The Greek Revival block in Bloomsbury got its glass-roofed Great Court in 2000; the collection acquired its controversies rather earlier.",
 deep: "The Enlightenment dream was to gather the whole world in one building and let anyone in free; the dream's afterlife is that much of the world would now like its things back, and the arguments over the Parthenon sculptures are part of any honest visit. The practical problem is different: eight million objects, a famous one per cent on display, and nearly everyone crushed into the same few ground-floor rooms by the main door — Egypt, the Assyrian reliefs, the Rosetta Stone behind its scrum of phones. The trick is height and distance. Go up and go outward: the clocks, the prints, the Japanese galleries at the top empty out entirely. Enter from Montague Place at the back, work downward toward the icons, and meet the Rosetta Stone last, when the coaches have gone.",
 by: 'Opus · Fable' },
 "nga-canberra": {
 about: "Australia's national collection, opened in 1982 in a Brutalist concrete landmark beside Lake Burley Griffin, with a sculpture garden running down to the water. Built late, it collected forward: strong international modern and contemporary holdings, and the largest collection of Aboriginal and Torres Strait Islander art in the world.",
 deep: "Arriving late turned out to be its advantage: while the state galleries were buying Victorian narrative pictures a century ago, the NGA assembled itself in the late twentieth century and leans modern by birth — this is the museum that scandalised the country by paying $1.3 million for Pollock's Blue Poles in 1973, a purchase now worth hundreds of times that and remembered as a national vindication. The moral centre, though, is the Aboriginal Memorial: two hundred hollow log coffins from Ramingining, one for each year of European occupation to 1988, made as a war memorial for people who never got one. Meet it first, slowly, before the day fills. Canberra's distance keeps weekdays close to serene, and the sculpture garden by the lake is what short visits always sacrifice. Don't.",
 by: 'Opus · Fable' },
 "whitney": {
 about: "Born of a rejection: when the Metropolitan declined Gertrude Vanderbilt Whitney's offer of her collection of living American artists, she founded her own museum in 1930. It has been arguing for the American art of the last hundred years ever since — since 2015 from a Renzo Piano building in the Meatpacking District, at the foot of the High Line.",
 deep: "The founding snub still sets the temperament: American, modern, biased toward the living — the Biennial, begun as an annual in 1932, remains the closest thing the country has to a survey of its own present, and the most reliably argued-about show in New York. The building is designed as a descent: ride to the top and work down through the outdoor terraces, which hand you the Hudson on one side and the Manhattan grid on the other between galleries — the view is not a break from the art so much as the argument continued. The anchor is Hopper: Josephine Hopper left her husband's entire estate to the Whitney in 1968, some three thousand works, so nowhere else can you watch that hard American light develop from sketch to Early Sunday Morning. Weekday mornings, top floor first, terraces slowly.",
 by: 'Opus · Fable' }
};
