// museum_about.js — institution reads for museum pages (pilot 10, 2026-07-17).
// Same two-tier convention as art-about: about = what this place is, deep = how it works
// as an experience. Drafted by Opus, verified and polished by Fable (per-entry by:).
window.CANVAS_MUSEUM_ABOUT = {
 "met-nyc": {
 about: "America's largest art museum, founded in 1870 by New Yorkers who felt the young country ought to have one. Encyclopedic by design — five thousand years, every continent, an Egyptian temple to European paint to arms and armour — behind a Beaux-Arts façade on the edge of Central Park, extended and re-extended for a century and a half.",
 deep: "The Met's ambition is coverage, not argument: one great example of everything, and it mostly has one, so the building rewards wanderers and punishes planners. It is really a dozen museums under one roof — each wing donor-built, donor-named, run to its own taste — which is why the whole reads as a city's accumulated appetite rather than a single vision. Crowds pool in the same few rooms, European paintings and the Temple of Dendur, so go at opening or aim where people don't: the American Wing, arms and armour, the instruments. The Great Hall staircase gets you to the paintings ahead of the tour groups. And give yourself permission to leave unfinished — nobody completes the Met, and treating it as many small museums, one per visit, is the only sane way in.",
 by: 'Opus · Fable' },
 "marmottan": {
 about: "A hunting lodge turned mansion on the edge of the Bois de Boulogne, left to the Académie des Beaux-Arts by Paul Marmottan in 1932. Michel Monet's 1966 bequest of his father's own holdings made it the largest Monet collection in the world — including Impression, Sunrise, the canvas that named Impressionism — with the finest Berthe Morisot holdings anywhere alongside.",
 deep: "A house, not a hall, and it works on you that way: panelled rooms of Empire furniture upstairs, then the floor gives way to a purpose-built basement gallery where the Monets hang — the late water lilies among them, dim and enveloping, close enough to read every stroke, and rarely a crowd between you and them. Impression, Sunrise carries two good stories: a hostile critic coined \"Impressionism\" from its title as a sneer and the movement kept the slur as a badge; then in 1985 the painting was stolen at gunpoint from these rooms and spent five years missing before turning up in Corsica. Go down to the Monets first, while you're fresh. Then climb back up for Morisot — most visitors treat her rooms as a corridor, and they are the best of her anywhere.",
 by: 'Opus · Fable' },
 "van-gogh-museum": {
 about: "The world's largest Van Gogh collection, built on what brother Theo's family kept and never sold: some two hundred paintings, five hundred drawings, and the letters. Opened in 1973 on Amsterdam's Museumplein in a building designed by Gerrit Rietveld of De Stijl, it traces one short, ferocious career from the dark Dutch years to the final blaze in France.",
 deep: "Because the collection descends from what the family kept rather than what the market picked, it tells a life in order, and it hangs that way: chronological, from the muddy Nuenen peasants up through Paris to the sunstruck south and the last weeks at Auvers. That inheritance also makes it rich in the unfamous — studies, misfires, second attempts — so this museum explains Van Gogh where greatest-hits hangs merely display him. The letters quoted on the walls do more than any label. And the whole thing exists because Jo van Gogh-Bonger, Theo's widow, spent decades placing and publishing the work of a man who sold almost nothing alive. Everyone climbs the same route in the same direction and the middle floors clot: book ahead, come at opening or in the last hours, and double back against the flow for the famous ones.",
 by: 'Opus · Fable' },
 "guggenheim": {
 about: "Frank Lloyd Wright's white spiral on Fifth Avenue, opened in 1959 and as much sculpture as building. It grew from Solomon R. Guggenheim's collection of \"non-objective\" painting, assembled on the advice of Hilla Rebay, and stays strongest in early European modernism — above all Kandinsky. The rotunda ramp, coiling up beneath its glass dome, is the collection's most famous object.",
 deep: "Wright built a building that tells you how to move: lift to the top, then walk down, gravity doing the choreography as each work swings into view around the curve. It is a beautiful idea permanently at war with the art — the floor slopes, the outer wall leans, and painters have grumbled for decades that nothing hangs straight — a museum whose masterpiece fights its own pictures. Wright himself died six months before the opening; he never stood in the finished rotunda. The spine of the collection is abstraction's founding generation, the Kandinskys above all, while the Renoirs and Manets you didn't expect come from the later Thannhauser gift, tucked into a side wing. Those galleries off the ramp are easy to miss and where the quiet treasures wait. Ride straight up, drift down, and let the building be the first exhibit.",
 by: 'Opus · Fable' },
 "belvedere": {
 about: "A baroque summer palace completed in 1723 for Prince Eugene of Savoy, crowning a terraced garden above Vienna. It now holds Austrian art across the centuries, and its glory is the world's largest collection of Klimt paintings — The Kiss above all — with strong Schiele and Viennese modernism beside. The gilded state rooms are half the visit.",
 deep: "You come for pictures and find yourself in a palace: in through the Sala Terrena, where four stone giants hold up the vault, then up the staircase to the Marble Hall — the room where, in 1955, the treaty restoring Austria's sovereignty was signed and shown from the balcony. Imperial baroque housing radical modernism is the whole character of the place; Klimt's gold reads differently in halls built to glitter, one empire's swagger framing the artists who broke with it. The Kiss pulls the entire crowd into a single room, phones up on arrival, so take Schiele and the nineteenth century first. Regulars remember the missing one: Adele Bloch-Bauer I hung here until 2006, when it was restituted to the family the Nazis robbed, and left for New York. Come early, and give the gardens and the city view their minutes — the view is why it stands up here.",
 by: 'Opus · Fable' },
 "orsay": {
 about: "Western art from 1848 to 1914, housed in Victor Laloux's Beaux-Arts railway station built for the 1900 World's Fair and nearly demolished in the 1970s. Opened as a museum in 1986, it bridges the Louvre and the Pompidou and holds the world's foremost Impressionist and Post-Impressionist collection under its vast glass train-shed vault.",
 deep: "The Orsay's spine is a chronology and its bones are a station: the sculpture court runs where the platforms lay, the great gilded clock still keeps time, and everything funnels upward to the Impressionists under the roof — which is why the fifth floor is a crush by noon. Reverse the flow: ride to the top at opening, take Monet, Renoir and Van Gogh while they're quiet, then descend through the realists and the academic Salon machines most people skip; the Bouguereaus and Courbets on the way down are half the argument of the place, the world Impressionism was fighting. The station itself died of progress — by 1939 its platforms were too short for modern trains — and in the 1970s France nearly flattened it for a hotel: the country that once refused to hang this art almost demolished its perfect frame.",
 by: 'Opus · Fable' },
 "nationalmuseum": {
 about: "Sweden's museum of art and design, founded in 1792 and housed since 1866 in Friedrich August Stüler's Renaissance-revival palace on the Stockholm waterfront, facing the Royal Palace across the water. Swedish painting and sculpture, older European masters, and a serious design collection share the building, rehung and re-coloured in a grand restoration finished in 2018.",
 deep: "A national self-portrait as much as an art museum: strongest where it tells Sweden's own story — Zorn's midsummer light, Sergel's furious drawings — so the Nordic rooms carry a charge the European masters don't quite match. Climb the ceremonial staircase and you're inside the collection's best story: Carl Larsson's murals cover it, and his vast Midwinter Sacrifice, painted for the top landing, was rejected on delivery, drifted for decades and reached Japan before Sweden bought it back in 1997 — it now hangs exactly where he meant it to. Crowds are gentle by continental standards; you can stand alone with the Rembrandts, including the Conspiracy of the Batavians that Amsterdam's town hall rejected too. Start at the top with the paintings, drift down through design, and don't treat the applied-arts floors as a footnote — here a chair ranks with a canvas on purpose.",
 by: 'Opus · Fable' },
 "frick": {
 about: "Steel-and-coke magnate Henry Clay Frick's private collection, shown in the Fifth Avenue mansion Carrère and Hastings built for him in 1914 — designed from the start to become a museum once the family was done living in it. Old Masters, French furniture, porcelain and bronzes, bought with a ruthless eye for quality over quantity. It opened to the public in 1935.",
 deep: "The Frick's genius is restraint: one man bought only what he judged best, so the walls hold few pictures and almost no weak ones — three Vermeers, Bellini's St Francis, Holbein's Cromwell and More glaring at each other across a fireplace — and you meet them in rooms built for living, not display. The serenity was bought with one of the Gilded Age's most hated fortunes; the man who hung the Vermeers also broke the Homestead strike and survived an anarchist's bullets, an irony the house never mentions and you can't unfeel. The Garden Court, everyone's resting place, isn't original — John Russell Pope added it in the museum conversion, over the old carriage court. Since the 2025 renovation the upstairs family rooms are open for the first time, small rooms with small pictures, and they restore what the collection is really about: living with it.",
 by: 'Opus · Fable' },
 "nga-dc": {
 about: "The United States' national gallery, Andrew Mellon's gift to the nation along with the core of its collection. John Russell Pope's neoclassical West Building opened on the Mall in 1941; I. M. Pei's angular East Building for modern art followed in 1978. Old Masters run deep here, including Ginevra de' Benci, the only Leonardo painting in the Americas.",
 deep: "Two buildings, two temperaments, joined underground: Pope's West Building is a marble temple, skylit rooms strung along garden courts with fountains, while Pei's East Building is sharp angles and atrium light for the twentieth century — the walk between them runs through Leo Villareal's LED tunnel, the one stretch of museum photographed more than the art. Mellon's modesty was strategy: he refused to let the gallery carry his name so that other collectors would give too, and they did — Kress, Widener, Dale — which is how a national collection materialised within a decade. It is free, it is not part of the Smithsonian despite what half its visitors assume, and it rarely overwhelms: crowds cluster at the Leonardo and the Impressionists while the Dutch and Italian rooms nearby stay calm. Take the West first, and rest in the garden courts — they're built for it.",
 by: 'Opus · Fable' },
 "ngi": {
 about: "Ireland's national collection, opened in 1864 on Merrion Square, holding a solid European survey alongside the fullest gathering of Irish painting anywhere. Its modern legend is Caravaggio's The Taking of Christ, which hung unrecognised in a Dublin Jesuit house until 1990. Successive wings, the Millennium extension among them, wrap the original Victorian galleries.",
 deep: "The gallery reads in two registers: a compact European survey — Vermeer, Velázquez, Goya — and beside it the national story, Irish painters given room no bigger country would spare them, with Jack B. Yeats a museum within the museum. Its luck is legendary in both directions. The Caravaggio hung misattributed in a Jesuit dining room for decades before a researcher recognised it in 1990; the Jesuits left it on permanent loan. The Vermeer came via the Beit collection, stolen twice — once by an IRA gang, once for a Dublin crime boss — and recovered both times. And the money is literary: Bernard Shaw, who called the gallery his real schoolroom, left it a share of his royalties, so My Fair Lady quietly paid for pictures. Admission is free, crowds are modest, and the Irish rooms are quietest of all — see the Caravaggio early, then give them your unhurried hour.",
 by: 'Opus · Fable' }
,
 "mnw": {
 about: "Poland's largest art museum, founded in 1862 and rebuilt more than once alongside the city itself. The core is Polish painting — Matejko's enormous history machines, the Gierymskis, the moderns — flanked by European old masters and the Faras Gallery: Europe's only permanent display of medieval Nubian wall painting, lifted from a cathedral in Sudan before the Aswan dam took the site.",
 deep: "A museum shaped by loss and salvage: much was looted or destroyed in the war, and what hangs now is partly the story of what came back. Gierymski's orange seller is that story in miniature — vanished in 1944, recovered at a German auction sixty-odd years later, home again. The Polish galleries are the heart, and they ask something of you: Matejko's vast canvases are less pictures than arguments, painted to keep a partitioned nation's memory alive when the state had vanished from the map. Then it softens into quiet portraits where looking is enough. Most visitors do the grand halls and thin out fast, which leaves the old masters and the Faras frescoes nearly private. Find Saint Anne there, finger raised to her lips — the museum's quietest famous face. Weekday mornings, the big rooms are close to yours alone.",
 by: 'Opus · Fable' },
 "artizon": {
 about: "One family's eye, made public: the collection of Shōjirō Ishibashi, the industrialist whose surname — 'stone bridge' — flipped into English gave Bridgestone its name. His Bridgestone Museum of Art opened in 1952 and re-emerged in 2020 as the Artizon, filling the lower floors of a new tower in Kyōbashi, minutes from Tokyo Station: French Impressionism beside the Japanese painters who answered it.",
 deep: "A connoisseur's museum rather than an encyclopaedic one — one family's taste, weighted to late-nineteenth-century France — and it rewards slow looking over long walking. The 2020 rebuild bought it high, immaculate galleries across three floors of the tower, and the hang is generous: paintings that would be jostled elsewhere get a wall to themselves. The real reward is watching the French and Japanese rooms talk to each other. Fujishima and his generation went to Paris, took what they needed and came home; the collection lets you follow that round trip across adjacent walls. Because it is compact and sits in office-block Kyōbashi, it is easy to underestimate — which is exactly why it stays calm while the big Ueno museums heave. Book the timed slot, come at opening, and let the Cézannes set your pace.",
 by: 'Opus · Fable' },
 "national-gallery-london": {
 about: "Founded in 1824 around thirty-eight pictures bought from a banker's estate, and grown since into one of the world's great surveys of European painting, thirteenth-century gold grounds to 1900. Deliberately compact, free to all, and dead-centre on Trafalgar Square — put there, its founders reasoned, so the poor could reach it as easily as the rich.",
 deep: "The scale is the secret: around 2,300 pictures, most of them on the walls, so this is a collection you can actually finish — a tight chronological spine you could walk in a morning if you were brutal about it. Don't be. The crowds pool around a dozen famous names — the Sunflowers, the Arnolfini, Turner's Temeraire — while whole centuries hang half-empty; the Sainsbury Wing's early Renaissance rooms are what people rush through on their way to the Impressionists, which is exactly backwards. Walked in order, the building tells one long story: gold-ground altarpieces losing their flatness, oil arriving, light dissolving into Turner and then Seurat. Come at opening or in the final hour, start at the medieval end, and move with time rather than against the flow of the crowd.",
 by: 'Opus · Fable' },
 "rodin": {
 about: "Rodin spent his last working years in the Hôtel Biron, an eighteenth-century Paris mansion, and in 1916 gave the state everything — sculpture, drawings, his own art collection — on condition it become his museum. The result is the fullest gathering of his work in bronze, marble and plaster, indoors and out, with Camille Claudel given serious space and a formal garden where The Thinker broods.",
 deep: "The bargain was shrewd on both sides: Rodin arranged his own immortality, and France got a museum that feels like a house because it is one — domestic rooms where marble sits by tall windows, a garden where the bronzes stand among roses exactly as he intended. Claudel is not a footnote here but the argument the museum quietly stages: The Waltz and The Mature Age get rooms of their own, so you can measure her against the master she loved and left, and decide the comparison is less one-sided than history pretended. There is also the collection Rodin kept for himself — his Van Goghs, Père Tanguy among them, hang inside: a sculptor's eye on painting. Most visitors cluster at the garden bronzes and never slow down indoors; take the house first, before the sun sends everyone out.",
 by: 'Opus · Fable' },
 "ngv": {
 about: "Founded in 1861 with gold-rush money, the National Gallery of Victoria is Australia's oldest public art gallery and its most visited. The international collection — European painting, antiquities, serious Asian holdings — lives behind the water wall on St Kilda Road, under Leonard French's vast stained-glass ceiling; the Australian pictures have their own building at Federation Square.",
 deep: "A gold-rush colony keen to prove itself cultured built early and bought well, which is why Melbourne holds a spread of European painting nobody expects to find here — Rembrandt, van Ruisdael, a run of Dürer prints. The split is the thing visitors trip over: International on St Kilda Road, Australian art a ten-minute walk away at Federation Square, so decide which you have come for and do it properly. Regulars know the Great Hall ritual — you lie flat on the floor and let Leonard French's stained-glass ceiling pour colour down on you. Meanwhile the crowds pat the water wall, queue for the ticketed blockbuster, and leave the permanent European and Asian rooms pleasantly empty. The Japanese holdings repay a detour. One collection taken slowly beats two taken at a jog.",
 by: 'Opus · Fable' },
 "agnsw": {
 about: "Sydney's state gallery has held its edge of the Domain's parkland since the 1870s: a Grecian temple front with the defining collection of Australian art inside, alongside European rooms, Asian galleries and one of the country's most significant First Nations holdings. In late 2022 it doubled — Naala Badu, a pavilion campus by SANAA, now steps down the slope toward the harbour.",
 deep: "The spine is Australian, and the nineteenth-century rooms tell a particular story: a settler nation teaching itself to look at its own light, Streeton and Roberts and McCubbin chasing a heat and distance the European formula could not handle. Around that core sit respectable European rooms, strong Asian galleries, and — in Naala Badu — the Yiribana galleries of Aboriginal and Torres Strait Islander art, moved from the old building's lowest level to the new one's front door, which tells you where the institution thinks its future lies. The expansion changed the choreography too: the older the art, the higher and older the building; the further you descend the slope, the more recent it gets. Start in the original building while your eye is fresh — the colonial and Heidelberg rooms — then walk down into the new.",
 by: 'Opus · Fable' },
 "agsa": {
 about: "Adelaide's gallery has held its spot on North Terrace — the city's single street of culture, shoulder to shoulder with museum, library and university — since 1881. For a mid-sized city the collection is outsized: deep nineteenth-century British and Australian painting, Waterhouse's Circe Invidiosa among the trophies, and the only permanent display of Islamic art in Australia.",
 deep: "The intimacy is the point: this is a gallery you can finish in an afternoon without the fatigue the encyclopaedic museums impose, and the collection runs deep enough that finishing it feels like an achievement. Its signature is the hang itself — the Melrose Wing was rehung close and high, salon-style, colonial pictures beside contemporary ones, centuries arguing across a single wall — so the rooms reward a second lap; you notice different pairings walking back the other way. The nineteenth-century holdings are the strength: British narrative and academic painting alongside the Australians, storytelling canvases built to be read standing still. Sharing North Terrace with the museum and the library keeps the flow steady but never crushing — walkable on days Sydney and Melbourne are heaving. Take it unhurried, and let the smallness work for you.",
 by: 'Opus · Fable' },
 "british-museum": {
 about: "Founded in 1753 around Hans Sloane's bequest — the first free national public museum in the world — and still trying to hold all human history under one roof: two million years of it, from hand axes to Hokusai. The Greek Revival block in Bloomsbury got its glass-roofed Great Court in 2000; the collection acquired its controversies rather earlier.",
 deep: "The Enlightenment dream was to gather the whole world in one building and let anyone in free; the dream's afterlife is that much of the world would now like its things back, and the arguments over the Parthenon sculptures are part of any honest visit. The practical problem is different: eight million objects, a famous one per cent on display, and nearly everyone crushed into the same few ground-floor rooms by the main door — Egypt, the Assyrian reliefs, the Rosetta Stone behind its scrum of phones. The trick is height and distance. Go up and go outward: the clocks, the prints, the Japanese galleries at the top empty out entirely. Enter from Montague Place at the back, work downward toward the icons, and meet the Rosetta Stone last, when the coaches have gone.",
 by: 'Opus · Fable' },
 "nga-canberra": {
 about: "Australia's national collection, opened in 1982 in a Brutalist concrete landmark beside Lake Burley Griffin, with a sculpture garden running down to the water. Built late, it collected forward: strong international modern and contemporary holdings, and the largest collection of Aboriginal and Torres Strait Islander art in the world.",
 deep: "Arriving late turned out to be its advantage: while the state galleries were buying Victorian narrative pictures a century ago, the NGA assembled itself in the late twentieth century and leans modern by birth — this is the museum that scandalised the country by paying $1.3 million for Pollock's Blue Poles in 1973, a purchase now worth hundreds of times that and remembered as a national vindication. The moral centre, though, is the Aboriginal Memorial: two hundred hollow log coffins from Ramingining, one for each year of European occupation to 1988, made as a war memorial for people who never got one. Meet it first, slowly, before the day fills. Canberra's distance keeps weekdays close to serene, and the sculpture garden by the lake is what short visits always sacrifice. Don't.",
 by: 'Opus · Fable' },
 "whitney": {
 about: "Born of a rejection: when the Metropolitan declined Gertrude Vanderbilt Whitney's offer of her collection of living American artists, she founded her own museum in 1930. It has been arguing for the American art of the last hundred years ever since — since 2015 from a Renzo Piano building in the Meatpacking District, at the foot of the High Line.",
 deep: "The founding snub still sets the temperament: American, modern, biased toward the living — the Biennial, begun as an annual in 1932, remains the closest thing the country has to a survey of its own present, and the most reliably argued-about show in New York. The building is designed as a descent: ride to the top and work down through the outdoor terraces, which hand you the Hudson on one side and the Manhattan grid on the other between galleries — the view is not a break from the art so much as the argument continued. The anchor is Hopper: Josephine Hopper left her husband's entire estate to the Whitney in 1968, some three thousand works, so nowhere else can you watch that hard American light develop from sketch to Early Sunday Morning. Weekday mornings, top floor first, terraces slowly.",
 by: 'Opus · Fable' }
,
 "tate-modern": {
 about: "Tate Modern is Britain's museum of international modern and contemporary art, housed in the former Bankside Power Station on the south bank of the Thames, opposite St Paul's. Free to enter, it holds work from around 1900 to now — painting, sculpture, film, installation — and is one of the most-visited art museums in the world.",
 deep: "The building is the exhibit before the art is: Giles Gilbert Scott's brick power station, its cathedral-scale Turbine Hall left deliberately empty so a single commissioned work can own the volume. Herzog & de Meuron converted it in 2000 and added the twisted brick pyramid of the Blavatnik Building in 2016, keeping the industrial bones raw. The displays hang thematically rather than chronologically, so a Rothko can face a video piece and a century collapses into a room. The irony worth carrying: a temple to the immaterial sits inside a machine built to burn oil for the city's light. Craft — go early or late; the free collection is vast and punishes a queue at your back. Let the Turbine Hall reset your eyes before you climb, and treat the river-facing windows as unframed works of their own.",
 by: 'Opus · Fable' },
 "nmk-seoul": {
 about: "The National Museum of Korea in Seoul is the country's flagship museum of art, archaeology and history — one of the largest museums in Asia. Its permanent galleries trace Korean civilisation from prehistory through the Three Kingdoms, Goryeo and Joseon eras, spanning Buddhist sculpture, celadon, gold, calligraphy and painting across a long, deliberately paced building.",
 deep: "You enter along the Path to History, a processional axis running the length of the ground floor with the ten-storey Gyeongcheonsa pagoda framed at its far end — architecture as a slow breath before the objects. The quiet stars are the two gilt-bronze Pensive Bodhisattvas, given their own darkened Room of Quiet Contemplation, and the Goryeo celadons prized for a glaze admirers called kingfisher-coloured. Jeong Seon's true-view landscapes broke from copying Chinese models to paint actual Korean mountains — a declaration of self in ink. The building stands on land in Yongsan recovered from a foreign military base: a site of occupation turned keeping-house of the national self. Craft: it is enormous and free, so do not attempt all of it. Pick one dynasty and let the unhurried spacing work; the Bodhisattva room rewards standing still longer than feels comfortable.",
 by: 'Opus · Fable' },
 "orangerie": {
 about: "The Musée de l'Orangerie sits in the corner of the Tuileries in Paris, a former winter shelter for the garden's orange trees. It is a small museum built around one overwhelming thing — Monet's late Nymphéas murals — with a fine collection of early-modern painting, the Walter-Guillaume group of Cézanne, Renoir, Matisse and Soutine, held below.",
 deep: "Monet offered the panels to France the day after the 1918 Armistice — water and light as a monument to peace for a country counting its dead — and the two oval rooms were built to his own specification, opening in 1927, months after his death. Laid end to end the ovals trace an infinity sign, the cycle of a single day rounding walls with no corner to stop you, top-light washing the surfaces as the sky shifts outside. This is where The Clouds floored you, and the room earns it: the paintings sit at eye level and wrap you until the pond stops being a picture and becomes weather. Downstairs is a deliberate palate-cleanse, intimate and grounded after the dissolution above. Craft: come at opening and take the central bench. The Nymphéas do not reward walking; they reward staying until your peripheral vision surrenders.",
 by: 'Opus · Fable' },
 "tokyo-met": {
 about: "The Tokyo Metropolitan Art Museum stands in Ueno Park, the city's dense cluster of museums. It is primarily an exhibition venue rather than a collecting one — it holds no permanent display of its own but hosts a rotating programme of major loan shows, public-submission salons and touring exhibitions, so what you see depends entirely on when you come.",
 deep: "Because there is no fixed collection to anchor a visit, the building becomes the constant. It opened in 1926 as Japan's first public art museum, a hall where artists' associations mounted their own annual salons — a democratic function that still runs alongside the blockbuster loans. Kunio Maekawa, who trained in Le Corbusier's studio, rebuilt it in 1975 in warm rust-red brick around a sunken plaza, the galleries dropped partly below the park so you descend into them, a calm counter-rhythm to Ueno's crowds above. It was here, in a passing exhibition, that Fjæstad's wood-grain painting floored you — proof that the venue's whole character is contingency. Craft: check the programme before you go, since a great show and an empty week are equally possible, and book timed tickets for the headliners, which sell out.",
 by: 'Opus · Fable' },
 "pompidou": {
 about: "The Centre Pompidou is Paris's museum of modern and contemporary art, its collection among the largest in Europe, wrapped in Renzo Piano and Richard Rogers's radical inside-out building in the Beaubourg quarter. Escalators, pipes and ducts are slung on the exterior in primary colours so the interior can be open, flexible gallery floors.",
 deep: "The design was a provocation that won a 1971 competition and appalled Paris — a cultural palace turned inside out like a refinery, its guts colour-coded (blue for air, green for water, yellow for electricity, red for movement) so the art could have uninterrupted floors. The gag has aged into affection, and the caterpillar escalator up the façade gives one of the great Paris panoramas. The collection runs deep on Fauvism, Cubism and the twentieth-century French line — the home of Marquet's night-lit Pont Neuf and Delaunay's prismatic Paris. The building closed in 2025 for a wholesale renovation planned to run towards 2030, its collection meanwhile lent out to partner venues, so check its status before you plan around it. Craft for the reopening: ride to the top first for the view, then descend through the galleries so the city stays in your eye.",
 by: 'Opus · Fable' },
 "sukiennice": {
 about: "The Sukiennice Gallery is the Gallery of 19th-Century Polish Art, a branch of the National Museum in Kraków, set on the upper floor of the Cloth Hall in the middle of the main market square. It is a single grand suite of Polish Romantic and academic painting — history pictures, portraits and landscapes from the era of the partitions.",
 deep: "The setting is the point: a medieval trading hall, still a working arcade of stalls below, crowned by a nineteenth-century picture gallery — commerce and national art stacked on Europe's largest medieval square. The National Museum in Kraków was born in these rooms in 1879, when Henryk Siemiradzki donated his vast Nero's Torches, which still commands a wall. The collection speaks for a Poland then absent from the map, painting its own history under partition. Its charge is Podkowiński's Szał uniesień — the naked rider and the black stallion: first shown at Warsaw's Zachęta in 1894, it caused such scandal that after thirty-six days the artist slashed his own canvas with a knife; restored after his death, it became Polish Symbolism's founding shock. Craft: the hall is compact enough to see whole in an unhurried hour. Come to meet a few large pictures properly, not to graze.",
 by: 'Opus · Fable' },
 "czestochowa-mgs": {
 about: "The Miejska Galeria Sztuki is Częstochowa's municipal art gallery, a modest civic venue with a changing programme in a city better known for its pilgrimage monastery. For fifteen years it offered a pilgrimage of another kind: from 2006 to 2021 it housed a dedicated Beksiński display — thirty paintings and thirty drawings on deposit from a Paris collection — one of the fullest gatherings of his work outside Sanok.",
 deep: "Beksiński painted his 'fantastic' period without titles and without stated meaning, insisting the pictures be misread freely — decaying figures, bone architecture and burning skies rendered with an old master's patience. Seeing a body of them together changes the encounter: what reads as macabre one canvas at a time becomes, in a room, oddly serene and formally obsessive. This gallery's Beksiński hall, hung close and unguarded by crowds, is where that happened for you — one of your three meetings with his work. The deposit that made it possible has since moved on, which is its own Beksiński-shaped lesson in impermanence. Craft: regional galleries keep short and changeable hours, so check what is on before travelling; the programme still turns over steadily, and the place rewards the quiet weekday visit it was built for.",
 by: 'Opus · Fable' },
 "amnh": {
 about: "The American Museum of Natural History, on the edge of Central Park in New York, is one of the great natural-history museums of the world. Across dozens of halls it holds dinosaurs, meteorites, gems, dioramas of the world's wildlife and habitats, and vast anthropological collections — a cathedral of the physical world rather than an art museum, though it moves like one.",
 deep: "The habitat dioramas are the reason it belongs in any conversation about looking: hand-painted curved backgrounds fused seamlessly to mounted specimens and modelled foregrounds, an illusion of depth so total that painters come to study them as compositions. The Verreaux workshop's Lion Attacking a Dromedary — the taxidermy melodrama staged for the 1867 Paris Exposition, unmistakably a sculpture that happens to use skin and bone — began its American life in these halls in 1869, until the museum sold it to Pittsburgh's Carnegie for fifty dollars in 1898. The building itself sprawls across a century of styles, from the Beaux-Arts Roosevelt Memorial Hall to the Hayden sphere floating in its glass cube at the Rose Center. Craft: it is huge and easy to exhaust yourself in — pick two or three halls, and take the diorama galleries when they are quiet, because the illusion only fully lands when you can forget the room behind you.",
 by: 'Opus · Fable' },
 "petit-palais": {
 about: "The Petit Palais is the fine-arts museum of the City of Paris, built with its larger sibling the Grand Palais for the 1900 World's Fair and kept afterwards as a permanent gallery. Entry to the collection is free. It holds painting, sculpture and decorative arts from antiquity into the early twentieth century — a broad, generous city collection in a beautiful Beaux-Arts shell.",
 deep: "The building is a low, garlanded palace of stone and glass wrapped around a semicircular garden courtyard with its own café, so the museum breathes in a way grander institutions do not. Charles Girault's design gives you a domed vestibule and gilded staircases that make the free entry feel almost illicitly generous. The collection is a magpie's spread — Dutch cabinet pictures, medieval enamels, nineteenth-century salon painting — home of Dinet's Femmes arabes à la promenade. Dinet is worth the pause: Étienne Dinet learned Arabic, settled in the Algerian oasis town of Bou Saâda and converted to Islam, taking the name Nasreddine — an Orientalist who crossed over rather than merely looked. Craft: because it is free and central, use it as a refuge rather than a marathon — an hour, a few rooms, the garden — on a weekday morning before the crowds drift across from the Champs-Élysées.",
 by: 'Opus · Fable' },
 "kunsthaus-zurich": {
 about: "The Kunsthaus Zürich is Switzerland's largest art museum, a fine-arts collection running from medieval painting to the contemporary, with particular strength in Swiss art, the largest Munch holding outside Norway, and a deep body of Giacometti. A major Chipperfield-designed extension, opened in 2021, doubled its space across the road from the original building.",
 deep: "The two buildings tell the museum's argument in stone: Karl Moser's 1910 house for the historic collection, David Chipperfield's austere block opposite for classic modernism, joined beneath the square. Its Munch rooms and Giacometti holdings give it weight beyond its city's size. This is where you met Renoir's Irène Cahen d'Anvers, and the picture's sweetness hides a hard history: looted by the Nazis in 1941 from the château where her family had hidden it, restituted to Irène in 1946, then sold by her to Emil Bührle — the arms manufacturer whose fortune grew selling weapons to the Reich, and whose collection has hung in the new wing since 2021 under an unresolved public reckoning. Craft: decide beforehand whether you have come for the modern rooms or the historic house, and cross between them rather than fusing both into one tired pass.",
 by: 'Opus · Fable' },
 "moma": {
 about: "The Museum of Modern Art in midtown Manhattan is the institution that effectively defined the canon of modern art. Its collection runs from Post-Impressionism through the twentieth-century movements — Cubism, Surrealism, Abstract Expressionism — into contemporary work, and includes painting, sculpture, photography, film, design and architecture, held across a much-expanded building on West 53rd Street.",
 deep: "MoMA opened in November 1929, days after the Wall Street Crash, and did not just collect modern art — it wrote the story of it, its early hangs shaping how the century would be taught. The collection is a roll-call of images that escaped the museum and became wallpaper of the mind. Chief among them — and the most famous of the works that floored you here — is Van Gogh's Starry Night, in the collection since 1941 — a painting so reproduced that meeting the actual canvas, smaller than you expect and thickly furrowed with real paint, is a genuine shock after a lifetime of posters. It is almost always ringed by phones, which is its own modern tableau. Craft: go straight to the fifth-floor galleries at opening and stand with it before the crowd forms; the picture needs a few quiet seconds to shed the cliché and become a nocturne again.",
 by: 'Opus · Fable' },
 "reina-sofia": {
 about: "The Museo Reina Sofía is Madrid's national museum of twentieth-century and contemporary art, completing the city's 'Golden Triangle' with the Prado and Thyssen. Housed in a converted eighteenth-century hospital with glass lift-towers bolted to its façade, it holds the great Spanish moderns — above all Picasso, Miró and Dalí — and the century's most famous political painting.",
 deep: "The building was a general hospital before it was a museum, and the long ward-like galleries suit an art of witness. Its heart is Guernica, which you met here — the vast grey scream Picasso painted for the Spanish Pavilion at the 1937 Paris fair after the bombing of the Basque town, then refused to let enter Spain until the country was a democracy again. It arrived in 1981, eight years after his death, and hung at first behind bulletproof glass; the glass came off in 1995, a quiet declaration that the democracy had held. Since 1992 it has anchored a Reina Sofía room built around its scale, radiating a size no reproduction carries. Craft: see it early or late to dodge the school groups, and start with the preparatory sketches nearby, watching the horse, the bull and the fallen find their places before you turn to the wall itself.",
 by: 'Opus · Fable' },

 "tate-britain": {
 about: "Britain's national gallery of British art, on Millbank since 1897, built over the cleared site of a penitentiary. The Clore Gallery, opened by James Stirling in 1987, gave the Turner Bequest its dedicated rooms. January 1928 brought the Thames into the basement, destroying eighteen works. When Tate Modern opened in 2000, the modern collection left for the South Bank and Tate Britain took its present form.",
 deep: "The 1928 flood is a corrective to the institution's permanence: eighteen paintings destroyed, 226 badly damaged, water finding its way up through the floor from voids left by the prison demolition beneath. The collection's centre of gravity is the mid-nineteenth century. The Turners run from the recognisable to the nearly-abstract — the dissolving light of Norham Castle, the vortex of Snow Storm, the pale headland sunrises that his contemporaries found unfinished. The Constables work as counterpoint: where Turner evaporates, Constable fixes, and the cloud studies read as meteorological documents that also happen to be paintings. The two Henry Moores in the sculpture hall act as a pivot between the figurative tradition and what came after. The long Millbank frontage, the rotunda, and the Clore annexe never cohere into a single visitor logic; treat the Turner rooms as the destination and move outward.",
 by: 'Opus · Fable' },
 "npg-london": {
 about: "A gallery constitutionally unlike any other: founded in 1856 on the principle that significance belongs to the sitter, not the artist. Earl Stanhope's founding motion named those most honourably commemorated in British history — in war, statesmanship, art, and science. The collection runs chronologically from the Tudors to the contemporary. After a three-year closure, it reopened in June 2023 with a new entrance and the East Wing brought into full use.",
 deep: "The founding logic is stubborn: a portrait earns its place here because of who sat for it, not who painted it. That inverted the usual museum hierarchy — a minor artist's likeness of a great general outranks a masterwork whose subjects were nobody in particular. The collection climbs from the Tudors on the upper floors, where familiar Elizabethan faces stare out from dark grounds, down through the Georgian and Victorian rooms to the ground floor's contemporary commissions. Period objects — maps, manuscripts, medals — supplement the paintings and keep the hang from reading as a picture gallery in disguise. The 2023 refurbishment reordered those galleries, opened a new public entrance, and brought the East Wing into full use. Start at the Tudors and let British history unwind floor by floor; the contemporary rooms at the bottom are where the NPG is still deciding who matters.",
 by: 'Opus · Fable' },
 "kunstmuseum-basel": {
 about: "The oldest public art collection in the world, by the standard that matters: in 1661 the city of Basel purchased the Amerbach Cabinet — fifty paintings, fifteen of them by Hans Holbein the Younger — and opened it to the public, predating any comparable institution. In 1939 it bought twenty-one works deaccessioned by the Nazis as degenerate. A second building, by Christ and Gantenbein, opened across the street in 2016.",
 deep: "The claim to oldest rests on a specific purchase: in 1661 the Amerbach Cabinet was at risk of being sold to Amsterdam; Basel's university professors and the city council intervened, paying 9,000 reichsthalers to keep it. That act of civic acquisition, making the collection public immediately, is what no earlier institution can match. The cabinet's core was Holbein — drawings, prints, and oils — and Holbein remains the museum's deepest historical seam. The 1939 purchase of twenty-one works the Nazi government had classified as degenerate and put up for sale abroad included Lovis Corinth's Ecce Homo, which you stood in front of. The 2016 Neubau across the street, designed by local architects Emanuel Christ and Christoph Gantenbein, takes post-1950 work and is connected to the main building by an underpass. Cross under to see what the collection became; come back to the Hauptbau for what it was.",
 by: 'Opus · Fable' },
 "alte-nationalgalerie": {
 about: "Nineteenth-century art museum on Museumsinsel, in a building by Friedrich August Stüler and Heinrich Strack that opened in 1876 as a classical temple on a high plinth. Its founding collection was the 262-work bequest of banker Johann Heinrich Wilhelm Wagener, given to the Prussian state in 1861. Bombed heavily in the war, it reopened in 2001 after restoration by HG Merz.",
 deep: "The Wagener bequest brought the collection into being but also shaped its character: a German collector's taste ran to Belgian history painting and the Düsseldorf school, and those rooms still carry the density of someone's considered eye. The floors above open into German Romanticism — the Alte Nationalgalerie's real distinction. The Friedrich rooms, where Monk by the Sea and Abbey in the Oakwood hang together, are among the strongest in any German museum. Higher still, the Impressionist and late-Realist galleries are where you stood in front of Monet's L'Été and Liebermann's Die Gartenbank, two works that between them mark the range from French Impressionism to the German response. The building's temple form — a high plinth, sweeping steps, a full colonnade — is itself a nineteenth-century argument about what art is for. Bombed into ruin after 1944, it was restored by HG Merz and reopened in 2001, marking its 125th anniversary.",
 by: 'Opus · Fable' },
 "v-and-a": {
 about: "Founded on the profits of the 1851 Great Exhibition, it opened in 1852 as the Museum of Manufactures, became the South Kensington Museum in 1857, and was renamed the Victoria and Albert Museum in 1899 when Queen Victoria laid the foundation stone for Aston Webb's new entrance — her last official public engagement. It collects applied and decorative arts: furniture, ceramics, textiles, metalwork, and design, not paintings.",
 deep: "The distinction matters: the V&A is not a picture gallery. Its brief has always been the material world — how things are made, what they looked like, how they were used — across furniture, ceramics, textiles, metalwork, and jewellery. The Cast Courts are the most startling rooms in any London museum: two vast halls built in the 1870s to house plaster casts of the world's great sculptural monuments, Trajan's Column split in two to fit, Michelangelo's David reproduced at full scale. The paintings that do hang here — including the Constable and Danby's Disappointed Love that you stood in front of — arrived as part of the applied-arts mission, not as a picture collection. That context makes them stranger and more interesting than they would be in a conventional hang. The building has grown by accretion across successive campaigns of building; the unexpected room — the jewellery corridor, the ironwork gallery — rewards as much as any planned route.",
 by: 'Opus · Fable' },
 "louvre": {
 about: "The building existed for six centuries before it became a museum. Philip Augustus raised a defensive fortress on the Seine around 1190; Francis I began replacing it with a Renaissance palace in 1546; Louis XIV abandoned it for Versailles in 1682. The revolutionary government opened the Musée Central des Arts on 10 August 1793. I. M. Pei's glass pyramid, the new main entrance, went up in 1989.",
 deep: "About 35,000 objects are on display; the collection runs to roughly 550,000, which means the overwhelming majority of what the Louvre owns is in storage or at the reserve facility in Lens. The rooms you walk are a small editorial selection from an accumulation growing since Francis I brought Leonardo to France. That context changes what a visit is: not a survey of the collection, but a tour of the curators' argument about what matters most. The seven departments — Egyptian antiquities, Near Eastern antiquities, Greek, Etruscan and Roman, Islamic art, sculpture, decorative arts, and paintings — run through the palace's wings at a scale that defeats a single day. Three of the works you have met are spread across it: Canova's Psyche Revived by Cupid's Kiss on the ground floor, Leonardo's Saint Jean Baptiste in its wing, the Winged Victory of Samothrace commanding its staircase. The Victory is the building's best piece of curation — an unroofed ship prow, the marble still moving.",
 by: 'Opus · Fable' },
 "neue-pinakothek": {
 about: "Ludwig I founded the Neue Pinakothek in 1853 as Europe's first public museum devoted to the art of its own century. The original building, designed by August von Voit, was gutted in the Second World War; the replacement by Alexander von Branca opened in 1981. It is now closed for a structural renovation that began in 2019, with reopening projected no earlier than 2029.",
 deep: "Until the building reopens, the paintings are not in it. A selection spanning Classicism and Romanticism through to early Modernism has been redistributed across two nearby venues: the ground floor of the Alte Pinakothek holds the larger share, and the Sammlung Schack carries further works. The Schack is worth the detour in its own right — an obsessive patron's personal collection of Romantic German painting, now absorbing Neue Pinakothek loans alongside its own Böcklins and Spitzwegs. Which pictures hang where shifts with the loan rotation, so the Van Gogh sunflowers, the Corinth or the Böcklin may be in either building on any given day. The Alte Pinakothek wing is a serviceable temporary home even if von Branca's sightlines are gone. The practical visit: Alte Pinakothek ground floor first, then cross to the Schack. The building itself cannot be entered; what it holds largely can.",
 by: 'Opus · Fable' },
 "bavarian-state-paintings": {
 about: "The Bayerische Staatsgemäldesammlungen — Bavarian State Painting Collections — is not a building but an administrative body that holds and distributes the Free State of Bavaria's art holdings across a network of venues. Its Munich flagship houses are the Alte Pinakothek, the Neue Pinakothek, the Pinakothek der Moderne, and Museum Brandhorst; it also governs the Sammlung Schack and around a dozen branch galleries spread across Bavaria.",
 deep: "The distinction matters practically. When you stand in front of Der Höllensturz der Verdammten by Rubens in the Alte Pinakothek, or Der Ritt des Todes by Böcklin, you are in a building managed by this body, not something called the Bavarian State Painting Collections. The organisation decides which works travel to which branches — Aschaffenburg, Bamberg, Bayreuth, Schleissheim among them — and presently coordinates the dispersal of the Neue Pinakothek's holdings while that building undergoes renovation. It also sets the loan and display policy for the whole network, so a single acquisition decision ripples across every room in every house it governs. For visitors the implication is useful: a Bayerische Staatsgemäldesammlungen search of any work will tell you which physical venue currently holds it, cutting through the confusion between the Pinakotheken's similar names. The collection body dates to the 19th-century Bavarian royal collecting tradition; the institutions it runs span six centuries of European painting.",
 by: 'Opus · Fable' },
 "altes-museum": {
 about: "Karl Friedrich Schinkel's neoclassical building on the Lustgarten opened in 1830 as Berlin's first purpose-built public museum. Its defining feature is the central rotunda, modelled on the Pantheon, which greets visitors before the galleries begin. The permanent exhibition — Ancient Worlds: Greeks, Etruscans and Romans — runs across two floors and holds one of the most substantial collections of classical antiquity outside Italy.",
 deep: "The rotunda is doing real architectural work: a deliberate decompression chamber between street and object, calibrated to shift your register before you reach anything Greek or Roman. Schinkel put it there on purpose. The ground floor presents Greek art from the ninth to the first century BC, moving Archaic through Classical and Hellenistic in a thematic arrangement — vases, bronzes, funerary reliefs, architectural fragments, jewelry all in the same sequence. The upper floor belongs to Etruscan and Roman art, including one of the most complete Etruscan holdings outside Italy: ceramics, urns, sarcophagi, and mummy portraits alongside Roman sculpture and mosaic. Die Sünde and Wilhelm Gentz's large-format record of the 1869 Jerusalem procession sit oddly against all that antiquity — a reminder that the building has held many things. Museum Island has shuffled its collections repeatedly; the current arrangement, settled around 2010–2011, finally gives the Altes Museum a stable identity as the ancient worlds house.",
 by: 'Opus · Fable' },
 "new-york-historical": {
 about: "Founded in 1804, New York Historical is the city's oldest museum, predating the Metropolitan Museum of Art by 66 years. It holds American history, material culture, and art together in a single institution on the Upper West Side. In October 2024 it dropped the hyphen and the word Society from its name — a rebranding that also shed the 19th-century spelling that had distinguished New-York from the modern city.",
 deep: "The gap between 1804 and the Met's 1870 founding is not trivial: it means New York Historical was accumulating American history before there was consensus about what American history was, and the collection shows that — a library and archive operating alongside the art holdings rather than separately from them. The art is strongest in two areas. The Hudson River School paintings, including major works by Thomas Cole and Frederic Edwin Church, represent the movement's most nationalist phase, when landscape painters were arguing that the continent's wilderness was itself a form of civilisation. The Audubon watercolours are an institution unto themselves: all 435 of John James Audubon's preparatory studies for The Birds of America, acquired from his widow in 1863, occupy a dedicated gallery and constitute the most complete surviving record of his working method. The building holds works across American genres — Corot, Hudson River painters, American urban realists — and the Audubon room is the reason to make the visit specific rather than general.",
 by: 'Opus · Fable' },
 "museum-ludwig": {
 about: "A 1986 building wedged between the Cologne Cathedral, the Rhine, and the Hauptbahnhof — designed by Peter Busmann and Godfrid Haberer. It grew from a 1976 donation of roughly 350 works by Peter and Irene Ludwig, and now holds the third-largest Picasso collection in the world and the most comprehensive Russian avant-garde holdings outside Russia. Kirchner's Five Women on the Street is here.",
 deep: "The building imposes itself before you enter: a sawtooth roof over a wedge of ground caught between one of the world's great Gothic cathedrals and a busy main station. The Ludwigs wanted their collection exactly where the city could not avoid it. The Picasso rooms are the headline, anchored by the 1994 gift of ninety works covering every period of his output; the Russian avant-garde galleries are equally strong and less visited, with works that rarely appear outside Moscow or St Petersburg. The Pop Art holdings — the other pillar of the original 1976 donation — run from Warhol and Lichtenstein through American and European Pop. Ernst Ludwig Kirchner's Five Women on the Street, angular figures cutting through a Berlin night, holds a prime position in the German Expressionism rooms. Start with the Picassos if you must, but the Russian galleries are where the museum earns its claim to be genuinely irreplaceable.",
 by: 'Opus · Fable' },
 "mam-paris": {
 about: "The city of Paris's own modern art museum, distinct from the state-run Centre Pompidou. It occupies the east wing of the Palais de Tokyo, built for the 1937 International Exposition, and its permanent collection is free. The overwhelming object here is Raoul Dufy's La Fée Électricité — 600 square metres of oil on panel, among the largest paintings in existence. Robert Delaunay's Tour Eiffel hangs here.",
 deep: "The confusion is easy: Paris has two major modern art museums and most visitors know only one. The Centre Pompidou is the national collection, famously inside-out on the Beaubourg plateau. This is the municipal one, free for the permanent galleries, in a quieter corner of the 16th arrondissement. The building was purpose-built for the 1937 Exposition Internationale, and its long stone wing gives the museum a gravity the Pompidou's funfair exterior does not. The anchor is Dufy's La Fée Électricité: 250 oil-on-plywood panels in a curved sweep tracing the history of electricity from ancient myth to the modern grid, commissioned for that same Exposition. In May 2010 a single thief broke in overnight and removed five works — Picasso, Matisse, Braque, Modigliani, and Léger — estimated at a hundred million euros; none has been recovered. The free entry and the Dufy room make this the better museum for the kind of slow looking Paris rarely allows.",
 by: 'Opus · Fable' },
 "lenbachhaus": {
 about: "Franz von Lenbach's Italianate villa in Munich, now home to the world's largest Blaue Reiter collection. That collection exists because of one decision: in 1957, on her eightieth birthday, Gabriele Münter donated more than a thousand works she had preserved through the Nazi years — ninety Kandinsky oils, his watercolours and sketchbooks, and paintings by Franz Marc, August Macke, Paul Klee, and others. Franz Marc's Vögel is here.",
 deep: "Münter's gift is one of the great acts of cultural stewardship of the twentieth century. She had been Kandinsky's companion until 1914, and when he left Munich for Russia at the outbreak of war she kept his work at her house in Murnau — through the years when the Nazis classified it as degenerate and it could not be shown. By handing the entire tranche to the Städtische Galerie on her birthday, she turned a regional city gallery into the essential address for the Blaue Reiter. The villa — built by Lenbach in the 1880s in Italianate style — sits in contrast to the modern extension added later. Kandinsky's Munich-period canvases form the overwhelming core, but the Mackes, the Klees, and the Münters themselves repay careful attention. Franz Marc's Vögel hangs among works that show exactly how much that group achieved in a few concentrated years before the war ended it.",
 by: 'Opus · Fable' },
 "royal-castle-warsaw": {
 about: "The seat of Polish kings and parliament at the heart of Warsaw's Old Town. The Nazis burned and looted it in 1939, then demolished it to its foundations in 1944 after the Warsaw Uprising failed. Reconstruction ran from 1971 to 1984. Two Rembrandt paintings — given by Countess Karolina Lanckorońska in 1994 — are among its most significant holdings. Rembrandt's Scholar at his Desk hangs here.",
 deep: "The destruction was systematic. After the 1944 Uprising the Nazis dynamited what remained, building by building. The reconstruction that followed was funded largely by public donation and run by a Civic Committee — an act of national will rather than restoration in any conventional sense. There were no standing walls to work from, only pre-war surveys, photographs, and the painted views of Bernardo Bellotto that had documented the interiors in eighteenth-century detail. The shell was rebuilt by 1974; the interiors completed and opened in 1984. In 1994 Countess Karolina Lanckorońska, who had taken two Rembrandts out of Poland before the war and kept them safe in Rome for decades, gave them back. Both now hang in the Lanckoroński Gallery; Scholar at his Desk is one. Walking apartments reconstructed at this precision is a different experience from walking an original — the craft is deliberate, and knowing what was lost is part of what the rooms mean.",
 by: 'Opus · Fable' },
 "science-museum": {
 about: "London's national museum of science and technology on Exhibition Road — not an art museum. Its origins lie in the 1851 Great Exhibition; it separated from the Victoria and Albert Museum in 1909 and moved into its current building in 1928. The collection runs from early steam locomotives — including Stephenson's Rocket — through computing, aviation, medicine, and space exploration. Stanhope Forbes's The Munitions Girls hangs here.",
 deep: "The Science Museum is most useful to understand as a place where technology becomes history. The objects that matter most are not curiosities but working things that changed the world: Stephenson's Rocket, which won the 1829 Rainhill Trials and effectively defined the modern steam locomotive, sits in the same building as early computing hardware, an Apollo 10 command module, and the iron lung. The galleries span several floors and move roughly chronologically. The lower levels tend toward heavy machinery — engines, vehicles, the history of energy — while the upper floors cover medicine, mathematics, and the modern sciences. Temporary exhibitions on the ground floor draw the crowds; the permanent galleries above are where the depth is. The Munitions Girls by Stanhope Forbes, one of the few paintings in the collection, hangs as a document of industrial labour rather than as art — a reminder that this museum's relationship to making things is its governing logic. Entry is free.",
 by: 'Opus · Fable' },
 "neue-kunst-karlsruhe": {
 about: "Part of ZKM — the Zentrum für Kunst und Medientechnologie in Karlsruhe — in a former munitions factory built between 1914 and 1918. The Museum für Neue Kunst's collection merged with ZKM's Media Museum in 2017, producing a combined survey of twentieth and twenty-first century art across painting, sculpture, video, and computer-based work. ZKM holds one of the largest video art collections in Europe. Ferdinand Keller's Böcklins Grab is here.",
 deep: "The building explains the museum. Hallenbau A — a listed industrial structure built for arms production — was occupied by artists in the early 1980s before Karlsruhe's city council committed to turning it into a cultural centre. ZKM moved in permanently in 1997 after Schweger + Partner completed a renovation that preserved the factory's scale and character. The Museum für Neue Kunst was one of ZKM's two constituent museums until a 2017 restructuring dissolved both and merged their collections. The logic was that separating painting from video and computer art had become artificial — artists were working across all those forms simultaneously. The result covers painting, performance, body art, and media-based practice; the computer art collection is described as the largest of its kind in the world. Ferdinand Keller's Böcklins Grab — a nineteenth-century elegy for a dead peer — sits in a museum whose main purpose is the art of the present, which is itself a contrast worth noticing.",
 by: 'Opus · Fable' },
 "tubingen-antiquities": {
 about: "A numismatic and archaeological teaching collection at the University of Tübingen, housed in Hohentübingen Castle — not a public art museum. The coin holdings run to around 8,000 Greek and 6,000 Roman coins plus medieval and Islamic material, making it the most extensive university coin collection in Germany. The broader classical archaeology holdings include original ancient sculptures used directly in research and teaching. An Augustan portrait is among them.",
 deep: "University collections of this kind exist to be handled and studied rather than viewed at a distance, and Tübingen's is among the richest in Germany, having accumulated steadily since the nineteenth century without being absorbed into a regional or national institution. Hohentübingen Castle — a hilltop Renaissance structure overlooking the old town — provides the setting; the Museum Ancient Cultures there gathers the archaeology, anthropology, and numismatic holdings of several university institutes under one roof. The coin collection is the most technically significant element: Greek, Roman, Byzantine, medieval European, and Islamic series, each large enough to support specialist research, and accessible to students in ways a national collection in a major city would not be. Visiting as a non-specialist is possible but the experience is closest to a research library — organised for study, rich in depth, limited in spectacle. An Augustan portrait from the Allgäu region is among the original sculptures that anchor the classical archaeology holdings.",
 by: 'Opus · Fable' },
 "warsaw-old-town-centre": {
 about: "An interpretation centre about the reconstruction of Warsaw's Old Town — not an art museum. The district was deliberately destroyed by the Nazis in 1944 and rebuilt 1949–1956, using pre-war surveys, photographs, and the eighteenth-century views of Bernardo Bellotto. UNESCO listed the Historic Centre of Warsaw as a World Heritage Site in 1980, citing it as a pioneering example of reconstruction and a symbol of national survival.",
 deep: "The reconstruction of Warsaw's Old Town is exceptional in the history of urban heritage because it was not restoration — it was rebuilding from nothing. Nazi demolition units worked systematically through the district after the 1944 Uprising, leaving almost nothing. What made reconstruction possible was the documentary record: pre-war inventories, photographs, and above all the painted views of Bernardo Bellotto, court painter in Warsaw in the 1770s, whose panoramas were detailed enough to serve as architectural blueprints. The rebuilding ran from 1949 to 1956 and reproduced the district as it appeared in the late eighteenth century. UNESCO's 1980 inscription listed the site not as intact historic fabric but as a demonstration that a community can reconstruct its own past from records and will. The centre interprets that process — what was documented, how decisions were made, what was lost — inside the very streets it describes. A Rembrandt, Jonge vrouw in een schilderijlijst, is associated with this venue.",
 by: 'Opus · Fable' },
 "aus-performing-arts": {
 about: "Australia's largest specialist collection documenting the performing arts, held at Arts Centre Melbourne — not an art museum. The collection runs to more than 850,000 items spanning ballet, circus, dance, music, opera, and theatre: costumes, set models, stage designs, props, photographs, posters, programmes, and personal archives. Nicholas Chevalier's The Buffalo Ranges is among its holdings.",
 deep: "The Australian Performing Arts Collection exists at the intersection of archive and museum, and most of what it holds can only be seen by appointment in the Research Centre — a reading room open two days a week, with visits booked six to eight weeks ahead. This is not a complaint but a description: the collection is organised for scholarship and preservation as much as public display. What is visible without a booking are the exhibitions that Arts Centre Melbourne runs through its galleries, drawing on the holdings to tell stories about specific performers, productions, or moments in Australian performance history. The breadth is genuine: from nineteenth-century touring companies to Kylie Minogue's stage costumes, from Bell Shakespeare's archives to Nick Cave's notebooks. Nicholas Chevalier's The Buffalo Ranges — a nineteenth-century landscape — sits in a collection whose primary logic is performance rather than fine art. If you want access to the full depth of the holdings, book early.",
 by: 'Opus · Fable' },
 "museo-fortuny": {
 about: "A fifteenth-century Venetian Gothic palazzo in Campo San Beneto, once the home and studio of Mariano Fortuny — painter, photographer, stage designer, and textile inventor. Fortuny moved in in 1902; the palazzo was gifted to the City of Venice in 1956 and opened as a museum in 1975. It holds his fabrics, his distinctive atmospheric lamps, and his paintings across two floors that still feel like a working atelier.",
 deep: "Mariano Fortuny (1871–1949) disrupts simple categories: he made fabrics that became central to twentieth-century fashion, invented stage lighting systems used across Europe, painted in the tradition of the old masters, and made lamps whose diffused light was itself an aesthetic statement. The palazzo — originally Palazzo Pesaro Orfei, built for the Pesaro family in the fifteenth century — became the laboratory for all of it. The museum preserves the atmosphere of the working space: the upper floor shows his paintings and the history of the atelier; the lower floor holds the textiles and the distinctive globular lamps. It is narrow in the sense that it documents one artist's practice rather than a broad survey, but deep in exactly the way single-figure house museums can be — objects accumulate meaning because they were all made by the same hands in the same rooms. The museum was marking the fiftieth anniversary of its 1975 opening with programming running through 2025–2026.",
 by: 'Opus · Fable' },
 "kunstsalon-franke-schenk": {
 about: "A commercial gallery in Munich rather than a museum, dealing in painting, drawing and sculpture from the sixteenth to the twentieth century, with Old Masters and German Expressionism its declared ground. Stock rotates and there is no permanent public collection, so what is on the walls in any given month is whatever is currently for sale.",
 deep: "This is a dealing room, and the difference from a museum is the whole of it: nothing here is held in perpetuity, nothing is hung to make an argument, and the works on show are a function of what the trade has moved recently. A visit means gallery hours and an appointment mentality rather than a ticket. Munich has a deep private-gallery culture of exactly this kind — the city was a centre of the German art trade through the twentieth century, and much of what now hangs in its public collections passed through rooms like this one first. Treat it as a place where a picture surfaced rather than a place a picture lives. The Arellano flower piece is the reason it is in this collection at all, and by the nature of the business it will not be there indefinitely.",
 by: 'Opus · Fable' }
};
