// museum_about.js — institution reads for museum pages (pilot 10, 2026-07-17).
// Same two-tier convention as art-about: about = what this place is, deep = how it works
// as an experience. Drafted by Opus, verified and polished by Fable (per-entry by:).
window.CANVAS_MUSEUM_ABOUT = {
 "met-nyc": {
 about: "America's largest art museum, founded in 1870 by New Yorkers who felt the young country ought to have one. Encyclopedic by design — five thousand years, every continent, an Egyptian temple to European paint to arms and armour — behind a Beaux-Arts façade on the edge of Central Park, extended and re-extended for a century and a half.",
 deep: "The Met's ambition is coverage, not argument: one great example of everything, and it mostly has one, so the building rewards wanderers and punishes planners. It is really a dozen museums under one roof — each wing donor-built, donor-named, run to its own taste — which is why the whole reads as a city's accumulated appetite rather than a single vision. Crowds pool in the same few rooms, European paintings and the Temple of Dendur, so go at opening or aim where people don't: the American Wing, arms and armour, the instruments. The Great Hall staircase gets you to the paintings ahead of the tour groups. And give yourself permission to leave unfinished — nobody completes the Met, and treating it as many small museums, one per visit, is the only sane way in.",
 by: 'Opus · Fable' },
 "marmottan": {
 about: "A hunting lodge turned mansion on the edge of the Bois de Boulogne, left to the Académie des Beaux-Arts by Paul Marmottan in 1932. Michel Monet's 1966 bequest of his father's own holdings made it the largest Monet collection in the world — including Impression, Sunrise, the canvas that named Impressionism — with the finest Berthe Morisot holdings anywhere alongside.",
 deep: "A house, not a hall, and it works on you that way: panelled rooms of Empire furniture upstairs, then the floor gives way to a purpose-built basement gallery where the Monets hang — the late water lilies among them, dim and enveloping, close enough to read every stroke, and rarely a crowd between you and them. Impression, Sunrise carries two good stories: a hostile critic coined \"Impressionism\" from its title as a sneer and the movement kept the slur as a badge; then in 1985 the painting was stolen at gunpoint from these rooms and spent five years missing before turning up in Corsica. Go down to the Monets first, while you're fresh. Then climb back up for Morisot — most visitors treat her rooms as a corridor, and they are the best of her anywhere.",
 by: 'Opus · Fable' },
 "van-gogh-museum": {
 about: "The world's largest Van Gogh collection, built on what brother Theo's family kept and never sold: some two hundred paintings, five hundred drawings, and the letters. Opened in 1973 on Amsterdam's Museumplein in a building designed by Gerrit Rietveld of De Stijl, it traces one short, ferocious career from the dark Dutch years to the final blaze in France.",
 deep: "Because the collection descends from what the family kept rather than what the market picked, it tells a life in order, and it hangs that way: chronological, from the muddy Nuenen peasants up through Paris to the sunstruck south and the last weeks at Auvers. That inheritance also makes it rich in the unfamous — studies, misfires, second attempts — so this museum explains Van Gogh where greatest-hits hangs merely display him. The letters quoted on the walls do more than any label. And the whole thing exists because Jo van Gogh-Bonger, Theo's widow, spent decades placing and publishing the work of a man who sold almost nothing alive. Everyone climbs the same route in the same direction and the middle floors clot: book ahead, come at opening or in the last hours, and double back against the flow for the famous ones.",
 by: 'Opus · Fable' },
 "guggenheim": {
 about: "Frank Lloyd Wright's white spiral on Fifth Avenue, opened in 1959 and as much sculpture as building. It grew from Solomon R. Guggenheim's collection of \"non-objective\" painting, assembled on the advice of Hilla Rebay, and stays strongest in early European modernism — above all Kandinsky. The rotunda ramp, coiling up beneath its glass dome, is the collection's most famous object.",
 deep: "Wright built a building that tells you how to move: lift to the top, then walk down, gravity doing the choreography as each work swings into view around the curve. It is a beautiful idea permanently at war with the art — the floor slopes, the outer wall leans, and painters have grumbled for decades that nothing hangs straight — a museum whose masterpiece fights its own pictures. Wright himself died six months before the opening; he never stood in the finished rotunda. The spine of the collection is abstraction's founding generation, the Kandinskys above all, while the Renoirs and Manets you didn't expect come from the later Thannhauser gift, tucked into a side wing. Those galleries off the ramp are easy to miss and where the quiet treasures wait. Ride straight up, drift down, and let the building be the first exhibit.",
 by: 'Opus · Fable' },
 "belvedere": {
 about: "A baroque summer palace completed in 1723 for Prince Eugene of Savoy, crowning a terraced garden above Vienna. It now holds Austrian art across the centuries, and its glory is the world's largest collection of Klimt paintings — The Kiss above all — with strong Schiele and Viennese modernism beside. The gilded state rooms are half the visit.",
 deep: "You come for pictures and find yourself in a palace: in through the Sala Terrena, where four stone giants hold up the vault, then up the staircase to the Marble Hall — the room where, in 1955, the treaty restoring Austria's sovereignty was signed and shown from the balcony. Imperial baroque housing radical modernism is the whole character of the place; Klimt's gold reads differently in halls built to glitter, one empire's swagger framing the artists who broke with it. The Kiss pulls the entire crowd into a single room, phones up on arrival, so take Schiele and the nineteenth century first. Regulars remember the missing one: Adele Bloch-Bauer I hung here until 2006, when it was restituted to the family the Nazis robbed, and left for New York. Come early, and give the gardens and the city view their minutes — the view is why it stands up here.",
 by: 'Opus · Fable' },
 "orsay": {
 about: "Western art from 1848 to 1914, housed in Victor Laloux's Beaux-Arts railway station built for the 1900 World's Fair and nearly demolished in the 1970s. Opened as a museum in 1986, it bridges the Louvre and the Pompidou and holds the world's foremost Impressionist and Post-Impressionist collection under its vast glass train-shed vault.",
 deep: "The Orsay's spine is a chronology and its bones are a station: the sculpture court runs where the platforms lay, the great gilded clock still keeps time, and everything funnels upward to the Impressionists under the roof — which is why the fifth floor is a crush by noon. Reverse the flow: ride to the top at opening, take Monet, Renoir and Van Gogh while they're quiet, then descend through the realists and the academic Salon machines most people skip; the Bouguereaus and Courbets on the way down are half the argument of the place, the world Impressionism was fighting. The station itself died of progress — by 1939 its platforms were too short for modern trains — and in the 1970s France nearly flattened it for a hotel: the country that once refused to hang this art almost demolished its perfect frame.",
 by: 'Opus · Fable' },
 "nationalmuseum": {
 about: "Sweden's museum of art and design, founded in 1792 and housed since 1866 in Friedrich August Stüler's Renaissance-revival palace on the Stockholm waterfront, facing the Royal Palace across the water. Swedish painting and sculpture, older European masters, and a serious design collection share the building, rehung and re-coloured in a grand restoration finished in 2018.",
 deep: "A national self-portrait as much as an art museum: strongest where it tells Sweden's own story — Zorn's midsummer light, Sergel's furious drawings — so the Nordic rooms carry a charge the European masters don't quite match. Climb the ceremonial staircase and you're inside the collection's best story: Carl Larsson's murals cover it, and his vast Midwinter Sacrifice, painted for the top landing, was rejected on delivery, drifted for decades and reached Japan before Sweden bought it back in 1997 — it now hangs exactly where he meant it to. Crowds are gentle by continental standards; you can stand alone with the Rembrandts, including the Conspiracy of the Batavians that Amsterdam's town hall rejected too. Start at the top with the paintings, drift down through design, and don't treat the applied-arts floors as a footnote — here a chair ranks with a canvas on purpose.",
 by: 'Opus · Fable' },
 "frick": {
 about: "Steel-and-coke magnate Henry Clay Frick's private collection, shown in the Fifth Avenue mansion Carrère and Hastings built for him in 1914 — designed from the start to become a museum once the family was done living in it. Old Masters, French furniture, porcelain and bronzes, bought with a ruthless eye for quality over quantity. It opened to the public in 1935.",
 deep: "The Frick's genius is restraint: one man bought only what he judged best, so the walls hold few pictures and almost no weak ones — three Vermeers, Bellini's St Francis, Holbein's Cromwell and More glaring at each other across a fireplace — and you meet them in rooms built for living, not display. The serenity was bought with one of the Gilded Age's most hated fortunes; the man who hung the Vermeers also broke the Homestead strike and survived an anarchist's bullets, an irony the house never mentions and you can't unfeel. The Garden Court, everyone's resting place, isn't original — John Russell Pope added it in the museum conversion, over the old carriage court. Since the 2025 renovation the upstairs family rooms are open for the first time, small rooms with small pictures, and they restore what the collection is really about: living with it.",
 by: 'Opus · Fable' },
 "nga-dc": {
 about: "The United States' national gallery, Andrew Mellon's gift to the nation along with the core of its collection. John Russell Pope's neoclassical West Building opened on the Mall in 1941; I. M. Pei's angular East Building for modern art followed in 1978. Old Masters run deep here, including Ginevra de' Benci, the only Leonardo painting in the Americas.",
 deep: "Two buildings, two temperaments, joined underground: Pope's West Building is a marble temple, skylit rooms strung along garden courts with fountains, while Pei's East Building is sharp angles and atrium light for the twentieth century — the walk between them runs through Leo Villareal's LED tunnel, the one stretch of museum photographed more than the art. Mellon's modesty was strategy: he refused to let the gallery carry his name so that other collectors would give too, and they did — Kress, Widener, Dale — which is how a national collection materialised within a decade. It is free, it is not part of the Smithsonian despite what half its visitors assume, and it rarely overwhelms: crowds cluster at the Leonardo and the Impressionists while the Dutch and Italian rooms nearby stay calm. Take the West first, and rest in the garden courts — they're built for it.",
 by: 'Opus · Fable' },
 "ngi": {
 about: "Ireland's national collection, opened in 1864 on Merrion Square, holding a solid European survey alongside the fullest gathering of Irish painting anywhere. Its modern legend is Caravaggio's The Taking of Christ, which hung unrecognised in a Dublin Jesuit house until 1990. Successive wings, the Millennium extension among them, wrap the original Victorian galleries.",
 deep: "The gallery reads in two registers: a compact European survey — Vermeer, Velázquez, Goya — and beside it the national story, Irish painters given room no bigger country would spare them, with Jack B. Yeats a museum within the museum. Its luck is legendary in both directions. The Caravaggio hung misattributed in a Jesuit dining room for decades before a researcher recognised it in 1990; the Jesuits left it on permanent loan. The Vermeer came via the Beit collection, stolen twice — once by an IRA gang, once for a Dublin crime boss — and recovered both times. And the money is literary: Bernard Shaw, who called the gallery his real schoolroom, left it a share of his royalties, so My Fair Lady quietly paid for pictures. Admission is free, crowds are modest, and the Irish rooms are quietest of all — see the Caravaggio early, then give them your unhurried hour.",
 by: 'Opus · Fable' }
};
