#!/usr/bin/env node
// shard-about.js — split the committed llm-about.js (single source of truth) into lazy,
// bucketed shards + an inverted theme index, so the "what it's about" reads stop shipping as
// one ~4 MB blob (it TRIPLES as coverage descends to all ≥2-play tracks).
//
//   node shard-about.js
//
// Reads  : rotation/llm-about.js  (window.ROTATION_LLM_ABOUT — { "artistSlug~trackSlug": {src,haiku,web,sonnet,opus,fable,fableDeep} })
// Emits  : rotation/about/g-00.js … g-15.js   GIST tier  (light default read: src + haiku + web)
//          rotation/about/d-00.js … d-15.js   DEEP tier  (heavy reads: sonnet + opus + fable + fableDeep)
//          rotation/about/index.js            inverted theme index (token → entry-id list)
//
// Bucketing: _slugHash(artistSlug) % 16 — the artistSlug is everything before the first "~".
// This co-locates one artist's tracks in one shard, so a track page loads exactly one gist file.
//
// These are CI ARTIFACTS (like music-core.js): about/ is gitignored; only this script is committed.
// Run in CI right after build-data.js (see sync.yml). Nothing here touches the merge pipeline.

const fs = require("fs");
const path = require("path");
const vm = require("vm");
const { _slugHash } = require("./lib-slug");

const HERE = __dirname;
const SRC = path.join(HERE, "llm-about.js");
const OUT_DIR = path.join(HERE, "about");
const N_BUCKETS = 16;

// theme-index tuning ------------------------------------------------------------------------
// tokens are lowercased alphanumeric words len≥3, stopwords removed. A token is kept only if it
// appears in ≥ MIN and ≤ CEIL_FRAC * entries — ultra-common words (drops toward stopword-like
// noise) and hapax typos add bytes without helping search. Keys are referenced by integer id
// into a shared `keys` array to keep the file compact.
const TOK_MIN = 1;                 // must appear in at least this many entries
const TOK_CEIL_FRAC = 0.35;        // and no more than this fraction of all entries (too generic)
const MIN_TOK_LEN = 3;

const STOPWORDS = new Set((
  "the a an and or but nor for yet so of to in on at by from with as is are was were be been being " +
  "it its it's they them their there here this that these those what which who whom whose when where why how " +
  "not no yes into onto over under out up down off about above below between through during before after " +
  "he she his her him hers you your yours we our ours us i me my mine himself herself itself themselves " +
  "one two also all any both each few more most other some such only own same than too very can will just " +
  "song track lyric lyrics narrator speaker singer voice about theme themes read reads about's " +
  "s t re ve ll d m don don't doesn isn aren wasn weren won wouldn couldn shouldn"
).split(/\s+/).filter(Boolean));

// GIST holds only what the default track-page read needs; DEEP holds the interpretive reads.
const GIST_FIELDS = ["src", "haiku", "web"];
const DEEP_FIELDS = ["sonnet", "opus", "fable", "fableDeep"];

function loadSource() {
  if (!fs.existsSync(SRC)) {
    console.error("shard-about: llm-about.js not found at " + SRC);
    process.exit(1);
  }
  const code = fs.readFileSync(SRC, "utf8").replace(/^﻿/, "");
  const ctx = { window: {} };
  vm.createContext(ctx);
  vm.runInContext(code, ctx, { filename: "llm-about.js" });
  const O = ctx.window.ROTATION_LLM_ABOUT;
  if (!O || typeof O !== "object") {
    console.error("shard-about: llm-about.js did not define window.ROTATION_LLM_ABOUT");
    process.exit(1);
  }
  return O;
}

const bucketOf = (key) => {
  const artistSlug = key.slice(0, key.indexOf("~") < 0 ? key.length : key.indexOf("~"));
  // _slugHash returns base-36; convert to a Number modulo the bucket count deterministically.
  const h = _slugHash(artistSlug);
  let acc = 0;
  for (let i = 0; i < h.length; i++) acc = (acc * 36 + parseInt(h[i], 36)) % N_BUCKETS;
  return acc;
};

// a self-registering shard: merges into a shared global so concurrent loads never clobber.
function shardFile(glob, bucket, obj) {
  const bb = String(bucket).padStart(2, "0");
  const body = JSON.stringify(obj);
  return `// GENERATED by shard-about.js — do not edit. bucket ${bb}/${N_BUCKETS} of ${glob}\n` +
    `(window.${glob} = window.${glob} || {});\n` +
    `Object.assign(window.${glob}, ${body});\n`;
}

function main() {
  const t0 = Date.now();
  const O = loadSource();
  const keys = Object.keys(O);

  fs.mkdirSync(OUT_DIR, { recursive: true });
  // clean stale shards so a shrink never leaves orphans deployed
  for (const f of fs.readdirSync(OUT_DIR)) {
    if (/^(g|d)-\d\d\.js$/.test(f) || f === "index.js") fs.unlinkSync(path.join(OUT_DIR, f));
  }

  const gist = Array.from({ length: N_BUCKETS }, () => ({}));
  const deep = Array.from({ length: N_BUCKETS }, () => ({}));

  // inverted index: token -> Set of entry-ids (index into `keys`). Built alongside the shards.
  const keyId = new Map();
  keys.forEach((k, i) => keyId.set(k, i));
  const tokenMap = new Map();   // token -> Set<int>

  const pick = (e, fields) => {
    const o = {};
    for (const f of fields) if (e[f] != null) o[f] = e[f];
    return o;
  };

  for (const k of keys) {
    const b = bucketOf(k);
    const e = O[k];
    const g = pick(e, GIST_FIELDS);
    const d = pick(e, DEEP_FIELDS);
    // `has` — compact marker of which DEEP reads exist, so the switcher can render the
    // Sonnet/Opus/Fable buttons (and the Interpretation toggle) from the gist alone, then
    // lazy-load the deep shard only when one is actually opened. letters: s/o/f + I(fableDeep).
    let has = "";
    if (e.sonnet) has += "s";
    if (e.opus) has += "o";
    if (e.fable) has += "f";
    if (e.fableDeep) has += "I";
    if (has) g.has = has;
    if (Object.keys(g).length) gist[b][k] = g;
    if (Object.keys(d).length) deep[b][k] = d;

    // tokenise every present read (mirrors the theme-search corpus: haiku+sonnet+opus+fable+web)
    const id = keyId.get(k);
    const text = [e.haiku, e.sonnet, e.opus, e.fable, e.web].filter(Boolean).join(" ").toLowerCase();
    const toks = text.split(/[^a-z0-9]+/);
    const seen = new Set();
    for (const tk of toks) {
      if (tk.length < MIN_TOK_LEN || STOPWORDS.has(tk) || seen.has(tk)) continue;
      seen.add(tk);
      let s = tokenMap.get(tk);
      if (!s) { s = new Set(); tokenMap.set(tk, s); }
      s.add(id);
    }
  }

  // write the shards
  let gistBytes = 0, deepBytes = 0;
  for (let b = 0; b < N_BUCKETS; b++) {
    const gf = path.join(OUT_DIR, "g-" + String(b).padStart(2, "0") + ".js");
    const df = path.join(OUT_DIR, "d-" + String(b).padStart(2, "0") + ".js");
    const gc = shardFile("ROTATION_ABOUT_G", b, gist[b]);
    const dc = shardFile("ROTATION_ABOUT_D", b, deep[b]);
    fs.writeFileSync(gf, gc, "utf8"); gistBytes += gc.length;
    fs.writeFileSync(df, dc, "utf8"); deepBytes += dc.length;
  }

  // trim + serialise the index: token -> sorted int[] of entry-ids
  const ceil = Math.max(TOK_MIN, Math.floor(keys.length * TOK_CEIL_FRAC));
  const tok = {};
  let kept = 0, dropped = 0;
  for (const [t, set] of tokenMap) {
    if (set.size < TOK_MIN || set.size > ceil) { dropped++; continue; }
    tok[t] = Array.from(set).sort((a, b) => a - b);
    kept++;
  }
  const indexObj = { v: 1, buckets: N_BUCKETS, keys, tok };
  const indexBody =
    "// GENERATED by shard-about.js — do not edit. inverted theme index for llm-about.\n" +
    "// shape: { v, buckets, keys:[entryKey...], tok:{ token:[keyId...] } }. keyId indexes keys[].\n" +
    "window.ROTATION_ABOUT_INDEX = " + JSON.stringify(indexObj) + ";\n";
  const indexPath = path.join(OUT_DIR, "index.js");
  fs.writeFileSync(indexPath, indexBody, "utf8");

  const kb = (n) => (n / 1024).toFixed(0) + " KB";
  console.log("shard-about.js:");
  console.log(`  source        : ${keys.length} entries`);
  console.log(`  gist tier     : ${N_BUCKETS} shards (${kb(gistBytes)} total, ROTATION_ABOUT_G)`);
  console.log(`  deep tier     : ${N_BUCKETS} shards (${kb(deepBytes)} total, ROTATION_ABOUT_D)`);
  console.log(`  theme index   : ${kept} tokens kept, ${dropped} dropped (ceil=${ceil}) — ${kb(indexBody.length)}`);
  console.log(`  → rotation/about/  (${Date.now() - t0} ms)`);

  if (kept < 5000) {
    console.warn(`  ⚠ index has only ${kept} tokens (<5000) — smoke-test will flag this.`);
  }
}

main();
